### ISSUE TITLE
Preferred Display: enable ALL

### ISSUE THREAD

**Issue by AshSimmonds** [ModernFlyouts-Community/ModernFlyouts#1002]
### Description of the new feature / enhancement

Have the flyout appear on all screens.

### Scenario when this would be used?

If a user has a screen out of sight (eg behind them) and adjusts the volume, they won't be able to see a visual indicator of the volume adjustment without looking at the other screen.

### Additional context

Personal version: I have my computer output on 2 monitors and a big-screen TV. The monitors are on the west side of the room where I do dev work etc, the TV is on the east side where I do gaming on the sofa. When I'm on the sofa I can't see the monitor where the flyout shows up, so I'd just like it to show up on all screens if possible.

**Comment by Samuel12321** [comment]
Closing in favor of #736
