### ISSUE TITLE
Audio Flyout Windows 11 Bug

### ISSUE THREAD

**Issue by Invader001** [ModernFlyouts-Community/ModernFlyouts#1003]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 22H2

### OS build

22598.200

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

On Windows 11 Insider Preview when you are triggering the Audio Flyout there are both system and yours.

![image](https://user-images.githubusercontent.com/96627311/165641809-be6c35ca-7ea7-4e8e-a4cd-cc8ebb610007.png)

### ✔️ Expected Behavior

I was expecting only your Flyout to appear.

### ❌ Actual Behavior

There were both system and your Flyouts.

### Other Software

At the moment I was watching a video on youtube using Cent Browser(chromium based), but the bug happens even without it.

### Additional Context

I saw the same issue reported, but I also write about this to pay more attention.

**Comment by Cyberdroid1** [comment]
Filing a duplicate issue would not increase the visibility of the issue 🙂
