### ISSUE TITLE
When the main monitor is unplugged and plugged back in, the flyouts will stay on a secondary monitor

### ISSUE THREAD

**Issue by essenjey01** [ModernFlyouts-Community/ModernFlyouts#1004]
### ModernFlyouts Version

0.9.3.1

### Windows version

Windows 11 21H2

### OS build

22000.613

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1. Have two monitors
2. set the flyouts to the main one
3. unplug it
4. plug it back in
5. trigger a flyout

### ✔️ Expected Behavior

The flyout appears in the monitor you set it to before unplugging it

### ❌ Actual Behavior

The flyout appears in the secondary monitor

### Additional Context

I use a laptop which I connect to an external monitor when I'm at home, and it's quite annoying to have the flyouts in the wrong monitor every day i come back home

**Comment by Samuel12321** [comment]
Closing in favor of #736
