### ISSUE TITLE
Change Display Automatically when Input New Video Cable

### ISSUE THREAD

**Issue by leorcdias** [ModernFlyouts-Community/ModernFlyouts#1010]
### Description of the enhancement
Leave display setting saved when reconnecting the video cable.

### Scenario when this would be used?
When reconnecting a video cable (HDMI, Display Port, VGA) where the display was the main one.

### Additional context
I have a main monitor in my studio, which I connect to my notebook. In ToolTip, my preferred display screen is the primary monitor. Sometimes I need to unplug the HDMI to go out with the notebook. When I do this, the preferred monitor setting automatically switches to the notebook screen. Every time I reconnect the monitor to the notebook, I have to keep selecting it every time again to be the main one.

Sometimes I need to do this 4 times a day. It ends up being exhausting. If the program itself can save the preferred monitor setting when reconnecting the HDMI, that would be perfect.

**Comment by Samuel12321** [comment]
Hi, thanks for reporting this bug.
We are aware of this issue, it annoys me as well.
We are working on fixing this for the next release.
Closing in favor of #736
