### ISSUE TITLE
A small question in Chinese translation

### ISSUE THREAD

**Issue by TPAXcc** [ModernFlyouts-Community/ModernFlyouts#1011]
### ModernFlyouts version

0.10.0.0

### Area with translation issue

Flyouts

### 🌐 Language affected or requested

zh-Hans

### ❌ Actual phrase(s)

插入
![图片](https://user-images.githubusercontent.com/91980905/167995512-a9ecad94-bbf8-4df4-b45d-7735fe9d27a3.png)

### ✔️ Expected phrase(s)

插入/覆写模式切换

**Comment by prakharb5** [comment]
If you'd like, can you please submit this as a pull request?
