### ISSUE TITLE
Audio flyout progress bar and media length not working as intended.

### ISSUE THREAD

**Issue by EliasRonefors** [ModernFlyouts-Community/ModernFlyouts#1019]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Home 21H2

### OS build

19044.1706

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Turn on any media on your computer, for example a video on youtube or music on spotify, then let it play for a short time. Change the volume of your computer or use any media control shortcuts and notice that the progress bar in ModernFlyouts does not work.

### ✔️ Expected Behavior

Audio Flyout ModernFlyouts should show time left of media, how long a piece of media is, and a progress bar that visualizes how much of a piece of media is left.

### ❌ Actual Behavior

Audio Flyouts sets time left of media to "0:00", total length of media to "0:00" and displays the progress bar always completely full. See attached image for visual demonstration.

![image](https://user-images.githubusercontent.com/90244703/169859070-b12677b1-a10e-42e1-9118-74b214978fe3.png)

### Other Software

Firefox
Spotify Desktop version 1.0.96.181.gf6bc1b6b
Edge

### Additional Context

The problem persists no matter what program I use to play media.

**Comment by Cyberdroid1** [comment]
Not all apps support the timeline bar.

[Check out more info here](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md)
