### ISSUE TITLE
ı cant find how to open modernflyouts

### ISSUE THREAD

**Issue by Laidra** [ModernFlyouts-Community/ModernFlyouts#1021]
when ı am gaming ı listen to music but when ı need to stop it ı cant find how to open modernfloyouts

**Comment by JohnLGalt** [comment]
Windows System tray - it's a blue icon that, when you hover your mouse over it, actually says "ToolTip".

![Screenshot 2022-05-26 152744](https://user-images.githubusercontent.com/7432512/170562581-68f46b37-5a5e-4523-8eb4-81a99b47a13c.png)

If you need to start it again, `ModernFlyouts (Preview)` is the name to search for / scroll through your apps.

HTH

**Comment by Samuel12321** [comment]
Closing as user error, but does reinforce the need for #146
