### ISSUE TITLE
Flyout Auto Alignment is not working

### ISSUE THREAD

**Issue by alessandro-newzoo** [ModernFlyouts-Community/ModernFlyouts#1024]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 21H2

### OS build

22000.675

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout, Lock keys Flyout

### Steps to reproduce

- Open Settings > Layout
- Set Flyout alignment to Auto, and change any alignment setting (top-left, bottom-right, etc)

### ✔️ Expected Behavior

The flyout should stick to the position chosen

### ❌ Actual Behavior

The flyout always follows the Manual setting, which in my case is top-left. 
So if I switch to Manual, change the coordinates, and back to Auto, the flyout will still use Manual coordinates.

### Additional Context

Video showing the issue: https://www.loom.com/share/5310693bead34984bbe2aaffa3f02682

**Comment by Cyberdroid1** [comment]
Yeah, this is a known issue with 0.9.3, wherein after using manual, it will break auto mode. Will be fixed with 0.11

For now, you can reset the app from windows settings.
