### ISSUE TITLE
Can't disable audio flyout

### ISSUE THREAD

**Issue by vdt2210** [ModernFlyouts-Community/ModernFlyouts#1027]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.1

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

1. Open app
2. Go to Audio
3. Disable Audio Flyout

### ✔️ Expected Behavior

Disable Audio Flyout and save option

### ❌ Actual Behavior

App not responding, crash and not save

**Comment by arnavbhate** [comment]
Duplicate of #888

**Comment by Samuel12321** [comment]
Duplicate of #592
