### ISSUE TITLE
Windows default flyout isn't hidden in Windows 11 22H2

### ISSUE THREAD

**Issue by Lorenzo-Effe** [ModernFlyouts-Community/ModernFlyouts#1029]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.1

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1. Increase the volume while ModernFlyouts is running
2. Windows's default flyout will still be visible.

![image](https://user-images.githubusercontent.com/80783030/172937741-5c93402c-773d-42fa-b7f7-fef9ff0a0462.png)

It's the same with brightness.

### ✔️ Expected Behavior

The default flyout of Windows should be hidden

### ❌ Actual Behavior

The flyout of Windows is still visible

### Additional Context

The problem persists even after uninstalling and reinstalling the app

**Comment by Cyberdroid1** [comment]
#920
