### ISSUE TITLE
unable to change song play slider 

### ISSUE THREAD

**Issue by Soren6999** [ModernFlyouts-Community/ModernFlyouts#1033]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

So i am using an application to play my apple music called Cider(beta). when i want to change the play time on the flyouts, it wouldn't let me. However, while doing this on Spotify, it works. 

### ✔️ Expected Behavior

I thought i was given the option to change the time stamp of each song via modern flyouts

### ❌ Actual Behavior

It would not let me to change time stamp of song. The entire bar is darken and the time is 0:00 and the end time is 0:00 on the bar 

### Other Software

Cider (beta) From the Microsoft store 

### Additional Context

Cider does not work, however i am allowed to change the time stamp on spotify

**Comment by Cyberdroid1** [comment]
Cider most probably does not support the timeline feature of the GSMTC API, hence the slider is greyed out.

You can try asking the app dev to add support for this feature.
