### ISSUE TITLE
ModernFlyouts (MFl) does not recognize MusicBee (with the Media Control Plugin) while it is running. MFl will only recognize MusicBee once I restart the MFl app.

### ISSUE THREAD

**Issue by KrisSchneider** [ModernFlyouts-Community/ModernFlyouts#1045]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 10 Pro 21H2

### OS build

19044.1806

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

**1. Open MusicBee and play a random song:**
![(explorer)m1P8r4_07-03-2022](https://user-images.githubusercontent.com/101912712/177080481-e84d223b-e91e-4e37-8a5d-0123ad2c538a.gif)

**2. Toggle ModernFlyouts using the volume control on your keyboard to see if ModernFlyouts recognizes your audio player.**
![(explorer)R615j8_07-03-2022](https://user-images.githubusercontent.com/101912712/177080999-fb8daeb7-6f2a-4389-aeab-1f757e381a39.gif)

**3. Restart ModernFlyouts, and toggle it again using the volume keys to confirm that ModernFlyouts recognizes MusicBee.**
![(explorer)V5s883_07-03-2022](https://user-images.githubusercontent.com/101912712/177081310-6500baae-a6ad-4124-807e-aa4accd08ebd.gif)
### 
**4. Congratulations! You will now have to repeat these steps every time you start/close MusicBee.**

### ✔️ Expected Behavior

I was expecting ModernFlyouts to normally recognize MusicBee.

### ❌ Actual Behavior

ModernFlyouts would not recognize MusicBee on the first session. So, I had to restart MFl in order to for the application to recognize MusicBee.

### Other Software

MusicBee (installed by ScoopInstaller, a package manager for Windows 10/11)

### Additional Context

N/A

**Comment by KrisSchneider** [comment]
> Suppose you don't have modernflyouts running. Does the default volume flyout show the media info correctly?

It works fine with the default metro flyout:
https://imgur.com/a/TDWUUxX

**Comment by KrisSchneider** [comment]
**UPDATE: I decided to uninstall ModernFlyouts entirely from my system by using the standard Windows uninstaller and removing remaining leftover files that were related to ModernFlyouts. Then I reinstalled ModernFlyouts using the installer package from the repositories releases section ([32669SamG.ModernFlyouts_0.9.3.0_neutral___pcy8vm99wrpcg.Msixbundle](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/download/0.9.3/32669SamG.ModernFlyouts_0.9.3.0_neutral___pcy8vm99wrpcg.Msixbundle)). My issue is now fixed. ModernFlyouts is now recognizing MusicBee properly this time.**

**Comment by KrisSchneider** [comment]
The bug appears in ModernFlyouts occasionally. Yesterday, ModernFlyouts was not working properly. But today, ModernFlyouts is working properly now.

**Comment by KrisSchneider** [comment]
I have found a small solution for this bug until it gets patched in later updates. 

1. First, you uninstall ModernFlyouts, and remove any remaining files released to ModernFlyouts. 
2. Second, then you open the Microsoft Store and search up “ModernFlyouts” on there. Once you find it in the MS Store, click on “Get”. 
3. After waiting a few mins for ModernFlyouts to install, open the app from the start menu. 
4. ModernFlyouts should now be functioning normally. If the bug occurs again, just repeat these 3 steps every time it happens.

**Comment by KrisSchneider** [comment]
My issue has been solved. It turns out I just needed to install a beta version of ModernFlyouts. The beta version fixes all the issues I had with the previous version.

**Comment by Samuel12321** [comment]
Which beta version?

**Comment by Samuel12321** [comment]
ok thanks
