### ISSUE TITLE
No scrubbing/song duration with foobar2000

### ISSUE THREAD

**Issue by theodotgr** [ModernFlyouts-Community/ModernFlyouts#1048]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 21H2

### OS build

22000.739

### Platform

x86

### Area(s) with issue?

Media Flyout

### Steps to reproduce

Change the playback of media using media control keys

### ✔️ Expected Behavior

Flyout shows the song thats playing in foobar2000 and allows me to scrub through the song/show duration of the song.

### ❌ Actual Behavior

Flyout shows the song thats playing but doesnt allow me to scrub through the song/doesnt show songs duration.
![image_2022-07-09_223316639](https://user-images.githubusercontent.com/100288685/178120167-51c46d72-cd53-4353-b766-f669e6305f4c.png)

### Other Software

Foobar2000

**Comment by Cyberdroid1** [comment]
Foobar doesn't support this feature.

Find out more here : https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md
