### ISSUE TITLE
Switching off 'Enable Audlo Flyout' causes crash

### ISSUE THREAD

**Issue by M-rt4** [ModernFlyouts-Community/ModernFlyouts#1051]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22622.290

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Switch off the "Enable Audio Flyout".

### ✔️ Expected Behavior

Turning off the audio flyout and display only media controls standalone.

### ❌ Actual Behavior

App crashing.

**Comment by Cyberdroid1** [comment]
#888
