### ISSUE TITLE
Windows flyout is not hidden in W11 22H2

### ISSUE THREAD

**Issue by Eyji** [ModernFlyouts-Community/ModernFlyouts#1053]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22622.290

### Platform

x86

### Steps to reproduce

Upgrade to 22H2

### ✔️ Expected Behavior

Windows flyout hidden

### ❌ Actual Behavior

Windows flyout is shown

**Comment by ZoomMan2** [comment]
SAME

**Comment by Cyberdroid1** [comment]
#920
