### ISSUE TITLE
Changing song doesn't update UI when changed on Spotify

### ISSUE THREAD

**Issue by bzefferino** [ModernFlyouts-Community/ModernFlyouts#1057]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 

### OS build

22000.795

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

Change the song, the UI shows, but it is always the same song at the same time showing.

### ✔️ Expected Behavior

Should show the updated song and album as well as time.

### ❌ Actual Behavior

The UI only shows the first song from whenever it froze.

### Other Software

Spotify Desktop App 1.1.90.859.gf1bb1e36

**Comment by Cyberdroid1** [comment]
Duplicate of #684
