### ISSUE TITLE
App randomly crashes after a period of time

### ISSUE THREAD

**Issue by HTMLdu** [ModernFlyouts-Community/ModernFlyouts#1058]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 21H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Wait a few hours to days and app will crash

### ✔️ Expected Behavior

Ability to see flyouts from ModernFlyouts

### ❌ Actual Behavior

The app crashed and I am not able to see Windows' volume flyout, or any of ModernFlyouts' flyouts

### Event Viewer logs

The program ModernFlyoutsHost.exe version 10.0.17763.1 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 5e0c
 Start Time: 01d8a76dc17f1e06
 Termination Time: 4294967295
 Application Path: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.9.3.0_x64__pcy8vm99wrpcg\ModernFlyoutsHost.exe
 Report Id: 28f47cb8-1b05-4685-bec8-e3341b2c7ef7
 Faulting package full name: 32669SamG.ModernFlyouts_0.9.3.0_x64__pcy8vm99wrpcg
 Faulting package-relative application ID: App
 Hang type: Quiesce

**Comment by Cyberdroid1** [comment]
#642
