### ISSUE TITLE
When I Set to No Audio Fly Out Its just crash

### ISSUE THREAD

**Issue by Not123456789** [ModernFlyouts-Community/ModernFlyouts#1061]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 22H2

### OS build

19045.1826

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Go to Audio Flyout and turn off Enable Audio Flyout

### ✔️ Expected Behavior

am expecting it to turn off the playing things

### ❌ Actual Behavior

just audio flyout no what playing

### Other Software

chrome edge and others browser 
spotify and others

**Comment by Cyberdroid1** [comment]
#888
