### ISSUE TITLE
Hover prompt is displayed in a wrong position.

### ISSUE THREAD

**Issue by john9999911** [ModernFlyouts-Community/ModernFlyouts#1074]
### ModernFlyouts Version

0.10.0

### Windows version

windows 11 21H2

### OS build

22000.832

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

![image](https://user-images.githubusercontent.com/80616586/184570197-9a707bea-90f2-49b7-9ad3-0322729f6039.png)
When I hover the mouse over the pause button, the prompt of the button is displayed under the interface. (You can see in the picture that there is a white rectangle under the interface.)

### ✔️ Expected Behavior

The prompt should be displayed over the interface.

### ❌ Actual Behavior

When I hover the mouse over the button, the prompt of the button is displayed under the interface.

**Comment by Cyberdroid1** [comment]
It's a known issue, and would be fixed with a future release
