### ISSUE TITLE
The interface displays a blank after I open the Caps Lock.

### ISSUE THREAD

**Issue by john9999911** [ModernFlyouts-Community/ModernFlyouts#1075]
### ModernFlyouts Version

0.10.0

### Windows version

windows 11 21H2

### OS build

22000.832

### Platform

x64

### Area(s) with issue?

Lock keys Flyout

### Steps to reproduce

![image](https://user-images.githubusercontent.com/80616586/184576299-3b784be9-1ca9-4793-b800-963a6e88b1a8.png)

### ✔️ Expected Behavior

The interface should display others.

### ❌ Actual Behavior

The interface just displays a blank after I open the Caps Lock.

**Comment by Cyberdroid1** [comment]
This is a known issue with the 0.10 beta and will be fixed with the next release
