### ISSUE TITLE
Port to Linux

### ISSUE THREAD

**Issue by Drakon1505** [ModernFlyouts-Community/ModernFlyouts#1080]
### Description of the new feature / enhancement

how cool it would be if this program was on linux

### Scenario when this would be used?

I adjust the volume and see this beauty

**Comment by Samuel12321** [comment]
Hi @Drakon1505 We have no plans to port to Linux. Most of the app is quite heavily windows specific. We wouldn't object if someone wanted to submit a PR for this, but the core developers wont be focusing on this.

**Comment by Drakon1505** [comment]
Thank you @Samuel12321 for the answer
