### ISSUE TITLE
Auto-closing flyout not closing

### ISSUE THREAD

**Issue by MarioP-Dev** [ModernFlyouts-Community/ModernFlyouts#1082]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Pro

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Modify volume, play or use the Flyout

### ✔️ Expected Behavior

The flyout should dissapear in some seconds after it use

### ❌ Actual Behavior

The flyout won't desapear in the expected seconds. It will stick until manually closing

**Comment by ezbooz** [comment]
same

**Comment by MarioP-Dev** [comment]
Suddenly the flyout started working again after closing all apps, restarting and updating Windows.
Closing the issue.
