### ISSUE TITLE
Audio buttons become disabled after restarting spotify

### ISSUE THREAD

**Issue by dfantonio** [ModernFlyouts-Community/ModernFlyouts#1083]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Pro 21H2

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

1. Use spotify to play any music:
![image](https://user-images.githubusercontent.com/40124768/186203097-2b7d73eb-2881-41a8-9c61-385aae58a5cb.png)

2. Close spotify
3. Open spotify again
4. Adjust the audio to open the flyout and notice that the buttons to pause and skip the music are "disabled", I can't click on them:
5. 
![image](https://user-images.githubusercontent.com/40124768/186203420-a4a913f9-5d31-48c5-8ef0-55a5f2e17d4b.png)

To fix this I need to totally close the modern flyout and reopen it. After doing this it works again.

### ✔️ Expected Behavior

The action buttons should work even when I close and reopen spotify.

It's worth noting that the default media control keeps working normally when I reopen spotify:
![image](https://user-images.githubusercontent.com/40124768/186203921-092423fe-486f-416d-a57f-554e3f1d3c26.png)
Spotify

### ❌ Actual Behavior

The action buttons become disabled when I close and reopen spotify.

### Other Software

Spotify from windows store

**Comment by Cyberdroid1** [comment]
#446
