### ISSUE TITLE
Top-Center positioning doesn't work

### ISSUE THREAD

**Issue by Sollace** [ModernFlyouts-Community/ModernFlyouts#1089]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 21H2

### OS build

19044.1889

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

In the settiongs "Layout" section go to "Flyout placement"

- Set placement mode to "Auto"
- Set flyout alignment to Top/Center
![image](https://user-images.githubusercontent.com/6429283/188820346-9be43836-d638-4623-9245-a7df508079c0.png)

### ✔️ Expected Behavior

The flyout should be aligned to the top edge of the screen and centered horizontally, both after logging in and when clicking the "align to default position" on the flyout's header bar.

### ❌ Actual Behavior

After a reboot the flyout appears either aligned to the top/left or center of the screen. After dragging the flyout to the correct position, clicking "align to default position" sends the flyout to the top/left.

Changing the alignment in the settings does not affect this behaviour.

### Additional Context

This is a fresh install from the Windows Store.

**Comment by Cyberdroid1** [comment]
This is a big in 0.9.3 wherein dragging the flyout manually breaks the auto flyout alignment. For now, refrain from dragging manually.

To fix this bug, reset the app from settings.

**Comment by Sollace** [comment]
Shucks. Well okay, thank you

**Comment by Cyberdroid1** [comment]
This bug will be fixed with the next release (0.11) which would be released soon :D
