### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by ALeX400** [ModernFlyouts-Community/ModernFlyouts#1114]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 21H2

### OS build

19044.2075

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Step by step processes:

1. Windows starts 

2. startup programs 

3. application starts and open popup of application:

![v1](https://user-images.githubusercontent.com/10267988/193816714-8e465a68-0428-4754-b43c-3e900d047712.png)

4. although the status of "show icon in system tray area" option is disabled...

![v2](https://user-images.githubusercontent.com/10267988/193816738-d38f91f7-b1ee-4a52-b6b0-f46b167f9106.png)

... the application icon is displayed in the system tray area:

![v3](https://user-images.githubusercontent.com/10267988/193816778-6dd98070-abf3-4042-bda7-a7597df78f88.png)

### ✔️ Expected Behavior

the app starts in silent mode/minimized
the application is not displayed in the system tray area

### ❌ Actual Behavior

certain settings of the application are reset at startup but the application starts successfully
the application opens the application popup at startup and does not run in silent mode/minimized

### Additional Context

the application behavior was from my own inference and i don't have an event log

the application does not always display the icon in the system tray area
but the popup is displayed regardless

#### Edit:
version **0.10.0.0** in beta state, seems to solve this problem
i want to mention that i performed several reinstallation and deletion processes of the application's previous data
### Edit 2:
same problem
just that the icon still appears and the popup doesn't

**Comment by brian6932** [comment]
It doesn't start up at all for me, you can make a shortcut to the executable within `WindowsApps`, as a workaround, but you really shouldn't have to do that
