### ISSUE TITLE
Будет ли доведен до ума 0.10?

### ISSUE THREAD

**Issue by llimonix** [ModernFlyouts-Community/ModernFlyouts#1117]
### Description of the new feature / enhancement

Установил бетку, так как там исправлено много багов, но плохо выглядит без отображения нажатий caps lock / num lock и прочее. Будет ли доделано или на проект уже давно положили болт?

### Scenario when this would be used?

.

**Comment by Samuel12321** [comment]
we are continuing to work on 0.11 which we hope to release soon.
