### ISSUE TITLE
Volume flyout doesn't override the new default volume control since windows build 25227.1000

### ISSUE THREAD

**Issue by rateforx** [ModernFlyouts-Community/ModernFlyouts#1129]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

25231.1000

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

1. Change volume with a hotkey (mouse or keyboard)

### ✔️ Expected Behavior

Modern flyout displays on their own.
![image](https://user-images.githubusercontent.com/24194569/198575906-47fe5e8e-5765-478b-b25a-118338dbed32.png)

### ❌ Actual Behavior

A new Win11 volume popup appears on the bottom center of the screen.

### Additional Context

I am on the windows insider build, problem appeared after updating to Windows 11 Insider Preview 25227.1000 (rs_prerelease).

**Comment by Nateay0** [comment]
Same here

**Comment by Xryphon** [comment]
HideVolumeOSD seems to "fix" this issue for now. I would like to see this be built into ModernFlyouts as default, so that newer Windows 11 users can use this as well.

**Comment by rateforx** [comment]
> HideVolumeOSD
What exactly is that? A registry key?
Can you provide a step-by-step?

**Comment by capitano799** [comment]
https://github.com/gpkgpk/HideVolumeOSD/releases

**Comment by izMotions** [comment]
Same here
