### ISSUE TITLE
Windows 11 update (Windows volume still showing)

### ISSUE THREAD

**Issue by KapelaanHP** [ModernFlyouts-Community/ModernFlyouts#1135]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22h2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

With volume changes windows pops up the new windows 11 volume window as well. Is there a work around to only show ModernFlyout volume and NOT windows 11?
![image](https://user-images.githubusercontent.com/117721424/200521422-6f10a0b2-de55-479c-8669-7f3f8b6aebc1.png)

### ❌ Actual Behavior

Sorry, new to github.

**Comment by zYn-Hazard** [comment]
same thing here,

**Comment by Poopooracoocoo** [comment]
Duplicate of #920

**Comment by Ridoou** [comment]
I use HideVolumeOSD by Marcus Venturi to hide the W11 one
