### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by Berops423** [ModernFlyouts-Community/ModernFlyouts#1137]
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 10 22h2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

You hover on the music controls in the audio flyout, and the tooltip appears behind it.

### ✔️ Expected Behavior

the tooltips should appear at the front, right?

### ❌ Actual Behavior

they appeared at the back instead.

**Comment by Movisivi** [comment]
@Cyberdroid1 When will 0.11 release? Are you guys even working on it? There have been no new commits since April. Let us know if this project is dead so we can move on to finding other apps

**Comment by Samuel12321** [comment]
Hi, we are still working on it internally. We just haven't pushed anything yet.
Apologies for the delay, we have all been very busy, in addition to waiting for microsoft to fix its mess of winui 3.
No eta yet, but I will talk to our other contributors about setting a date.
