### ISSUE TITLE
Timeline info suggestion

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#114]
> The Time Line info bar should always show in panel, instead of click button to see the progress!

Store review, perhaps this could be a toggle setting

**Comment by ShankarBUS** [comment]
Nice suggestion.

But the layout would be different from what it is now.

We may expect some issues.

I'll think of an efficient way to do this

**Comment by Cyberdroid1** [comment]
Isn't this counted as duplicate of #97?

**Comment by WinstonSepruko** [comment]
Not necessarily, but they can definitely be bundled together.

**Comment by ShankarBUS** [comment]
They're mutually exclusive.

That one's for asking support.

This one's for UX.

**Comment by Cyberdroid1** [comment]
Ah I see.

**Comment by ShankarBUS** [comment]
Done
