### ISSUE TITLE
Crash when Disable Audio confing

### ISSUE THREAD

**Issue by Montesi-Flavio** [ModernFlyouts-Community/ModernFlyouts#1140]
### ModernFlyouts Version

"0.9.3.0"

### Windows version

"Windows 10 22H2"

### Platform

x86

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

when you trigger the main switch in Audio configs it instantly crash

### ❌ Actual Behavior

crash

**Comment by Spilyah** [comment]
I have the same issue, did you find any solution to disable the audio slider ?

**Comment by stevenya97** [comment]
There has been a beta build [v0.10.0-beta.1](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.1) available under Releases that addresses the crash bug. Fixes it for me, and I can disable the audio flyout no issues.  See #592  for crash details

**Comment by war59312** [comment]
Tried that myself but the cert is expired so cant run even after adding to root store.

Win 11 22H2

**Comment by prakharb5** [comment]
Duplicate of #592
