### ISSUE TITLE
Media track position for Tidal

### ISSUE THREAD

**Issue by J055Y** [ModernFlyouts-Community/ModernFlyouts#1143]
### Description of the new feature / enhancement

Currently, track position information does not work for Tidal (shows 0:00 - 0:00 in the media flyout).
Would be neat if this could be implemented. 

Alternatively, would great if there were an option to hide the track position, so there isn't a redundant track position bar in the media flyout.

### Scenario when this would be used?

When using Tidal as a music streaming service.

### Additional context

![image](https://user-images.githubusercontent.com/13116746/205131169-6eb68294-71af-4f83-af35-d8f459260d64.png)

**Comment by Poopooracoocoo** [comment]
@J055Y Tidal would have to implement it. File a suggestion over there.
