### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by error7404** [ModernFlyouts-Community/ModernFlyouts#1146]
The certificate in the beta release ([v0.10.0-beta.1](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.1)) of the app is expired since the `2022/10/05 17:47:49`

**Comment by foursplaysroblox** [comment]
same issue

**Comment by zahinwadud** [comment]
Same situation here. 
Then I installed the _store_ version.

**Comment by error7404** [comment]
That not the same version

**Comment by boromyr** [comment]
same problem

**Comment by hdadhich01** [comment]
Would recommend [this workaround](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1161#issuecomment-1399208776) for now.

**Comment by Samuel12321** [comment]
Resolved with 0.10 beta release
