### ISSUE TITLE
Unable to install beta

### ISSUE THREAD

**Issue by yoyoda2048** [ModernFlyouts-Community/ModernFlyouts#1149]
### ModernFlyouts Version

beta

### Windows version

Win 10 22H2

### OS build

19045.2311

### Platform

x64

### Area(s) with issue?

Installer

### Steps to reproduce

Trying to install beta.
![Capture d’écran 2022-12-11 133236](https://user-images.githubusercontent.com/120314258/206903890-54941f76-7ae5-4888-a9e4-d133f88611b5.png)

### ✔️ Expected Behavior

Is there any way to install beta version ?
The only certificate I found is no longer valid.

### ❌ Actual Behavior

Can't install beta version.

**Comment by Samuel12321** [comment]
Thanks for letting us know

**Comment by Samuel12321** [comment]
Duplicate
