### ISSUE TITLE
ModernFlyouts not working.

### ISSUE THREAD

**Issue by faruq-q** [ModernFlyouts-Community/ModernFlyouts#1161]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### Platform

x64, x86

### Area(s) with issue?

General

### Steps to reproduce

I turn on my computer, I open modernflyoutsu, but it does not open. It doesn't show up in task manager. I tried repairing from application settings, tried resetting, deleting and reinstalling but it doesn't fix.

Edit: When I run the application, something called Application Frame Host works in Task Manager, but the application still does not work.

![Screenshot_5](https://user-images.githubusercontent.com/76094369/213329702-d1e56719-fc9b-4b32-ba79-c9669861a2b1.png)

### ✔️ Expected Behavior

Opening and using

### ❌ Actual Behavior

.

**Comment by Naveen-131** [comment]
Facing the same issue.

**Comment by hdadhich01** [comment]
Seems to be persistent on 10/11 21H2 distributions and up. Development has been inactive as of 5 months ago on an [update branch](https://github.com/ModernFlyouts-Community/ModernFlyouts/tree/0.11-winui3). A current workaround is by installing the last working version at [0.9.0](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.9.0) with the `.Msixbundle` executable (at least on my 11 22H2). However, you will need to [cease Windows Store updates](https://winbuzzer.com/2020/07/17/how-to-turn-off-automatic-updates-for-microsoft-store-apps-in-windows-10-xcxwbt/) to keep it functioning. Although this works, I can't seem to find a non-tedious way to disable updates for a single app. I'm not sure what the issue has been with the latest ModernFlyouts versions, probably expired certification.

**Comment by faruq-q** [comment]
> Seems to be persistent on 10/11 21H2 distributions and up. Development has been inactive as of 5 months ago on an [update branch](https://github.com/ModernFlyouts-Community/ModernFlyouts/tree/0.11-winui3). A current workaround is by installing the last working version at [0.9.0](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.9.0) with the `.Msixbundle` executable (at least on my 11 22H2). However, you will need to [cease Windows Store updates](https://winbuzzer.com/2020/07/17/how-to-turn-off-automatic-updates-for-microsoft-store-apps-in-windows-10-xcxwbt/) to keep it functioning. Although this works, I can't seem to find a non-tedious way to disable updates for a single app. I'm not sure what the issue has been with the latest ModernFlyouts versions, probably expired certification.

What is a .msixbundle? if file what is the file location?

**Comment by hdadhich01** [comment]
It's in the Assets section of the [0.9.0](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.9.0) release page. You can also download with this [direct link](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/download/v0.9.0/32669SamG.ModernFlyouts_0.9.0.0_neutral___pcy8vm99wrpcg.Msixbundle).

**Comment by faruq-q** [comment]
> It's in the Assets section of the [0.9.0](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.9.0) release page. You can also download with this [direct link](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/download/v0.9.0/32669SamG.ModernFlyouts_0.9.0.0_neutral___pcy8vm99wrpcg.Msixbundle).

oh finally it worked, thank you for your help

**Comment by faruq-q** [comment]
> It's in the Assets section of the [0.9.0](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.9.0) release page. You can also download with this [direct link](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/download/v0.9.0/32669SamG.ModernFlyouts_0.9.0.0_neutral___pcy8vm99wrpcg.Msixbundle).
