### ISSUE TITLE
No Abre en Windows 11

### ISSUE THREAD

**Issue by ghost** [ModernFlyouts-Community/ModernFlyouts#1164]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 21H2

### OS build

22000.1516

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Trato de iniciar la aplicacion pero no abre

### ✔️ Expected Behavior

Activar el control de volumen de modern flyouts e iniciar la aplicacion automaticamente

### ❌ Actual Behavior

No se inicia ni abre la aplicacion

**Comment by WiseTomCat** [comment]
Thank you for this answer of installing the v9.0 on my Windows 11 21h2. I wish the OP could close this issue as there are too many issues in this forum.

**Comment by casperdcvd** [comment]
> First, delete the version installed on your computer. then disable automatic updates from microsoft store. then download and install the version in [this link](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/download/v0.9.0/32669SamG.ModernFlyouts_0.9.0.0_neutral___pcy8vm99wrpcg.Msixbundle). It should work now.
> 
> ![Screenshot_52](https://user-images.githubusercontent.com/76094369/216062567-8d1c47a0-b8ae-442c-a2f1-9e338f92ebcc.png) ![Screenshot_53](https://user-images.githubusercontent.com/76094369/216062672-3e79d7b5-397a-4998-9237-556584fa814c.png) ![Screenshot_54](https://user-images.githubusercontent.com/76094369/216062731-32d10b73-d118-4027-8a4c-e11010b21e7a.png)

I downloaded Windows 11 and reverted back again after not liking it and now ModernFlyouts won't start at all, even with this version it immediately terminates itself after opening it.

**Comment by manstheram** [comment]
This bug does not occur on v10 beta 3, or so I believe.

**Comment by InteXX** [comment]
@faruq-q Thank you, that works.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
