### ISSUE TITLE
Windows 11 default flyout still appearing

### ISSUE THREAD

**Issue by JhalCMP** [ModernFlyouts-Community/ModernFlyouts#1166]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.1105

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Just changing the volume.

### ✔️ Expected Behavior

Volume flyout appears and shows me when the volume is changing

### ❌ Actual Behavior

It's still changed but the old windows flyout is still appearing.

**Comment by DeZenTID** [comment]
Issue already discussed in https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/920

**Comment by manstheram** [comment]
Fixed in v10 beta 3.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
