### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Skrubi12** [ModernFlyouts-Community/ModernFlyouts#1169]
### ModernFlyouts Version

0.9.1

### Windows version

Windows 10 H20

### OS build

22523.1000

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

i cant start modern flyouts. i did everything i needed to do but i cant start it up, it doesnt show me at the left top corner.

### ✔️ Expected Behavior

.

### ❌ Actual Behavior

.

### Other Software

.

### Additional Context

.

**Comment by Xndr2** [comment]
I'm having the same issue. It also doesn't show in the tray icons for me.

**Comment by bajwaboi** [comment]
> ### ModernFlyouts Version
> 0.9.1
> 
> ### Windows version
> Windows 10 H20
> 
> ### OS build
> 22523.1000
> 
> ### Platform
> x64
> 
> ### Area(s) with issue?
> General
> 
> ### Steps to reproduce
> i cant start modern flyouts. i did everything i needed to do but i cant start it up, it doesnt show me at the left top corner.
> 
> ### ✔️ Expected Behavior
> .
> 
> ### ❌ Actual Behavior
> .
> 
> ### Other Software
> .
> 
> ### Additional Context
> .

same.

**Comment by bajwaboi** [comment]
@Xndr2 @Skrubi12 https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1164#issuecomment-1412100509

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
