### ISSUE TITLE
The App doesn't appear

### ISSUE THREAD

**Issue by thebrodie** [ModernFlyouts-Community/ModernFlyouts#1170]
### Provide a description of requested docs changes

The App doesn't work, I'm using the Spotify, YouTube, twitch all these app and modern Flyouts can't appear at all

**Comment by bajwaboi** [comment]
@thebrodie https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1164#issuecomment-1412100509

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
