### ISSUE TITLE
v0.10.0-beta.1 -- Certification Expired

### ISSUE THREAD

**Issue by C0rtx** [ModernFlyouts-Community/ModernFlyouts#1173]
### ModernFlyouts Version

none

### Windows version

Windows 10 Pro 22H2

### Platform

x64

### Steps to reproduce

Installing Certification while being expired.
![image](https://user-images.githubusercontent.com/126973723/223272317-5c95176d-73fd-4672-a76c-19628dbc7d44.png)

### ✔️ Expected Behavior

Certification not be expired and Modern Flyouts BETA be installed correctly.

### ❌ Actual Behavior

Modern Flyouts BETA Certification Expired

### Additional Context

Creators should upload a Renewed Certification to the Microsoft Store, or just give a new Cert file.

I know this project is being rewritten, but you should include pictures to the progress to get hype.
Also is very sad the community being wiped because of no hype about ModernFlyouts, though I think they have a good reason for it.

I hope Rewritten ModernFlyouts will solve our problems! :)

**Comment by Erikcb91** [comment]
You can use this tutorial to make it work, i just tried and worked for me :D
https://forum.xda-developers.com/t/install-unsigned-appx-uwp.4178179/

**Comment by C0rtx** [comment]
> You can use this tutorial to make it work, i just tried and worked for me :D https://forum.xda-developers.com/t/install-unsigned-appx-uwp.4178179/

Can you send me your custom msixbundle with the cert fix installed?
It doesn't seem to want to open with the .msixbundle extension.

**Comment by C0rtx** [comment]
w

**Comment by jh30uk** [comment]
Thanks for doing the above (I was going to ask but he beat me to it) but you forgor the password to install the Cert.

**Comment by C0rtx** [comment]
> [Modern Flyouts.zip](https://github.com/ModernFlyouts-Community/ModernFlyouts/files/10969198/Modern.Flyouts.zip) This are my appx and my cert file, install first the certificate and then the app, it should work (it did for me).

Thank you, but whats the password of the .cer file??

**Comment by C0rtx** [comment]
[Ignore all that above, I literally only can post comments if I close the issue.]
like now it will also close.

> Thanks for doing the above (I was going to ask but he beat me to it) but you forgor the password to install the Cert.

Also the cert file doesn't expire?

**Comment by C0rtx** [comment]
It worked, Thank you.

**Comment by jh30uk** [comment]
I cannot get it to install.
I install the Cert and left all setting default so current user not local machine, but the App still looks for the Cert to install.

I just ran both from the desktop not a folder in C etc.

**Comment by Erikcb91** [comment]
> 

Yea, did you follow the instructions from the link i sent?

![image](https://user-images.githubusercontent.com/75399666/225758750-cbd1eaaa-6248-4b07-aa82-6d2c36f075bc.png)

Do it that way and then install the app, it should work as it did or us.

**Comment by jh30uk** [comment]
Thanks for detailed instructions, it worked.

TBH it does not look much different to the previous build, time will tell it is less temperamental.
