### ISSUE TITLE
Software certificate expiration

### ISSUE THREAD

**Issue by wsilenceio** [ModernFlyouts-Community/ModernFlyouts#1180]
### ModernFlyouts Version

v0.10.0-beta.1

### Windows version

Windows 11 22H2

### OS build

25346.1001

### Platform

x64

### Area(s) with issue?

Installer

### Steps to reproduce

I have already installed the certificate, but the certificate has expired and the system prompts that I cannot install this application.
![1682228025159](https://user-images.githubusercontent.com/114924470/233821711-cdea8a31-4639-414e-85be-4a989a309a8a.png)

### ✔️ Expected Behavior

After installing the certificate, the application can be installed and started normally.

### ❌ Actual Behavior

The installation program prompts that the publisher certificate for this application package cannot be verified. Please contact your system administrator or application developer to obtain a new application package with a verification certificate. The root certificate and all direct certificates signed in the application package must be verified. （0x800B010A）

**Comment by jh30uk** [comment]
Did you even use search?

This was posted before and answered, and TBH it is so buggy/non functionable you are better off on the current non beta build.

**Comment by manstheram** [comment]
use this workaround: https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1161#issuecomment-1399208776

**Comment by humansouls** [comment]
**FIX**
Disable internet > go to time settings > disable "Set time automaticaly" > set your date between 20.10.2021 - 20.10.2022 > install certificate to Local machine - trusted people > install .msixbundle app

**Comment by Samuel12321** [comment]
@wsilenceio this should be resolved with our new beta being released
