### ISSUE TITLE
Spotify Progress Bar Getting Stuck

### ISSUE THREAD

**Issue by CyberExpert04** [ModernFlyouts-Community/ModernFlyouts#1182]
When I pause/play, the progress bar updates, but doesn't update live. I know you guys have a ton of issues logged by users of your product. I absolutely love it, and this is a small QoL issue. But I'd love to see it fixed. You devs are doing a great thing here, and yours looks MUCH better than the default. Thanks!

**Comment by prakharb5** [comment]
Spotify followed Microsoft's suggestion to only update status every 4-5 seconds. Nothing can be done, unfortunately.
