### ISSUE TITLE
Vertical direction volume bar

### ISSUE THREAD

**Issue by fate1ess** [ModernFlyouts-Community/ModernFlyouts#1183]
### Description of the new feature / enhancement

Wish to set the vertical direction volume bar

### Scenario when this would be used?

all.

### Additional context

Something like this
![Snipaste_2023-05-01_13-32-32](https://user-images.githubusercontent.com/25172023/235411573-1ea49347-6b55-40c9-b7da-a45c2ab926fe.png)
not
![Snipaste_2023-05-01_13-28-59](https://user-images.githubusercontent.com/25172023/235411591-2bcbfc97-4356-417b-93f7-5edb3531221d.png)

**Comment by fate1ess** [comment]
> I second this. 我支持这个。
> 
> Why would I want a horizontal bar in the first place considering pretty much all previous iterations of Windows used a vertical one?考虑到几乎所有以前的 Windows 迭代都使用垂直条，为什么我首先想要一个水平条？

I use the "ModernFlyouts" software because I hate the large volume bar in Win10, just like this:

![2c033a0f-5f83-4e7b-b4ae-1b0afd361557](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/25172023/3f65b7e3-b60a-4ca6-a5d9-4d3d64ecdd8c)

But I'm not quite used to the horizontal volume bar, I still prefer the vertical one.

**Comment by manstheram** [comment]
I've finished this in my pull-request #1217

**Comment by manstheram** [comment]
@Samuel12321
