### ISSUE TITLE
MS STORE is outdated

### ISSUE THREAD

**Issue by caleb-gamer** [ModernFlyouts-Community/ModernFlyouts#1186]
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/89547443/d3a878fa-b9c8-4c68-932e-bdc9eb1129c3)
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/89547443/2438d102-c6f5-435a-9a58-21870a33f4fc)
the microsoft store version appears to be outdated compared to github.

**Comment by FrzMtrsprt** [comment]
It's only the changlog that was not updated. The actual latest version is still 0.9.3.

Result from https://store.rg-adguard.net/:
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/15852717/a959ab08-c1cb-4692-8c79-bf915261b0e2)
