### ISSUE TITLE
切换输入法时，音量弹窗 异常弹出

### ISSUE THREAD

**Issue by God-Dragon-God** [ModernFlyouts-Community/ModernFlyouts#1192]
### ModernFlyouts Version

0.9.1

### Windows version

Windows 10 20H2

### OS build

22523.1000

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

按下Shift+Ctrl就会出现音量弹窗，只是弹窗并不会改变音量
具体操作：先按住Ctrl不放，在点击Shift，就会触发。
如先按住Shift，在点击Ctrl，则不会触发。

### ✔️ Expected Behavior

不知道是哪的问题，如是软件问题希望改进为Shift+Ctrl组合键时不触发音量弹窗

### ❌ Actual Behavior

因为我把切换输入法改成了Shift+Ctrl，切换输入法时，概率会出现音量弹窗

**Comment by littlewhitecloud** [comment]
这个算是按键冲突吧
