### ISSUE TITLE
Tooltip will show behind the window

### ISSUE THREAD

**Issue by littlewhitecloud** [ModernFlyouts-Community/ModernFlyouts#1194]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 22H2

### OS build

19045.3031

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Show the Audio Flyout.
Put your mouse on the any of the button who can show the tooltip.
You will see the tooltip is behind the window.
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/71159641/3fc65bf4-2ae5-462f-901a-4042babdec01)

### ✔️ Expected Behavior

The tooltip shows in front of the window

### ❌ Actual Behavior

The tooltip shows behind the window.

### Other Software

/

### Additional Context

/

**Comment by manstheram** [comment]
This does not happen for me on v10 beta 3.
