### ISSUE TITLE
Modernflyouts immediately terminates after opening it

### ISSUE THREAD

**Issue by casperdcvd** [ModernFlyouts-Community/ModernFlyouts#1196]
### ModernFlyouts Version

All versions

### Windows version

Windows 10 22H2 (OS Build 19045.3086)

### OS build

 OS Build 19045.3086

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

A while back I downloaded Windows 11 but reverted back within the hour because I didn't like the WIndows 11 layout and options. After that ModernFlyouts doesn't seem to work anymore, even after removing and downloading ModernFlyouts again it still doesn't work. I have tried a few fixes in this forum but none of them have worked. I have tried [this](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1164#issuecomment-1412100509) too. 

### ✔️ Expected Behavior

I expect the app to open and work like it is supposed to and how it used to work.

### ❌ Actual Behavior

The app does fire up, I notice ModernFlyout's icon starting in the hidden icon tab on the taskbar but it closes immediately after seeing it.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
