### ISSUE TITLE
Does not open even though I have downloaded the latest version

### ISSUE THREAD

**Issue by hhd43** [ModernFlyouts-Community/ModernFlyouts#1200]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

I just installed it from the microsoft store and try to open it. it does not work :(

### ✔️ Expected Behavior

For it to open

### ❌ Actual Behavior

does not open

**Comment by manstheram** [comment]
Try using the 0.9.0.0 build from the releases tab.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
