### ISSUE TITLE
the app doesnt open

### ISSUE THREAD

**Issue by TheMaker69420** [ModernFlyouts-Community/ModernFlyouts#1201]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

installed from microsoft store, then github, and then tried repairing it in settings, but it still doesnt open.

### ✔️ Expected Behavior

i was expecting the app to open to a menu of some kind. i wouldnt know because this is my first time using modernflyouts.

### ❌ Actual Behavior

the app doesnt open

**Comment by WiseTomCat** [comment]
try the version 9.0 which might work.....only that specific version works on my 21h2

**Comment by shuohao** [comment]
same。Windows11 23H2

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
