### ISSUE TITLE
Modern Flyout showing together with windows internal volume control

### ISSUE THREAD

**Issue by MrfalconGER** [ModernFlyouts-Community/ModernFlyouts#1203]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 Enterprise 22H2

### OS build

22621.1992

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

When I started it and changed the volume it showed both volume parts at the bottom and at the top left corner ![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/96948850/d0ac5c9e-8797-4acb-b3c2-58ba65f3b7d6)

### ✔️ Expected Behavior

I expected that only the part at the left top corner will show up

### ❌ Actual Behavior

it showed both audio controls (windows internal and modern flyouts)

**Comment by Hit4man47** [comment]
update it to 0.10.0-beta.3 it has been fixed
[0.10.0-beta.3](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.3)

**Comment by Samuel12321** [comment]
Fixed in 0.10 beta 3
