### ISSUE TITLE
Modern Flyouts Not showing Up

### ISSUE THREAD

**Issue by Hit4man47** [ModernFlyouts-Community/ModernFlyouts#1207]
### ModernFlyouts Version

10.0.0

### Windows version

Windows 11 23H2

### OS build

25915.1000

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

I recently updated my Windows Insider Version to 2915.1000, and I don't have any pop-ups for Modern Flyouts. Then I uninstalled and reinstalled it, but the problem persisted. Then I updated the Modern Flyouts to Beta Version 0.10.0-beta.3, but the problem still exists, and somehow the Windows default flyout stopped appearing, which fixed the last bug of both popping out at the same time, i.e., Windows default and Modern Flyouts, But now the Modern Flyout is Also not appearing.

Help!!! plz

### ✔️ Expected Behavior

Modern Flyouts appears flawlessly and the windows default flyout does not appear

### ❌ Actual Behavior

The Modern Flyout is not appearing when the Default flyout is on Modern Flyouts

**Comment by manstheram** [comment]
Can you see that the app is open in the tray section? There used to be an issue where it would close immediately or freeze up. I will also try reproducing this when I can.

**Comment by Hit4man47** [comment]
Yes I can see the app in the tray

**Comment by manstheram** [comment]
Which insider channel are you in?

**Comment by Hit4man47** [comment]
> Which insider channel are you in? Is it beta?

Canery I guess.

**Comment by manstheram** [comment]
Well, I just installed Beta by accident since that was recommended, I'll switch to Canary then.

**Comment by manstheram** [comment]
For your info, Beta works fine so far. I'm gonna have to reset my vm since I started with only 50 gigs of space so this will take a while..

**Comment by Hit4man47** [comment]
> For your info, Beta works fine so far. I'm gonna have to reset my vm since I started with only 50 gigs of space so this will take a while..

Any Update On the situation.

**Comment by manstheram** [comment]
@Hit4man47 I've reset my vm 2 times and still cannot get into that channel stupidly enough (keep getting some error when I hit install in the update page). I'm taking a break in the mean time, so I'll restart working on it probably from tomorrow. It might be an issue with some drivers so it'll take a while before I can actually update..

**Comment by Hit4man47** [comment]
@manstheram any update on the issue

**Comment by manstheram** [comment]
@Hit4man47 I am working on it as I finally got onto the channel. It's just that there's a lot that could be going wrong and probably is going wrong and this code wasn't originally written by me. I'll keep working at it. The thing is, this might be a temporary issue and Microsoft might fix whatever they screwed with very soon.

**Comment by manstheram** [comment]
@Hit4man47 I have a suspicion that the issue is being caused by the CreateWindowInBand function from v9.0.0, so theoretically, any version before that works alright if you want to know. However, the old versions don't have the fix I put in the new beta for both of the volume popups showing.

**Comment by manstheram** [comment]
It could also be the feature to set which display the flyouts show on.

**Comment by manstheram** [comment]
@Hit4man47 I've figured out what's causing the issue, when the window is made, WS_EX_NOREDIRECTIONBITMAP is used as the style of the window so it can have transparency around it. When I get rid of the style, the flyout can appear, but it has a noticeable black background behind it. I'll see if I can find a workaround, otherwise I can't fix it.

**Comment by Hit4man47** [comment]
@manstheram thanks for your efforts.😀😀

**Comment by manstheram** [comment]
@Hit4man47 I think I fixed it. If I have, it was only one line of code.

**Comment by Hit4man47** [comment]
@manstheram so have you updated the version now or do I have to wait

**Comment by manstheram** [comment]
Honestly, I don't know. I'll publish it on my repo soon.

**Comment by Samuel12321** [comment]
I can publish a 0.10 beta 4 and run some tests.

**Comment by manstheram** [comment]
@Samuel12321 That'd probably be better. 👍

**Comment by manstheram** [comment]
I did make a pull-request so if you would like to do that, that'd be alright.

**Comment by fancybear-dev** [comment]
I'm running latest canary build 25931 and have the same issue that is likely solved here. Will the beta 4 be released soon?

**Comment by Hit4man47** [comment]
@manstheram, any idea about when the  0.10.4 beta will be released?

**Comment by manstheram** [comment]
Gotta ask @Samuel12321.

**Comment by Hit4man47** [comment]
@Samuel12321 any idea about when the  0.10.4 beta will be released?

**Comment by Samuel12321** [comment]
If all goes according to plan, I will release 0.10 beta 4 tomorrow

**Comment by Samuel12321** [comment]
released

**Comment by fancybear-dev** [comment]
> released

Much appreciated!

**Comment by Poopooracoocoo** [comment]
Any chance of a stable release?

**Comment by manstheram** [comment]
@Samuel12321

**Comment by Samuel12321** [comment]
Will put one together this weekend.

**Comment by wefalltomorrow** [comment]
> Will put one together this weekend.

ETA? :)

**Comment by manstheram** [comment]
@wefalltomorrow The devs are planning to rewrite the UI for this app so it'll be a long while.

**Comment by wefalltomorrow** [comment]
> @wefalltomorrow The devs are planning to rewrite the UI for this app so it'll be a long while.

Fair enough, cheers for the explanation!

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
