### ISSUE TITLE
I turned off the buttom to disable the "Audio Flyout", and then the program crashed.

### ISSUE THREAD

**Issue by Ducheese** [ModernFlyouts-Community/ModernFlyouts#1211]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 22H2

### OS build

22621.2070

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

I want to disable the "Audio Flyout" just by turning off the button "Audio Flyout", because the Win11 has its own volume window. 

### ❌ Actual Behavior

BUT, no matter how I try to turn off the buttom "Audio Flyout", the program crashes everytime. (In contrast, the "Brightness Flyout" could be turned off successfully.)

**Comment by manstheram** [comment]
@Ducheese Try using v10 beta 3 in the releases tab. It also solves the issue where Win11's own volume window shows up.
