### ISSUE TITLE
Old flyout come up with modern flyout together

### ISSUE THREAD

**Issue by hyunki** [ModernFlyouts-Community/ModernFlyouts#1212]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 23H2

### OS build

22631.2129

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

turn on the windows
volume up and down

### ✔️ Expected Behavior

only modern flyout should display

### ❌ Actual Behavior

Old one and modernflyout are comeup together after windows update.
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/25163778/ef01be86-958c-4b6d-8ab9-4a32bcf9b1a7)

**Comment by UnravelY** [comment]
me too

**Comment by Samuel12321** [comment]
Fixed in 0.10 beta 3 
and will be resolved in 0.11 stable
