### ISSUE TITLE
More customization for lock keys

### ISSUE THREAD

**Issue by AINER** [ModernFlyouts-Community/ModernFlyouts#1216]
### Description of the new feature / enhancement

I think it would be nice to give more visibility and customization for lock keys.

![1](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/101467664/91907627-f1ac-4f92-9731-d9335d662a23)

### Scenario when this would be used?

Icons allow you to navigate faster and also allow you to use a small view.

**Comment by manstheram** [comment]
I was already starting to work on this. I do like those icons you used, where did you get them? I might use those.

**Comment by AINER** [comment]
I did it in a hurry with Photoshop 😅 But I can do it in vector format if you give me the original lock image so I can keep the original format and proportions of the icons. Or tell me where I can find it in the files.

**Comment by AINER** [comment]
> I was already starting to work on this. I do like those icons you used, where did you get them? I might use those.

I did it in a hurry with Photoshop 😅 But I can do it in vector format if you give me the original lock image so I can keep the original format and proportions of the icons. Or tell me where I can find it in the files.

**Comment by manstheram** [comment]
@AINER, the code actually uses a font glyph for the icons, so there isn't really a proper file I can send you.

**Comment by manstheram** [comment]
The font that is used is Segoe MDL2 Assets, and the codes are E72E & E785. If you want to try keeping the proportions, try using those to inform you how you can. However, I think it won't matter too much when I import it into the program.

**Comment by AINER** [comment]
@manstheram, 
[icons.zip](https://github.com/ModernFlyouts-Community/ModernFlyouts/files/12328375/icons.zip)

**Comment by manstheram** [comment]
I have made a pull-request for this. #1217

**Comment by AINER** [comment]
@manstheram, i added icons for insert button and also fixed margins of other icons. Please, use this version - [IconsV1.1.zip](https://github.com/ModernFlyouts-Community/ModernFlyouts/files/12339583/IconsV1.1.zip)

**Comment by manstheram** [comment]
I have added those in now.

**Comment by Samuel12321** [comment]
This has been something we have been looking into for a while in different forms. 
#593 
For consistency reasons we have tried to stick with Segoe MDL2 or Segoe ui icons but last i checked none suited, so we may need to use these.

**Comment by manstheram** [comment]
I am quite close to finishing this feature fully and some vertical volume flyouts so then another release can be made. I will just include it all in one pull-request (so it's simple).

**Comment by manstheram** [comment]
This feature has been finished in my pull-request and so are the vertical volume flyouts. 👍

**Comment by manstheram** [comment]
@tahayparker They have been made but haven't been pulled to this repo. If you know how to build it yourself, you can download the code off of my fork.

**Comment by tahayparker** [comment]
> If you know how to build it yourself

I wish bro, I wish
