### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#122]
We need to create a contributing.md or better inform contributors.
A good example of this is that language contributions are being made to the .xlf files instead of the resx files

**Comment by ShankarBUS** [comment]
Good idea!

Should we also include how to setup the development environment somewhere in the README?

**Comment by Samuel12321** [comment]
we can
we probably need to reconsider what goes in the readme and what goes else where

**Comment by ShankarBUS** [comment]
Any updates @Samuel12321?

**Comment by Samuel12321** [comment]
not yet.

**Comment by ShankarBUS** [comment]
Ok, I hope you will fond time to do this 😄.

**Comment by ShankarBUS** [comment]
We need this ASAP. Most people don't even look at the *.xlf files and directly modify the *.resx files.
We must make them aware of the fact that the *.resx files are modified at build time and the *.xlf files are the ones that are dedicated to be modified by contributors or translators.

@Samuel12321,
Please take some of your time and make this happen.

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/102706200-c960a500-42b5-11eb-95b4-726f6b85c4a0.png)

**Comment by ShankarBUS** [comment]
Hey @Samuel12321,

What the heck! How should a contributor actually contribute a translation!
There is no template to work on! i.e. no culture and language neutral **ModernFlyouts.xlf** is present in the MultilingualResources folder!
That's why they go for the **Strings.resx**, copy it, rename it to **Strings.(lang-code).resx** and modify it!!!!

You better answer me how to or get your knee caps removed!

**Comment by ShankarBUS** [comment]
@Samuel12321,

Please verify the [translation guidelines](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/CONTRIBUTING.md#translation-contribution-guidelines) part of the [Contribution guidelines](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/CONTRIBUTING.md) document.
I don't know if my guidelines are correct or not. You have to confirm it.

**Comment by Samuel12321** [comment]
Hi @ShankarBUS  , sorry have been really busy. Will look at it now.

**Comment by Samuel12321** [comment]
Both look excellent.
