### ISSUE TITLE
Autostart app still not works in 0.9.8513.0

### ISSUE THREAD

**Issue by FadeMind** [ModernFlyouts-Community/ModernFlyouts#1223]
### ModernFlyouts Version

0.9.8513.0

### Windows version

Windows 11 22H2

### OS build

22621.2215

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1. Install/Upgrade to `0.9.8513.0`
2. Enable autostart in app settings.
3. ModernFlyouts is available and enabled in Autostart tab in Task Manager.

### ✔️ Expected Behavior

Autostart app works.

### ❌ Actual Behavior

ModernFlyouts does not autostart after login user.

**Comment by manstheram** [comment]
@Samuel12321 I think this would have been finished in my pull-request.

**Comment by ckaspers** [comment]
Version 0.10.0.0 has the exact same issue.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
