### ISSUE TITLE
I chose the ModernFlyouts as the default flyouts, but the Windows Flyouts still came out.

### ISSUE THREAD

**Issue by UnravelY** [ModernFlyouts-Community/ModernFlyouts#1228]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.2215

### Platform

x64

### Area(s) with issue?

General, Audio Flyout

### Steps to reproduce

<img width="132" alt="Snipaste_2023-09-03_12-44-33" src="https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/87799109/7835312e-fda2-452a-969e-f8caa779b85c">

I chose the ModernFlyouts as the default flyouts, but the Windows Flyouts still came out, whether audio or brightness flyouts.

<img width="383" alt="Snipaste_2023-09-03_12-44-00" src="https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/87799109/7643f693-d2e1-4c81-ba03-6e3280430083">

<img width="308" alt="Snipaste_2023-09-03_12-44-14" src="https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/87799109/03978260-1d79-44d2-af09-8dc7d9b18d7b">

I tried to close the Audio Flyouts of ModernFlyouts, but when I closed it, the ModernFlyouts crashed.

### ✔️ Expected Behavior

I hope only the ModernFlyouts comes out, not the Windows Flyouts.

### ❌ Actual Behavior

But both of them came out. And I can't close the Audio Flyouts of ModernFlyouts because when I closed it, the ModernFlyouts crashed. But the good thing is I can close the Brightness Flyouts of ModernFlyouts.

**Comment by manstheram** [comment]
Try the beta build in the Releases tab of this repository.

**Comment by boromyr** [comment]
I have the same problem with 0.10 beta 3. The volume control is always the same as in Windows 11, but if I press the caps key twice, ModernFlyouts works correctly for each type of control. It must be repeated on every reboot.

**Comment by manstheram** [comment]
@boromyr Make a new issue and give some more info like exactly whether it's only caps key that can get the other flyouts and stuff like that.

**Comment by UnravelY** [comment]
> Try the beta build in the Releases tab of this repository.

It's worked, thank you!
