### ISSUE TITLE
No ModernFlyOut windows Insider 

### ISSUE THREAD

**Issue by clydo** [ModernFlyouts-Community/ModernFlyouts#1230]
### ModernFlyouts Version

0.10.0.0

### Windows version

Windows 11 insider 23H2

### OS build

25951.1000

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

I'm not sure how to reproduce it, except that it were working before i update my insider to the latest build

### ❌ Actual Behavior

No flyout when i press volume+/- or anything else (num lock, etc...) 
Still can access to the settings btw.
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/28127165/fd2d8458-5f71-44a2-ae1c-22d645d3379f)
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/28127165/10e8894d-3bac-4520-b243-c5d5a1d1e4d3)

**Comment by manstheram** [comment]
Are you on beta 3 rather than beta 4? Beta 4 should have a fix for this. [Beta 4](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4)

**Comment by clydo** [comment]
Certainly, it works perfectly, thank you! 👌
Sorry for the inconvenience, I thought I had downloaded the latest beta version before posting my message 😅
