### ISSUE TITLE
Doesn't auto start on restart 

### ISSUE THREAD

**Issue by nightzeyy** [ModernFlyouts-Community/ModernFlyouts#1231]
### ModernFlyouts Version

0.10.0-beta.4

### Windows version

Windows 11 22H2

### Platform

x64

### Steps to reproduce

Restart PC/Laptop

### ✔️ Expected Behavior

Auto start up with PC

### ❌ Actual Behavior

Doesn't Open have to manually open it

**Comment by manstheram** [comment]
Trying to currently work this out. It's an issue with the host part of the app.

**Comment by eProject** [comment]
As a temporary workaround > manually add moderflyouts to startup win10/11

1st find startup folder
press win+r 

for your user account... type:
shell:startup

for all users:
shell:common startup

file explorer will open in that location


now open start menu > find moderflyout
drag and drop it to the previously opened explorer window
will create a link

done

**Comment by manstheram** [comment]
@Samuel12321 Do you have any idea what the Host part of the app is doing? Does it have any other function than starting the app, because it might as well be removed. The startup task can just start the main app instead which I have implemented already.

**Comment by Samuel12321** [comment]
That was a workaround we were using to get topmost window access, to allow displaying flyouts above lock screen etc.
We have run into a lot of issues with it, i will talk to adeltax, but i imagine it will be removed or replaced in 0.11.
We have a myriad of issues open for this so will close in favor of #437
