### ISSUE TITLE
Doesn't work on Windows 10 22H2

### ISSUE THREAD

**Issue by uynilo9** [ModernFlyouts-Community/ModernFlyouts#1232]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 10 22H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1. Install it from Microsoft Store
2. Try to open it, but it doesn't work

### ✔️ Expected Behavior

Be opened

### ❌ Actual Behavior

Not opened

**Comment by manstheram** [comment]
Try the beta build in the Releases tab of this repository.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
