### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by verixyt3** [ModernFlyouts-Community/ModernFlyouts#1234]
### Description of the new feature / enhancement

no

### Scenario when this would be used?

no

### Additional context

Maybe not on topic, but I have a question, because of what, when I change the keyboard layout to Win +
space, I have a pop-up window?, and is it possible to disable it, it's annoying
(The pop-up window says volume, and if music is playing, it says which track is playing)

**Comment by manstheram** [comment]
I believe that trying the beta build in the Releases tab of this repository will solve this. There hasn't been a stable build in ages.

**Comment by Samuel12321** [comment]
Fixed in 0.10 beta 3
Will be included in 0.11 stable
