### ISSUE TITLE
Preffered Display Monitor switches while In-Game

### ISSUE THREAD

**Issue by ArenfeIdt** [ModernFlyouts-Community/ModernFlyouts#1235]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 22H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Having set the preferred Display Monitor to  1  instead of  2  -  In Game (doesn't matter wich Game for me) it displays the Pop Ups only on the Second Monitor.

### ✔️ Expected Behavior

Showing up on the preffered Monitor even if i am In Game.

### ❌ Actual Behavior

In-Game shows only on second Monitor

### Other Software

Any Game

**Comment by Samuel12321** [comment]
Closing in favor of #736
