### ISSUE TITLE
Volume Flyout not Appearing

### ISSUE THREAD

**Issue by S0M-007** [ModernFlyouts-Community/ModernFlyouts#1236]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Home Insider Preview Single Language 23H2

### OS build

25951.1010

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

When I try to increase the volume or change the track the flyout doesn't appear on screen. I mean its there but not visible so I can press the play button and all like it's supposed to, but none of it is visible.

### ❌ Actual Behavior

the flyout isn't visible

**Comment by manstheram** [comment]
This was fixed in a beta build - for some reason, you now need to add an extra flag to go and create the window.

**Comment by Samuel12321** [comment]
fixed in 0.11 beta 3
Will also be part of 0.11 stable
