### ISSUE TITLE
Modern Flyouts is not running in the system tray

### ISSUE THREAD

**Issue by ambarish35** [ModernFlyouts-Community/ModernFlyouts#1240]
### ModernFlyouts Version

0.9.1

### Windows version

Windows 11 22H2

### OS build

22621.2361

### Platform

x64

### Area(s) with issue?

System tray

### Steps to reproduce

Got a new laptop just today, and after installing Modern Flyouts from Microsoft Store and running it, it just crashes. After installation when I click "Open" button in Microsoft Store, it does nothing.

### ✔️ Expected Behavior

Modern Flyouts should've run in the system tray.

### ❌ Actual Behavior

Doesn't run art all or crash.

**Comment by manstheram** [comment]
Install it using a beta build in this Github repository. For some reason, only recent builds are working - if I rebuild an older release, it works fine. But if I use the original build of that release, it's just broken.

**Comment by Samuel12321** [comment]
Fixed in 0.10 beta 3
will be included in 0.11 stable
