### ISSUE TITLE
Brightness bar isn't displaying

### ISSUE THREAD

**Issue by Scarlaid** [ModernFlyouts-Community/ModernFlyouts#1242]
### ModernFlyouts Version

0.10.0-beta3

### Windows version

Windows 11 IoT Entperise LTSC 22H2

### OS build

22624.1546

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

- Turn on "open at startup"
- Restart
- Try tuning the brightness using hotkeys (if possible)

### ✔️ Expected Behavior

Usually from first installation, the flyout displays normally

### ❌ Actual Behavior

It became a small line, only one affected

### Additional Context

![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/90851437/f02ffe3e-d16b-440d-b290-b34750c79013)
*volume bar being normal*
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/90851437/bf120739-f921-4a2b-aeb3-e159a437bbd0)
*brightness bar being, a line*

**Comment by Scarlaid** [comment]
strange, now it does
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/90851437/fbeca588-463e-44c3-9fed-9df524017775)

**Comment by Samuel12321** [comment]
Hi @Scarlaid, Thanks for letting us know. We are currently working on our next major release which will completely redesign how our flyouts work and should solve this problem. Don't have an exact timeframe yet, but it will be part of our 0.11 release.
