### ISSUE TITLE
GUI invisible (Windows insider build preview)

### ISSUE THREAD

**Issue by eThibault** [ModernFlyouts-Community/ModernFlyouts#1247]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows Home Insider Preview Build 

### OS build

25982.re_prerelease.231020-1353

### Area(s) with issue?

General

### Steps to reproduce

When triggering flyout by pausing music, audio flyout doesnt show up

### ✔️ Expected Behavior

Audio flyout pops up

### ❌ Actual Behavior

GUI invisible, controls still work, yet invisible

**Comment by manstheram** [comment]
This has been sorted out in beta 4. [Beta 4 (GitHub)](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4)

**Comment by manstheram** [comment]
@eThibault

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
