### ISSUE TITLE
App (off Microsoft Store) suddenly stopped working?

### ISSUE THREAD

**Issue by kadester505** [ModernFlyouts-Community/ModernFlyouts#1249]
Went on a short weekend trip, and when I got back to my PC (windows 10), the app seemingly either stopped working, or refuses to open. I'm not a software engineer my any means and have insanely low capacity in coding, so I'm trying to figure out what the issue is. The only thing different about my PC that I can think of is I removed my GPU recently to sell, and am currently waiting for a new one to arrive. I wouldn't think that would be an issue but then again I'm a hardware guy not a software guy. I'm having a really hard time adjusting back to the default windows flyouts and it's driving me crazy. If anyone has any ideas it would be greatly appreciated. <3

Windows Version: Windows 10 22H2
Modern Flyouts Via: Microsoft Store

**Comment by manstheram** [comment]
I think some update occured or something as that's happened to me. I had it working for a month, then it stopped working for 4 months, then it started working again randomly. I don't the GPU itself has any link.
