### ISSUE TITLE
volume bar not working correctly?

### ISSUE THREAD

**Issue by CrimeTOSTig** [ModernFlyouts-Community/ModernFlyouts#1253]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

i have no idea, tried everything i could think of

![obraz](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/75879987/0aa14b9b-064a-4bb0-afdb-fba20039dd14)

### ✔️ Expected Behavior

replacing Windows flyouts with custom ones

### ❌ Actual Behavior

flyouts are doubled and are overlaping themselves. No matter what setup or settings i'm using.

### Additional Context

Yes, I marked in settings ModernFlyouts as default and clicked every single possible combination of settings.

![obraz](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/75879987/58f9e0a6-78a8-471f-b370-6d22c754d044)
![obraz](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/75879987/3435abdb-08de-4f04-86b2-71966345498e)
![obraz](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/75879987/f7b7d842-bdca-4263-9141-45e5b7675484)

**Comment by manstheram** [comment]
It's been solved in a beta release. The latest beta release is here. [Beta 4](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4)

**Comment by CrimeTOSTig** [comment]
> It's been solved in a beta release. The latest beta release is here. [Beta 4](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4)


![obraz](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/75879987/c418f39c-8fa5-429c-a611-ff54e7ee6094)


"The publisher certificate for this application package could not be verified. Please contact your system administrator or application developer to obtain a new application package with verified certificates. The root certificate and all immediate signing certificates in the application package must be verified (0x800B010A)"

**Comment by manstheram** [comment]
From the github description, "Remember to install the certificate in the trusted root authority under "local machine". As this is a pre-release i haven't signed it via the MS Store."
There should be a .cer file you need to install, you need to make sure it gets installed in the right directory.

**Comment by CrimeTOSTig** [comment]
> From the github description, "Remember to install the certificate in the trusted root authority under "local machine". As this is a pre-release i haven't signed it via the MS Store." There should be a .cer file you need to install, you need to make sure it gets installed in the right directory.

i did it and it still don't want me to install it, but i'll try again...

**Comment by Skrublord540** [comment]
After going through the trust process, nothing changes on my system, the install process still says to go through the prior process. Just wanted to throw that out there if it helps.

**Comment by Ozanelon** [comment]
Did you solve the problem?
