### ISSUE TITLE
The default Windows 11 volume sliders still appear.

### ISSUE THREAD

**Issue by kurosaki225** [ModernFlyouts-Community/ModernFlyouts#1254]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 23H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

After this new update, Windows 11 23H2, the default Windows 11 volume sliders still appear even with the app installed.
The Windows volume control appears in the bottom center, EXACTLY where the subtitles for my series are and this makes it difficult to see.
This Microsoft, instead of improving, only makes everything more difficult.

### ✔️ Expected Behavior

Please, make the default Windows 11 volume slider disappear when the app is running.

### ❌ Actual Behavior

Windows 11's default volume slider still appears instead of disappearing.

![screen](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/152229127/a6b12e86-5e6e-4d13-acde-dd3149f4a6b2)

### Additional Context

Windows 23H2.
If you could resolve this issue I would greatly appreciate it.

**Comment by manstheram** [comment]
It's been solved in a beta. [Beta 4](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1254)

**Comment by kurosaki225** [comment]
> It's been solved in a beta. [Beta 4](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1254)

I'm using version 0.9.3 of the app.
After the new W11 update - 23H2 that appeared again.

Was this "Beta 4" made before or after the new update?

**Comment by kurosaki225** [comment]
@manstheram 
Could you give me the download link for the new version?

**Comment by manstheram** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1254

**Comment by manstheram** [comment]
I accidentally sent the wrong link earlier, sorry about that.

**Comment by kurosaki225** [comment]
Thanks

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
