### ISSUE TITLE
ModernFlyouts Crash on Start (Windows 11 23H2)

### ISSUE THREAD

**Issue by Drag0nR3b0rn** [ModernFlyouts-Community/ModernFlyouts#1255]
### ModernFlyouts Version

0.10.0-beta.3 (0.9.8113.0 in settings)

### Windows version

Windows 11 23H2

### OS build

22631.2715

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Trying to launch newly installed ModernFlyouts (beta3 from github releases).
A tray icon appears for a few seconds and then disappears and a crash log appears.

### ✔️ Expected Behavior

ModernFlyouts icon in the tray and beautiful flyouts everywhere across the system

### ❌ Actual Behavior

ModernFlyouts crashes =(

### Additional Context

**Crash Report:**
AppName ModernFlyouts.exe 
  AppVersion 0.10.0.0 
  AppTimeStamp 648f9582 
  ModuleName KERNELBASE.dll 
  ModuleVersion 10.0.22621.2715 
  ModuleTimeStamp 10f6a783 
  ExceptionCode e0434352 
  FaultingOffset 000000000006565c 
  ProcessId 0x7ad4 
  ProcessCreationTime 0x1da261afddb8a68 
  AppPath C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.9.8113.0_x64__0dbdf1n3n58kt\ModernFlyouts.exe 
  ModulePath C:\Windows\System32\KERNELBASE.dll 
  IntegratorReportId a4109069-c2e9-4b98-88b2-66cd798124a9 
  PackageFullName 32669SamG.ModernFlyouts_0.9.8113.0_x64__0dbdf1n3n58kt 
  PackageRelativeAppId App

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
