### ISSUE TITLE
Crucial bug

### ISSUE THREAD

**Issue by fe2-Nyxar** [ModernFlyouts-Community/ModernFlyouts#1264]
### ModernFlyouts Version

0.9.1

### Windows version

latest windows 11

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout

### Steps to reproduce

![check-this-out](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/153492661/be321747-7375-4dd5-bb6f-bed3dcc112c3)

### ✔️ Expected Behavior

I expect your design to pop up just not the Windows thing
and for the progress bar of the audio/video, I expect it to update smoothly even when ui is shown

### ❌ Actual Behavior

First: you can see both the default Windows sound UI and the modern flyout UI are visible, and this is not only for the volume but also the brightness.
Second: the bar of the audio is stuck and it changes only after another increase or a decrease of the volume.

### Other Software

I'm using Thorium version of the open-source chromium.

### Additional Context

just taking this moment to appreciate your work guys, and I'll keep using this app even if this bug exists :)
thx for your attention.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
