### ISSUE TITLE
check-this huge error in windows 11

### ISSUE THREAD

**Issue by fe2-Nyxar** [ModernFlyouts-Community/ModernFlyouts#1265]
### ModernFlyouts Version

0.9.1

### Windows version

latest windows 11

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout

### Steps to reproduce

![check-this-out](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/153492661/fe60f8d0-7b9c-4f1d-81bc-e45ac8dea17c)

### ✔️ Expected Behavior

I expect your design to pop up just not the Windows thing
and for the progress bar of the audio/video, I expect it to update smoothly even when ui is shown

### ❌ Actual Behavior

First: you can see both the default Windows sound UI and the modern flyout UI are visible, and this is not only for the volume but also the brightness.
Second: the bar of the audio is stuck and it changes only after another increase or a decrease of the volume.

### Other Software

I'm using Thorium version of the open-source chromium.

### Additional Context

just taking this moment to appreciate your work guys, and I'll keep using this app even if this bug exists :)
thx for your attention.

**Comment by fe2-Nyxar** [comment]
@Bear141  merci ;)

**Comment by fe2-Nyxar** [comment]
@Bear141  It didn't work :'(

**Comment by manstheram** [comment]
It's solved in the beta.

**Comment by Suraj5260** [comment]
> Just checked. Issue solved in [0.9.3](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/0.9.3)

its not working

**Comment by Suraj5260** [comment]
pls let me know how to get rid of double flyouts

![Screenshot (2)](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/94602236/d761a5e7-0541-496d-86dd-9e3523fbc8f0)

**Comment by fe2-Nyxar** [comment]
it's fixed in the beta, but I don't recommend it becuz it's not stable yet if you wanna install it, here's how: 
you need choco first, so open PS as admin: 
`run this: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`

after that, run this to install the beta 10 (not stable): `choco install modernflyouts --pre `

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
