### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by beebella** [ModernFlyouts-Community/ModernFlyouts#1267]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.3007

### Platform

x64

### Area(s) with issue?

General, Installer

### Steps to reproduce

Installed the app, opened it and got the settings, made sure that "Run on startup" is on, and restarted my PC.

### ✔️ Expected Behavior

For me to see a preview of the spotify song when I adjust volume or skip song (just like how the automatic pop-up worked on Windows 10)

### ❌ Actual Behavior

No change happened, as if I never installed the app.

### Other Software

Spotify

**Comment by poly000** [comment]
maybe dup of issue: #1223 
did you try start ModernFlyout manually

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
