### ISSUE TITLE
several performers in the song

### ISSUE THREAD

**Issue by b3nzyexe** [ModernFlyouts-Community/ModernFlyouts#1275]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22621.3007

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

When a song is played on Spotify with multiple artists, the program writes only one main artist, and not all at once. At the same time, if the same song from Yandex.Music is played, then all the performers will be written
![dasads](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/85969126/5744c482-d02f-49e9-b1bb-09f6c3cb993b)
![dsaf](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/85969126/771d7ef6-a892-4bef-8473-961dbdb31c60)

### ✔️ Expected Behavior

I would like all the performers from the song to be written

### ❌ Actual Behavior

The program writes only one main artist of the song, and there are no others

### Other Software

Spotify, Yandex.Music

**Comment by manstheram** [comment]
This is Spotify's fault, so I don't think there's anyway to solve it.
