### ISSUE TITLE
The global media button cannot close the media box below ,even if v0.10.0

### ISSUE THREAD

**Issue by pika-99** [ModernFlyouts-Community/ModernFlyouts#1276]
### ModernFlyouts Version

0.9.3

### Windows version

windows 10 22h2

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

开关 全局媒体按钮不能关闭下面的媒体框   即使v0.10.0 ... win10 22h2 workstationversion
The global media button cannot close the media box below ,even if v0.10.0

### ✔️ Expected Behavior

111

### ❌ Actual Behavior

开关 全局媒体按钮不能关闭下面的媒体框   即使v0.10.0 ... win10 22h2 workstationversion
The global media button cannot close the media box below ,even if v0.10.0

![11111](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/62867488/02804e21-ec7e-45db-b499-5f4ca3f619c1)

**Comment by prakharb5** [comment]
I cannot reproduce this bug. Is this bug still present?

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
