### ISSUE TITLE
Why is there a gray outline?

### ISSUE THREAD

**Issue by Intrivus** [ModernFlyouts-Community/ModernFlyouts#1277]
### ModernFlyouts Version

0.10.0.0

### Windows version

Windows 11 23H2

### OS build

22631.3155

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

It happen after install

### ✔️ Expected Behavior

![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/81963564/aa1f8df5-d482-42e4-80ec-1db09ec68cf9)

### ❌ Actual Behavior

![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/81963564/993d8009-bdc5-4bb5-ac69-5f40f8f3d9d8)

yes

### Other Software

still ofc

**Comment by Perndoe** [comment]
It is not about the media flyout it is about the outline

**Comment by prakharb5** [comment]
This was a design choice

**Comment by Intrivus** [comment]
alr
