### ISSUE TITLE
Flyouts not working for Windows build 26052 and after

### ISSUE THREAD

**Issue by outnampichtim** [ModernFlyouts-Community/ModernFlyouts#1280]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 24H2

### OS build

26058.1400

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Having modern flyouts installed on this version of Windows.

### ✔️ Expected Behavior

Flyouts appearing when changing the volume, brightness or pressing lock keys.

### ❌ Actual Behavior

The flyouts don't appear but the software seems to be working. Also, when I try to turn off specific flyouts, the software crashes and after it is restarted, it did not turn of the flyouts.

### Additional Context

I am having the same issue on 2 devices running the same Windows build.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
