### ISSUE TITLE
Flyouts not working

### ISSUE THREAD

**Issue by TP-RevelK** [ModernFlyouts-Community/ModernFlyouts#1281]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 24h2

### OS build

26063.1

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

after the update the flyouts just stopped working at all they just dont respond to anything neither the locks or the sound

### ❌ Actual Behavior

no response

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
