### ISSUE TITLE
No the app is not running

### ISSUE THREAD

**Issue by cantfixit** [ModernFlyouts-Community/ModernFlyouts#1283]
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 11 22H2

### OS build

windows pro 22H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

install the app it happes when i install the app

### ✔️ Expected Behavior

the app to run properly 

### ❌ Actual Behavior

it dosent even start

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
