### ISSUE TITLE
app does not run after downloading 

### ISSUE THREAD

**Issue by DANIEL200436** [ModernFlyouts-Community/ModernFlyouts#1286]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 Home  22H2

### OS build

22621.3296

### Platform

x64

### Area(s) with issue?

Installer

### Steps to reproduce

-To reproduce the problem, I simply download and try to open the ModernFlyouts (Preview) app from the Windows Store.
-After downloading, the app does not appear in the taskbar, even though the Windows Store indicates that it is installed.
-I click on the app icon in open in Windows Store. 
-The loading cursor is displayed for less than a second, but the application does not open or perform any action.

### ✔️ Expected Behavior

After downloading the application from the Windows Store, you should be able to open it normally and use its functions without any problems.

### ❌ Actual Behavior

Although the application appears to install correctly, when I try to open it, it only shows the loading cursor for less than a second and then does not run anything.

### Other Software

I do not have any other software installed that would interfere with the ModernFlyouts (Preview) application. My laptop is newly installed and only has basic programs. There are no additional security programs or system optimization utilities that could be causing problems.

### Additional Context

I have tried installing the application several times and have tried different methods to solve the problem, such as rebooting the system and checking for updates. However, the problem still persists. I have no other applications installed that could interfere with its operation, since my laptop is newly installed and only has basic programs. Also, it is important to note that the ModernFlyouts (Preview) application does not appear in the taskbar after its supposed installation, which is another point to consider.

I would like guidance on how to address possible security issues that could be preventing the application from working. In addition, I would like to know if there are other applications that could be causing interference, although I consider this unlikely due to the recent nature of my operating system installation.

**Comment by 791E** [comment]
Do the flyouts not appear when you pause, skip, etc. an audio/video file, or is it just the fact, that no window appears?

If it's the latter: Modern Flyouts doesn't actually open a window when starting it, the program is only visible in system tray (right-hand side of the taskbar, you probably have to click on the up-arrow, the leftmost icon on the right side of the taskbar), there you can right click on the icon that's called "ModernFlyouts" and click on settings, only then will you see a window open.

**Comment by anventia** [comment]
Not OP, but I also have this problem on a new PC. I have the app installed on my old laptop as well, and it continues to work perfectly fine there, so I'm unsure what the issue is.

**Comment by prakharb5** [comment]
@DANIEL200436 @anventia can you verify if this issue exists with the latest beta of 0.10?

**Comment by anventia** [comment]
I got an error from the installer about the certificate could not be verified, even after installing the .cer file provided. Is there a workaround?

**Comment by manstheram** [comment]
@anventia I think you need to instal the certificate in a certain certificate store "trusted root authority" under "local machine".

**Comment by manstheram** [comment]
First, you need to open the .cer, then click Install Certificate.
Then click Local Machine and then continue.
Then click all certificates in the following store then click Browse.
In the popup, click Trust Root Certification Authorities
Then accept it and press OK.

**Comment by anventia** [comment]
Aha! It works now. Thank you!

**Comment by prakharb5** [comment]
I'll be closing this then
