### ISSUE TITLE
en window 11 aparecen las barras de sonodo y la por defecto no se quita

### ISSUE THREAD

**Issue by ersanti14** [ModernFlyouts-Community/ModernFlyouts#1292]
### ModernFlyouts Version

0.9.3

### Windows version

windows 11

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

aparecen las 2 barras de sonido en window 11 y la de defecto no se desaparece

### ❌ Actual Behavior

aparecen las 2 barras de sonido en window 11 y la de defecto no se desaparece

### Other Software

la barra por defecto no se va

### Additional Context

aparecen las 2 barras de sonido en window 11 y la de defecto no se desaparece

**Comment by XP1R3** [comment]
Me pasa lo mismo, ¿has conseguido alguna solución?

**Comment by prakharb5** [comment]
Duplicate of #920
