### ISSUE TITLE
No se aplica el widget del panel de sonido

### ISSUE THREAD

**Issue by jheanpiere453** [ModernFlyouts-Community/ModernFlyouts#1295]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 24H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Cuando descargo la app, se supone que debe de cambiarse el panel de subir y bajar el volumen, sin embargo, no se aplican, la barra de sonido sigue siendo la predeterminada de Windows
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/72107602/ac965692-c81a-41b2-8653-9cd3da628510)

### ❌ Actual Behavior

Cuando descargo la app, se supone que debe de cambiarse el panel de subir y bajar el volumen, sin embargo, no se aplican, la barra de sonido sigue siendo la predeterminada de Windows
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/72107602/ac965692-c81a-41b2-8653-9cd3da628510)

**Comment by prakharb5** [comment]
Duplicate of #920
