### ISSUE TITLE
App flyout appears, when it's not mean to be.

### ISSUE THREAD

**Issue by NachoDel** [ModernFlyouts-Community/ModernFlyouts#1303]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 pro

### OS build

10.0.22631

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Every time i click "Extract all" from any zip file (at least ubicated in download folder), with the native unzipper of windows 11, the flyout appears like when i try to rise the volume.
![clip](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/143521846/7ba9016b-8da8-48ae-99d9-9ea16e27dce0)

### ✔️ Expected Behavior

Not to open.

### ❌ Actual Behavior

Open when it shouldn't.

**Comment by manstheram** [comment]
I cannot replicate this on the newer beta build but I can on 0.9.3.0 so perhaps it was fixed in there?

**Comment by NachoDel** [comment]
It can be, yes.
I tried to install the beta version, but i don´t figure it out how to do it😅 (i have an error with the certificates, even having downloaded them)

**Comment by manstheram** [comment]
Ah, you need to place them in the Trusted Root Certification store. @NachoDel

**Comment by manstheram** [comment]
First, you need to open the .cer, then click Install Certificate.
Then click Local Machine and then continue.
Then click all certificates in the following store then click Browse.
In the popup, click Trust Root Certification Authorities
Then accept it and press ok.

**Comment by NachoDel** [comment]
Sorry for the delay.
I already instaled and also tested it. 
It seems the bug is fixed!
