### ISSUE TITLE
Flyout and Taskbar not shown in Windows 11 24H2

### ISSUE THREAD

**Issue by errypuu** [ModernFlyouts-Community/ModernFlyouts#1307]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 24H2

### OS build

26100.712

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1. Open ModernFlyout from Start Menu, or wait for the application to launch on startup

### ✔️ Expected Behavior

1. Taskbar icon shown, ModernFlyoutsHost.exe opened and shown in Task Manager, Flyout shown when changing the volume, brightness, etc

### ❌ Actual Behavior

1. Taskbar icon not shown, Flyout not shown when changing the volume, brightness, etc. Only ModernFlyoutsHost.exe opened and shown in Task Manager

### Additional Context

The Windows build that I am using is Windows 11 24H2 Release Preview that just released a day ago.

**Comment by BlackusPL** [comment]
Download [0.10.0 beta 4](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4)

**Comment by errypuu** [comment]
Thanks, I can confirm that this issue is solved in version 0.10.0 beta 4.
