### ISSUE TITLE
win+space

### ISSUE THREAD

**Issue by KEHT1K** [ModernFlyouts-Community/ModernFlyouts#1309]
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 10 21H2

### Platform

x64

### Area(s) with issue?

General, Audio Flyout, Lock keys Flyout

### Steps to reproduce

when you press win+space (to change the language), the audio tab opens

https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/171099113/816c8b0e-b01e-40a8-bb15-82fbaba96ddf

### ✔️ Expected Behavior

display that the language has been changed and not the music
additional settings for this keyboard shortcut (as with caps and numlock)

### ❌ Actual Behavior

I have shown above

**Comment by manstheram** [comment]
I cannot replicate this in [Beta 4](https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.4). Please try downloading it.
