### ISSUE TITLE
Conflict between ModernFlyouts and Windows 11 system animations

### ISSUE THREAD

**Issue by HLaloH98** [ModernFlyouts-Community/ModernFlyouts#1316]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Home

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Despite having set "ModerFlyouts" as the default animations for my computer, the default Windows 11 animations continue to appear, resulting in when I raise or lower the volume or brightness, the ModernFlyouts and Windows animations are displayed at the same time. the time

### ✔️ Expected Behavior

That only the "ModernFlyouts" animations appeared

### ❌ Actual Behavior

Both animation, windows and "ModernFlyouts" appear at the same time

**Comment by prakharb5** [comment]
update to the latest 0.10 beta for now. it has the required fix
