### ISSUE TITLE
Option to disable multimedia flyout independently of volume flyout

### ISSUE THREAD

**Issue by revanmj** [ModernFlyouts-Community/ModernFlyouts#1319]
### Description of the new feature / enhancement

I'd like to have an option to disable multimedia flyout (so that pressing volume keys only show volume flyout, like currently with default Windows 11 one).

### Scenario when this would be used?

Flyout showing on pressing volume keys

### Additional context

1. Default Win11 volume flyout broke for me (volume value on it is stuck, it always shows the same one no matter the actual value), so I replaced it with ModernFlyouts (but currently it shows both volume and multimedia flyouts on volume key press, unlike Windows 11's default flyout)
2. I usually have a chromium-based browser opened with some YouTube in the background, so multimedia control of Windows is almost always active in my case, hence multimedia flyout is always displayed). I know I can disable system media control via flag, but I want to have it on demand (to be able to control YT playback via KDE Connect on the phone).

**Comment by BrianG61UK** [comment]
This is already an option.
<img width="688" alt="Screenshot 2024-08-09 153142" src="https://github.com/user-attachments/assets/d3b88543-5845-4265-a4fa-864d796c5c66">

**Comment by revanmj** [comment]
Well, Polish translation of this option is wrong then as it says "Show volume control (GSMTC) in volume flyout" when translated back to english.

**Comment by Samuel12321** [comment]
Updated translation merged, will be visible in the next release.
