### ISSUE TITLE
The app won't start

### ISSUE THREAD

**Issue by yelfaramawy** [ModernFlyouts-Community/ModernFlyouts#1320]
### ModernFlyouts Version

10.0.4

### Windows version

Windows 22H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

When running the app, It shows the app icon on the system tray icons, then disappears after 5 secs.

### ✔️ Expected Behavior

The app should start and I can see the modernFlyout or open the settings

### ❌ Actual Behavior

The app does not start.

### Additional Context

I noticed some tabs related to the app in the start menu like (Settings and Restore legacy flyout) but if I click on any of them it says the item is unavailable it might be deleted or moved. I tried to reinstall many times and also installed the beta 10.0.4 and 10.0.3 versions but unfortunately, it didn't help.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5

**Comment by yelfaramawy** [comment]
Tired this beta 5, but it didn't help either
