### ISSUE TITLE
Run at startup doesn't work

### ISSUE THREAD

**Issue by BrianG61UK** [ModernFlyouts-Community/ModernFlyouts#1321]
### ModernFlyouts Version

v0.10.0-beta.4

### Windows version

Windows 11 23H2

### OS build

22631.3958

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Install certificate
Install Modern Flyouts
Setup Modern Flyouts including enabling switching on "Run at startup".
...
Reboot Windows.
...
Modern Flyouts will not be running and flyouts will be Windows default flyouts.

### ✔️ Expected Behavior

Modern Flyouts will be running and flyouts will be Modern flyouts as I configured.

### ❌ Actual Behavior

Modern Flyouts will not be running and flyouts will be Windows default flyouts.

### Additional Context

Ask for more info if you cannot reproduce this.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
