### ISSUE TITLE
flyouts not working

### ISSUE THREAD

**Issue by TheFireless** [ModernFlyouts-Community/ModernFlyouts#1327]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 pro 24H2

### OS build

26120.1330

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

I downloaded the app, launched it, and set my settings, but nothing worked. I tried reinstalling the app and resetting it through the settings and I also tried the repair option. I even reset my laptop software and still. it was working before.

### ✔️ Expected Behavior

the showing the modern flyouts when pressing volume and other buttons

### ❌ Actual Behavior

nothing is working and I tried everything to get working
<img width="677" alt="image" src="https://github.com/user-attachments/assets/45877fe8-5e92-4777-bd2c-f5fa495da13b">

### Additional Context

please help :)

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
