### ISSUE TITLE
Using touchpad gestures to control the volume doesn't open the flyout

### ISSUE THREAD

**Issue by MJavadJafari** [ModernFlyouts-Community/ModernFlyouts#1328]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 23H2

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Add 4-finger change volume gesture to the touchpad. Use it to control the volume. It won't open the flyout.

### ✔️ Expected Behavior

Flyout should be opened when volume is changed using touchpad gesture.

### ❌ Actual Behavior

It doesn't open up, the default windows volume shows up instead.

**Comment by prakharb5** [comment]
works on latest beta, try it and update here

**Comment by MJavadJafari** [comment]
Thanks for the reply. 
I uninstalled the old version and tested the new beta version. The issue still persists. Using touchpad gestures to change tracks or change the volume doesn't trigger the new UI elements.

**Comment by prakharb5** [comment]
@MJavadJafari 
Huh, it works perfectly for me on 4-finger gestures.
What are you trying?
