### ISSUE TITLE
The Flyout widget is invisible but I can click on it

### ISSUE THREAD

**Issue by Voltairis1** [ModernFlyouts-Community/ModernFlyouts#1330]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 

### OS build

Windows 11 Insider Preview 10.0.26120.1542

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

Just from installing the app, the media control flyout is invisible but clickable.

### ✔️ Expected Behavior

I was expecting the flyout to not be invisible

### ❌ Actual Behavior

The flyout is invisible

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
