### ISSUE TITLE
Modern Flyouts not opening

### ISSUE THREAD

**Issue by Toch2x** [ModernFlyouts-Community/ModernFlyouts#1331]
### ModernFlyouts Version

0.9.1

### Windows version

Windows 11

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

I've used Modern Flyouts before on my old laptop but on my current one it doesn't opening after installing.

### ✔️ Expected Behavior

Application opening, flyouts to show on screen

### ❌ Actual Behavior

Application not opening

**Comment by s626ch** [comment]
same thing happens to me, windows 10 x64, IoTE
opens on my home desktop (also running IoTE), and works fine there, but NOT on my laptop i just got

tried to debug or find logs, but the application doesnʻt output any helpful logs that i can easily find

**Comment by s626ch** [comment]
i was able to install the beta (had to set my date earlier due to an expired certificate during installation), and it seems to work

**Comment by Toch2x** [comment]
> i was able to install the beta (had to set my date earlier due to an expired certificate during installation), and it seems to work

alright, how were you able to set your date eariler

**Comment by s626ch** [comment]
![m3PorS6ZFQ](https://github.com/user-attachments/assets/7ea40e4b-f252-400e-a6fa-0242c72029bd)

**Comment by Toch2x** [comment]
ok it worked, thanks a lot!

**Comment by manstheram** [comment]
You can also use the beta from this fork: https://github.com/manstheram/ModernFlyouts/releases/tag/v0.10.0-beta.4
The certificate is much newer.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
