### ISSUE TITLE
Latest beta certificate expired Aug 22, 2024

### ISSUE THREAD

**Issue by hestenet** [ModernFlyouts-Community/ModernFlyouts#1333]
### ModernFlyouts Version

v0.10.0-beta.4

### Windows version

Windows 11

### Platform

x64

### Area(s) with issue?

Installer

### Steps to reproduce

Attempting to install the certificate into the Trusted Root Certificates store for Local Machine is not successful because the beta cert is now over a year old and is expired.

### ✔️ Expected Behavior

We need a new cert, or a full release with a cert in the app store, in order to install

### ❌ Actual Behavior

Beta is uninstallable.

**Comment by manstheram** [comment]
https://github.com/manstheram/ModernFlyouts/releases/tag/v0.10.0-beta.4

**Comment by wefalltomorrow** [comment]
> https://github.com/manstheram/ModernFlyouts/releases/tag/v0.10.0-beta.4

Same issue unfortunately

**Comment by neradp** [comment]
`Add-AppPackage ".\ModernFlyouts.Package_0.9.8513.0_x86_x64_arm64.msixbundle" -AllowUnsigned`

Use this in powershell console to install ModernFlyouts without certificate.

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
