### ISSUE TITLE
Modern Flyout + Windows Default flyout appears when changing volume

### ISSUE THREAD

**Issue by Root1-2** [ModernFlyouts-Community/ModernFlyouts#1336]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 23H2

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Whenever I try to increase/decrease my volume, the windows 11 default flyout appears along with the modern flyout.

v0.10.0-beta.4 this is the version I have downloaded.

![Screenshot 2024-06-08 023655](https://github.com/user-attachments/assets/74b206be-e5b0-4561-85b5-ff706c1df68b)

### ✔️ Expected Behavior

Only want the modern flyout

### ❌ Actual Behavior

Windows 11 default flyout + modern flyout appears.

**Comment by manstheram** [comment]
It doesn't seem like you're using the beta? According to the screenshot at least.

**Comment by Root1-2** [comment]
Yeah actually I didn't uninstalled my previous version before installing the beta. Now it's working. Thanks though...
