### ISSUE TITLE
Modern Flyout + Windows Default flyout appears when changing volume

### ISSUE THREAD

**Issue by joao-carmassi** [ModernFlyouts-Community/ModernFlyouts#1338]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 23H2

### OS build

22631.4112

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Whenever I try to increase/decrease my volume, the windows 11 default flyout appears along with the modern flyout.

![Captura de tela 2024-09-09 191552](https://github.com/user-attachments/assets/8dfa1378-d5c1-4fb4-8b70-b935cdc5c6ad)

### ✔️ Expected Behavior

Only want the modern flyout

### ❌ Actual Behavior

Windows 11 default flyout + modern flyout appears.

**Comment by prakharb5** [comment]
Switch to the latest beta on github
