### ISSUE TITLE
Brightness Flyover is not shown as Expected

### ISSUE THREAD

**Issue by AmarnathCJD** [ModernFlyouts-Community/ModernFlyouts#1340]
### ModernFlyouts Version

betav4 latest 10

### Windows version

Win11 2H23

### OS build

-

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

![image](https://github.com/user-attachments/assets/f7833c33-fe09-40e1-9d12-8fe235b8cefd)

### ❌ Actual Behavior

the slider be expanded

**Comment by prakharb5** [comment]
switch to beta 5 and update on the issue
