### ISSUE TITLE
ModernFlyouts not working on Windows 11

### ISSUE THREAD

**Issue by baddie006** [ModernFlyouts-Community/ModernFlyouts#1342]
### ModernFlyouts Version

"0.9.3.0"

### Windows version

"Windows 11 24H2"

### OS build

"26120.1542"

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Inglese

ModernFlyouts starts automatically at system startup but does not work with CAPS LOCK or NUM LOCK or with the volume.

### ✔️ Expected Behavior

It should appear on the screen

### ❌ Actual Behavior

It doesn't appear on the screen

**Comment by SirOMGitsYOU** [comment]
To add onto this Mine is working on W11 with caps and numlock and the volume up and down on my KB shortcuts. However, the only thing that never works for me is Spotify/Media pausing or playing or the next song starting doesn't cause a flyout to appear. I will say I did have to restart my PC after installing MF to have any of them appear.

![image](https://github.com/user-attachments/assets/4c1d26f2-34f2-4498-b617-45985f9b7121)

**Comment by naturbrilian** [comment]
Maybe because modernflyouts doesnt support with windows version 24h2

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
