### ISSUE TITLE
system default flyout does not disappear 

### ISSUE THREAD

**Issue by c45rr** [ModernFlyouts-Community/ModernFlyouts#1343]
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 11 23H2

### OS build

22631.4169

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Both the default and the app flyout appear even after toggling the modernflyouts. see attached image.

<img width="722" alt="image" src="https://github.com/user-attachments/assets/994341f2-b203-4184-b977-f108d7a3a1e6">

### ✔️ Expected Behavior

system flyout not appear and Modernflyouts does 

### ❌ Actual Behavior

both the system default and the modern fly out appear together

**Comment by prakharb5** [comment]
Please switch to the new beta

**Comment by c45rr** [comment]
I did thank you

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
