### ISSUE TITLE
certificate for ver beta 10.0 is outdated 

### ISSUE THREAD

**Issue by ivan8994** [ModernFlyouts-Community/ModernFlyouts#1345]
### ModernFlyouts Version

10.0.0

### Windows version

Windows 10 22H2

### Platform

x64

### Area(s) with issue?

Installer

### Steps to reproduce

certificate to install beta ver 10.0.0.4 is not valid anymore, the date expired on august 2024. can you please update it ?

https://github.com/ModernFlyouts-Community/ModernFlyouts/releases

https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/download/v0.10.0-beta.4/ModernFlyouts.Package_0.9.8513.0_x86_x64_arm64.cer

### ❌ Actual Behavior

cant install MFU ver 10.0.0.0.4 because certificate is expired

**Comment by wefalltomorrow** [comment]
Same issue here :(

**Comment by USLTD** [comment]
You can compile it by yourself and then sign it with your own certificate. That's what I did.

**Comment by ivan8994** [comment]
> You can compile it by yourself and then sign it with your own certificate. That's what I did.

thanks for your reply , could you provide any instructions how to do this ? or maybe you could just share your current certificate ?

**Comment by THEBOSSES7000** [comment]
I find a solution! It's simpler than it seems. Just change the date of your computer to one in which the certificate is not expired and install the application, then change it to how you had it and that's it.

**Comment by THEBOSSES7000** [comment]
> I find a solution! It's simpler than it seems. Just change the date of your computer to one in which the certificate is not expired and install the application, then change it to how you had it and that's it.

The aplication works fine, I only see a problem that I don't know if it is because when the certificate expires it does this or it is a problem with the application itself, but the application does not start with Windows even though the option is activated. If the same thing happens to you, please let me know so I can find out.

**Comment by ivan8994** [comment]
> The application does not start with Windows even though the option is activated. If the same thing happens to you, please let me know so I can find out.

hello @THEBOSSES7000 I confirm this issue exists and frommy point of view it doesnt depend on certificate, since I still have this problem for about 2 years of using this app. Try to add the link of the application directly to shell:startup folder , this workaround works .

**Comment by manstheram** [comment]
Delete any install files for this repo's ModernFlyouts, then use this fork instead https://github.com/manstheram/ModernFlyouts/releases/tag/v0.10.0-beta.4

**Comment by THEBOSSES7000** [comment]
> > The application does not start with Windows even though the option is activated. If the same thing happens to you, please let me know so I can find out.
> 
> hello @THEBOSSES7000 I confirm this issue exists and frommy point of view it doesnt depend on certificate, since I still have this problem for about 2 years of using this app. Try to add the link of the application directly to shell:startup folder , this workaround works .

Thanks dude, you saved me, it works fine now.

**Comment by wefalltomorrow** [comment]
> I find a solution! It's simpler than it seems. Just change the date of your computer to one in which the certificate is not expired and install the application, then change it to how you had it and that's it.

Hmm I tried this and still doesn't work :(

**Comment by neradp** [comment]
`Add-AppPackage ".\ModernFlyouts.Package_0.9.8513.0_x86_x64_arm64.msixbundle" -AllowUnsigned`

Use this in powershell console to install ModernFlyouts without certificate.

**Comment by ivan8994** [comment]
> `Add-AppPackage ".\ModernFlyouts.Package_0.9.8513.0_x86_x64_arm64.msixbundle" -AllowUnsigned`
> 
> Use this in powershell console to install ModernFlyouts without certificate.

so this is what I get in Powershell when trying to use this method 

```
Add-AppxPackage : A parameter cannot be found that matches parameter name 'AllowUnsigned'.
At line:1 char:78
+ ... rnFlyouts.Package_0.9.8513.0_x86_x64_arm64.msixbundle" -AllowUnsigned
+                                                            ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Add-AppxPackage], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageComm
   and
```

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
