### ISSUE TITLE
Wrong timing

### ISSUE THREAD

**Issue by Nirvaan0265** [ModernFlyouts-Community/ModernFlyouts#1347]
### ModernFlyouts Version

0.9.3.0

### Windows version

Win 11 23H2

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

pressing volume increase or decrease while playing any songs

### ✔️ Expected Behavior

right timing

### ❌ Actual Behavior

timing stuck at 0:00

**Comment by Samuel12321** [comment]
Not enough information
