### ISSUE TITLE
ModernFlyouts doesnt hide standard win11 flyout

### ISSUE THREAD

**Issue by VertyXvc** [ModernFlyouts-Community/ModernFlyouts#1348]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 22H2

### OS build

22621.4169

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

![Снимок экрана 2024-10-02 100613](https://github.com/user-attachments/assets/1a92839d-274e-425e-a367-70e1e00bb817)

### ❌ Actual Behavior

ModernFlyouts doesnt hide standard win flyout

**Comment by naturbrilian** [comment]
try this
https://github.com/manstheram/ModernFlyouts/releases/tag/v0.10.0-beta.4

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
