### ISSUE TITLE
ModernFlyouts doesn't work on Win11 24H2

### ISSUE THREAD

**Issue by JingHai-Lingyun** [ModernFlyouts-Community/ModernFlyouts#1349]
### Discussed in https://github.com/ModernFlyouts-Community/ModernFlyouts/discussions/1335

<div type='discussions-op-text'>

<sup>Originally posted by **JingHai-Lingyun** September  6, 2024</sup>
App installed via MS Store</div>

**Comment by Skatanax** [comment]
Same :(

**Comment by JoAl115** [comment]
Same here after update

**Comment by KerimSaman** [comment]
Please update

**Comment by ArenfeIdt** [comment]
Use the Beta Version from @manstheram — https://github.com/manstheram/ModernFlyouts/releases

Works perfectly fine for me on 24H2

**Comment by Skatanax** [comment]
> Use the Beta Version from @manstheram — https://github.com/manstheram/ModernFlyouts/releases
> 
> Works perfectly fine for me on 24H2

Can't install it, even with the certificate :(

**Comment by ArenfeIdt** [comment]
Did you do the Certificate Install like this?

![1](https://github.com/user-attachments/assets/1a2d4318-006e-43fa-97d4-5f9611b19fab)
![2](https://github.com/user-attachments/assets/3b1143e8-9cf4-40db-b566-ae9522e16a5a)

**Comment by Skatanax** [comment]
> Did you do the Certificate Install like this?
> 
> ![1](https://private-user-images.githubusercontent.com/41451315/373872853-1a2d4318-006e-43fa-97d4-5f9611b19fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzcyODYsIm5iZiI6MTcyODEzNjk4NiwicGF0aCI6Ii80MTQ1MTMxNS8zNzM4NzI4NTMtMWEyZDQzMTgtMDA2ZS00M2ZhLTk3ZDQtNWY5NjExYjE5ZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE0MDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzEzYmE4OGFiYmNlYjQ2MzQ3MDBmMDQzZDgwMjA4MTY1OGFhMzdkN2RiODkzNjJhNGVlYTllYmUxMTM2YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2HvZquJrP5H65nYReRig4RSCbAxJxZy--1KnQWfVBe0) ![2](https://private-user-images.githubusercontent.com/41451315/373872854-3b1143e8-9cf4-40db-b566-ae9522e16a5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzcyODYsIm5iZiI6MTcyODEzNjk4NiwicGF0aCI6Ii80MTQ1MTMxNS8zNzM4NzI4NTQtM2IxMTQzZTgtOWNmNC00MGRiLWI1NjYtYWU5NTIyZTE2YTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE0MDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOTRiOTE1Yzc5MTBmOGIyZDMyNjE4YmY3MDg4OWZiNDVhMjgyNmFkNzk5M2ViOWI3ZmFiZDY0YWY1YmRmYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Tz1nWDid_FTUIeusTVrODa_lekyVTVj_y8JunI-wwQ)

Now yes, and it works. Thanks !

**Comment by KerimSaman** [comment]
> Did you do the Certificate Install like this?
> 
> ![1](https://private-user-images.githubusercontent.com/41451315/373872853-1a2d4318-006e-43fa-97d4-5f9611b19fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDM1NTcsIm5iZiI6MTcyODE0MzI1NywicGF0aCI6Ii80MTQ1MTMxNS8zNzM4NzI4NTMtMWEyZDQzMTgtMDA2ZS00M2ZhLTk3ZDQtNWY5NjExYjE5ZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE1NDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxOTE5MTFhNjkwMWFlNjA4MTU0YzdlNDYwMDYxYWI1ODMyYWI5MzdmMDM0ZmE1N2QzYjJhNDVlODU4MDlhMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LgSUN-klb24Q3hOo0BalDe6KrWxGbTF_xt3N7zVj1J4) ![2](https://private-user-images.githubusercontent.com/41451315/373872854-3b1143e8-9cf4-40db-b566-ae9522e16a5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDM1NTcsIm5iZiI6MTcyODE0MzI1NywicGF0aCI6Ii80MTQ1MTMxNS8zNzM4NzI4NTQtM2IxMTQzZTgtOWNmNC00MGRiLWI1NjYtYWU5NTIyZTE2YTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE1NDczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZWQyODRmZDlmOTljNjc5YWJiMWQyM2RmN2U0NzRkZGYyNTA5MWU2MWEzMjI3ODhiNDRhNWYxODQ4NGYzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oHxNmP3nNNU_KZ119ynUiqLkd8Jq6ce9boEcqyCFnbU)

Dude, you're a hero.

**Comment by manstheram** [comment]
I should've mentioned that somewhere in the release..

**Comment by CanerTaylan** [comment]
> Use the Beta Version from @manstheram — https://github.com/manstheram/ModernFlyouts/releases
> 
> Works perfectly fine for me on 24H2

Thanks Its working with Beta Version

**Comment by Poxpig** [comment]
you are my hero,my sweetie!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by wefalltomorrow** [comment]
> Did you do the Certificate Install like this?
> 
> ![1](https://private-user-images.githubusercontent.com/41451315/373872853-1a2d4318-006e-43fa-97d4-5f9611b19fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTM2MjAsIm5iZiI6MTcyODYxMzMyMCwicGF0aCI6Ii80MTQ1MTMxNS8zNzM4NzI4NTMtMWEyZDQzMTgtMDA2ZS00M2ZhLTk3ZDQtNWY5NjExYjE5ZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MDRlN2JkZDU3OGI1YTNlOTlhNjYwZGY4NWFhMTFiNjdiODZjNzU4Mzk2ZjIzNjQ0OWE0ODA4N2ZiZTcyYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0PxDqm0-IIUTGeL8sXJzArMGCXWguMLYhDQUxvhymv0) ![2](https://private-user-images.githubusercontent.com/41451315/373872854-3b1143e8-9cf4-40db-b566-ae9522e16a5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTM2MjAsIm5iZiI6MTcyODYxMzMyMCwicGF0aCI6Ii80MTQ1MTMxNS8zNzM4NzI4NTQtM2IxMTQzZTgtOWNmNC00MGRiLWI1NjYtYWU5NTIyZTE2YTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTU5YjRhYjJhZjI0ODYzZWJmZmUwYTc4Njc4OTk4MTNmMWYxODlmNTFlOTVhNWNlMWU0NjZhYmJiYmUwMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pGsw7kzAZfFsdNwS_XnDxCHDURy7o4nQfukLIOtUHQM)

Cheers boss!

**Comment by CanerTaylan** [comment]
I have error when starting (0xlx) with this beta version. App worked only one day. How can I fix it?. 
Windows 11 24H2

**Comment by KerimSaman** [comment]
> I have error when starting (0xlx) with this beta version. App worked only one day. How can I fix it?. Windows 11 24H2

Have you tried doing it all over again?

**Comment by CanerTaylan** [comment]
> > I have error when starting (0xlx) with this beta version. App worked only one day. How can I fix it?. Windows 11 24H2
> 
> Have you tried doing it all over again?

I have reinstalled the program several times but the same problem persists.

**Comment by neradp** [comment]
`Add-AppPackage ".\ModernFlyouts.Package_0.9.8513.0_x86_x64_arm64.msixbundle" -AllowUnsigned`

Use this in powershell console to install ModernFlyouts without certificate.

**Comment by TheAdmiral95** [comment]
> Add-AppPackage ".\ModernFlyouts.Package_0.9.8513.0_x86_x64_arm64.msixbundle" -AllowUnsigned

this works, had to adjust the filename slightly for the current msi

**Comment by halfblack** [comment]
> Did you do the Certificate Install like this?
> 
> ![1](https://private-user-images.githubusercontent.com/41451315/373872853-1a2d4318-006e-43fa-97d4-5f9611b19fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDU1NjQsIm5iZiI6MTczMDMwNTI2NCwicGF0aCI6Ii80MTQ1MTMxNS8zNzM4NzI4NTMtMWEyZDQzMTgtMDA2ZS00M2ZhLTk3ZDQtNWY5NjExYjE5ZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE2MjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDViMzI5ZmViYmE1YjY4MTUxNzUyYTM1ZWE4OGYxMTE0Yjc5NmIyOTQ4MjJmZmE0YTFlZWQ5ODE1MzYwNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RiVUTiym17Y1liZnQ6L66ZYJ1n0NB0WQ_pwahf7s1FI) ![2](https://private-user-images.githubusercontent.com/41451315/373872854-3b1143e8-9cf4-40db-b566-ae9522e16a5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDU1NjQsIm5iZiI6MTczMDMwNTI2NCwicGF0aCI6Ii80MTQ1MTMxNS8zNzM4NzI4NTQtM2IxMTQzZTgtOWNmNC00MGRiLWI1NjYtYWU5NTIyZTE2YTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE2MjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODU5OTZlNTcwNDQzM2Y5MzcxODdjOWFlMDNjODliYzIyMGNjYzJmZGE3NmYyMWFjYWU4MjllYjA2YjUwMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JyTcttquSSdlqxaGMoMqwCzj23-OEib4pbAgVrfydQk)

Commenting just to say thank you, this worked. Much appreciated.

**Comment by nguerrera** [comment]
Is there a non-beta release to Windows Store planned?

**Comment by RhapsodySL** [comment]
Is there a fix for this that also works for the current release version, 0.9.3.0? The latest version from manstheram's repo has some rather large stylistic changes that I am not a fan of.

**Comment by manstheram** [comment]
@RhapsodySL  I don't currently use Windows but I'll make a release to revert any of those changes or make them optional if you can tell me what they are.

**Comment by RhapsodySL** [comment]
Hi, sorry for the delay. I'll get around to this soon, I've been otherwise occupied.

**Comment by RhapsodySL** [comment]
> @RhapsodySL I don't currently use Windows but I'll make a release to revert any of those changes or make them optional if you can tell me what they are.

Sorry again for the delay. Mainly I'm finding that the visual design between 0.9.3.0 (current Microsoft Store version) and 0.10.0.0 (current repo version) is a general downgrade in functionality and appearance. Some specifics:

| Issue  | 0.9.3.0 | 0.10.0.0 |
| ------------- | ------------- |  ------------- |
| Pervasive outline on all elements, not present in older version  | ![image](https://github.com/user-attachments/assets/aefd6752-d12c-4f5a-85fd-6990734a86af) | ![image](https://github.com/user-attachments/assets/8014897d-9613-45cd-a973-1a77f7ab638f) |
| No longer able to show media control buttons and track time together | (refer to above image) | ![image](https://github.com/user-attachments/assets/e53c9d92-70ea-4d4c-98ce-bfb00e9f9820) |
| Secondary track bar is redundant and can't be used for scrubbing | N/A | (refer to above image) |

There's some other nits, but in general I don't find 0.10.0.0 as having any changes that would prompt me to want to use it rather than just using 0.9.3.0, which I've had no real issues with. I'd appreciate if you could compile a release of that version that works on the latest version of Windows 11, or failing that, instructions on what commit fixes compatibility, and how to compile the application so that I can do it myself.

**Comment by Kf637** [comment]
Does not work.

Edition	Windows 11 Pro
Version	24H2
OS build	26100.2161
Experience	Windows Feature Experience Pack 1000.26100.32.0

**Comment by Kf637** [comment]
> > `Add-AppPackage ".\ModernFlyouts.Package_0.9.8513.0_x86_x64_arm64.msixbundle" -AllowUnsigned`
> > Use this in powershell console to install ModernFlyouts without certificate.
> 
> this doesnt work , can you please give any additional advice how to correctly make use this script ? every time I get this mistake
> 
> `Add-AppxPackage : A parameter cannot be found that matches parameter name 'AllowUnsigned'.`

It worked for me, I have developer mode on but not sure if that's what allowed me to install it with the AllowUnsigned flag.

**Comment by neradp** [comment]
Are you sure you have windows 11? I mean that the parameter AllowUnsigned is missing in Win10 ...

https://learn.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=windowsserver2022-ps
vs
https://learn.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=windowsserver2019-ps

The bug is about win11 24H2 version. You can use the store version if it is your case (win10), i mean.

**Comment by manstheram** [comment]
If you can't use the beta, maybe try this: https://github.com/unchihugo/FluentFlyout

**Comment by ivan8994** [comment]
> Are you sure you have windows 11? I mean that the parameter AllowUnsigned is missing in Win10 ...
> 
> https://learn.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=windowsserver2022-ps vs https://learn.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=windowsserver2019-ps
> 
> The bug is about win11 24H2 version. You can use the store version if it is your case (win10), i mean.

thanks for pointing this out, thats true I not use W11 and tried to launch this script on W10 . so on W10 I can ony use BETa ver with certificate

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5

**Comment by Rensoraa** [comment]
> Did you do the Certificate Install like this?
> 
> ![1](https://github.com/user-attachments/assets/1a2d4318-006e-43fa-97d4-5f9611b19fab) ![2](https://github.com/user-attachments/assets/3b1143e8-9cf4-40db-b566-ae9522e16a5a)

where should i install the .cer for the app to work

**Comment by Rensoraa** [comment]
hey you know what dont mind me im stupid!
