### ISSUE TITLE
Feature Request: On Computers with multiple monitors, have a setting to change which monitor the flyout appears on.

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#135]
While this can be done by dragging the flyout to the second monitor, an option or toggle to set which monitor it appears on would be nice.

**Comment by ShankarBUS** [comment]
I was thinking of this exact same thing.

It will be really helpful in case of auto placement.

**Comment by ShankarBUS** [comment]
Implemented this as a part of #369.

The display monitor picker allows us to move the flyout to other displays based on the relative position of flyout and its current monitor.

Hope this is enough :smile:
