### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by skydron9** [ModernFlyouts-Community/ModernFlyouts#1351]
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 11 24H2

### OS build

26100.1591

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout, Lock keys Flyout, Battery Flyout, Audio Tray Flyout

### Steps to reproduce

it doesnt work at all 
![image](https://github.com/user-attachments/assets/60f85e66-fa32-46e3-a3d3-bf6cb25e4187)

### ❌ Actual Behavior

just apears the default one

**Comment by manstheram** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1349

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
