### ISSUE TITLE
NOT OPENING!!!

### ISSUE THREAD

**Issue by tech-guru-2** [ModernFlyouts-Community/ModernFlyouts#1352]
When trying to open the app, it just won't open. It'll just load and not open. I am running windows 11 24h2. The version that I am running is 0.9.3.0 Preview from the Microsoft store. Let me know whether other people have experienced this. This app is really good and I have heard good reviews about it. Just don't know why it won't open.

**Comment by manstheram** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1349

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
