### ISSUE TITLE
Mordern Flyouts is invisble. It says it's working but I don't see anything. 

### ISSUE THREAD

**Issue by SirRicky007** [ModernFlyouts-Community/ModernFlyouts#1353]
### ModernFlyouts Version

latest one? I reinstalled it and same issue. 

### Windows version

Windows 11 Home 24H2

### OS build

26100.1742

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

All I did was updated windows then turned off the laptop until the next day. 

### ✔️ Expected Behavior

To work normally? change volume and it would appear. 

### ❌ Actual Behavior

Nothing happens and I checked to see if it was running and it is. But I can't see anything happening. 

### Other Software

windows 11? spotify, youtube (chrome and opera gx) 

### Additional Context

Yeah it's not working.

**Comment by manstheram** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1349

**Comment by CanerTaylan** [comment]
It doesn't work for me either. It was working till 24H2 update.
Windows version : Windows 11 Home 24H2
OS build : 26100.2033
Platform : x64

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
