### ISSUE TITLE
Modern Flyout is not wr

### ISSUE THREAD

**Issue by AdemEsadAk** [ModernFlyouts-Community/ModernFlyouts#1354]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 24H2

### OS build

26100.1742

### Steps to reproduce

![resim_2024-10-12_220248550](https://github.com/user-attachments/assets/d2803a1f-9822-43a5-a22e-19ffa178696d)

### ❌ Actual Behavior

The app opens but when pressing the volume up and down keys or other keys, the pop-up window does not appear. This worked fine in version 23H2 but now it does not work

**Comment by Seayay** [comment]
#1349

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
