### ISSUE TITLE
Don't work on Windows 11 24H2

### ISSUE THREAD

**Issue by KobilyanskyS** [ModernFlyouts-Community/ModernFlyouts#1355]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 24H2

### Platform

x64

### Area(s) with issue?

System tray

### Steps to reproduce

Just don't work widget on Windows 11 24H2.
When I was on older Windows version, widget was working.
![Снимок экрана 2024-10-14 011546](https://github.com/user-attachments/assets/6565129d-9170-4974-9c3a-80202acc23ce)

### ❌ Actual Behavior

-

**Comment by Seayay** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1349#issuecomment-2395029357
Try this

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5

**Comment by N0WYK** [comment]
> [#1349 (comment)](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1349#issuecomment-2395029357) Try this

work thx
