### ISSUE TITLE
flyout not working

### ISSUE THREAD

**Issue by mehmetgazikrc** [ModernFlyouts-Community/ModernFlyouts#1356]
### ModernFlyouts Version

0.9.3

### Windows version

windows 11 24h2

### OS build

26100.2033

### Platform

x64

### Area(s) with issue?

General, Audio Flyout, Media Flyout, Lock keys Flyout, Battery Flyout, Audio Tray Flyout, Camera Flyout, Mic Flyout

### Steps to reproduce

program is working and i see on system tray but flyout not working (program is good working before windows 11 24h2 update)

### ❌ Actual Behavior

program is working and i see on system tray but flyout not working (program is good working before windows 11 24h2 update)

**Comment by neradp** [comment]
#1349

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
