### ISSUE TITLE
ModernFlyouts is not working

### ISSUE THREAD

**Issue by sebastianm7** [ModernFlyouts-Community/ModernFlyouts#1357]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 24H2

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Just start ModernFlyouts and it doesn't work.

### ✔️ Expected Behavior

The flyouts to be displayed and working fine.

### ❌ Actual Behavior

The flyouts are not displayed and not working.

**Comment by neradp** [comment]
#1349

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
