### ISSUE TITLE
not visible after latest windows update 2024/10/18

### ISSUE THREAD

**Issue by SimoCu3** [ModernFlyouts-Community/ModernFlyouts#1358]
### ModernFlyouts Version

V0.9.1 (12/03/21)

### Windows version

Windows 11 Pro 24H2

### Platform

x64

### Area(s) with issue?

Welcome / ModernFlyouts OOBE

### Steps to reproduce

with the latest windows update the pop up seems to no longer be present, by passing the cursor over it and clicking you notice that it is present but you can't see it

### ✔️ Expected Behavior

work

### ❌ Actual Behavior

not visible after latest windows update 2024/10/18

**Comment by neradp** [comment]
[1349](https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1349l)

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
