### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Pratham3642** [ModernFlyouts-Community/ModernFlyouts#1359]
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 11

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

no idea since after downloading its not working directly 

### ✔️ Expected Behavior

it should work properly when downloaded without any issue

### ❌ Actual Behavior

when i downloaded it is not working only the application is seen but the main feature is not working like the flyout even after selecting modern flyout
![Screenshot 2024-10-29 161935](https://github.com/user-attachments/assets/0a7122ab-78fa-429e-b709-aad5c0703469)

### Other Software

system

### Additional Context

nothing

**Comment by Samuel12321** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
