### ISSUE TITLE
Feature Request: Split the Media session Flyouts and volume flyouts as it was pre 0.5

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#136]
I have talked with @ShankarBUS about this, but thought i would create a proper request for it.

- Aligns more with windows 10X and feels more modern in my opinion

**Comment by ShankarBUS** [comment]
I will find the possibilities for this.

I will try to include this before v0.8

**Comment by ShankarBUS** [comment]
Ok guys choose either.

Option **A**: Space between media controls and volume controls ✔. No Shadows✖.

![](https://user-images.githubusercontent.com/18244287/88845979-9d9d2f80-d1ed-11ea-96c2-cf7f52ca685c.png)

Option **B**: Shadow ✔. Spacing ✖.

![](https://github.com/ShankarBUS/ModernFlyouts/raw/main/docs/images/Audio_Session_Music_NoTop.png)

👍 for Option **A**. 👎 for Option **B**

**Comment by Samuel12321** [comment]
The other option is could this be a user setting?

**Comment by lucasskluser** [comment]
I think the gap is more concise with win 10 UI

![image](https://user-images.githubusercontent.com/28795323/97209441-1aaf5500-179b-11eb-8683-5f6b9caa489a.png)

**Comment by Poopooracoocoo** [comment]
@lucasskluser the problem with referencing the current SMTC is that it's from the Windows 8 or Metro era.

**Comment by Samuel12321** [comment]
Windows 10X
![image](https://user-images.githubusercontent.com/35312698/97247964-94ac1080-1865-11eb-88b0-381e5a3a20e6.png)

**Comment by Samuel12321** [comment]
Tentatively added this to 0.8.3

**Comment by Samuel12321** [comment]
@ShankarBUS just noticed you removed this from 0.8.5, did you have another release in mind?

**Comment by ShankarBUS** [comment]
@Samuel12321,

Yup! Will do later in a future release.

We need a UI\UX designer's guidance first. I keep messing things up. We need to plan properly and then do the UI.

**Comment by Samuel12321** [comment]
@GSonofNun @jayasio,@WinstonSepruko Any ideas on this one.

**Comment by WinstonSepruko** [comment]
The three of us could probably figure something out together, I'd really like to be able to implement the fluent UI icons too, giving two style choices to the end user. Would they like to go with Segoe Assets or the new FluentUI icons? I know the new icons aren't readily and easily available for development and come in different sizes, the only official source I've seen was for building mobile apps. I do hope they become an option in the near future as I personally prefer them. Segoe will be number one priority.

**Comment by Samuel12321** [comment]
we tried the new fluent icons a while back, unfortunately the looked awful

**Comment by WinstonSepruko** [comment]
> we tried the new fluent icons a while back, unfortunately the looked awful

Every possibility the current design didn't mix well with them, and as I said Segoe takes priority.

**Comment by GSonofNun** [comment]
> @GSonofNun @jayasio,@WinstonSepruko Any ideas on this one.

I guess, what are you looking for exactly? Do you want someone to make some UI mockups? Someone to actually implement what was designed? Both? Other?

**Comment by Samuel12321** [comment]
both, probably.
As you can see above we do have an example ui from an older release. 
Advice on whether this is better in terms on UI styling would be good

**Comment by GSonofNun** [comment]
I do personally like the idea of it being split. Going off the example above, I'd want maybe a little larger of a gap than what was there before. Something around what the Windows 10X screenshot has.

**Comment by jayasio** [comment]
> I do personally like the idea of it being split. Going off the example above, I'd want maybe a little larger of a gap than what was there before. Something around what the Windows 10X screenshot has.

I agree. 
Keeping the media controls away as a separate card keeps the volume slider consistent with the brightness slider. 
The media controls are 'adding' to the slider only when some media is active; the volume slider is permanent. Visually it is easier to comprehend.

**Comment by ShankarBUS** [comment]
The drop Shadow is the only problematic thing.

If the controls are hosted in a single shadow chrome, there's no overcast of shadows. This is why I had to merge them.

But if the slider and media controls are hosted on different shadow chromes (which is a requirement inorder to split them), the media controls would cast shadow on the slider. Which is unwanted and unappealingly for the users.

So we have to remove the shadow completely which will result in yet another inconsistency with the Windows 10X shell.

**Comment by Cyberdroid1** [comment]
Umm, I think we can try ditching the Win10X design language, eh? 

I mean, save the code of present situation somewhere.

If did not look good, we can revert back, no? 

I don't know if it would be a practical idea, but hey, why not try it?

**Comment by zeealeid** [comment]
I like how it is right now but I'm in favour of splitting the card into two as it provides distinction between elements like the volume slider and the media controls.

**Comment by ShankarBUS** [comment]
@zeealeid,

Cool!

So do you want the shadows to be there too?

If we are to remove the shadows, the process of splitting the controls will be relatively easy.

What do you say?

**Comment by GSonofNun** [comment]
> If the controls are hosted in a single shadow chrome, there's no overcast of shadows. This is why I had to merge them.
> 
> But if the slider and media controls are hosted on different shadow chromes (which is a requirement inorder to split them), the media controls would cast shadow on the slider. Which is unwanted and unappealingly for the users.

Is this a problem with the shadow chrome control? Or could it be a Z-order problem with the layout of the XAML?

**Comment by ShankarBUS** [comment]
It's a problem with both the shadow chrome control and the z-order.

**Comment by GSonofNun** [comment]
To save me a little time while I look at the code, is this a WPF application hosting UWP controls with XAML Islands?

**Comment by ShankarBUS** [comment]
No, this is a pure WPF application using ModernWpf as the UI library.

**Comment by GSonofNun** [comment]
Gotcha.

**Comment by GSonofNun** [comment]
I made a quick test WPF app using ModernWpfUI for the shadow, and it doesn't seem to be impossible to make the shadows work properly.

![image](https://user-images.githubusercontent.com/3924712/103180256-27672c80-4862-11eb-8d30-e3729a128486.png)


If I get the Z-order wrong though, the shadows can overlap improperly.

![image](https://user-images.githubusercontent.com/3924712/103180301-862ca600-4862-11eb-9f9e-f5c67ab1c45a.png)


In case you aren't aware, (I don't know you or your XAML skill/knowledge levels very well), when multiple objects are defined at the same indentation level, the second object has a higher Z-order. Which is why the case in the second images doesn't work. The second 'ThemeShadowChrome' is defined after the first one, so it will render over the top of the first one.

**Comment by ShankarBUS** [comment]
@GSonofNun,

Hmmmmm, that worked! But not in every case.

With v0.9 we are planning to add the ability to auto place the flyout, change the expand direction and the stacking of controls (media controls above volume controls and vice versa).

In that case we would need to change the z-order of whatever control in bottom to be the highest.
Could this be done by using the `Panel.ZOrder` attached property?

The shadow chrome from ModernWpf is designed to be directed downwards so we didn't expect any issue. But if the shadow was uniform, we could do nothing.

So anyways, it works! I was lazy and didn't have time to experiment with it.

Thank you so much @GSonofNun!

I would try to do this ASAP.

**Comment by GSonofNun** [comment]
The `Panel.ZOrder` property only works when the controls are parented in a `Canvas` control. The downside to using a Canvas is you have to be more specific about size and location of child elements.

I see you are using a `CrossFadeContentControl` to host `FlyoutHelper.PrimaryContent` and another to host `FlyoutHelper.SecondaryContent`. We can probably play around with this pattern to allow re-arranging content.

**Comment by ShankarBUS** [comment]
I heard from someone that `Panel.ZIndex` works even for Grid. Ref: https://blog.mzikmund.com/2020/12/control-rendering-order-in-uwp-grid-using-canvas-zindex/

I'm planning to use a `DockPanel` instead of the `StackPanel` (this way we could swap the controls up and down easily).

**Comment by GSonofNun** [comment]
> I heard from someone that `Panel.ZIndex` works even for Grid. Ref: https://blog.mzikmund.com/2020/12/control-rendering-

So it does. I stand corrected. 🙂

**Comment by ShankarBUS** [comment]
@GSonofNun,

So mate, I remember you wanted to make a global media control app.

I have abstracted the code here https://github.com/ModernFlyouts-Community/ModernFlyouts/tree/main/ModernFlyouts.Core/Media/Control

You could use this as the base for your app. I also added some converters and stuff but I know you know how to them work.

This is the only thing I could do in return of your help.

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/103351412-2a178b00-4ac9-11eb-8951-283af30db5e8.png)

You all happy now? Any corrections or suggestions?

**Comment by Cyberdroid1** [comment]
Awesome!!!

**Comment by Samuel12321** [comment]
Great

**Comment by GSonofNun** [comment]
I like it.

**Comment by zeealeid** [comment]
Hot
