### ISSUE TITLE
не работает на последних версиях windows 11

### ISSUE THREAD

**Issue by samiynekonfliktnywindows11user** [ModernFlyouts-Community/ModernFlyouts#1364]
### ModernFlyouts Version

0.9.3.0

### Windows version

winsdows 24H2

### OS build

26100.2161

### Platform

x64

### Area(s) with issue?

General, Audio Flyout, Media Flyout, Lock keys Flyout, Battery Flyout, Audio Tray Flyout, Camera Flyout, Mic Flyout, Welcome / ModernFlyouts OOBE, System tray

### Steps to reproduce

не работает ничего на последних версиях windows 11 , 24H2 

### ✔️ Expected Behavior

не работает ничего на последних версиях windows 11 , 24H2 

### ❌ Actual Behavior

не работает ничего на последних версиях windows 11 , 24H2

**Comment by ivan8994** [comment]
ну тут как бы на англ принято писать

**Comment by neradp** [comment]
Use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5

**Comment by Samuel12321** [comment]
> Use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
