### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by RyouYamada2006** [ModernFlyouts-Community/ModernFlyouts#1368]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro 24H2

### OS build

26100.2161

### Platform

x64

### Area(s) with issue?

General, Audio Flyout, Media Flyout, Lock keys Flyout, Battery Flyout, Audio Tray Flyout, Camera Flyout, Mic Flyout, Welcome / ModernFlyouts OOBE

### Steps to reproduce

I switch music but the program does not react (no animation)

### ✔️ Expected Behavior

new track picture and player

### ❌ Actual Behavior

track switched but no picture or player.

### Other Software

Spotify Free, windows player and I think all the other apps.

**Comment by neradp** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5

**Comment by Samuel12321** [comment]
> use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5
