### ISSUE TITLE
Flyouts Not Appearing - Nov 2024

### ISSUE THREAD

**Issue by X-CPTION** [ModernFlyouts-Community/ModernFlyouts#1370]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Home 24H2

### Platform

x64

### Area(s) with issue?

Flyout does not appear.

### Steps to reproduce

N/A App does not respond.

### ✔️ Expected Behavior

The app appears when keyboard volume up and down buttons are pressed.

### ❌ Actual Behavior

App does not appear.

### Other Software

Media / Volume Control

### Additional Context

I tried to reinstall the certificate, but it did not fix the issue. I also uninstalled and reinstalled (once through MS Store and another through the GitHub package repository), but it also did not fix the issue.

**Comment by neradp** [comment]
use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5

**Comment by Samuel12321** [comment]
> use https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.5

**Comment by X-CPTION** [comment]
Fixed, thank you!
