### ISSUE TITLE
Reveal effect for settings menu

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#167]
Just split this from #66 so each thread is specific to the feature.

**Comment by Samuel12321** [comment]
Tentatively adding this to the 0.8.2 release, especially as 0.8.X is focusing on the settings menu.

**Comment by ShankarBUS** [comment]
Well reveal and in-app acrylic are completely possible.

These could be easily added 😄

**Comment by Poopooracoocoo** [comment]
Is there honestly a point? Microsoft will probably be ditching it because FluentUI for React doesn't have it, which they're increasingly switching, and adapting, to.

**Comment by Samuel12321** [comment]
doesn't mean it doesn't look great.
Furthermore i doubt they will be dropping it any time soon.

**Comment by ShankarBUS** [comment]
Fuck it, **G A Y** flyout! /s
![Flyout](https://user-images.githubusercontent.com/63704247/99844054-89b07b80-2b98-11eb-80f0-bcfd20b301fc.gif)
_(Woah! this GIF is too low quality. I can assure you the rainbow reveal looks fantastic IRL.)_

---

Enough joking. Let me get on topic.

I guess applying reveal to the buttons in the top bar would be too distracting.
My suggestion is to apply reveal effects just to the buttons in the media controls and some buttons in the settings.
Reveal effect on any other places would be distracting and may seem irritating to some users.
What do you think @Samuel12321?
What are your thoughts or guidelines?

**Comment by Samuel12321** [comment]
I was actually only thinking of the settings menu (navigation bar), for exactly this reason.
But yes if we were to apply reveal affect to the flyout it should probably be just to the media buttons.

**Comment by Samuel12321** [comment]
Also The reveal affect should be on the buttons themselves not the flyout border as shown by the GIF

**Comment by ShankarBUS** [comment]
Ok half the work done!

**Reveal Border Effect** has been implemented in cd3652fec69d5eadd4b06932df25b5b03af37794. (still has some complications. will fix it later)
**Reveal Background Effect** is yet to be done. (that ripple effect while pressing) (Is this important tho?)

@Samuel12321,

Even though I found an easy way to add acrylic effect to our app, we shouldn't do that until #32 is fixed.
Because the codebase would change drastically after that. It would be hard to alter the acrylic helpers then. Currently, the demo I showed is hardcoded to depend upon a WPF window ('cause it's easy to detect location & size change). It currently isn't optimized for HWNDs. It's better for us to do it once #32 has been fixed.

**Comment by Samuel12321** [comment]
Ok, will remove this from the 0.8.5 release.
Which release were we going to do #32 ?

**Comment by ShankarBUS** [comment]
v0.10 is max timeline. We should try to fix #32 before v0.9.

Don't add it to any projects because I'm still inconclusive of the solution. Let me ask aΔx before coming to a conclusion.

**Comment by ShankarBUS** [comment]
We did it bois!

After a series of **4 commits**,
1. cd3652fec69d5eadd4b06932df25b5b03af37794
2. 5445f96f6a468d203b4a54e541ea3ae8e8f92e9b
3. 41ac5e16884ae2dab824092e143c16c473ad0d80
4. bff841fc31b0fcdd791c9daa5fdb05be11cc57a9

Reveal effect is finally implemented properly. I will decouple these in the next release and move them to the **ModernWpfCommunityToolkit** so that other apps can be benefitted too.

P.S.
@Samuel12321,

Oopsie....
I forgot to remove the rainbow flyout border reveal. It's still there but hidden. Could we make this an easter egg? Outlook did something like that this year during Pride Month. Should we? Or should we keep it clean?

**Comment by ShankarBUS** [comment]
@Samuel12321,

Could we release v0.8.5 now?
Only the Chinese Localization issue is pending. We may do it with the next release.
Or should we do it immediately?
You can merge the awaiting PR. I will do the culture remap later after v0.8.5.

Whatcha say?

**Comment by Samuel12321** [comment]
> We did it bois!
> 
> After a series of **4 commits**,
> 
> 1. [cd3652f](https://github.com/ModernFlyouts-Community/ModernFlyouts/commit/cd3652fec69d5eadd4b06932df25b5b03af37794)
> 2. [5445f96](https://github.com/ModernFlyouts-Community/ModernFlyouts/commit/5445f96f6a468d203b4a54e541ea3ae8e8f92e9b)
> 3. [41ac5e1](https://github.com/ModernFlyouts-Community/ModernFlyouts/commit/41ac5e16884ae2dab824092e143c16c473ad0d80)
> 4. [bff841f](https://github.com/ModernFlyouts-Community/ModernFlyouts/commit/bff841fc31b0fcdd791c9daa5fdb05be11cc57a9)
> 
> Reveal effect is finally implemented properly. I will decouple these in the next release and move them to the **ModernWpfCommunityToolkit** so that other apps can be benefitted too.
> 
> P.S.
> Bruh, it took me 5 hrs to get the exact same effect as in WinUI. RIP UI designers. Now I understand their pain.

Well-done @ShankarBUS,
Were we going to add reveal to the settings menu navigation headers?

> Oopsie....
> I forgot to remove the rainbow flyout border reveal. It's still there but hidden. Could we make this an easter egg? Outlook did something like that this year during Pride Month. Should we? Or should we keep it clean?

How large is it? 
I'm usually a fan of keeping it clean, however a setting to enable it could be added to the personalisation menu.
Perhaps community feedback on this would bee helpful. @Poopooracoocoo @Cyberdroid1

**Comment by Poopooracoocoo** [comment]
~~i'm gay.~~ it's up to you

**Comment by ShankarBUS** [comment]
> Were we going to add reveal to the settings menu navigation headers?

<img src="https://i.kym-cdn.com/entries/icons/mobile/000/029/405/jordan.jpg" width="500" />

<details>
<summary>I'll add them eventually.</summary>

Sush! I'll kill you mate!
</details>

**Comment by ShankarBUS** [comment]
@Samuel12321,

Answer this https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/167#issuecomment-743043414

**Comment by Cyberdroid1** [comment]
> Perhaps community feedback on this would bee helpful. @Poopooracoocoo @Cyberdroid1 

I guess it can be made into an option. It would be great!

**Comment by Poopooracoocoo** [comment]
@ShankarBUS ahahahah! I see you saw my cheeky edit!! btw i've seen you on the unigram telegram channel. would love to talk to you guys about stuff outside of this repo!!

**Comment by ShankarBUS** [comment]
@Poopooracoocoo,

> I see you saw my cheeky edit!!

Which one? I'm confused...

The **'~~i'm gay~~"** comment?

> btw i've seen you on the unigram telegram channel.

@Cyberdroid1 and I had a beef so we had to clear it up there.

> would love to talk to you guys about stuff outside of this repo!!

You can contact me on Discord (ShankarBUS#3086) or Telegram. We also have a internal discord group (me, @Samuel12321 and @Cyberdroid1). You can join us there.

**Comment by Cyberdroid1** [comment]
Heya @Poopooracoocoo ! Join the telegram channel/discord server! We don't have any way to contact you!

**Comment by Samuel12321** [comment]
> Could we release v0.8.5 now?

sure if you want, only question is whether we wanted to add a button for rainbow reveal and the Chinese localisation issue.

> Only the Chinese Localization issue is pending. We may do it with the next release.
> Or should we do it immediately?

I personally think (as long as there isn't too much work involved), that it may be best to do it now so the languages are defined and we don't have any duplicate translation work done.

> Also I didn't even get the v0.8.2 update! I'm still stuck with the v0.8.1 build! Do something!

That's strange, v0.8.4 (rebranded 0.8.2 due to annoying store issues) has been in the store for a while now.
I'm looking into better ways to sort updates both beta and release. I like the way ear trumpet is using azure pipelines, but will update you with what i come up with.

**Comment by Samuel12321** [comment]
> > Were we going to add reveal to the settings menu navigation headers?
> 
> <img alt="" width="500" src="https://camo.githubusercontent.com/acf382a249bb0c3b7142629ed6165b8c576cf3d83a19003b9fb743e6e3945ddc/68747470733a2f2f692e6b796d2d63646e2e636f6d2f656e74726965732f69636f6e732f6d6f62696c652f3030302f3032392f3430352f6a6f7264616e2e6a7067">
> 
> I'll add them eventually.
> Sush! I'll kill you mate!

hah, just saw that.🤣

**Comment by Samuel12321** [comment]
just changed title to reflect what still needs to be added.

**Comment by ShankarBUS** [comment]
Ah comeon!

I have to do that again 😤.

> rainbow reveal

It could stay hidden. We can do something later.

> I personally think (as long as there isn't too much work involved), that it may be best to do it now so the languages are defined and we don't have any duplicate translation work done.

Ok merge the PR. Remove zh-CN and zh-TW resources. Imma add the remap. We bout to release v0.8.5.

> That's strange, v0.8.4 (rebranded 0.8.2 due to annoying store issues) has been in the store for a while now.
I'm looking into better ways to sort updates both beta and release. I like the way ear trumpet is using azure pipelines, but will update you with what i come up with.

Whooooooo, **Azure pipelines** releasing builds to store? Wouldn't that require **"💲💰💵💸 M O N E Y 💲💰💵💸"**?????
You opened a Dev account in Partner Center not an Organisation account. How would that work with Azure pipelines?

**Comment by ShankarBUS** [comment]
Hey @Poopooracoocoo,

Where you at? Been waiting for you. What's going on?

**Comment by Jaiganeshkumaran** [comment]
Microsoft has removed reveal effects from WinUI 2.6 preview so I recommend not to add reveal to be consistent with other Windows apps in the future.

**Comment by FireCubeStudios** [comment]
> Microsoft has removed reveal effects from WinUI 2.6 preview so I recommend not to add reveal to be consistent with other Windows apps in the future.
i dont care rgb reveal is cool

**Comment by Samuel12321** [comment]
De-prioritized for now.

**Comment by Cyberdroid1** [comment]
So, reveal is officially dying now...

Is it still worth to develop this anymore?

**Comment by ShankarBUS** [comment]
As @Jaiganeshkumaran & @Cyberdroid1 said, reveal is ded 💀. So, we should drop this 💀

**Comment by Samuel12321** [comment]
Agreed, pity I quite liked reveal
