### ISSUE TITLE
Bug: Syntax error appears instead of off beside toggle switches

### ISSUE THREAD

**Issue by Poopooracoocoo** [ModernFlyouts-Community/ModernFlyouts#178]
ModernFlyouts version: 0.8.0.1
Windows 10 version: 20H2
Windows 10 language: English (Australia)

**Comment by ShankarBUS** [comment]
@Samuel12321, FYI

**Comment by ShankarBUS** [comment]
@Poopooracoocoo
¿uɐılɐɹʇsn∀ uɐ ǝɹɐ no⅄

**Comment by Samuel12321** [comment]
@ShankarBUS why is thus closed. Have you fixed it?

**Comment by ShankarBUS** [comment]
Sorry!

**Comment by ShankarBUS** [comment]
@Samuel12321,

This must have been fixed by now, isn't it?

**Comment by Samuel12321** [comment]
unfortunately no, still a problem

**Comment by Samuel12321** [comment]
Tentatively adding to the 0.9 release as this is a frequent bug.

**Comment by Renzo904** [comment]
This is a "translation error", I mean, seems like the Australian english is using the "en-GB" strings, and that strings have "Syntax error" as translation of "Off", tomorrow (12-11 hours later😂) Im going to made a PR if nobody does haha

**Comment by Samuel12321** [comment]
oh, i didn't notice that. 
I only checked en-NZ when i checked to see whether it could just be a translation error.😉😂

**Comment by Samuel12321** [comment]
will include a fix in my next PR

**Comment by Renzo904** [comment]
Haha me too, but then I wanted to check everything
No problem👍

**Comment by Samuel12321** [comment]
9e8bfb453cb1db77175da6f24a2d6854d4753d22

**Comment by Poopooracoocoo** [comment]
Still seeing this issue with version 0.9.0.0 from MS Store and am a beta tester :) @Samuel12321

**Comment by Samuel12321** [comment]
Will look into this.

**Comment by Samuel12321** [comment]
@Poopooracoocoo does this still occur in 0.9.1?
with the exception of the start with windows toggle off position, which has been fixed for 0.9.2 they should all be resolved.

**Comment by Poopooracoocoo** [comment]
@Samuel12321 Still occurring in 0.9.1 :(

**Comment by Samuel12321** [comment]
@Poopooracoocoo can you send a screenshot  + info about your setup - set language, os version...

**Comment by Poopooracoocoo** [comment]
@Samuel12321 
info: 
ModernFlyouts version 0.9.1
Windows 10 20H2
English (Australia)

screenie: 
![image](https://user-images.githubusercontent.com/51363864/111112843-f8389f80-85b4-11eb-92f1-2277776be327.png)

**Comment by Cyberdroid1** [comment]
Aw man. Be fixed already!

**Comment by baloo32** [comment]
Just to add to this:

Modern Flyouts v 0.9.1.0 (just updated)
Win 10 Pro 20H2 (Build19042.868)
English (United Kingdom) [EN-gb?]

![image](https://user-images.githubusercontent.com/10596679/111623940-f6542380-87e2-11eb-8972-3aa4185a1356.png)

![image](https://user-images.githubusercontent.com/10596679/111623985-01a74f00-87e3-11eb-809a-f6ce7cb5e86f.png)

![image](https://user-images.githubusercontent.com/10596679/111624000-079d3000-87e3-11eb-8e9c-b420dce3d751.png)

![image](https://user-images.githubusercontent.com/10596679/111624041-15eb4c00-87e3-11eb-8990-a36658efd921.png)

![image](https://user-images.githubusercontent.com/10596679/111624061-1c79c380-87e3-11eb-8ffc-8c2cc1134090.png)

etc. etc.

**Comment by ErenAKGUN2007** [comment]
In ModernFlyouts.en-GB.xlf, there is a "syntax error" as a translation of "off" in all branches.

`<trans-unit id="Settings.Off" translate="yes" xml:space="preserve">`
`  <source>Off</source>`
`  <target state="needs-review-translation" state-qualifier="tm-suggestion">Syntax error</target>`
`</trans-unit>`

**Comment by Samuel12321** [comment]
Yes it keeps reoccurring, will try to fix it again.

**Comment by Samuel12321** [comment]
Hopefully fixed this time for 0.9.3

**Comment by Poopooracoocoo** [comment]
Can confirm that it's fixed! 🎉
