### ISSUE TITLE
Feature Request: Move flyout default position setting to personalisation page from general

### ISSUE THREAD

**Issue by Poopooracoocoo** [ModernFlyouts-Community/ModernFlyouts#183]
poor guy is all alone :(
![image](https://user-images.githubusercontent.com/51363864/97950477-16161c80-1deb-11eb-9b6c-7a961a2de9d4.png)

ModernFlyouts version: 0.8.0.1
Windows 10 version: 20H2

**Comment by ShankarBUS** [comment]
Will make a new page dedicated to flyout alignment and positioning.

Just waiting to implement auto positioning and expand direction features.

Will do this then.
