### ISSUE TITLE
Bug: Win32 apps' information are not shown in the media session controls

### ISSUE THREAD

**Issue by Poopooracoocoo** [ModernFlyouts-Community/ModernFlyouts#184]
**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Additional context:**

**Comment by ShankarBUS** [comment]
I'll look into it

**Comment by Poopooracoocoo** [comment]
Let me know if you need any more info :)

**Comment by ShankarBUS** [comment]
Bruh! You're a developer debug it yourself 😂

**Comment by Cyberdroid1** [comment]
Do you receive app names for other apps?

**Comment by Cyberdroid1** [comment]
Because the issue that I face is that I never ever receive any app name in the flyout.

**Comment by Poopooracoocoo** [comment]
> Do you receive app names for other apps?

Yes I do

**Comment by Cyberdroid1** [comment]
The bug that I face might be different, since I don't receive app names for any of the media app.

**Comment by fxzxmicah** [comment]
Yes, I have the same problem.

**Comment by Poopooracoocoo** [comment]
weird but as of the latest update to ModernFlyouts and after an in-app reset, i don't have this issue anymore?

**Comment by ShankarBUS** [comment]
How is that even possible?

I didn't do anything to fix that bug!

How could it fix itself?

*(Harry Potter Theme song (earrape) starts playing)*

**Comment by ShankarBUS** [comment]
This is the reason https://github.com/ShankarBUS/ModernFlyouts/issues/140#issuecomment-717004610.

Not only MS Edge, Chrome (and other Chromium based browsers) and Firefox are affected by this but all Win32 apps (unpackaged) are affected.
https://github.com/ShankarBUS/ModernFlyouts/issues/230#issuecomment-731520354
foobar2000 (Store version) v1.5.1 must be a packaged desktop app so it's not affected.

Thers's nothing we can do. This is a bug in the OS. They won't fix it anytime soon. We have to live with this.

**Comment by ShankarBUS** [comment]
@Samuel12321, should we submit a bug report on FeedbackHub so that MS employees get to know of this bug?

Would they even care about this?

I'm pretty sure that this issue didn't occur on 20H2 (that's why I didn't care LOL). It's now happening to me (sed lyp) on Windows 10 Insider Preview Build 20262 (Dev Channel).

So, there is a good chance that they will fix this bug before 21H1.

**Comment by Poopooracoocoo** [comment]
but I'm on Windows 10 20H2? Microsoft never fixes anything. >.>

**Comment by ShankarBUS** [comment]
@Poopooracoocoo,

> but I'm on Windows 10 20H2?

Well it didn't happen to me.

> Microsoft never fixes anything. >.>

That's sad 😢. But we should at least try..... They won't fix it if they don't it exists! That's what I'm saying.

**Comment by Samuel12321** [comment]
@ShankarBUS, worth a try. 
We should probably have on the readme or somewhere a list of all the bugs we have reported to Microsoft and ask people to up vote them. The more votes the more likely they will be fixed.

**Comment by fxzxmicah** [comment]
Is this problem solved? The store has pushed version 0.8.4, and Microsoft edge has been displayed normally.
![image](https://user-images.githubusercontent.com/48860358/101525232-f8c60680-39c5-11eb-8ec6-49e835b9a50b.png)

**Comment by ShankarBUS** [comment]
@fxzxmicah,

No? I don't remember fixing anything 😅. It must have fixed itself. What Windows 10 version are you on?

P.S.

Cyberpunk 2077 Review by IGN? I saw that in the morning too! 🤜🤛

**Comment by fxzxmicah** [comment]
20H2 build 19042.630

P.S.
😘

**Comment by ShankarBUS** [comment]
This could be potentially fixed by migration to the INowPlayingSessionManager https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/29#issuecomment-745411804.

Stay tuned!

**Comment by ShankarBUS** [comment]
😳

![image](https://user-images.githubusercontent.com/63704247/104236107-f9960080-547b-11eb-8ab2-f6edb2a0c797.png)
