### ISSUE TITLE
Current crash reports for 0.8.1

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#212]
![Screenshot 2020-11-12 113233](https://user-images.githubusercontent.com/35312698/98872058-d205d480-24da-11eb-8f24-77453e25e3ad.png)

**Comment by ShankarBUS** [comment]
Wow!

The provided information is too **"helpful"**!

**Comment by Samuel12321** [comment]
i know, but its all they give me. Hence the experimentation with appcenter crash analytics

**Comment by Samuel12321** [comment]
will close this as it should be superseded by app centre crash data
