### ISSUE TITLE
Feature Request: Option to toggle the album art background for media controls

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#224]
Store feedback.

> "An excellent app that should be built into Windows 10. The updated design is fantastic and it works flawlessly! Possible ideas for improvement: - Allow the media controls to expand the volume control upwards. Right now you can't align the volume control to the bottom of the screen because when it expands to account for media, it ends up below the taskbar. This forces the user to pin the volume control near the top of the desktop (e.g. the default position). - An option to toggle the album art background when enabling media controls."

**Comment by ShankarBUS** [comment]
There is already an issue regarding this, isn't it?

**Comment by Poopooracoocoo** [comment]
There are issues 71 and 74 for the other part of their feedback. I don't think there's another issue for this main one.
