### ISSUE TITLE
Translation: Update Arabic language resources

### ISSUE THREAD

**Issue by nhhijgyuffu** [ModernFlyouts-Community/ModernFlyouts#237]
The Arabic language translations of ModernFlyouts are incorrect.

Please update the resources with proper Arabic translations.

**Comment by nhhijgyuffu** [comment]
allughat alearabia

**Comment by nhhijgyuffu** [comment]
> allughat alearabia

**Comment by Cyberdroid1** [comment]
Do you have any problem?

**Comment by Poopooracoocoo** [comment]
@nhhijgyuffu you could make a translation. a problem is that RTL languages may look buggy. 

@Samuel12321 see OP's edit to their above issue and please rename the title :)

**Comment by ShankarBUS** [comment]
Woah! what the hell happened here????

Why is this issue opened and closed too many times?

@Poopooracoocoo,

I will update this issue.

**Comment by Samuel12321** [comment]
we are happy to accept contributions but as we don't know Arabic unless someone contributes we will just have to rely on the machine translations.
