### ISSUE TITLE
Bug: Media keys no longer pause or play the next/previous song

### ISSUE THREAD

**Issue by notLeM** [ModernFlyouts-Community/ModernFlyouts#253]
**Describe the bug:**
Pressing a media key only opens the flyout, doesn't pause, skip or switch songs. It's now only possible by clicking into the respective keys on the flyout itself.

**To Reproduce:**
1. Press a media key (I'll use pause here as an example)
2. The flyout will open but the song won't pause
3. Clicking the pause button in the flyout itself works though

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Additional context:**
 - This issue applies to pause, previous and next media keys

**Comment by ShankarBUS** [comment]
It means that the media player doesn't respond to the media keys.

What is the media player which you experienced this behaviour?

**Comment by notLeM** [comment]
I tried Spotify, Groove Music and Google Chrome through PreMiD (discord RPC for chrome, allows sites like youtube to be controlled with media keys)

All of them didn't respond. They seem to work properly again when I close ModernFlyouts (with the exception of Groove Music for some reason)

**Comment by ShankarBUS** [comment]
Ok I'll investigate

**Comment by notLeM** [comment]
I'd like to correct myself, Spotify only works while the window is focused while the other programs don't respond at all anymore.

I'd also like to add that I installed the program not so long ago and everything worked fine before then, sadly I can't check how it'll work after a restart right now

**Comment by Poopooracoocoo** [comment]
>I'd also like to add that I installed the program not so long ago and everything worked fine before then, sadly I can't check how it'll work after a restart right now

You could try restarting Windows Explorer

I only run into issues after ModernFlyouts has been running for over a day or two, and then I'll have to restart it. I haven't had to restart Windows or Windows Explorer because of ModernFlyouts though.

**Comment by Cyberdroid1** [comment]
Still an issue, @notLeM ?

**Comment by notLeM** [comment]
> Still an issue, @notLeM ?

Oh, I forgot to close this one, sorry! I has been working fine after an update came out

**Comment by ShankarBUS** [comment]
@notLeM,

How TF is that even possible?

I can't believe the bug was fixed! How do people come up with some issues and after sometime the issue gets solved magically?????

I didn't even do anything. TBH, I completely forgot this issue exists.

😂😂😂

Anyways, I'm happy that your problem has been solved.

Please open new issues when you find some **"actual"** bugs.

**Comment by Cyberdroid1** [comment]
@ShankarBUS 
It's windows! You never know what breaks once, whether it gets fixed with an update 😄
