### ISSUE TITLE
Complete app centre Integration.

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#266]
for crash reports.

Have started on this. Just creating the page for it here so everyone knows and i dont forget.😁

**Comment by Samuel12321** [comment]
https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms
https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms

**Comment by ShankarBUS** [comment]
Didn't you add app center integration previously?

**Comment by Samuel12321** [comment]
yes, but i don't think i have it setup correctly to capture crash reports.

**Comment by ShankarBUS** [comment]
They also provide options for user consent before collecting & uploading crash dumps and telemetry. That's great!

You may proceed adding the app center integration!

**Comment by Samuel12321** [comment]
The other good thing about App Centre is that i will be able to add you as a developer if you want, so that you can see all the crash reports and anything else we set it to monitor as well.

**Comment by ShankarBUS** [comment]
Ok great!

**Comment by ShankarBUS** [comment]
Are you working on this?

Any updates?

**Comment by Cyberdroid1** [comment]
@Samuel12321 any updates?

**Comment by Samuel12321** [comment]
still on the to-do list. Im quite buisy at the moment, but will try to finish this in the next few days.

**Comment by Cyberdroid1** [comment]
Hey Sam! Were you able to do it? Just asking 😁

**Comment by Samuel12321** [comment]
Have been very busy recently. will try to look into it when i have some time. The azure pipelines have been my focus at the moment.
Also not sure what else needs to be done, this goes slightly outside my area of expertise. 😁😂

**Comment by Cyberdroid1** [comment]
@Samuel12321 
Were you able to figure this out?

**Comment by Samuel12321** [comment]
I think its done.
