### ISSUE TITLE
Bug:There is a problem with the option display in the APP settings

### ISSUE THREAD

**Issue by smdx** [ModernFlyouts-Community/ModernFlyouts#287]
**Describe the bug:**

Option to display mosaic in APP settings

**To Reproduce:**

1. Go to 'Open the APP settings window'
2. Click on 'Click the brightness module'or'Flight mode module'or'Lock key module'
3. See error

**Screenshots:**

![2020-12-05_180842](https://user-images.githubusercontent.com/9279217/101239873-0a897e80-3726-11eb-821d-8680856e6af5.jpg)
![2020-12-05_182035](https://user-images.githubusercontent.com/9279217/101239937-a4e9c200-3726-11eb-8a08-c18ad44eb7ce.jpg)
![2020-12-05_182043](https://user-images.githubusercontent.com/9279217/101239940-a915df80-3726-11eb-8582-01c8594b3d14.jpg)
![2020-12-05_180938](https://user-images.githubusercontent.com/9279217/101239870-08bfbb00-3726-11eb-89a6-3306b96c5ecb.jpg)

**OS Version:**
 - Windows 10 Version: Windows10 Pro For Workstations 20H2 19042.630

**ModernFlyouts Version:**
 - Version: 0.8.3.0

**Comment by Cyberdroid1** [comment]
Try reinstalling the app. Is it still the same?

**Comment by ShankarBUS** [comment]
Must be a problem with their GPU or Video Driver.

Try updating Windows or tge particular driver.

I heard that some DirectX based apps can break other DirectX based apps (including WPF). In such cases the window content may be scaled randomly.

https://github.com/dotnet/wpf/issues/707

**Comment by smdx** [comment]
> Must be a problem with their GPU or Video Driver.
> 
> Try updating Windows or the particular driver.
> 
> I heard that some DirectX based apps can break other DirectX based apps (including WPF). In such cases the window content may be scaled randomly.
> 
> [dotnet/wpf#707](https://github.com/dotnet/wpf/issues/707).
> 
> Could you check if the last comment help you in fixing the bug?
> What are your PC specifications?

The FakeD3D9 provided in the last comment seems to be used for SteamApps?

My computer configuration：
CPU：AMD Ryzen 5 3600X
Chipset：AMD X570
RAM：32GB
Graphics card：Radeon RX 590

Windows10 Pro For Workstations 20H2 19042.630

**Comment by ShankarBUS** [comment]
<sub>Damn baby your PC specs are hella lit!</sub>

 Look over the thread and see if there are any solutions. I would try to fix this on my side. But you gotta make sure everything's fine on your side. Okay?

**Comment by smdx** [comment]
Okay thank you.
