### ISSUE TITLE
Bug: Media Sessions are not updating in Windows 10 2004

### ISSUE THREAD

**Issue by ShankarBUS** [ModernFlyouts-Community/ModernFlyouts#29]
**Description of the bug :**

Starting from Windows 10 2004 the **GlobalSystemMediaTransportControlsSessionManager** is broken and the `GlobalSystemMediaTransportControlsSessionManager.SessionsChanged` event is not firing properly.

Meaning that the session controls won't be upated whenever an app opens/closes (e.g. Test yourself with Groove Music) & etc.
This makes the session controls (which is a very important feature of this app) useless. But the built-in flyout works somehow.

Source :
Manual verification and from our collaborator @ADeltaX (in https://github.com/ADeltaX/AudioFlyout/issues/12)

> Also I heard that GSMTC as WinRT api is broken in 19041.x (doesn't get notified when an app closes SMTC (e.g. when you close Groove Music))

**Current Workaround :**

Restarting the app updates the sessions (won't update again we have to restart again to update).

**Expected behaviour :**

The app updates itself whenever the GSMTC sessions are updated.

**Proposed method :**

If can't provide any programmatic fix, at-least provide an update button to refresh them manually. Instead of forcing users to restart the app and making things complex.

**Comment by ADeltaX** [comment]
The built-in flyout uses the very old INowPlayingSessionManager com interface.

I haven't tested MtcModel (starting from 14393) enough to say if it's broken or not, but at current situation it will NOT work on .NET due to WinRT marshaller being picky to say the least (If the namespace starts with "Windows." the .NET WinRT marshaller will look for the winmd ONLY in "%windir%\system32\winmetadata". Obviously this is an internal one, so not available in that folder. Failing to find it will die.)

**Comment by ShankarBUS** [comment]
Mm okay. 😑


# HOW TF DO YOU KNOW IT? 🤯😵

Are only the sessions changed not firing? Are there some other events not firing too (for e.g. playback info changed, timeline properties changed & etc)?

Can we do some thing to update it in a programmatic way like by using the `INowPlayingSessionManager` somehow?

**Comment by ADeltaX** [comment]
> # HOW TF DO YOU KNOW IT? 🤯😵

Magic! (You have no idea how many interfaces I damn reversed. This is one of 2 reason why I'm still yet quiet. The another one is being a university student with many exams lol)

> Are only the sessions changed not firing? Are there some other events not firing too (for e.g. playback info changed, timeline properties changed & etc)?

So far I only observed sessions changes not firing.

> Can we do some thing to update it in a programmatic way like by using the INowPlayingSessionManager somehow?
The problem of this interface is that is different across Windows 10 versions.

**Comment by ShankarBUS** [comment]
> Magic! (You have no idea how many interfaces I damn reversed. This is one of 2 reason why I'm still quiet yet. I want to make a big surprise. The another one is being a university student with many exams lol)

dayum boi 🤯
![You are wizard harry](https://i.imgur.com/TFiT7P3.gif)

So the problem is only with .NET (Framework? Core 3.x? 5.0?), Right?

**Comment by ADeltaX** [comment]
If Cs/WinRT was stable enough we would use that compiler/marshaller to create a projection of MtcModel -> as you can have support up to 14393. (LockScreen uses this btw)

**Comment by ShankarBUS** [comment]
What is MtcModel btw?

I'm new to desktop development 😁

**Comment by ShankarBUS** [comment]
Hey @ADeltaX,

> If Cs/WinRT was stable enough we would use that compiler/marshaller to create a projection of MtcModel -> as you can have support up to 14393. (LockScreen uses this btw)

I assume **MTC** abbreviates to **Media Transport Controls** ?

So we're gonna make our ABI projection lib using the Cs/WinRT tool and use that instead of the GSMTC API, right?

So the MtcModel is also a WinRT lib, right?

**Comment by Cyberdroid1** [comment]
Any news, when it will be fixed?

**Comment by PhantomRTX** [comment]
Any idea when this will be fixed?

**Comment by ShankarBUS** [comment]
No updates yet 😅. But this is a high priority and will sure be fixed

**Comment by Samuel12321** [comment]
Microsoft seems to have fixed this on insider builds

**Comment by Samuel12321** [comment]
Can the community verify this.

**Comment by Cyberdroid1** [comment]
I broke my Windows Update, so can't say... 😅 😂

**Comment by Samuel12321** [comment]
@ADeltaX are you able to verify if this has been resolved?

**Comment by Lukasz-egg** [comment]
Hmm, I know this issue, in version 20h2 still appears, but the best way to repair it is to uninstall any last windows update (it will work now) and (optionally) install it again 😉 the bug can unfortunately appears again with small chance, can be repaired using the same method (I comment it because of 'community feedback wanted') 😁

**Comment by ShankarBUS** [comment]
I got a happy new for us!

Yeah!!!!!!!!!! Thank you so much @ADeltaX for helping us.

![](https://i.imgur.com/9DDdDXA.png)

Our delta boi found successfully reversed the `INowPlayingSessionManager`.

This new API is 🔥🔥🔥🔥.

It give us the HWND and Process Id of the media source. F*** even a method to activate the source app!

I hope this would also enable us to find and activate the source with high precision (unlike the current guess and pick one method).

I still haven't seen the full potential of it. All I have is just the metadata. But if this turns out successfully, our app would be a robust alternative to the legacy one.

We could get an insight of it within a few days.

**Comment by Parth-Mawai** [comment]
so when is it going to be released?

**Comment by Parth-Mawai** [comment]
so when is it going to be released ?

**Comment by Parth-Mawai** [comment]
so when can we see the code into action or is it already released?

**Comment by Cyberdroid1** [comment]
It's already under development, as far as I know.

**Comment by Parth-Mawai** [comment]
would you include a flyout for discord too?

**Comment by Cyberdroid1** [comment]
I did not understand what you mean. Why would there be a separate flyout for discord?

**Comment by Parth-Mawai** [comment]
not seperate, but a flyout similar too the existing ones, just indicate that discord is playing audio

**Comment by Cyberdroid1** [comment]
That... would be unnecessary work, IMO. I mean, the current flyout works fine, right?

**Comment by Parth-Mawai** [comment]
no, it doesn't show up for discord

**Comment by WinstonSepruko** [comment]
For me, it does show when Discord is playing audio. This can be seen here:

![image](https://user-images.githubusercontent.com/33651534/103063804-803a8900-4606-11eb-8ee4-5302a70c68fe.png)

(The `#4` is a channel name)

This does seem to have the need of being "provoked" by playing media that is longer than a few seconds, otherwise it will never show.

**Comment by Cyberdroid1** [comment]
Discord maybe does not fully support GSMTC. Otherwise the flyout should support.

What about the default flyout of windows?

**Comment by WinstonSepruko** [comment]
It does, but it doesn't tell you anything other than the channel name (window title MINUS " - Discord").

![image](https://user-images.githubusercontent.com/33651534/103064181-841adb00-4607-11eb-93eb-4722b4810a54.png)

**Comment by ShankarBUS** [comment]
Isn't that like Discord's fault?

What else can we do?

**Comment by WinstonSepruko** [comment]
Nothing. Discord doesn't serve any other information I believe.

**Comment by Cyberdroid1** [comment]
ModernFlyouts atleast tells the app name. Default one doesn't even tell that.

**Comment by Cyberdroid1** [comment]
I think we need to file an issue against Discord.

**Comment by Parth-Mawai** [comment]
@Cyberdroid1 no it doesn't, that's what i'm trying to say

**Comment by WinstonSepruko** [comment]
You'll likely be denied immediately. Discord won't accept requests for features like this, development has also slowed down for Discord, until next year.

**Comment by Parth-Mawai** [comment]
I can't see that kinda flyout 
![image](https://user-images.githubusercontent.com/76217236/103064488-160bef00-45da-11eb-8b63-a2fe32058f2d.png)

**Comment by Cyberdroid1** [comment]
I guess it is a Windows bug then, if you are not seeing like that.

Try restarting the app.

**Comment by Parth-Mawai** [comment]
no change

**Comment by WinstonSepruko** [comment]
> You'll likely be denied immediately. Discord won't accept requests for features like this, development has also > slowed down for Discord, until next year.

I can think of a couple reasons to deny this request...

1. Discord's purpose isn't to serve media outside of itself, it's not a music application or anything of the like.
2. Any audio it creates that responds to keybinds outside of the app within purpose are ones related to video and voice calls, which are not media sessions.

**Comment by Cyberdroid1** [comment]
That are some valid points.

Conclusion--
Its all Discord's fault. Nothing that ModernFlyouts can fix.

**Comment by Parth-Mawai** [comment]
you mean you can't do anything about it, right? ok if you say so

**Comment by WinstonSepruko** [comment]
Not unless Discord suddenly decides to just randomly support serving more information for media sessions on their own will.

**Comment by Cyberdroid1** [comment]
The "magical" moment.

**Comment by Parth-Mawai** [comment]
i thought maybe the new API could have helped in this.

**Comment by ShankarBUS** [comment]
Wee woo wee woo!

Feature update time!

NPSM is in prototyping stage right now.

https://github.com/ADeltaX/NPSMLib

The actual incorporation would happen in a few days.

Stay tuned for more updates 😏.

**Comment by Parth-Mawai** [comment]
any updates?

**Comment by ShankarBUS** [comment]
Well @ADeltaX just fixed a few bugs. We expect to release feature with v0.9 within 2 weeks 😄

**Comment by ShankarBUS** [comment]
It's happening! v0.9 will be released in 2 days or so.

**Comment by iqfareez** [comment]
Excited to see its coming

**Comment by Parth-Mawai** [comment]
@Cyberdroid1 when will the v0.9 be released ?

**Comment by Cyberdroid1** [comment]
It should come soon.
@Samuel12321 any updates?

**Comment by Cyberdroid1** [comment]
@Parth-Mawai,
v0.9 is out!

You can get the app from the GitHub Repo, or you can wait a few days until it is released in store.

**Comment by Lukasz-egg** [comment]
I can't install, it says that app doesn't have needed certificates, even after installing *.cer file ://

**Comment by Parth-Mawai** [comment]
> I can't install, it says that app doesn't have needed certificates, even after installing *.cer file ://

same here

**Comment by Parth-Mawai** [comment]
![image](https://user-images.githubusercontent.com/76217236/105585420-b4949700-5db6-11eb-812e-70a8a3836c08.png)


the error : "This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)"

**Comment by Cyberdroid1** [comment]
To fix that, open the certificate, then install, then choose browse and select trusted people. And install.

Then try installing again. Should work. I just figured out today 😂

**Comment by Parth-Mawai** [comment]
@Cyberdroid1 in which step? i can't see any trusted people type of thing !!

**Comment by Lukasz-egg** [comment]
Media sessions are not updating still...... Spotify steering works, but microsoft edge and other apps no :/// But displaying over everything works ;D
![Zrzut ekranu 2021-01-23 175635](https://user-images.githubusercontent.com/73015967/105608665-9cb41780-5da4-11eb-9da6-de11a5ad242e.png)

![Zrzut ekranu 2021-01-23 175528](https://user-images.githubusercontent.com/73015967/105608628-53fc5e80-5da4-11eb-83d9-c846bedef8dc.png)
![Zrzut ekranu 2021-01-23 175635](https://user-images.githubusercontent.com/73015967/105608631-5a8ad600-5da4-11eb-9549-962d46a8d101.png)

**Comment by KibSquib48** [comment]
is it possible to maybe add an option to restart ModernFlyouts from the system tray context menu?

**Comment by KibSquib48** [comment]
> There is ability to exit app, and then start it from Start menu.
> 
> IMO, adding an option to restart isn't exactly great.

true but it's kind of annoying to have to close modernflyouts and open it from the start menu over and over again basically every hour, a button to restart it would still be nice and make it less of a hassle

**Comment by Cyberdroid1** [comment]
Why do you need to restart the app every hour though?

**Comment by KibSquib48** [comment]
because it happens almost every hour?

**Comment by AnwarBou** [comment]
I encountered this bug today. Kinda a dealbreaker.
