### ISSUE TITLE
Fix System.Runtime.InteropServices.COMException: クラスが登録されていません (0x80040154 (REGDB_E_CLASSNOTREG)) in AudioFlyoutHelper.SetupSMTCAsync ()

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#293]
### Stacktrace ###

ModernFlyouts.AudioFlyoutHelper.SetupSMTCAsync();ModernFlyouts

MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj);MS.Internal

MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state);MS.Internal

MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled);MS.Win32

MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o);MS.Win32

MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam);MS.Win32

MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg);MS.Win32

ModernFlyouts.Program.<>c.<Main>b__1_0();ModernFlyouts.Program

ModernFlyouts.AppLifecycle.AppLifecycleManager.StartApplication(String[] args, Action action);ModernFlyouts.AppLifecycle

ModernFlyouts.Program.Main(String[] args);ModernFlyouts

### Reason ###

System.Runtime.InteropServices.COMException: クラスが登録されていません (0x80040154 (REGDB_E_CLASSNOTREG))

### Link to App Center ###

* [https://appcenter.ms/orgs/ModernFlyouts/apps/ModernFlyouts/crashes/errors/3255476013u](https://appcenter.ms/orgs/ModernFlyouts/apps/ModernFlyouts/crashes/errors/3255476013u)

**Comment by ShankarBUS** [comment]
I mentioned that this crash is handled and won't make the app to close and that this could be ignored **in the AppCenter**. You didn't notice, did you?

Did you just enable services and connected AppCenter to your GitHub account for bug tracking?
Please disable it.

**Comment by Samuel12321** [comment]
> mentioned that this crash is handled and won't make the app to close and that this could be ignored in the AppCenter. You didn't notice, did you?

Autogenerated by appcentre

> Did you just enable services and connected AppCenter to your GitHub account for bug tracking?
Please disable it.

Yes, i thought it might make things easier, however seeing as it just generated a report for an error that you already closed on appcentre, i will disable it now.

Sorry about this

**Comment by Cyberdroid1** [comment]
So appcentre is quite powerful, integration with GitHub.

**Comment by ShankarBUS** [comment]
> So appcentre is quite powerful, integration with GitHub.

You don't know what I saw there. Complete stack trace of exceptions. Distinguishing between crashes and errors. Complete info about the device where the crash occur.

It's megique!

**Comment by Cyberdroid1** [comment]
Wow ok. That's a lotta stuff.
