### ISSUE TITLE
Bug: UI elements is overlap

### ISSUE THREAD

**Issue by Vixb1122** [ModernFlyouts-Community/ModernFlyouts#297]
**Describe the bug:**

**To Reproduce:**
1. play audio
2. change volume
3. right arrow overlap

**Screenshots:**
![image](https://user-images.githubusercontent.com/17810492/101970659-98092900-3c66-11eb-984f-4adfe2aeb9b9.png)

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 0.8.4.0

**Comment by Samuel12321** [comment]
Hi @Vixb1122,
Thanks for reporting this, This is a known issue #60 , please see #60 for further updates on this issue.
