### ISSUE TITLE
Untrusted app

### ISSUE THREAD

**Issue by alok-debnath** [ModernFlyouts-Community/ModernFlyouts#298]
![Screenshot (107)](https://user-images.githubusercontent.com/67475527/101978550-c8a78d80-3c7b-11eb-937e-35b0db996fe4.png)
Is there any way to fix it or any new update arriving soon.

**Comment by ShankarBUS** [comment]
This will be fixed in a few moments. Sorry for the inconvenience. @Samuel12321 FYI.

**Comment by Samuel12321** [comment]
Gah, sorry uploaded the wrong package.

**Comment by alok-debnath** [comment]
😅

**Comment by Samuel12321** [comment]
sorry, fixed now.

**Comment by alok-debnath** [comment]
So, do I need to download the same package again?

**Comment by Samuel12321** [comment]
yes (very slightly different package)

**Comment by alok-debnath** [comment]
Ok, thanks for your efforts
