### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by denisbogdan13** [ModernFlyouts-Community/ModernFlyouts#303]
**Describe the bug:**
The flyout default position is not working because the app replaces the colon with semi-colon. The red border is constantly around the settings and it doesn't seem to save the position settings.
**To Reproduce:**

**Screenshots:**

![image](https://user-images.githubusercontent.com/67539791/102097477-3f808a00-3e26-11eb-8d81-4bc5fa122d90.png)

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
It is planned to be fixed in new update.

**Comment by denisbogdan13** [comment]
Thanks!

pon, 14. pro 2020. 16:22 Pro <notifications@github.com> je napisao:

**Comment by Samuel12321** [comment]
Hi, thanks for reporting this. 
This is a known issue and has been fixed by V0.8.5, which should be released in the next few days.

**Comment by ShankarBUS** [comment]
Did you release it?

Don't do that!

If you didn't do it yet.

Please make sure you only include changes upto bff841fc31b0fcdd791c9daa5fdb05be11cc57a9.

Don't include new changes.

You have to create a new branch upto this commit locally.

Please don't include the new changes.

**Comment by Samuel12321** [comment]
haven't released it yet, was waiting for the language remap

**Comment by ShankarBUS** [comment]
Oh my god! Good.

https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/250#issuecomment-744603056

We are skipping it to post v0.9.

**Comment by Samuel12321** [comment]
👍, will release it now, just up till reveal effect.
