### ISSUE TITLE
Bug: Pressing and holding caps lock toggles flyout twice.

### ISSUE THREAD

**Issue by kotx** [ModernFlyouts-Community/ModernFlyouts#305]
**Describe the bug:**

**To Reproduce:**

1. Press and hold CAPS LOCK.
2. Notice how the correct flyout is displayed at first. 
3. Notice how the flyout toggles again to the incorrect icon and message.

**Screenshots:**

**OS Version:**
 - Windows 10 Version:  2004

**ModernFlyouts Version:**
 - Version:  0.8.4 (as shown in Windows settings)

**Additional context:**

After pressing CAPS LOCK a second time, it displays the correct icon. It only shows the incorrect flyout when holding. 
My flyout delay is set to 500ms.

**Comment by Renzo904** [comment]
I found the problem, when you hold the key, the program is still detecting that key repeatedly, so it pops ON and OFF again and again
