### ISSUE TITLE
Audio flyout not showing properly under some situations

### ISSUE THREAD

**Issue by eiarhabi** [ModernFlyouts-Community/ModernFlyouts#307]
**Describe the bug:**

The audio flyout seem to be not replacing Windows' native volume bar when

1. using volume up/down button on a USB headset to adjust system volume
2. using precision touchpad gesture to adjust system volume 

**To Reproduce:**

1. Attach a USB headset with volume control buttons
2. Adjust the volume using the buttons
3. See error
<br>

1. Set precision touchpad 3- or 4- finger swipe gesture action to volume control
2. Adjust the volume with the gestures
3. See error

**Screenshots:**

![image](https://user-images.githubusercontent.com/27269666/102275694-6eacff00-3eeb-11eb-8785-c1c6bcb233e6.png)

**OS Version:**
 - Windows 10 Version: Windows 10 2004 20251.1

**ModernFlyouts Version:**
 - Version: 0.8.4.0 

**Additional context:**

**Comment by ShankarBUS** [comment]
Oh, that's duplicate of #4.

Thanks for closing it yourself!
