### ISSUE TITLE
Bug: Pinning flyout is not working

### ISSUE THREAD

**Issue by seriaati** [ModernFlyouts-Community/ModernFlyouts#309]
**Describe the bug:**
Pinning flyout is not working.

**To Reproduce:**

**Screenshots:**
![just a gif](https://user-images.githubusercontent.com/61446626/102438298-f7947980-4056-11eb-8244-59ba8416c16b.gif)

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version:

**Comment by Cyberdroid1** [comment]
Hello friend. Sorry to say, but that is not this feature works. To achieve what you are trying to get, open settings and change the flyout timeout.

**Comment by ShankarBUS** [comment]
Oh!

That **"Pin"** button is just to pin or unpin the top bar not the flyout.

Sorry if it was confusing.

**Comment by Cyberdroid1** [comment]
I think having an OOBE could prevent issues like this.

**Comment by seriaati** [comment]
xd
ok
I'm sorry for that

**Comment by Cyberdroid1** [comment]
You can always change the flyout timeout to be a very big value. It will not hide then.

Or

You can keep your mouse on the flyout. Unless you move it, it will not disappear.
