### ISSUE TITLE
Bug: Use mouse change volume to 0, the sound icon not become mute.

### ISSUE THREAD

**Issue by Myuki** [ModernFlyouts-Community/ModernFlyouts#311]
**Describe the bug:**

 Change the sound volume to 0 by mouse not keyboard. The sound icon will not become mute.

The sound icon should become mute just like use keyboard adjust volume.

**To Reproduce:**

1. Active the flyouts

2. Change the sound volume to 0 by mouse not keyboard

**Screenshots:**

![issue](https://user-images.githubusercontent.com/27203797/102438954-3ecf3a00-4058-11eb-86e6-cdb4a4852ba0.jpg)

**OS Version:**
 - Windows 10 Version: 20H2 Build19042.685 

**ModernFlyouts Version:**
 - Version: 0.8.5.0 

**Additional context:**

**Comment by ShankarBUS** [comment]
That was intentional.

I would change that in v0.9.

Thanks for the reminder!
