### ISSUE TITLE
Bug: Use mousewheel turn up volume will stuck at some value

### ISSUE THREAD

**Issue by Myuki** [ModernFlyouts-Community/ModernFlyouts#312]
**Describe the bug:**

Use mousewheel to turn up the volume, it will stuck at some value. Turning down is as normal.

On my laptop it will stuck at 1 3 12 15 24 26 53 59, unless I use keyboard or mouse dragging to turn up across these value.

I don't know this is a common problem or just incompatible with some specific device.

**To Reproduce:**

1. Active the flyouts

2. Try to use mousewheel turn up volume

**OS Version:**
 - Windows 10 Version: 20H2 Build19042.685 

**ModernFlyouts Version:**
 - Version: 0.8.5.0 

**Device Model:**

 - Lenovo IdeaPad S540-13IML (i7-10710U)

**Comment by ShankarBUS** [comment]
I was exactly waiting for this!

I thought I was the only one.

Thanks for reminding me.
I will investigate and fix this issue.
