### ISSUE TITLE
Bug:  Play/Pause/Next and Previous song keys not working since recent update

### ISSUE THREAD

**Issue by Parth-Mawai** [ModernFlyouts-Community/ModernFlyouts#317]
**The bug:**
Since last update, the app(the flyout) is unusual and buggy. Sometimes it just hangs or it doesn't update the album art, but the main issue is that after update i'm not able to play/pause or change to next/previous song which is annoying. I checked the keyboards keys and are working just fine, also when i press play/pause or next/previous song key, the flyout shows up like normal but the action is not carried out(i believe). It used to work before so I assume the problem is not at my end. 

**OS Version:**
 - Windows 10 Version: Windows 10 Pro - 20H2 - 19042.685

**Modern Flyouts Version:**
 - Version: 0.8.5.0 

**Additional context:**
 Meanwhile, any idea how to downgrade, I installed from microsoft store.

**Comment by ShankarBUS** [comment]
Could you try to uninstall the app and reinstall it again?

It would be better if you cam reset all the settings to default ModernFlyouts's settings.

**Comment by Parth-Mawai** [comment]
ok i'll try

**Comment by Parth-Mawai** [comment]
one more thing, i tried restarting the app the my spotify, and it seemed to work temporarily

**Comment by Parth-Mawai** [comment]
i've reinstalled the app and it seems to work fine but i would prefer to test for a day to see if the problem is fixed.

**Comment by ShankarBUS** [comment]
Take your time and report to me once you're satisfied.

You can close this issue then.

**Comment by ShankarBUS** [comment]
@Samuel12321, are you sure you didn't include  b42729be5cc527b5041c2d54581367cafa5dce90 and newer?

Because I broke that thing temporarily.

Are you sure you included changes only upto bff841fc31b0fcdd791c9daa5fdb05be11cc57a9?

Please tell me ASAP.

**Comment by Samuel12321** [comment]
Fairly sure, i created a separate branch for the release.

**Comment by ShankarBUS** [comment]
But are you sure you checked out the new branch and released it?

Because you could have forgot to check out v0.8.5 branch and released the main branch accidentally.

**Comment by Parth-Mawai** [comment]
how can i downgrade until the problem is solved?

**Comment by Cyberdroid1** [comment]
You can get the msixbundle from releases page of the app from github. 

Store does not allow old version installations.

**Comment by Parth-Mawai** [comment]
which version should i go for?

**Comment by Cyberdroid1** [comment]
Sounds good!

Install that version and report if you face the same issue again.

**Comment by Parth-Mawai** [comment]
ya i'm facing same issues

**Comment by Parth-Mawai** [comment]
downgrading much further

**Comment by Parth-Mawai** [comment]
v0.8.1 is stable and functional

**Comment by Parth-Mawai** [comment]
btw after the music app is closed the flyout still shows the app 

![image](https://user-images.githubusercontent.com/76217236/102712174-fc6e5d00-42e4-11eb-993d-3fe2990e39d5.png)

**Comment by Parth-Mawai** [comment]
can you add a "restart app" in the system tray icon for faster testing and also for general troubleshooting

**Comment by ShankarBUS** [comment]
No, the bug you're experiencing is different and is on the OS level.

Please see #29. Closing this as a duplicate.

**Comment by Parth-Mawai** [comment]
pls look into this issue too: Play/Pause/Next and Previous song keys not working since recent update !!
its an important functionality

**Comment by Cyberdroid1** [comment]
Do the same buttons work with the windows default flyout?

**Comment by Parth-Mawai** [comment]
yes perfectly, they used to work with earlier versions of modern flyouts too.

**Comment by Parth-Mawai** [comment]
its like the app is receiving the commands but not responding to them, coz it pops up after pressing the buttons but doesn't do anything. idk how to show that to you.

**Comment by Cyberdroid1** [comment]
You can send a video recording maybe, showing the player and the flyout, if possible.

**Comment by Parth-Mawai** [comment]
ok i'll try

**Comment by Parth-Mawai** [comment]
after installing v0.8.5 to replicate the problem in the latest build, the issue seems to be fixed and the media keys seem to work properly

**Comment by Cyberdroid1** [comment]
The app is same as that of store. Only thing is that it will not update. 

Store might bugging out.

**Comment by Parth-Mawai** [comment]
should i close this issue then

**Comment by Cyberdroid1** [comment]
That's it, I guess. If you have any problem now, feel free to reopen this issue. 😁

**Comment by Parth-Mawai** [comment]
closing this issue, thank you for all the support and providing us with a great app.
