### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by RMA-17** [ModernFlyouts-Community/ModernFlyouts#318]
**Describe the bug:**
ModernFlyout doesn't appear when I set the volume with touchpad

**To Reproduce:**
Increase/Decrease sounds volume with touchpad

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.5.0

**Additional context:**
I have precision touchpad in my laptop, and when I changed volume with it, the sounds still changed but, it doesn't triggered by ModernFlyout

**Comment by Cyberdroid1** [comment]
Duplicate if #4. Please check out that issue.

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

T H A N K Y O U M Y F E L L O W H U M A N !

P.S.

@RMA-17,

W E A R E H U M A N S T O O !
