### ISSUE TITLE
Bug: The No audio device connected notification not showing

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#320]
push volume up or down button while no audio device is connected. No notification is displayed.

**Comment by ShankarBUS** [comment]
Because ShellHook won't be triggered in case of no audio devices.

It is expected. Previously we manually hooked the volume and media keys. So, we had to be clear of the status. But now, ShellHook takes care of that for us.

What do you expect then?
We can't fallback to the old method.

Isn't this the right behaviour?

**Comment by Cyberdroid1** [comment]
What does Shellhook report when there is no audio device?

What does the windows default show for the same?

**Comment by ShankarBUS** [comment]
> ShellHook won't be triggered in case of no audio devices.

The default flyout also have the same behaviour.

**Comment by Cyberdroid1** [comment]
Then, I think this is the correct behavior, no? 

Hey, how does EarTrumpet detect if there are audio devices or not? Their tray icon shows an X beside the volume icon when there is no audio device, IIRC. What if we use the same detection method?

**Comment by ShankarBUS** [comment]
We can detect the unavailability of a audio device since v0.4 for something!!!!!!!

ShellHook won't notify us when there are no connected audio devices and a corresponding key is pressed.

**Comment by Cyberdroid1** [comment]
> We can detect the unavailability of a audio device since v0.4 for something!!!!!!!

>We can detect the keys! Not the absence of devices!!!!!!!!😤😤😤😤😤😤😤😤😤😤😤😤😤😤

Um, seems ironic to me

**Comment by ShankarBUS** [comment]
> So you are saying that ShellHook stops responding to keys when no audio device is there?

Precise!

Profffffff:

![image](https://user-images.githubusercontent.com/63704247/102706752-97057680-42ba-11eb-845b-cda825ed0ebf.png)

![image](https://user-images.githubusercontent.com/63704247/102706749-9076ff00-42ba-11eb-8ff0-0dee302ed45a.png)

### Dil vid it 💲😎🚬

**Comment by Cyberdroid1** [comment]
Oh ok. Got your point!

Close this issue then.
