### ISSUE TITLE
Translation : Cleanup Korean translation

### ISSUE THREAD

**Issue by enusan** [ModernFlyouts-Community/ModernFlyouts#323]
**What version of ModernFlyouts are you using:** Version 0.8.5.0
 

Current Korean translation is translated by machine translator, whole string is weird and hard to understand. I want to contribute a better translation

**Comment by Cyberdroid1** [comment]
You are free to make a PR. 
On instructions on how to make a PR, check the readme for links to the same.

**Comment by ShankarBUS** [comment]
@enusan,

Please wait until we finish v0.9 work. We will notify you then.

**Comment by enusan** [comment]
> @enusan,
> 
> Please wait until we finish v0.9 work. We will notify you then.

OK
