### ISSUE TITLE
Bug:HEY! I was having some problem with the flyout getting stuck one the past song and sometimes having to restart but it still not fixes my problem instead it disables my media control keys . also the flyout are verry buggy and i like the ui you have used but due to this it bugs me a lot so pls fix it it will be great  

### ISSUE THREAD

**Issue by Prakrit-170807** [ModernFlyouts-Community/ModernFlyouts#324]
**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Please fill the issue format properly, only then can we help.

**Comment by Cyberdroid1** [comment]
Closing due to author being negligent.

**Comment by Cyberdroid1** [comment]
You are free to open this issue once you fill the issue template properly.
