### ISSUE TITLE
Feature request: Multi-monitor support

### ISSUE THREAD

**Issue by PIndividual** [ModernFlyouts-Community/ModernFlyouts#327]
Hope there can be a Multi-monitor support that allows user to configure modern flyout on extended displays on Windows 10.

**Comment by ShankarBUS** [comment]
Working on it right now.

Hope to wrap it up for v0.9 soon.

**Comment by ShankarBUS** [comment]
Could you give us more details? I would try to do any changes right away. Quick feedbacks would be really helpful to me in improving this app as soon as possible.
