### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Ansu72** [ModernFlyouts-Community/ModernFlyouts#329]
**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by ShankarBUS** [comment]
More information would be helpful for us to analyse your situation.

**Comment by Cyberdroid1** [comment]
@Ansu72 
Please fill the issue template properly so that we may help you fix the issue.

**Comment by Samuel12321** [comment]
closing due to k=insufficient information and lack of author response. Happy to re-open this @Ansu72 if you can provide more details.

**Comment by Ansu72** [comment]
Hi,

Sorry for the very late responce. 

Well the app downloads and installs but then when you excecute it absolutely nothing happens visibly diffrence even though the app is visible in the task tray. It’s the same old windows fly out with nothing changed.
It’s a new lap top and has some pretty good hardware intel i7, 16gb ram at 3200mhz, NVIDIA RTX 2060 and the intel graphics on the motherboard as well, Win 10 64Bit Pro that’s about as updated as can be and that goes for all hardware drivers,
My layman’s explanation would be that something is keeping the lid on the app not allowing it to excecute; but you know such better than me.

I do have a the TaskbarX app running at the same time just came to my mind but I don’t know if that is interfering. I’ll try to uninstal that one and give it a try again..I’ll let you know.

Thanks for taking your time!

Ansu Aronsson

**Comment by Cyberdroid1** [comment]
Hm, you say the app is visible in the system tray. Does the context menu open for tray icon on right-clicking?

**Comment by Ansu72** [comment]
Hi,

Yes when you right click a small menu comes up that has two options Settings and Quit, translated from Swedish. When you choose settings the settings window opens
As in the picture I attached,
You’ll also see the fly out looks as it always does on windows.

**Comment by Cyberdroid1** [comment]
Unfortunately, you have to share images using GitHub website, not your email client. 

If you have enabled lock keys flyout, does pressing caps lock trigger the flyout?

**Comment by Ansu72** [comment]
Hi,

When I tried doing what you said then a few things poped up, semi transparent windows.

But no real structure or orde to them, one overlapping the other and even if they are “pinned” they disappear as soon as you click else where

**Comment by Cyberdroid1** [comment]
It would really helpful if you can share a recording of your screen when performing the above steps. 
And, you have to send it using Githubz not email.

**Comment by Ansu72** [comment]
Sure i dont mind, its just that i dont have any good screen recorder, or rather i dont have any screen recorder (so its not surprising that its not very good, the one i would have😊)

 

Can yo advice which is good, also which format suits you best, thanks

 

 

 

Från: Pro <notifications@github.com> 
Skickat: den 19 januari 2021 12:57
Till: ModernFlyouts-Community/ModernFlyouts <ModernFlyouts@noreply.github.com>
Kopia: Ansu72 <ansuaronsson@me.com>; Mention <mention@noreply.github.com>
Ämne: Re: [ModernFlyouts-Community/ModernFlyouts] Bug: (#329)

 

It would really helpful if you can share a recording of your screen when performing the above steps.
And, you have to send it using Github, not email.

**Comment by Cyberdroid1** [comment]
You can use OBS Studio to record it.
obsproject.com

**Comment by erayrafet** [comment]
@Ansu72 Fluent Screen Recorder is excellent. Just remember that you can't upload files with a size greater than 10MB to GitHub so you'll have to upload it to Google Drive or similar.
https://www.microsoft.com/en-us/p/fluent-screen-recorder/9mwv79xlfqh7?activetab=pivot:overviewtab

**Comment by Samuel12321** [comment]
Does this still occurr on 0.9.1?

**Comment by Ansu72** [comment]
Hi,
I think it might have been me who did not fully understand the functionality of the app. O had to uninstall it but before i did i switched to English as I had it on Swedish before.

The Swedish text was not inaccurate all together but it’s strange when I understand something much better and clearer in English than Swedish which is my main language that i speak and read fluently although my English is quite ok my Swedish is Perfect to the dot I understood things much clearer in English version, that’s makes me think that it actually might be the translation to Swedish where things might be most wrong, my advice is not I let some other Swedes that you allow to make the app work and rate how easy or difficult  it was and then re-read it in English and ask the same thing again.
If they also understands it better in English like I did them it would have to be rewritten of course.

Best regards,

Ansu
