### ISSUE TITLE
Feature Request: A less distracting design for media transport controls 

### ISSUE THREAD

**Issue by MarcAnt01** [ModernFlyouts-Community/ModernFlyouts#337]
**Is your feature request related to a problem? Please describe:**

I find very annoying how the thumbnail is put on the background. It's already next to the text and there's no need in my opinion to iterate it

**Describe the solution you'd like:**

Consider a similar design to Windows original layout, putting just a thumbnail next to the volume control to make the other information about the track more readable

**Describe alternatives you've considered:**

None

**Additional context:**

Not needed

**Comment by ShankarBUS** [comment]
@fheck implemented this in #315.

I'm not sure if the feature has been released with v0.8.5 or not. If not It will be bundled with v0.9 later this month.

**Comment by MarcAnt01** [comment]
I am running 0.8.5 and it's not here, I'll wait for 0.9. Thanks for your answer
