### ISSUE TITLE
Bug: Volume media content is messed up after hibernation 

### ISSUE THREAD

**Issue by MarcAnt01** [ModernFlyouts-Community/ModernFlyouts#340]
I was watching a YouTube video before my pc run out of power, when I turned it on again plugging the charger, the volume controls were showing the old YouTube video even after closing the tab and playing new content

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 
 - 0.8.5

**Additional context:**

Not needed

**Comment by ShankarBUS** [comment]
Oh this issue could be tracked down to #29.

We are migrating to a new API. This is a bug in the OS.

We would fix this in v0.9 or v0.10.

**Comment by MarcAnt01** [comment]
Got it, feel free to close it if you think that's a duplicate 👍

**Comment by Samuel12321** [comment]
Thanks @MarcAnt01 , will close this. See #29 for updates.
