### ISSUE TITLE
Flyouts not coming on with on using gesture to change volume

### ISSUE THREAD

**Issue by walter6469** [ModernFlyouts-Community/ModernFlyouts#341]
When the settings are like this 👇
![image](https://user-images.githubusercontent.com/70185618/103533504-3e85ca00-4eb3-11eb-979a-138613169bcc.png)

https://user-images.githubusercontent.com/70185618/103533903-f2875500-4eb3-11eb-81b5-9dc15e81a78e.mp4

As you can see, first the old slider comes up when I use that gesture, and then I use volume key and the modern flyout comes up.
I close it.
I use gesture and old slider comes, I accidentally **click** and volume goes to number **7**, I then again move my cursor and use touchpad and the old slider comes, then I use volume key and the modern flyouts comes, and then **AFTER** modern flyout comes up, using the gesture **KEEPS** the modern flyout.

**Comment by Cyberdroid1** [comment]
This is a known issue and being tracked in #4. Please see that issue.
