### ISSUE TITLE
Bug: The 'Rate and Review on Microsoft Store' button in the About Section of the app doesn't work

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#344]
Store reported bug:

> The 'Rate and Review on Microsoft Store' button in the About Section of the app doesn't work. It just opens the home page of the Microsoft Store

**ModernFlyouts Version:**
 - Version: 0.8.5.0

**Comment by Cyberdroid1** [comment]
Yeah, I have noticed this, but I forgot to report 😅

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/103855204-c7e5f980-5077-11eb-9240-f2464bd22e9c.png)

I personally think that this entire page could get a revamp.

**Comment by Cyberdroid1** [comment]
Agreed.

**Comment by ShankarBUS** [comment]
I broke it intentionally so that no one can complain 😈 /s

Seriously? It must be a bug in the Store then. @Samuel12321, did our app's store product id get changed?

**Comment by ShankarBUS** [comment]
@Tropix126,

Like how?

**Comment by Samuel12321** [comment]
@ShankarBUS I'll take care of the broken rate button.

@Tropix126 we are open to any suggestions

**Comment by ShankarBUS** [comment]
@Samuel12321, 👍.

What branch are you working on?

**Comment by Samuel12321** [comment]
dev currently. About to merge samtesting and dev

**Comment by ShankarBUS** [comment]
No no. Don't merge that.

I told you some suggestions, right? Did you do them?

**Comment by Samuel12321** [comment]
I will before merging them

**Comment by ShankarBUS** [comment]
Just merge the app installer and app update improvements. Don't include the changes in Settings window (General and the new flyout position page). I'll take care of that.

**Comment by Samuel12321** [comment]
ok

**Comment by Cyberdroid1** [comment]
> Like how?

I would say similar to how the website looks, except that the background stays black, and the flyout is replaced by the app icon.

**Comment by ShankarBUS** [comment]
Then the app would be inconsistent from other inbox apps. I don't prefer creating a new design. Let the settings be the way it is.

**Comment by Cyberdroid1** [comment]
How about removing the "Open a new issue" button?
And adding background to all buttons, like how it is with rate and review button.
And, increasing the font size of the version number.
