### ISSUE TITLE
Bug: can`t install 

### ISSUE THREAD

**Issue by WhiteBite** [ModernFlyouts-Community/ModernFlyouts#345]
![image](https://user-images.githubusercontent.com/19576772/103929943-0c809c00-512f-11eb-83e3-8d4f4974f28d.png)
I tried to install the latest version from github and from microsoft store. Everywhere the same error (see screenshot)

**Comment by Cyberdroid1** [comment]
Try installing the app with the antivirus turned OFF. 

Looks like the exe file is getting deleted somehow.
