### ISSUE TITLE
Bug: The system flyout for caps lock is not hidden

### ISSUE THREAD

**Issue by stelulocom** [ModernFlyouts-Community/ModernFlyouts#346]
There is no hiding system default uppercase popup.

**To Reproduce:**

1. Go to Popup window module
2. Click on Caps lock
3. See error

**Screenshots:**

**OS Version:**
 - Windows 10 Version:  
 - 20H2

**ModernFlyouts Version:**
 - Version: 
 - 0.8.5
**Additional context:**

**Comment by Cyberdroid1** [comment]
Please give some more info. Like, screenshots or a recorded video to help you out.

**Comment by Tropix126** [comment]
The system does not have a caps lock flyout by default I believe. This is most likely related to software installed by your manufacturer. For example, lenovo has this.
![image](https://user-images.githubusercontent.com/42101043/104039992-b8ac9c00-519c-11eb-9e0d-f5689e940300.png)

**Comment by Cyberdroid1** [comment]
Ah, now I get it. Yeah, it's the doing of the OEM. I don't think if anything can be done to supress it. I would suggest to just turn off flyout for caps lock.

**Comment by Tropix126** [comment]
Only advice I can give is that if you're using a lenovo device, uninstall "LenovoUtility".

**Comment by stelulocom** [comment]
ok
