### ISSUE TITLE
Feature Request: Add an always on flyout that replaces the one on the Windows lock screen

### ISSUE THREAD

**Issue by Tech-How** [ModernFlyouts-Community/ModernFlyouts#347]
**Is your feature request related to a problem? Please describe:**
Whenever I lock my computer while I have music playing, I still get greeted with the old metro flyout in the bottom corner.

**Describe the solution you'd like:**
I think it would be cool if there was a flyout that replaced the one on the Windows lock screen. To see what I mean, start playing music in Groove (just import some mp3's or something) and then lock the screen (Win+L).

**Describe alternatives you've considered:**
None.

**Additional context:**
I would attach screenshots, but you can't take them while the screen is locked.

**Comment by Samuel12321** [comment]
Hi @Tech-How , great minds think alike.
We have been working on this for a while, it will be part of the next update v0.9, which we are planning on releasing in the next few days.
Please see #32 for follow-up on this issue.
