### ISSUE TITLE
Bug: Flyout doesnt appear during fullscreen

### ISSUE THREAD

**Issue by khushrxnx** [ModernFlyouts-Community/ModernFlyouts#354]
It would be great if flyouts can appear during fullscreen for youtube or any media because it very hard to know the adjustments during that time.

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: v0.8.5.0

**Comment by ShankarBUS** [comment]
We fixed it lol. Not yet released. But will be included in v0.9 in the upcoming weeks.

Now it will even show above lock screen 😏.

**Comment by khushrxnx** [comment]
> We fixed it lol. Not yet released. But will be included in v0.9 in the upcoming weeks.
> 
> Now it will even show above lock screen 😏.

Oh wow Perfect! Haha
