### ISSUE TITLE
Bug: Menu

### ISSUE THREAD

**Issue by rusti4** [ModernFlyouts-Community/ModernFlyouts#355]
**Describe the bug:**
The menu shows toggle 'off' as syntax error instead of 'off'.

**Screenshots:**

![image](https://user-images.githubusercontent.com/24264511/104379912-43670f80-557e-11eb-816f-82bc50e5d8d6.png)

**OS Version:**
 - Windows 10 Version: 10.0.19042 Build 19042

**ModernFlyouts Version:**
 - Version: 0.8.5.0

**Comment by Cyberdroid1** [comment]
This will be fixed in the upcoming release, v0.9. Please wait, for it will be released in the next week or so.

**Comment by Cyberdroid1** [comment]
Please see #178 if you would like to know more.
