### ISSUE TITLE
Feature Request: Make default position have X value centered

### ISSUE THREAD

**Issue by kleenkanteen** [ModernFlyouts-Community/ModernFlyouts#358]
**Is your feature request related to a problem? Please describe:**
Would look nice if it was centered at the top by default.

**Comment by Samuel12321** [comment]
Hi @kleenkanteen , we are working on a huge update to the positioning interface so it will be much easier to choose a position in 0.9.
I think its best to leave the default the same position as the Windows default flyout to appease the majority of users. However if the user wants it can be moved.
