### ISSUE TITLE
Bug:It sticks out when changing the font

### ISSUE THREAD

**Issue by umbrella-k** [ModernFlyouts-Community/ModernFlyouts#359]
**To Reproduce:**
I also Meiryo UIも大っきらい!! Change the font using (No Meiryo UI). ..
I am using Source Han Serif Heavy　9pt.

**Screenshots:**

![スクリーンショット 2021-01-15 232347](https://user-images.githubusercontent.com/68675858/104738329-bba12100-5788-11eb-8295-e17e4a73c1d3.png)

**OS Version:**
 - Windows 10 Version: 
Windows 10 Version 2001 OS Build 21292.1000 Home Insider Preview
**ModernFlyouts Version:**
 - Version: 
 0.8.0.1

**Additional context:**

I want you to make an option to change the font
<br> Used　GoogleTranslate </br>

**Comment by Tropix126** [comment]
@ShankarBUS Is there a setting to prevent text wrapping and just have it overflow from the container? It might be easier than dynamically scaling the font size.

**Comment by ShankarBUS** [comment]
1. This is not a bug

2. No, we are not responsible for your own actions or your own needs. This request is too specific for you.

I don't believe this will be worked on any further 🙂.
