### ISSUE TITLE
Feature Request: (Visual suggestion) Make media seek bar blended in more with the panel

### ISSUE THREAD

**Issue by eshuaiii** [ModernFlyouts-Community/ModernFlyouts#362]
Hi there! Apologies for accidentally pressing Enter before I finished editing this issue 😅
I really like ModernFlyouts, thank you to all the developers who came up with this idea and are maintaining it!
**Is your feature request related to a problem? Please describe:**
This issue is more of a suggestion/idea, but ties in with the strange looking timeline button that is present on my flyout:
![image](https://user-images.githubusercontent.com/63947753/104798942-ce632800-577f-11eb-8d7b-ec49d69d277c.png)

**Describe the solution you'd like:**
I thought maybe it'll be cool to have the timeline bar along the bottom edge of the flyout, perhaps as a (rounded) rectangular bar that goes along the bottom edge of the flyout from end to end. I thought of this idea after a visual bug caused a rectangle to appear near the bottom-middle of the flyout which caused me to think it was actually the seek bar.
A (super quick) sketch of what I'm thinking:
![image](https://user-images.githubusercontent.com/63947753/104799020-6f51e300-5780-11eb-8526-fd5f1506690f.png)
Perhaps with a glow-like appearance, like the new Google Assistant design on newer Pixel models? (context: https://www.androidpolice.com/wp-content/uploads/2019/10/2019-10-15-Google-Assistant-01.png)

This is just an idea, and I know it must be difficult to implement certain things, especially amidst all that happening right now. Thank you for your consideration!

**Comment by eshuaiii** [comment]
I'm so sorry! I can't believe I posted this before I got a chance to even edit it. I'll fix it pronto.

**Comment by Cyberdroid1** [comment]
We are adding seeking bar in the next version, which is just around the corner. Stay tuned!
