### ISSUE TITLE
Bug: Flyout not appearing when another key is pressed

### ISSUE THREAD

**Issue by dynamiquel** [ModernFlyouts-Community/ModernFlyouts#364]
I looked for a duplicate but couldn't find one.
When I press the Pause/Play button with any other button, the old audio flyout comes up instead (unless the modern layout is already open).

**Comment by Cyberdroid1** [comment]
Can you please elaborate? I was not able to understand. 
What keys in order?

**Comment by dynamiquel** [comment]
> Can you please elaborate? I was not able to understand.
What keys in order?

So if I was to press any key whiles also pressing the Play/Pause button, the old audio flyout appears.

For example:
- Pressing Shift and Play/Pause at the same time (which I do quite a bit because sprinting in games).
- Pressing R and Play/Pause at the same time.

**Comment by Cyberdroid1** [comment]
So, modernflyouts is not getting triggered hmmm.
@ShankarBUS have any idea?

**Comment by Renzo904** [comment]
Isn't this related to #4?

**Comment by dynamiquel** [comment]
> 
> 
> Isn't this related to #4?

It does seem very similar. It's just that in this case, it's media controls with other keys; not just other keys.

**Comment by OctoNezd** [comment]
+1 on this issue. Hitting media play/next/prev on my laptop makes default flyout appear. Maybe it is cause I use autohotkey for these buttons?

**Comment by Renzo904** [comment]
@OctoNezd Yes it is, unfortunately, the app doesn't support most of the 3rd party apps yet

**Comment by Cyberdroid1** [comment]
Using Powertoys Keyboard manager is better, it sometimes produces Modernflyouts instead of the default, but not every time. Try giving it a try

**Comment by OctoNezd** [comment]
Powertoys keyboard manager worked for me, thank you!
