### ISSUE TITLE
Bug: Volume control with Bluetooth headset uses classic flyout

### ISSUE THREAD

**Issue by Tech-How** [ModernFlyouts-Community/ModernFlyouts#365]
**Screenshots:**
![image](https://user-images.githubusercontent.com/76794507/104823141-dff70f00-5815-11eb-8960-fb720b0c73aa.png)

**OS Version:**
 - Windows 10 Version: Windows 10 Version 20H2 (OS Build 19042.746)

**ModernFlyouts Version:**
 - Version: 0.8.5.0

**Comment by Samuel12321** [comment]
Duplicate of #4
