### ISSUE TITLE
Audio Flyout is not visible in Valorant game when changing volume 

### ISSUE THREAD

**Issue by Sandakan** [ModernFlyouts-Community/ModernFlyouts#367]
Audio flyout is not visible when changing volume in the Valorant game. 

**OS Version:**
 - Windows 10 Version: Windows 10 Pro 20H2 build 19042.746 Windows Feature Experience Pack 120.2212.551.0

**ModernFlyouts Version:**
 - Version: v0.8.5.0

**Comment by ShankarBUS** [comment]
Working on it

**Comment by ShankarBUS** [comment]
And this is a dupicate of #32
