### ISSUE TITLE
Bug: (0.9.0) Duplicated media sessions

### ISSUE THREAD

**Issue by KibSquib48** [ModernFlyouts-Community/ModernFlyouts#381]
**Describe the bug:**
There are two or more sessions all for the same thing. In the screenshot provided there are only 2 for Xbox Game Bar, but there is also an additional 6 from Microsoft Edge

**To Reproduce:**

1. Open flyout
2. Try to pause video from another window
3. There are multiple sessions for multiple apps, all saying the exact same thing

**Screenshots:**
![image](https://user-images.githubusercontent.com/33189136/105621136-79a05c80-5dd2-11eb-8188-bf9daa7d7c07.png)

**OS Version:**
 - Windows 10 Version: Windows 10 20H2 19042.782

**ModernFlyouts Version:**
 - Version: 0.9.0

**Additional context**
Closing and restarting ModernFlyouts seems to fix the issue

**Comment by ADeltaX** [comment]
It's a bug very easy to trigger, I'm working on it.

**Comment by Samuel12321** [comment]
@ShankarBUS didn't adeltax already fix this?

**Comment by ShankarBUS** [comment]
Did he?

**Comment by ShankarBUS** [comment]
Oops sorry I didn't know that 😅

**Comment by Samuel12321** [comment]
I think that was #472

**Comment by Cyberdroid1** [comment]
Confusion affects us all humans. We must fix that by closing this issue as soon as Sam releases new version.

**Comment by fxzxmicah** [comment]
fixed?

**Comment by Samuel12321** [comment]
yes fixed in 0.9.1 which is live on the store and github

**Comment by fxzxmicah** [comment]
![image](https://user-images.githubusercontent.com/48860358/111019185-874c8880-83f8-11eb-9018-c097fe66fd88.png)
Is this caused by the program itself?

**Comment by Cyberdroid1** [comment]
I am guessing the media app. Which media player are you using?

**Comment by fxzxmicah** [comment]
@Cyberdroid1 this: https://www.microsoft.com/store/productId/9WZDNCRFJ1Q1

**Comment by Cyberdroid1** [comment]
Have you tried restarting the media app or ModernFlyouts? Does it still happen?

**Comment by fxzxmicah** [comment]
Tried and Yes.
