### ISSUE TITLE
Bug: Song progress bar not working properly

### ISSUE THREAD

**Issue by dim26** [ModernFlyouts-Community/ModernFlyouts#382]

**Comment by Tropix126** [comment]
This isn't a bug, just a limitation in the system media API.

**Comment by KChunStry** [comment]
Same issue, hope there will be a setting to disable just the bar from the ui completely without have extra unusable space

**Comment by CaidenBlock** [comment]
> 
> 
> Same issue, hope there will be a setting to disable just the bar from the ui completely without have extra unusable space

I mentioned this in #383 with the same thinking.
If i cant use it, id rather it not show it at all for that player, rather than have 1/3 of the flyout be a big greyed out timeline

**Comment by dim26** [comment]
@CaidenBlock that would be nice. However, it does not address the problem that the progress bar is updated for Spotify only when the song is paused or played.

**Comment by Cyberdroid1** [comment]
I will be closing this issue in favor of #392. Please continue in that issue.

**Comment by Cyberdroid1** [comment]
@dim26 
Spotify updates the timeline every 4 seconds or so. Try giving it a look again, or restart both Spotify and ModernFlyouts.
