### ISSUE TITLE
Bug/Feature: Hide timeline if time is null

### ISSUE THREAD

**Issue by CaidenBlock** [ModernFlyouts-Community/ModernFlyouts#383]
**Describe the bug:**
Timeline shows as 0:00 when it cannot pull a value

**To Reproduce:**
Play media in any unsupported app including:
-Dopamine
-Firefox
-Groove Music
-etc

**Screenshots:**
![image](https://user-images.githubusercontent.com/34176510/105626046-1b37a600-5df3-11eb-9cbd-dc3b002f812b.png)

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 9.0 Microsoft Store

**Additional context:**
Might be related to #382 ?

**Comment by CaidenBlock** [comment]
I understand that it's currently working as intended, but it is kinda... _gross_? to have a big greyed out progress bar that takes up an extra 50% of the application's space on the flyout.

**Comment by ShankarBUS** [comment]
Yes, I asked some designers about how to do it. And they told me to go with this design.

It's not a bug. It's a design flaw.

**Comment by CaidenBlock** [comment]
#392 is a better way of describing this.
