### ISSUE TITLE
Feature Request: Add support for webnowplaying, as Youtube music desktop app doesn't work normally.

### ISSUE THREAD

**Issue by Parth-Mawai** [ModernFlyouts-Community/ModernFlyouts#388]
This one : https://ytmdesktop.app/
Not working otherwise.

**Comment by Parth-Mawai** [comment]
it works so great on lockscreen, as anyone would expect, but not in logged in state.

**Comment by Cyberdroid1** [comment]
So, you mean to say that after logging in, on the desktop, the flyout stops appearing?

**Comment by Parth-Mawai** [comment]
> So, you mean to say that after logging in, on the desktop, the flyout stops appearing?
yes
> Are you on Telegram/Discord btw?
on both

**Comment by Cyberdroid1** [comment]
@Parth-Mawai 
I would request you to please join our discord server.
https://discord.gg/KCZrCAXnGV

**Comment by Parth-Mawai** [comment]
@Cyberdroid1 then what?

**Comment by Cyberdroid1** [comment]
@Parth-Mawai 
I tried the app and in settings window, integration tab, i found this hidden gem
![image](https://user-images.githubusercontent.com/51435948/106025316-a1533580-60ee-11eb-9ca7-dbeb051c02fe.png)

Enable these 2 options and restart app. 

BAM! It worked for me properly then.
![image](https://user-images.githubusercontent.com/51435948/106025388-b4660580-60ee-11eb-889f-ba8d01b6293d.png)

**Comment by Cyberdroid1** [comment]
Regarding the seek bar, you might want to open up an issue for the same in the app's repo.
https://github.com/ytmdesktop/ytmdesktop

**Comment by Cyberdroid1** [comment]
@Parth-Mawai 
I will be closing this issue now, since this is an app-side issue.
