### ISSUE TITLE
Bug: Sometimes media controls don't refresh or are disabled

### ISSUE THREAD

**Issue by JosephM101** [ModernFlyouts-Community/ModernFlyouts#390]
I noticed that when there is media playing, pretty often the controls don't refresh with the media host or are disabled. It's frustrating because I like having that level of accessibility, and the most recent update is supposed to put that front-and-center.

Specifically, this happened when I played media through Spotify and Groove. As for Groove, playback positions don't work at all. And if you were doing something like watching a video on YouTube, there is no ability to change positioning. I'd suggest removing the seek bar for applications that don't support it (if that's possible).

**Screenshots:**
![image](https://user-images.githubusercontent.com/28277730/105714093-ebb79500-5ee9-11eb-9610-2a74123f7b24.png)
![image](https://user-images.githubusercontent.com/28277730/105714193-0ab62700-5eea-11eb-8969-7e4b406eaa4c.png)
![image](https://user-images.githubusercontent.com/28277730/105714294-26213200-5eea-11eb-801d-ce78af5798bd.png)

**OS Version:**
Edition	Windows 10 Pro
Version	20H2
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

**ModernFlyouts Version:**
 - v0.9.0

I only noticed the "media controls not working" part happening after updating to v0.9.0. I've tried restarting the applications playing media, ModernFlyouts, and my whole computer. Nothing seems to fix the problem.

**Comment by Cyberdroid1** [comment]
Regarding the problem you face with Spotify, I had also faced it, but restarting the app fixed it.

Regarding the seek bar disabled, I agree with you.

**Comment by Cyberdroid1** [comment]
Regarding the progress bar being disabled, please put up your opinion in #392.

I will be closing this issue now.
