### ISSUE TITLE
Bug: caps lock and num lock aren't showing on flyout in fullscreen apps

### ISSUE THREAD

**Issue by Lukasz-egg** [ModernFlyouts-Community/ModernFlyouts#391]
When you tap caps lock or num lock, even if option to show flyout is on, flyout isn't opening in fullscreen apps.

Windows 10 20H2

Modern Flyouts 0.9.0

**Comment by Cyberdroid1** [comment]
Does caps lock flyout appear normally when not in full screen?

**Comment by Cyberdroid1** [comment]
Have you tried restarting the app/your PC?

**Comment by Lukasz-egg** [comment]
Yes, I tried restarting everything XD, in fullscreen apps only music flyout is working, other are under fullscreen app
