### ISSUE TITLE
Feature Request: Hide Timeline bar when not supported by media app

### ISSUE THREAD

**Issue by PIndividual** [ModernFlyouts-Community/ModernFlyouts#392]
If there is an option that allows the user to hide the progress bar by default in modern flyout, there will be less space consumed, and it will make the whole application looks better

**Comment by Poopooracoocoo** [comment]
I did, by the way, file issues on Chromium's and Firefox's bug trackers:

https://bugs.chromium.org/p/chromium/issues/detail?id=1170662
https://bugzilla.mozilla.org/show_bug.cgi?id=1689538

I don't expect them to go anywhere of course. :(

**Comment by Samuel12321** [comment]
#572

**Comment by ShankarBUS** [comment]
We have resolved this issue. This will be available in the v0.10 release

### 1. Media session in which timeline controls are not supported
![image](https://user-images.githubusercontent.com/63704247/128132299-bc07f995-3e03-4899-99e6-27883fa0e1c2.png)
### 2. Media session which supports timeline controls (collapsed state)
![image](https://user-images.githubusercontent.com/63704247/128132391-ad99c7e1-cd8a-4f0a-90c0-ecd3060b60fc.png)
### 3. Media session which supports timeline controls (expanded state)
![image](https://user-images.githubusercontent.com/63704247/128132393-ced39da0-91c1-43dc-af68-106e53c52199.png)

**Comment by Samuel12321** [comment]
Still not a fan of the fix, I don't think the user should have to click to open timeline. Would prefer previous design that just gets hidden (by shrinking flyout). Perhaps we should revisit this post - islands as I know there are issues with that approach in wpf.

**Comment by ShankarBUS** [comment]
> Still not a fan of the fix

Ye, me too. But I don't have any other ideas.

> I don't think the user should have to click to open timeline. Would prefer previous design that just gets hidden (by shrinking flyout)

Bruh, you know what kind of difficulties we had and still say this?
- The **"Height"** has to be fixed. All the sessions whether the support the feature or not should have the same layout.
- Not all apps support the timeline feature.
- Me so dum

>Perhaps we should revisit this post - islands as I know there are issues with that approach in wpf.

WinUI won't fix this issue. :/

**Comment by ShankarBUS** [comment]
Microsoft didn't even give a shit about the timeline feature. At least we have the option to control it.
I am not saying the design is good. But there are no alternative ways that I could think of. People suggested shrinking the slider's height and sneak it in. But that would be inconsistent with the volume slider.

There are many factors stopping us from doing what you say. This is the only optimal solution that I could come up with.

**Comment by Samuel12321** [comment]
I totally agree that this is the best solution that works, I was just stating that from an idealistic design perspective it's not optimal.
