### ISSUE TITLE
Bug: Default menu shows when I change the volume using a trackpad gesture (precision drivers)

### ISSUE THREAD

**Issue by plt-francesco** [ModernFlyouts-Community/ModernFlyouts#394]
The title pretty much describes itself.
**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 
Windows 10 20H2
**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Duplicate of #4. Please check out that issue.
