### ISSUE TITLE
Feature Request: Multiple Audio/Video Steam in Dropdown in  Media Controls

### ISSUE THREAD

**Issue by kbdharun** [ModernFlyouts-Community/ModernFlyouts#395]
**Is your feature request related to a problem? Please describe:**
Yes, I would request a Feature to show multiple videos or audio streams in Global Media Controls in Dropdown or a Separate Element. Currently, I can only see it by clicking on > this icon, I would prefer it to be Pinned and Present in a Separate Element Box or as a Dropdown option.

**Describe the solution you'd like:**
I would love it if you added multiple elements to the video and audio streams to Global Media Controls as a dropdown or separate elements instead of the current method. it would come in handy when I am watching multiple youtube videos or watching the video and hearing different audio streams/music at the same time.

**Describe alternatives you've considered:**
I think you could add this as a _Customizable extra feature where I can enable this option_ to show multiple streams as a Dropdown or a Separate Element in Settings.
Also, You can support **individual media controls to be pinned and moved free and not along with the Volume Settings**.

**Additional context:**
![ModernFlyouts (Preview) 26-01-2021 10_24_45 AM](https://user-images.githubusercontent.com/26346867/105802262-cba6d500-5fc0-11eb-9eb8-a88eb2af617c.png)
You can add the **Multiple Stream / Media Control Dropdown Enabling Option** in this **Media Settings**.

**Comment by Cyberdroid1** [comment]
@kbdharun 
You can change the media sessions panel orientation to vertical and increase the number which comes below to 3 or so.

Hope it helps.

**Comment by Cyberdroid1** [comment]
For the media sessions to be independent of volume, you can make it so such that on pressing play/pause, previous/next track buttons, only the media flyout appears.

Look for this setting in the General part of Audio tab.

**Comment by Cyberdroid1** [comment]
Closing this issue now. 

If you feel your question is not answered, do let me know 😃

**Comment by kbdharun** [comment]
> Closing this issue now.
> 
> If you feel your question is not answered, do let me know 😃

Can you consider this request to Allow the Independent Moving of Media elements and Not along with Volume Element?

**Comment by Cyberdroid1** [comment]
So you want the media flyout to appear in one location, and volume flyout to appear in other, am I right?

**Comment by kbdharun** [comment]
> So you want the media flyout to appear in one location, and volume flyout to appear in other, am I right?

Yes

**Comment by Cyberdroid1** [comment]
@ShankarBUS 
What's your opinion?

**Comment by ShankarBUS** [comment]
Bruh

**Comment by Cyberdroid1** [comment]
Should it be a PFAFR? 

Honestly, I feel things should be how they are right now.

**Comment by kbdharun** [comment]
> Should it be a PFAFR?
> 
> Honestly, I feel things should be how they are right now.

Agreed, The current Version is Perfect Just Wanted to Suggest an Addon feature, Just a Suggestion for a future version, if possible add an option inside settings that allows me (the user)  to move the media control separately, even if this feature is not implemented I am highly satisfied with your effort into this project, Thank you for taking your time to reply to me.
