### ISSUE TITLE
Feature Request: Option to revert to old flyout

### ISSUE THREAD

**Issue by Tech-How** [ModernFlyouts-Community/ModernFlyouts#397]
**Is your feature request related to a problem? Please describe:**
The new scrubber doesn't work, and it makes a big gap that I don't really like.

**Describe the solution you'd like:**
I loved how the old flyout looked, where there was no scrubber and it didn't split the volume and media into two cards.

**Comment by ShankarBUS** [comment]
Just uninstall ModernFlyouts and restart your computer.

🥲

**Comment by Tech-How** [comment]
@ShankarBUS 
Oh, I see what you mean. I meant I liked how the ModernFlyouts flyout looked before the 9.0.0.0 update.

**Comment by Cyberdroid1** [comment]
We currently have no plans to return to the old design.

Change is good! It's something different. Give it some time, you might start loving it 😄.
