### ISSUE TITLE
Bug: Scrubber is stuck at 0:00

### ISSUE THREAD

**Issue by Tech-How** [ModernFlyouts-Community/ModernFlyouts#398]
<!-- A few rules to keep in mind-
1. Please check if there is already an issue for the bug you are facing.
2. It would be best to create the issue in English language.
3. Properly follow the issue template and do not delete the template.
All good? Continue with your issue :)
--!>

**Describe the bug:**
No matter what type of media is playing, the scrubber is black and stuck at 0:00.

**To Reproduce:**
1. Start playing media.
2. Adjust the volume to trigger the flyout.
3. See the error.

**Screenshots:**
![image](https://user-images.githubusercontent.com/76794507/105884346-e59ee280-5fd5-11eb-9cfc-4ff17c9d0dbe.png)

**OS Version:**
 - Windows 10 Version: 20H2 (OS Build 19042.746)

**ModernFlyouts Version:**
 - Version: 0.9.0.0

**Additional context:**
I have tried multiple apps and websites, and they all have this issue.

**Comment by Tech-How** [comment]
Also, not sure about the formatting issue. You can copy and paste the link for the screenshot.

**Comment by Cyberdroid1** [comment]
I understand your issue.
This is due to the media app not supporting the functionality to change playback position externally.

Everything seems to work as intended.
