### ISSUE TITLE
Bug: Audio flyout is not shown when the volume is changed through means other than media keys

### ISSUE THREAD

**Issue by ShankarBUS** [ModernFlyouts-Community/ModernFlyouts#4]
**Description of the bug :**

The audio part of ModernFlyouts is not shown/triggered when the volume is changed through a **knob/dial** in a **USB speaker** or **headphones (wireless or wired)**, it will only shown the corresponding media keys are pressed. The old flyout is shown in that case.

**Expected Behavior :**
The audio part of ModernFlyouts should be shown when the volume is also changed through means other than media keys

**Additional context**
Source - **reddit** comments : 

1. > "... One odd thing, if I use the volume keys on my keyboard, I get your volume control, but if I use the knob on my USB speaker I get the regular Windows one." - [u/Froggypwns](https://www.reddit.com/user/Froggypwns/) : [source](https://www.reddit.com/r/Windows10/comments/honzd6/app_promotion_a_modern_replacement_for_existing/fxixegs?utm_source=share&utm_medium=web2x)
2. > "Same here with my Surface Headphones dial. The modern flyout shows up with the keys, but not with the dial on my headphones. ..." - [u/RealTeesh2257](https://www.reddit.com/user/RealTeesh2257/) : [source](https://www.reddit.com/r/Windows10/comments/honzd6/app_promotion_a_modern_replacement_for_existing/fxjphyn?utm_source=share&utm_medium=web2x)

**Comment by Dubzer** [comment]
This also happens when change volume with touchpad. Mine supports precision driver, not sure if this a thing for others. 
![image](https://user-images.githubusercontent.com/18244287/88840781-ac7fe400-d1e5-11ea-969e-0c0f4c5b60aa.png)

**Comment by ShankarBUS** [comment]
Hey @Dubzer, I wasn't aware of that. Thanks for reporting this. My laptop can do this too but I never used this will try to figure this out. Hey @ADeltaX FYI.

**Comment by ShankarBUS** [comment]
Hey @Dubzer, can you rebuild and test this app again to see if this issue persist? It should be solved by now due to the contribution from @ADeltaX. Can you please verify it?

**Comment by Dubzer** [comment]
Still shows an old flyout. But if new flyout has been opened by pressing media key, it captures volume changes by touchpad

Here's a video demo: https://lithi.io/file/B9rb.mp4

**Comment by ADeltaX** [comment]
I think DUIHook doesn't get triggered properly, hmmm...

What do you think @ShankarBUS ?

**Comment by ShankarBUS** [comment]
The DUIHook can only notify the native UI's events. It can't detect which UI (i.e. brightness/audio, etc) is shown. Each helper must trigger on their own (with your implementation, the audio & brightness helpers are triggered by shell messages) and the FlyoutHandler will hide the native when the helper need to show UIs. DUIHook has nothing to do with triggering anything. DUIHook can be completely removed if the native UI is permanently hidden on start. It's only a safety measure to fallback to the native UI when the case couldn't be handled by our app (originally created as a fallback for brightness flyout).

My guess is the shell hook messages are not received when the touchpad is used.

Hey @Dubzer, are you 100% you used the latest build, can you recheck it with v0.3.0 release?

**Comment by Dubzer** [comment]
@ShankarBUS I used the latest release release version

**Comment by ADeltaX** [comment]
Ok, I managed to repro with your exact settings. The touchpad doesn't use shellhook.
In fact there is a tiny bug: if you set "play/pause" as touchpad click, it will toggle the play/pause but it will not show the UI at all. So even MS' one isn't reliable lol

I'll see what I can do.

**Comment by ADeltaX** [comment]
Further digging:
Touchpad scrolling (audio) is handled by "TouchpadVolumeGestureHandler" which will show the "HardwareButtonFlyout" directly with no "system" notifications (hint: twinui.dll). Basically it renders "impossible" to hook. For the moment I haven't found anything API/Interface that I can try to "talk" into.

**Comment by oscargb1** [comment]
Also having this issue with a Bluetooth speaker on V0.4.1 (Microsoft Store)

**Comment by ShankarBUS** [comment]
@oscargb1
Sorry for your inconvenience 😅. I will try my best to solve this issue. Be patient until this bug is fixed.

**Comment by Cyberdroid1** [comment]
Any updates to this? @ShankarBUS @ADeltaX

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

The only workaround for this that I can come up for now is to show the audio flyout whenever the native flyout is shown (and not interrupted by other modules).

If I had a wireless/wired headset/headphones/earphones with media or volume buttons, I would've found out the shell messages of those signals and implemented a fix a long time ago. But unfortunately I don't.

Give me some more time 😅. **aΔx**, ya know anythin?

**Comment by Dubzer** [comment]
> If I had a wireless/wired headset/headphones/earphones with media or volume buttons, I would've found out the shell messages of those signals and implemented a fix a long time ago. But unfortunately I don't.

Is there anything we can do to help you with this?

**Comment by ShankarBUS** [comment]
@Dubzer,

> Is there anything we can do to help you with this?

Shit! I just realized how dumb I am 🤦‍♂️. I should've asked you this long ago. I completely forgot there are people out there with those devices 🤦‍♂️.

- Make sure the audio device is connected and working fine
- Download, extract and run the **`ShellHookDBG.exe`** (made by @ADeltaX). [ShellHookDBG.zip](https://github.com/ShankarBUS/ModernFlyouts/files/5654729/ShellHookDBG.zip)
- Play any media using any media player supported by ModernFlyouts (optional).
- Clear all the text in the textbox within the window shown by ShellHookDBG.exe (if there are any).
- Change the volume or media using the audio device.
- Make sure each input on the audio device produces a unique output message (press each button thrice consecutively).
- Report the output to me on here (either copy-paste the log or post a screenshot of the window).

Could you do this 🥺?

**Comment by Dubzer** [comment]
@ShankarBUS I actually don't have any devices with buttons, but I tried [touchpad gestures](https://github.com/ShankarBUS/ModernFlyouts/issues/4#issuecomment-665840978) and it didn't logged anything

**Comment by winston-de** [comment]
@ShankarBUS 
I tried this on my headphone's buttons, and with my touchpad, but nothing was logged. The logger is working though, as it logs properly for the media controls on my keyboard.

If there's anything I can do to help, please let me know.

**Comment by Parth-Mawai** [comment]
testing media buttons first then bluetooth headset buttons

49192 | Res:HOOK_MEDIA_VOLPLUS
49192 | Res:HOOK_MEDIA_VOLMINUS
49192 | Res:HOOK_MEDIA_VOLMUTE
49192 | Res:HOOK_MEDIA_NEXT
49192    | wParam: 6    | lParam: 132222
49192 | Res:HOOK_MEDIA_PLAYPAUSE
49192    | wParam: 6    | lParam: 132222
49192 | Res:HOOK_MEDIA_PREVIOUS
49192    | wParam: 6    | lParam: 132222

now bluetooth buttons(these didn't trigger the modern flyout)
49192    | wParam: 6    | lParam: 132222 (pause)
49192    | wParam: 6    | lParam: 132222 (play)
49192    | wParam: 6    | lParam: 132222 (next) 
49192    | wParam: 6    | lParam: 132222 (previous)

bluetooth volume doesn't log but play/pause/next/previous button log

https://user-images.githubusercontent.com/76217236/102747499-63901e00-4386-11eb-8da4-8ae01c9680ed.mp4

**Comment by ShankarBUS** [comment]
Hmm.

Thank you so much @Parth-Mawai!

**Comment by walter6469** [comment]
Any idea when this will be updated?

**Comment by Parth-Mawai** [comment]
any updates?

**Comment by Cyberdroid1** [comment]
When using hotkeys made by Twinkle Tray app to control brightness, the default flyout appears.

**Comment by ShankarBUS** [comment]
Saus pls. Where Twinkle Tray? Dis is unrelated to this issue. Lemme me open a new one for dis

**Comment by Cyberdroid1** [comment]
https://github.com/xanderfrangos/twinkle-tray
and
https://www.microsoft.com/store/productId/9PLJWWSV01LK

**Comment by Cyberdroid1** [comment]
It is not unrelated. It comes down to using hotkeys.

**Comment by ShankarBUS** [comment]
>It is not unrelated

> to control brightness

What a hypocrite. Look at this issue's title.

**Comment by Cyberdroid1** [comment]
Aaaaaaah! Ok fine.

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

Yo WTF, Twinkle Tray uses a separate window! Not trigger the native one as in #222. They made a window that looks like the native one.

**This is the native one:**

![image](https://user-images.githubusercontent.com/63704247/104130235-96ca3980-5395-11eb-97be-c05377e88127.png)

**This is a custom look-alike from Twinkle Tray:**

![image](https://user-images.githubusercontent.com/63704247/104130265-b9f4e900-5395-11eb-9e3b-f7d8f0adb925.png)

I can't add support for that unfortunately.

**Comment by Cyberdroid1** [comment]
Holy cow!!! That sneaky dev! 😂😂

**Comment by Parth-Mawai** [comment]
> Yo WTF, Twinkle Tray uses a separate window! Not trigger the native one as in #222. They made a window that looks like the native one.

so can we change something in twinkle tray code to trigger your flyout, is that possible?

**Comment by Cyberdroid1** [comment]
I have been using Powertoys KBM for remapping hotkeys for changing volume. Sometimes, the default flyout comes up before it gets hidden by modernflyouts in a second. Any idea?

Did same with play/pause, next/previous track, no fault in that. All normal.

**Comment by sheeepdev** [comment]
Hi! I couldn't find any other solutions, but my volume flyout isn't appearing when changing volume on my headphones, on my previous headphones, the flyout appeared. Now on my new headphones, the flyout doesn't appear, I'm talking about the default windows one. I wanted to try out modernflyouts but if the default windows one doesn't appear the modernflyouts one wouldn't too so if someone could help me make the default one appear so the modernflyouts one can appear

**Comment by ShankarBUS** [comment]
That means your new headphones work differently and doesn't trigger any flyouts (native one and ModernFlyouts).

I'll sure investigate this after v0.9 release 😃

**Comment by rsmyst** [comment]
Seems, it hasn't been fixed yet. I'm using v0.9.0.0 and my touchpad still brings up the legacy layout :(
Hopefully a fix can be found soon. 
Same condition for my BT headphones too. Good luck developers!

**Comment by dreaddr** [comment]
Same condition, using ATK package by Asus for Function key volume control but where as it overrides the ATK package for brightness and other menu items, it seems the volume key one isn't fixed yet. (Fn + F10 = Mute, Fn + F11 = Volume Down, Fn + F12 = Volume Up)

Also yes, good luck to the devs! Let me know if this issue should be reported elsewhere instead too. Truly amazing work.

**Comment by Harfeur** [comment]
> Same condition, using ATK package by Asus for Function key volume control but where as it overrides the ATK package for brightness and other menu items, it seems the volume key one isn't fixed yet. (Fn + F10 = Mute, Fn + F11 = Volume Down, Fn + F12 = Volume Up)
> 
> Also yes, good luck to the devs! Let me know if this issue should be reported elsewhere instead too. Truly amazing work.

I have an Asus but my volume keys on the keyboard works perfectly

**Comment by dreaddr** [comment]
> I have an Asus but my volume keys on the keyboard works perfectly

I'd think it depends on the model or software package used then, do you also use the ATK package or do you have dedicated Volume control keys?

**Comment by Harfeur** [comment]
> > I have an Asus but my volume keys on the keyboard works perfectly
> 
> I'd think it depends on the model or software package used then, do you also use the ATK package or do you have dedicated Volume control keys?

I use the ATK package with Fn volume keys

**Comment by dreaddr** [comment]
> I use the ATK package with Fn volume keys

Strange, I'm running on Windows 20H2 and so far the volume keys don't get detected, but all other settings do. (Brightness, and adjusting volume from other means,)

**Comment by Lyceris-chan** [comment]
I have this issue on the soundcore life q30 as well, thanks for your time and effort into this its amazing btw

**Comment by Sajtospoga01** [comment]
I will not pretend like I know how this program works but isn't implementing an audio level change listener on the core audio device, could bypass the problem?

**Comment by Samuel12321** [comment]
@ShankarBUS @ADeltaX see above

**Comment by ShankarBUS** [comment]
I have considered this previously but dropped the idea. Because,

1. The audio can be changed even without triggering the native flyout.

2. We should not display ours unnecessarily.

I am currently planning to do a different workaround.
That is, show ours whenever,
1. The native flyout is shown and
2. Volume is changed.

But lemme cleanup and refactor the code first.

**Comment by ShankarBUS** [comment]
Could anyone in our team or people in this thread verify if adb52c20ee14fb5f7c84986e7a97cb0d09e53d96 fixes this issue?

**Comment by Samuel12321** [comment]
Will do.

**Comment by Final-Hawk** [comment]
Good to hear it should be fixed!

**Comment by luximus-hunter** [comment]
Wicked! Is there a timeframe for when to expect the update?

**Comment by ShankarBUS** [comment]
Within 2 weeks?

**Comment by Samuel12321** [comment]
A fix for this has been included in 0.9.X - Beta.1

**Comment by Samuel12321** [comment]
While the main issue has been fixed by 0.9.3 there is a small bug #581

**Comment by ChristopheRoyer21** [comment]
Same here, I confirm I'm having this issue in Windows 11
