### ISSUE TITLE
Problems after launching Flyout on a cold boot

### ISSUE THREAD

**Issue by daniel-evans007** [ModernFlyouts-Community/ModernFlyouts#405]
I have Flyout set to launch at startup. Every time after startup, whenever I change the volume or brightness using the media keys, the UI experiences a little hiccup.

Almost every time, it shows the default Windows 10 UI for a split second before switching over to the modern flyout UI.  Also sometimes the brightness bar goes up to a higher value before coming down to the set value, on first launch.

Most of these issues disappear after the first launch of the app, except for the brightness bar showing a higher value than is actually set, which happens occasionally.

**Comment by Cyberdroid1** [comment]
Regarding the first triggering, I feel it is a limitation.

For brightness, I face the same issue with Twinkle Tray app (app to control brightness for multiple monitors), so I feel this is also a limitation.

@ShankarBUS what do you say?

**Comment by ShankarBUS** [comment]
This issue unfortunately is inevitable. I will try my best.
