### ISSUE TITLE
Feature Request: Toast notification support

### ISSUE THREAD

**Issue by UltraTV** [ModernFlyouts-Community/ModernFlyouts#406]
**Is your feature request related to a problem? Please describe: --**

**Describe the solution you'd like: Reskin of windows toast notifications**

**Describe alternatives you've considered: --**

**Additional context: I attached a screenshot, of the original toast notification and an example, how it could look like**

![KEvo5DtpAZ](https://user-images.githubusercontent.com/35925402/106008176-54a03800-60b7-11eb-9a72-3d1e98671e79.png)

![demo](https://user-images.githubusercontent.com/35925402/106008519-aa74e000-60b7-11eb-902d-ab90e97ba288.png)

**Comment by Cyberdroid1** [comment]
Windows is getting a redesigned with Sun Valley update. It is possible that what you are requesting may be served with Sun Valley.

Furthermore, it seems to be out of scope of this app for now. If we plan to reconsider it, we would open this issue again. Thank you.

**Comment by ShankarBUS** [comment]
Actually @ADeltaX is planning a similar feature for DynamicShell.

So, I hope that would fulfill your needs 🙂
