### ISSUE TITLE
Bug: Native flyout is not hidden on lock screen

### ISSUE THREAD

**Issue by Ein-Tim** [ModernFlyouts-Community/ModernFlyouts#408]
**Describe the bug:**
The native Windows 10 flyout is not hidden on the lock screen.

**To Reproduce:**
1. Make sure ModernFlyouts is running and play a song, etc.
2. Lock the machine
3. See the native Windows 10 flyout in the right corner
4. Change the volume or stop the song (my laptop has keys to do so)
5. See that ModernFlyouts shows but the Windows 10 native flyout is also shown

**Screenshots:**
![IMG_0289](https://user-images.githubusercontent.com/67682506/106103281-fddf4080-6140-11eb-9599-1c1c517e83d5.jpeg)

**OS Version:**
 - Windows 10 Version: Windows 10 Version 20H2 (Build 19042.746)

**ModernFlyouts Version:**
 - Version: 0.9.0 from Microsoft Store

**Additional context:**
ModernFlyout is not triggered if the shown control elements (play/skip/etc.) on the native Windows flyout are pressed.

I think this is a limitation from Windows, still I wanted to report this here.

**Comment by Cyberdroid1** [comment]
The windows flyout that you see is an always-show one. It doesn't hide automatically.

Regarding the buttons being clicked doesn't trigger the flyout, I think it is normal behaviour.

**Comment by Ein-Tim** [comment]
Okay, is it planned from your side to hide this flyout? Or is this not possible?
I would love to see this optionally

**Comment by ShankarBUS** [comment]
Unfortunately, it can't be hidden easily.

We could but we don't want to do it specifically.

**Comment by Ein-Tim** [comment]
Okay, thanks @ShankarBUS 

I will still open a Feature Request, maybe others also like the Idea. 

This Issue will be closed.
