### ISSUE TITLE
Bug: Stop banner gets hidden behind the volume flyout.

### ISSUE THREAD

**Issue by daniel-evans007** [ModernFlyouts-Community/ModernFlyouts#411]
**Describe the bug:**
The stop banner on hovering over the stop button in the volume flyout is shown either behind the entire flyout or partially behind the flyout. This varies from time to time.

**To Reproduce:**
1. Open video in a browser.
2. Change volume to bring up the volume flyout
3. Navigate to the stop button, and hover over it for the STOP description to appear.

**Screenshots:**
![image](https://user-images.githubusercontent.com/35403535/106238688-512bbe80-6227-11eb-9c09-a5389fd0de7b.png)

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: [v0.9.0]

**Comment by ShankarBUS** [comment]
That's called a tooltip.

IIRC, there is already an open issue for this.

**Comment by daniel-evans007** [comment]
> That's called a tooltip.
> 
> IIRC, there is already an open issue for this.

Oh, thanks :). Yeah I just noticed. My bad, should I close this issue then?

**Comment by Cyberdroid1** [comment]
Yup, it would be great :)
