### ISSUE TITLE
Bug: No seek bar (greyed out) for Tidal or MusicBee

### ISSUE THREAD

**Issue by brian6932** [ModernFlyouts-Community/ModernFlyouts#413]
**Describe the bug:**

Tidal HiFi/Master uses it's own channel and works a bit different than the High/Normal accounts (more on this here: https://github.com/File-New-Project/EarTrumpet/issues/313). However, this issue happens regardless of Tidal's set quality, the issue persists on Normal, High, HiFi, or Master quality.

With MusicBee I use the Media Control plugin (v1.0.2) that "Enables MusicBee to interact with the Windows 10 Media Control overlay" (specifically the bug fixed version here: https://getmusicbee.com/forum/index.php?topic=21240.msg173334#msg173334). The issue persists regardless of output configuration and file type.

**Screenshots:**
Spotify (works as intended):
![image](https://user-images.githubusercontent.com/18603393/106276474-a3f47e80-6205-11eb-8b31-8e19c97fb005.png)
Tidal:
![image](https://user-images.githubusercontent.com/18603393/106276597-d1412c80-6205-11eb-9b20-94c1700a3aec.png)
MusicBee:
![image](https://user-images.githubusercontent.com/18603393/106277815-ae177c80-6207-11eb-9ecd-e3cb0f298321.png)

**OS Version:**
 - Windows 10 Version: [Windows 10 2004]

**ModernFlyouts Version:**
 - Version: [v0.9.0]

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

Explain it to them.

**Comment by Cyberdroid1** [comment]
@ShankarBUS Right.

@brian6932,
The problem you are seeing is a limitation of the media app you are using. It does not support GSMTC timeline feature. Sadly, ModernFlyouts cannot do anything for this. You have to make a feature request with the app developer to implement this feature.

**Comment by brian6932** [comment]
ah I see

**Comment by Cyberdroid1** [comment]
I will be closing this issue now :) 
If you have any more questions, do join our discord server or our telegram group. 
                                                 (Pssst, link in the readme)

**Comment by Movisivi** [comment]
Hi there, I hope my comment doesn't reopen this issue. I was just curious about something. You say the app needs to support GSMTC timeline feature to fix this bug. Can you recommend any local media players for Windows that DO support this and preferably have dark mode?

**Comment by Cyberdroid1** [comment]
Dopamine - Windows is a good app
https://github.com/digimezzo/dopamine-windows

You can also refer to this document for more info and list of apps that support the timeline feature.
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md

**Comment by Movisivi** [comment]
Dopamine looks good but it doesn't seem to show anything as opposed to Musicbee with its dead seekbar.

**Comment by Movisivi** [comment]
Yeah this shit's just broken. Not working for foobar2000 either.

**Comment by Cyberdroid1** [comment]
> Dopamine looks good but it doesn't seem to show anything as opposed to Musicbee with its dead seekbar.

It works perfectly for me. Can you share an image of the same?

**Comment by Movisivi** [comment]
https://i.imgur.com/JWAYMJe.png

I'm playing something on Dopamine right now. 
It just shows the audio level. Does the same on the Windows 10 flyouts

**Comment by Cyberdroid1** [comment]
I would recommend restarting the PC, since this seems to be a Windows bug.

**Comment by Movisivi** [comment]
I see it now. I had to toggle "Enable system notification" in Settings cause it was disabled https://i.imgur.com/ZNWRPMg.png

**Comment by Cyberdroid1** [comment]
> Its working now, seekbar and all. I had to toggle "Enable system notification" in Settings cause it was disabled

Oh yes, i forgot about that 😂

> Now if only I could get the end timer to show time remaining instead of total track length

Now that seems like a feature request 😄
Do open a new issue for that :)

**Comment by Movisivi** [comment]
Done! https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/679 Thanks for your help.

**Comment by Amara97-sysz** [comment]
Maybe you can try to download Tidal music as a local file, and then upload it to Musicbee for playing. There are many third-party tools that can help you to do so, like Tunelf Tidal Music Converter.

**Comment by brian6932** [comment]
This isn't really a solution, this is just downloading the tracks, the point of a streaming service is to not do that

**Comment by HenryPDT** [comment]
I updated the MusicBee plugin to fully work with ModernFlyouts including Shuffle, Repeat and timeline.

Heres the link: [https://github.com/HenryPDT/mb_MediaControl](url)
