### ISSUE TITLE
Feature Request: Click an empty space to hide the flyout 

### ISSUE THREAD

**Issue by amrbashir** [ModernFlyouts-Community/ModernFlyouts#415]
**Is your feature request related to a problem? Please describe:**
I have my flyout set to appear in the center of the screen, sometimes when I am working or doing something I increase the volume or play the next song which triggers the flyout but I have to wait for the 2000ms duration to end before I can get back to what I am doing which gets kinda annoying sometimes.

**Describe the solution you'd like:**

if you click on an empty space in Windows 10 default flyout, it just hides it instantly which I think ModernFlyouts should implement.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Cyberdroid1** [comment]
Well, you can always click the cross in the top right corner of the flyout. Would it do?

**Comment by amrbashir** [comment]
That would work but I have my FlyouT Topbar visibility set to collapsed (I prefer this mode over the other 2 options) so clicking the cross in the top right corner won't work for me.

**Comment by Samuel12321** [comment]
@amrbashir you can reduce the flyout duration

**Comment by amrbashir** [comment]
I like 2000ms timeout and don't feel like changing it. 

Lowering the timeout is not a good solution imo but feel free to close this issue if it is not a feature you want to add.

**Comment by Samuel12321** [comment]
It’s not a case of not wanting to add it, but we are just (2 - 3) developers who work on this in our limited spare time.
I wont close it at this stage as its not a bad idea, but it is very low priority and probably wont be implemented in the near future.

**Comment by amrbashir** [comment]
Yeah that's understandable. My WPF skills ain't great but I might be able to make a PR if I get a chance.

**Comment by ShankarBUS** [comment]
Thanks for opening the issue and making a PR for that by yourself. You did an awesome job!

We can't thank you enough or ask for your forgiveness for forgetting your PR 😢. Thank you so much ❤️.

This issue has been fixed and will be available in v0.10.
