### ISSUE TITLE
Bug: Timestamps not working 

### ISSUE THREAD

**Issue by khushrxnx** [ModernFlyouts-Community/ModernFlyouts#416]
**Screenshots:**

![Screenshot (1851)](https://user-images.githubusercontent.com/67862114/106360186-8f60d500-6330-11eb-9a3f-c5d9c5948ff4.png)

![Screenshot (1852)](https://user-images.githubusercontent.com/67862114/106360192-925bc580-6330-11eb-8e46-3497bf88f2ca.png)

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: v0.9.0

**Comment by Cyberdroid1** [comment]
Unfortunately, it is the limitation of the app you are using to play media. Nothing that this app can fix.
