### ISSUE TITLE
Instruction on how to localize this application

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [ModernFlyouts-Community/ModernFlyouts#417]
Please provide some instructions or a guide in the Wiki on localizing ModernFlyouts

**Comment by ShankarBUS** [comment]
Bruh, see dev docs 😭.

In the readme, there is a link for contribution guidelines doc. I suggest you to check it out.

**Comment by Jaiganeshkumaran** [comment]
> Bruh, see dev docs 😭.
> 
> In the readme, there is a link for contribution guidelines doc. I suggest you to check it out.

Thanks
