### ISSUE TITLE
Bug: Clamping FN + keys ("sound", "brightness", "CarpsLk") Fluent Flyouts works great. But, with touchpad gestures increasing Fluent Flyouts volume doesn't work.  PS: Sorry, i have bad english!

### ISSUE THREAD

**Issue by Shadyar777** [ModernFlyouts-Community/ModernFlyouts#418]
**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Touchpad gestures are not supported yet. Please have a look at issue #4 for the same.

PS : Just a request, pls fill the issue onwards with the short title and explain issue in detail in description window. It helps us to help you faster and understand better :)
