### ISSUE TITLE
[BUG] When dragging program windows about the default flyout appears

### ISSUE THREAD

**Issue by gab003** [ModernFlyouts-Community/ModernFlyouts#419]

**Comment by Cyberdroid1** [comment]
Can you please detail your issue? I am failing to understand it 😅

**Comment by gab003** [comment]
Yeah no problem, whenever I drag, for instance, say my firefox window across my monitors and also change my volume using Fn + F10 / F11 ModernFlyout will disappear and the default windows 10 volume slider will appear. To re-create this bug just drag any window you have open about your monitor and then change your volume.

**Comment by npprmint** [comment]
That happens to me as well, but when I simply hold _any_ mouse button _anywhere_ and use media control buttons on my keyboard at the same time.

**Comment by Samuel12321** [comment]
@ADeltaX any ideas?

**Comment by Samuel12321** [comment]
Bug report replaced with #535

**Comment by ShankarBUS** [comment]
Will be fixed sooner ;)
