### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by johannes-langer** [ModernFlyouts-Community/ModernFlyouts#420]
**Is your feature request related to a problem? Please describe:**
When I use a Surface Dial for Volume-/Media-Control, it will show the default flyouts instead of the new ones.
**Describe the solution you'd like:**
Show the Modern Flyouts when using a Surface Dial for Volume-/Media-Control

**Comment by Cyberdroid1** [comment]
I think this issue is related to #4.

@johannes-langer Can you check that issue and tell if that issue suffices your needs?

**Comment by Samuel12321** [comment]
closing as a duplicate of #4
