### ISSUE TITLE
Feature Request: Option to create own styling

### ISSUE THREAD

**Issue by mxrixs** [ModernFlyouts-Community/ModernFlyouts#421]
**Is your feature request related to a problem? Please describe:**

> It is not really. I would like to have the option to style the flyouts myself without having to change the code itself because I 1) am not much of a dev and could probably destroy everything and 2) don't even know how to make an executable even If I downloaded the code from here and successfully styled 

**Describe the solution you'd like:**

> A file that overrides current styling, similar to how userChrome is handled in Firefox. Mybe add an toggle to it or just have me integrate some code in the settings app itself.

**Describe alternatives you've considered:**

> I would also be happy with being able to change the colours with just putting in my own hex (or whatever you guys use) colours. a colour picker wouldn't be necessary for me. If you gave me the files to edit and could implement them witha simple switch in the settings I would also be happy to try and provide another theme next to "Dark". "Light" and "High Contrast"

**Additional context:**

> preferably in css as you seem to use another language for styling. If thats not possible I will probably have to learn the basics of that language

**Comment by mxrixs** [comment]
I just realized that this is already a thing, sorry. Will leave up tho to add my personal opinion (which seems to be more detailed than previous issues)

**Comment by Samuel12321** [comment]
Hi @mxrixs, thanks for the feedback, will merge this with #67 to reduce duplicate issues.
See #67 for further updates on this, it probably wont happen any time soon as there are only 2 of us at the moment

**Comment by mxrixs** [comment]
Hey, I'm fine with that! Are there any docs or info what does what? The code does not seem to be commented. Maybe I could find the time to create my own Theme and do a pull requset
