### ISSUE TITLE
Feature Request: Remember Monitor Preference

### ISSUE THREAD

**Issue by arya1106** [ModernFlyouts-Community/ModernFlyouts#423]
**Is your feature request related to a problem? Please describe:**
I frequently connect and disconnect my laptop to an external monitor and the flyout remains on my laptop screen even if the external monitor is selected as the preferred monitor before disconnecting.

**Describe the solution you'd like:**
Remembering the user's preference to show the flyouts on an external monitor across monitor connect/disconnects.

**Describe alternatives you've considered:**
Setting the preferred monitor manually each time I connect/disconnect.

**Additional context:**
None

**Comment by Cyberdroid1** [comment]
We recently added a new Layout tab in the app settings, which includes changing the selected monitor for the flyout.

Does it work?

**Comment by arya1106** [comment]
Yes, I'm able to change the selected monitor, and the flyout appears there, but it does not remember my preference after I connect/disconnect.

**Comment by fihovi** [comment]
Yeah, when monitor is disconnected and then connected.. The preferred choice is main monitor. 
Which means when you update NVIDIA drivers, you'll get flyout on the main monitor. 
Preferred monitor from settings could be in a variable with monitor uuid, then on SystemEvents.DisplaySettingsChanged FlyoutHandler should check if monitor is available, and if so, set flyout's position back to the monitor.

Resolution change does not matter. Only when monitor gets disconnected/reconnected the problem occurs.

**Comment by arya1106** [comment]
> The preferred choice is main monitor.
> NVIDIA drivers
Interesting, I have an intel integrated graphics card and even though my external monitor is set as the main monitor, I get the flyout on my laptop monitor.

**Comment by fihovi** [comment]
> > The preferred choice is main monitor.
> > NVIDIA drivers
> 
> Interesting, I have an intel integrated graphics card and even though my external monitor is set as the main monitor, I get the flyout on my laptop monitor.

That's not what I meant.. When display settings changed, then preferred monitor is Main.
When you install/update NVIDIA drivers, it invokes the SAME problem which is that monitor gets reconnected but flyout seems to not check if the monitor is available.

**Comment by ShankarBUS** [comment]
I forgot this scenario. 🤦‍♂️

I only added code for desktop cases where the secondary monitors are always persistent (not connected/disconnected while the app is running).

I wanted to add dynamic detection and restoring to the monitor.

I forgot to code this part of my plan.

I was in a rush. I couldn't keep up my plans correctly.

Sorry. But this could implemented/fixed easily.

@ADeltaX, mind looking in?

**Comment by arya1106** [comment]
> When you install/update NVIDIA drivers, it invokes the SAME problem which is that monitor gets reconnected but flyout seems to not check if the monitor is available.  

I see, thanks.

> Sorry. But this could implemented/fixed easily.  

No worries, thanks for looking at the issue!

**Comment by coheneli98** [comment]
So, has it been fixed? Has anyone found a way yet?

**Comment by ShankarBUS** [comment]
Not yet. We are lacking free time.

I am a medical student and @ADeltaX is having university exams. So none of us devs are available right now. This may be delayed.

But I know what to do and how to fix this. I just have no time to code.

**Comment by ShankarBUS** [comment]
Oops.... I forgot to tag this issue.

This has been fixed with adb52c20ee14fb5f7c84986e7a97cb0d09e53d96.
