### ISSUE TITLE
Bug: ModernFlyouts randomly just crashes

### ISSUE THREAD

**Issue by KibSquib48** [ModernFlyouts-Community/ModernFlyouts#425]
**Describe the bug:**
ModernFlyouts just crashes randomly sometimes. I'm not sure if anything really causes it, it just sort of happens.

**OS Version:**
 - Windows 10 Version: Windows 10 20H2 19042.782

**ModernFlyouts Version:**
 - Version: v0.9.0

**Additional notes:**
I can't find any option in the settings to find a log file but if there is one that would be useful here, I'll post it

**Comment by Cyberdroid1** [comment]
Does anything log in Reliability monitor? Pls share a screenshot if yes.

**Comment by KibSquib48** [comment]
![image](https://user-images.githubusercontent.com/33189136/106919390-19fe5700-66d8-11eb-9054-3f7973bbb540.png)
here's a screenshot from reliability monitor from a few days ago

**Comment by Cyberdroid1** [comment]
@ADeltaX another bug :(

**Comment by KibSquib48** [comment]
happened again just now, new screenshot
![image](https://user-images.githubusercontent.com/33189136/106930572-b4b06300-66e3-11eb-8b97-396347347618.png)

**Comment by Toxteth** [comment]
same here

**Comment by ADeltaX** [comment]
0xc0000005 is the classic access violation error.... that's interesting.

@Toxteth are you also running on 10.0.19041.782/10.0.19042.782?
Also what antivirus are you using? Does it happen the same if you keep the AV shut down for a period of time?

**Comment by KibSquib48** [comment]
> Also what antivirus are you using? Does it happen the same if you keep the AV shut down for a period of time?
I'm not using any antivirus, except for Windows Defender

**Comment by Toxteth** [comment]
> Also what antivirus are you using?
Window Security

>Does it happen the same if you keep the AV shut down for a period of time?
I rather not do that
________________________________
Van: KibSquib48 <notifications@github.com>
Verzonden: zaterdag 6 februari 2021 00:17
Aan: ModernFlyouts-Community/ModernFlyouts <ModernFlyouts@noreply.github.com>
CC: Toxteth <toxtethogrady@outlook.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ModernFlyouts-Community/ModernFlyouts] Bug: ModernFlyouts randomly just crashes (#425)


Also what antivirus are you using? Does it happen the same if you keep the AV shut down for a period of time?

I'm not using any antivirus, except for Windows Defender

**Comment by therealtisbutascratch** [comment]
This may be due to a recent Windows .NET update.  I'm still on 1909 (18363.1379) and had exactly the same problem, every time I started ModernFlyouts it would crash.

Seems like KB4601556 Update Preview fixes this.

https://support.microsoft.com/en-us/topic/february-16-2021-kb4601556-cumulative-update-preview-for-net-framework-3-5-and-4-8-for-windows-10-version-1909-and-windows-server-version-1909-eae7585b-bef5-0017-d80f-ad9e32cbb40f

Download from the Microsoft Catalog:
https://www.catalog.update.microsoft.com/Search.aspx?q=4601556

I installed this rebooted and ModernFlyouts hasn't crashed since.

HTH

**Comment by KibSquib48** [comment]
> Download from the Microsoft Catalog:
> https://www.catalog.update.microsoft.com/Search.aspx?q=4601556

anything like this but for 20H2?

**Comment by therealtisbutascratch** [comment]
Seems like KB4601554 addresses the same issues in 20H2.

https://www.catalog.update.microsoft.com/Search.aspx?q=KB4601554

**Comment by Cyberdroid1** [comment]
@KibSquib48 does this still happen?

**Comment by KibSquib48** [comment]
I haven't been using modernflyouts lately but the last time I used it (which was in W11 22000.65) it didn't crash as often

**Comment by Cyberdroid1** [comment]
Nice to know. I will close this issue for now then. If you face the crashes again, will reopen it :)
