### ISSUE TITLE
Bug when using flyout.

### ISSUE THREAD

**Issue by danielc0603** [ModernFlyouts-Community/ModernFlyouts#426]
When adjusting value and your media bar is on the bottom it doesn't allow you to click your tab bar apps. Sorry if this is already an issue.

**Comment by danielc0603** [comment]
Sorry, there is no format it didn't give me a format.

**Comment by Cyberdroid1** [comment]
@danielc0603 
![image](https://user-images.githubusercontent.com/51435948/108317774-c6fec680-71e4-11eb-8efa-bb967b0cc0ed.png)

Please use the Bug template :)
