### ISSUE TITLE
Feature Request: Support for the microphone-mute lock key

### ISSUE THREAD

**Issue by Gravifer** [ModernFlyouts-Community/ModernFlyouts#428]
The current flyout for the mute/unmute lock key on my device looks like this:
![unmute](https://user-images.githubusercontent.com/44160838/106982406-0bc73e00-679f-11eb-9fb3-494c2255c5af.png)
![mute](https://user-images.githubusercontent.com/44160838/106982444-18e42d00-679f-11eb-90e7-eb555b377737.png)

I suppose this can be replaced with a modern one; however I do not really know whether this is platform-specific or not.

**Comment by ADeltaX** [comment]
Mute/unmute microphone is OEM specific, so a modern replacement is virtually impossible.

**Comment by Cyberdroid1** [comment]
Closing since not worth to fix this.
