### ISSUE TITLE
Bug: Tray icon shows up again when explorer.exe is restarted, even if it's completely turned off in settings

### ISSUE THREAD

**Issue by win98se** [ModernFlyouts-Community/ModernFlyouts#429]
**Describe the bug:**
Tray icon shows up again when explorer.exe is restarted, even if it's completely turned off in settings.

**To Reproduce:**
1. (Turn off tray icon/ensure that tray icon is turned off) in settings.
2. Restart explorer.exe using any method (e.g. Task Manager).
3. Tray icon shows up again.

**Screenshots:**
None

**OS Version:**
 - Windows 10 Version: 20H2 (OS Build 19042.789)

**ModernFlyouts Version:**
 - Version: 0.9.0.0

**Additional context:**
None

**Comment by Cyberdroid1** [comment]
Thanks! But I would consider it a dupe of #281. Please check out that issue :)
