### ISSUE TITLE
Full translation into Ukrainian :)

### ISSUE THREAD

**Issue by yuragit-web** [ModernFlyouts-Community/ModernFlyouts#430]
What version of ModernFlyouts are you using: 0.9.0.0
[Strings.uk.zip](https://github.com/ModernFlyouts-Community/ModernFlyouts/files/5936610/Strings.uk.zip)

**Comment by Cyberdroid1** [comment]
@Samuel12321

**Comment by Samuel12321** [comment]
hi, please translate the xlf files not the resx files.

**Comment by Samuel12321** [comment]
This should be a PR not an issue
