### ISSUE TITLE
May I sign up the insider program?

### ISSUE THREAD

**Issue by pklion** [ModernFlyouts-Community/ModernFlyouts#438]
I want to join the insider program ([this](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAALdxYU9UQU9GMzQ2Rk40MDJFSkU5UzRKTVg2Nk1PTy4u)), but I couldn't.
Is it in the specifications?

**Comment by ShankarBUS** [comment]
@Samuel12321 have to add you to the internal list manually.
He seems to be busy. So, you may need to wait.

**Comment by Samuel12321** [comment]
Hi, the insider program is currently not functional. When i get time i will modify it to use App centre builds auto generated from azure pipelines dev branch. 
Currently you aren't missing out on anything.

**Comment by pklion** [comment]
Thank you.
