### ISSUE TITLE
Bug: After installation, no flyout bars on screen with BT headset Vol Up/Dwn

### ISSUE THREAD

**Issue by gotterfield** [ModernFlyouts-Community/ModernFlyouts#440]
**Describe the bug:**
Pressing the Up/Down volume buttons on the bluetooth headset,
after the installation of ModernFlyouts, the volume bar doesn't appear,
not the new one neither the old one.

**To Reproduce:**
(The headset is already paired) Connect (turn on) the headset.
Pressing the volume Up or Down nothing appears on the screen.
Closing the application doesn't restore the old fashion vertical/squared bar, it totally disappeared.

Edit: It works (old W8 bar & ModernFlyouts) only touching the keys on the keyboard.
With the buttons on the headset the problem still remains

**OS Version:**
 - Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 0.9.0.0

**Comment by Cyberdroid1** [comment]
Thank you, this is a known issue since some time. Do check out issues #4 for the same :)

**Comment by gotterfield** [comment]
Thanks a lot for the answer!
