### ISSUE TITLE
Bug: Feature box explaining what the shuffle, repeat and stop button is are hidden behind active window

### ISSUE THREAD

**Issue by rsmyst** [ModernFlyouts-Community/ModernFlyouts#442]
<!-- A few rules to keep in mind-
1. Please check if there is already an issue for the bug you are facing.
2. It would be best to create the issue in English language.
3. Properly follow the issue template and do not delete the template.
All good? Continue with your issue :)
--!>

**Describe the bug:**
Idk how to explain it exactly but the text box that appears when you hover over the shuffle, repeat and stop buttons in the extra menu are hidden behind the volume controller. i.e. not visible. See Screen shot for clearer understanding

1. Play some music. (i used spotify)
2. Use the volume controls
3. Click 3-dot menu in the popup
4. Hover over any button there to see issue

**Screenshots:**
![err](https://user-images.githubusercontent.com/30620767/107879589-cadfcf80-6eea-11eb-9b72-2636f021e673.png)

**OS Version:**
Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 0.9.0.0

**Additional context:**
None

**Comment by ShankarBUS** [comment]
It's the tooltip bug again?!

This is a duplicate issue.

**Comment by rsmyst** [comment]
Ah yes, tooltip is what it was called. Does this issue already exist?

**Comment by ShankarBUS** [comment]
Yes. I even included this in "known issues" section of v0.9 release notes.
