### ISSUE TITLE
Bug: Button that looks like a reposition button doesn't do anything

### ISSUE THREAD

**Issue by rsmyst** [ModernFlyouts-Community/ModernFlyouts#444]
**Describe the bug:**
The button that appears next to the settings gear icon in the top bar doesn't seem to be doing anything on my install atleast. see SC for clearer understanding. The button is circled in red.

![Circled in red](https://user-images.githubusercontent.com/30620767/107880351-32981980-6eef-11eb-8a30-2a4c60356c23.png)

Windows 20H2
Flyout version: 0.9.0.0

**Comment by Cyberdroid1** [comment]
That button is meant to reset the flyout position after you have manually moved the flyout. Clicking it without manually moving the flyout does not do anything.
