### ISSUE TITLE
Feature Request: Toggle option for disable animations

### ISSUE THREAD

**Issue by oacoello** [ModernFlyouts-Community/ModernFlyouts#445]
**Is your feature request related to a problem? Please describe:**
Love the fade and swipe animation when i touch a key for voumen and brightness controls. Sometimes when I have open a editing software, the flyout animation is laggy.

**Describe the solution you'd like:**
Add an animation toggle to desactive them like Windows flyout. It does not has an animation. 

**Describe alternatives you've considered:**
Try making better performance. I think is ok, but I'll prefer an option. The animation is nice, but in that case is necessary to stop.

**Additional context:**
![screen-100](https://user-images.githubusercontent.com/72462404/107890756-31132500-6ee0-11eb-8340-dc1e59c36580.jpg)
Design of how "disable animation" option can be in settings.

**Comment by Cyberdroid1** [comment]
@ShankarBUS 
Is this feature possible to code?
