### ISSUE TITLE
Bug: Audio flyout is not shown when the volume is changed through means other than media keys

### ISSUE THREAD

**Issue by Wxhaj** [ModernFlyouts-Community/ModernFlyouts#450]
This bug is very annoying. I use headphones and whenever I volume up from my headphones it volumes up with the default UI. I am requesting everyone on the team to fix this bug, please!

**Comment by Cyberdroid1** [comment]
We are trying our best to resolve this issue quickly. It is on high priority as well. And truth be told, there are just 2 developers and they are maintaining this app in their spare time. So, if anything, chill out and show some love :)

Regarding your issue, please use issue #4, we are tracking this issue there :)
