### ISSUE TITLE
Feature Request: iTunes not showing media info

### ISSUE THREAD

**Issue by danielc0603** [ModernFlyouts-Community/ModernFlyouts#451]
**Is your feature request related to a problem? Please describe:**
The feature I want is the ability to control iTunes music and to show the song that is playing. No, it's not a problem it is just an improvement.

**Describe the solution you'd like:**
The ability to at least see what song is playing.

**Describe alternatives you've considered:**
If it's not possible then either I just ignore it or just start to use Spotify.

**Additional context:**
No additional information.

**Comment by Cyberdroid1** [comment]
I think it is the issue on iTunes' side, not ours. We support only those apps which have ability to share the media info.

Apple is known to create windows apps which are very bare minimum. (And there is a reason for it :P) 

Not a bug on our side :)
