### ISSUE TITLE
Translation: Improve Korean translation from #422

### ISSUE THREAD

**Issue by howon-kim** [ModernFlyouts-Community/ModernFlyouts#453]
Version: 0.9.0

Hi there,
I had spare time to create a Korean translation but realized there's a closed pull request #422 about Korean translation. So, I compared my work with his and tried to choose the best translation possible. Mainly focused on changing leftover English words such as Windows, Microsoft, Lock Key to Korean and trying to explain conceptually translated parts in detail. I am sure that crowd-knowledge can improve the overall quality of the translation of your great works! Anyway, I am waiting for to do pull request after this issue will be seen by assignees. So, please letting me know.

If I have a chance, I would do look into further improvement or bug fixing of your works. Thank you for your great work!

**Comment by Cyberdroid1** [comment]
@Samuel12321

**Comment by Samuel12321** [comment]
Hi, thanks for your help. We would welcome all help with translations, as none of the main devs for this project speak most of the languages supported we are dependant on the community for translation help.

**Comment by mate131909** [comment]
(편의상 한국어로 적겠습니다.)

안녕하세요! #422 PR 작성했던 사람입니다.
혹여나 더 나은 번역을 만드는 데 도움이 될까 싶어, 제가 번역할 때 유의했던 사항들을 적어보고자 합니다.
*어디까지나 제 기준이기 때문에 크게 신경쓰실 필요는 없습니다.

1. 윈도우 내 동일 단어가 존재하는 경우

윈도우용 프로그램인 만큼, 윈도우와 동일한 단어를 사용했습니다.
ex)

- `Windows` -> `Windows`
![image](https://user-images.githubusercontent.com/51040091/108602620-3ee80f00-73e6-11eb-88ea-196f5fae3058.png)
- `Microsoft Store` -> `Microsoft Store`
![image](https://user-images.githubusercontent.com/51040091/108602700-bddd4780-73e6-11eb-9df1-e85463a7ad38.png)
- `Volume` -> `볼륨`
![image](https://user-images.githubusercontent.com/51040091/108602688-af8f2b80-73e6-11eb-8532-c5864cf2ab11.png)

2. 단어 통일

말 그대로 여러 번 쓰이는 단어는 될 수 있으면 통일하였습니다.

---

그리고 번역하신 부분을 한번 살펴보았는데 (https://github.com/howon-kim/ModernFlyouts/commit/4640fe85d6cf08e8e5d75dff26bddf6abca085cd 기준) 일부 개선이 필요한 것 같아 적어봅니다.

1. `Settings.Modules.Audio`
```
        <trans-unit id="Settings.Modules.Audio" translate="yes" xml:space="preserve">
          <source>Audio</source>
          <target state="translated">미디어</target>
        </trans-unit>
```

이 부분은 오타를 놓치신 것 같네요. 의도하신 거라면 모르겠지만, `오디오`가 맞는 것 같습니다.

2. `Enums.TopBarVisibility.Collapsed`
```
        <trans-unit id="Enums.TopBarVisibility.Collapsed" translate="yes" xml:space="preserve">
          <source>Collapsed</source>
          <target state="translated">접음</target>
        </trans-unit>
```

이런 경우에는 `축소`가 더 보편적으로 사용되었습니다.
![image](https://user-images.githubusercontent.com/51040091/108603642-78bc1400-73ec-11eb-8c09-fbd1f957dcba.png)

![image](https://user-images.githubusercontent.com/51040091/108603683-bc168280-73ec-11eb-9a6d-debbb670d5ec.png)

3. `조정`(`음량 조정시 플라이아웃 사용`, `밝기 조정시 플라이아웃 사용`)

[조정과 조절의 차이](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=82361)

의미상 `조절`이 더 적절할 것 같습니다.

4. `~시`

[시 띄어쓰기](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=42724)

이외에도 맞춤법 오류가 꽤 있어서, 번역문을 적용하기 전에 맞춤법 검사기를 한번 돌려주시면 좋을 것 같습니다.


기존의 설명이 부족한 부분에 사용자가 이해하기 쉽도록 보충 설명이 들어간 건 되게 좋네요!
저에게도 마음에 드는 프로그램인 만큼, 개선해 주신 것에 대해 저도 감사의 말씀을 드립니다.
적용된 모습이 기대되네요.

**Comment by howon-kim** [comment]
Hi,

Thanks for your opinion. My thought about translation is to use as many as Korean words possible. You firstly mention that Microsoft left Windows and Microsoft Store in English in their operating system, but since it is a proper noun there's a Korean version too. Like 마이크로소프트, 윈도우즈, 윈도우 is also trademark from Microsoft, so for unified feeling and better appearance purpose, I translated all of the proper nouns to Korean. Again, leftover English words into translation are the least favorite and @Samuel12321 also mentioned somewhere in other translation thread as I remember. Besides, Volume is translated into 볼륨 in Windows 10. However, the thumb of translation is first translated into pure Korean words. Obviously, Volume has the Korean word '음량'. I don't know why Microsoft left volume as it sounded into translation, but in my opinion, to use pure Korean is the top priority, and it's very crucial to use our language.

In terms of collapse, I think it would be better to think about how the program works not just translating as it means. Since the topbar can be expanded and shrink, it would be translated into '접기(folding)' than '축소(minimizing)'. Also, 미디어 part was my intention same reason with collapse. 

AND I take numbers 3 and 4 into the new pull request and thank you for pointing out those grammar mistakes. Since it looks like I got enough opinions, I will create a new pull request, so if you think you disagree somewhere or catch other mistakes, please make another request from your side. I am just afraid I would be too late to respond taking new changes in my hand. 

My last thought is there's many parts to make me think 'how to translate in better way'. Since @Samuel12321 is in charge of multi-language translation, it would be better to leave English comment than Korean, so actually he can also take in part for better translation.

Hope you have a great rest of the day,
Howon

**Comment by howon-kim** [comment]
@Samuel12321 Created pull request.

**Comment by howon-kim** [comment]
#459 Approved. Close this thread.
