### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Zockedidock** [ModernFlyouts-Community/ModernFlyouts#454]
**Describe the bug:**
I'm not sure if this counts as a bug, but ModernFlyouts custom audio controls only appear when you change the Volume with your Keyboard. When I change my volume with my headphones, the default windows audio controls appear instead.

**To Reproduce:**
1. Change the volume with headphones

**OS Version:**
 - Windows 10 Version: 19042.804 / 20H2

**ModernFlyouts Version:**
 - Version: v0.9.0.0

**Additional context:**
 - I'm using Bluetooth headphones, Idk if this makes a difference.

**Comment by Cyberdroid1** [comment]
Hmm, this is an often reported bug #4. Please check that out.

We are actively looking for ways to fix this.

For now, you will have to deal with it 😅

Thanks for reporting!
