### ISSUE TITLE
Feature Request: Transparency with album art

### ISSUE THREAD

**Issue by fillwithjoy1** [ModernFlyouts-Community/ModernFlyouts#455]
What about a slider that allows us to toggle how much transparency we want

PS. https://modernflyouts-community.github.io/

**Comment by fillwithjoy1** [comment]
(low effort post lol)

**Comment by Samuel12321** [comment]
so what's wrong with it?
too transparent not enough, should it be changeable?

please fill out the issue templates correctly otherwise the report is useless.

**Comment by fillwithjoy1** [comment]
how do I mark this as a feature request...

**Comment by Cyberdroid1** [comment]
Please use the proper template :)
