### ISSUE TITLE
Bug: Volume bar does not show when using the 3/4 finger gesture on touchpad to adjust volume on laptop

### ISSUE THREAD

**Issue by TallEwan** [ModernFlyouts-Community/ModernFlyouts#457]
**Describe the bug:**
Volume bar does not show when using the 3/4 finger gesture on touchpad to adjust volume on laptop. Also if you set volume using keyboard button then adjust with touchpad, the volume flyout controls correctly but the timeout doesn't reset on volume change

**To Reproduce:**
1. Go to Windows Settings > Devices > Touchpad > Enable "Change audio and volume" under swipes on either 3 or 4 finger gesture.
2. Scroll up/down with 3/4 fingers, original windows volume box shows instead of modern flyout

**OS Version:**
 - Windows 10 Version: 10.0.18363 Build 18363

**ModernFlyouts Version:**
 - Version: 0.9.0.0

**Comment by Cyberdroid1** [comment]
Thanks for the report. We are already tracking this issue in #4. Please have a look at that issue :)
