### ISSUE TITLE
Feature Request: Please add option for wake at Windows startup

### ISSUE THREAD

**Issue by PrinceMayur007** [ModernFlyouts-Community/ModernFlyouts#458]
**Is your feature request related to a problem? Please describe:**
The App doesn't so time at windows startup to trigger when volume is raised or lowered. Maybe it gets stopped and restarted when we manually trigger.

**Describe the solution you'd like:**
Solution is make it start at Windows startup or like a startup background process. That will resolve the issue.

**Describe alternatives you've considered:**
Its hangs sometimes at startup. When triggered by button.  Love the way it works but it should be initialize at start of Windows.

**Comment by Cyberdroid1** [comment]
This seems to be a bug. This app already supports automatic start on boot. Something seems wrong :/

@ShankarBUS 
This startup delay, is this a design flaw or something else?

**Comment by Hawksprey420** [comment]
This seems to happen on my end too. Modern Flyouts isn't starting up on either cold boot or a restart. I set the Modern Flyouts to start at boot. However, it does not happen. Instead, I have to manually start Modern Flyouts.

I'm on version 9 of this app, Windows 10 20H2.

**Comment by BoolCube** [comment]
> This seems to happen on my end too. Modern Flyouts isn't starting up on either cold boot or a restart. I set the Modern Flyouts to start at boot. However, it does not happen. Instead, I have to manually start Modern Flyouts.
> 
> I'm on version 9 of this app, Windows 10 20H2.
> ![image](https://user-images.githubusercontent.com/75325547/109126413-2bdb9300-7788-11eb-9956-dff0dd88ea06.png)

even i have version 9 of the app, windows 10 insider 21322 and modernflyouts boots whenever windows boots

**Comment by Cyberdroid1** [comment]
@ShankarBUS 
Any idea?

**Comment by Hawksprey420** [comment]
> > This seems to happen on my end too. Modern Flyouts isn't starting up on either cold boot or a restart. I set the Modern Flyouts to start at boot. However, it does not happen. Instead, I have to manually start Modern Flyouts.
> > I'm on version 9 of this app, Windows 10 20H2.
> > ![image](https://user-images.githubusercontent.com/75325547/109126413-2bdb9300-7788-11eb-9956-dff0dd88ea06.png)
> 
> even i have version 9 of the app, windows 10 insider 21322 and modernflyouts boots whenever windows boots

I set it to mine via Task Manager and it doesn't start up at boot. 
Could it be because it needs to be forced on the registry?

**Comment by Cyberdroid1** [comment]
Try a reinstall of the app, I would suggest

**Comment by Samuel12321** [comment]
This isn't a feature request, this is a bug. Modern Flyouts has supported start on boot since 0.4.5 if i recall correctly. 
This is the second bug report we have gotten about this, i suspect it may be related to #384.
Please see this duplicate issue #437  for further updates on this bug.
