### ISSUE TITLE
Feature Request: Realign text block to album art

### ISSUE THREAD

**Issue by lazurit11** [ModernFlyouts-Community/ModernFlyouts#460]
**Is your feature request related to a problem? Please describe:**
Left album art alignment doesn't look appealing, because of weird text placing (Right is just not noticable)
![image](https://user-images.githubusercontent.com/62574650/108625998-fae52080-745e-11eb-963b-a65ce17214d7.png)
![Screenshot 2021-02-21 154751](https://user-images.githubusercontent.com/62574650/108625799-e18fa480-745d-11eb-9c13-6040798e1aab.png)
![Screenshot 2021-02-21 154829](https://user-images.githubusercontent.com/62574650/108625800-e2283b00-745d-11eb-8839-696a4d01953f.png)

**Describe the solution you'd like:**
Move text block sligtly lower, to make alignment even
![Asset 2](https://user-images.githubusercontent.com/62574650/108625871-3e8b5a80-745e-11eb-9e26-f248a6314e99.png)

**Describe alternatives you've considered:**
None

**Additional context:**
None

**Comment by ShankarBUS** [comment]
@ADeltaX, could you include this change in your UX revamp?

**Comment by Cyberdroid1** [comment]
Now that's why I didn't like the left alignment of the album art. Nice catch!

**Comment by ADeltaX** [comment]
There is an ongoing overhaul of the app (UI and UX wise)
Stay tuned :P

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/128132299-bc07f995-3e03-4899-99e6-27883fa0e1c2.png)

They are aligned now!

Will be available in v0.10!
