### ISSUE TITLE
Feature Request:Support Windows touchpad gesture on volume control

### ISSUE THREAD

**Issue by sceraser** [ModernFlyouts-Community/ModernFlyouts#463]
**Is your feature request related to a problem? Please describe:**
 I notice that Windows will still use  default volume bar when I try to use touchpad gesture to control volume. The screenshot are shoing below.
![image](https://user-images.githubusercontent.com/42718757/108698902-99e14980-753f-11eb-90dd-7e76599a19de.png)

**Describe the solution you'd like:**
 The volume bar will change to  ModernFlyouts style when I using touchpad gesture

**Comment by Cyberdroid1** [comment]
Thanks for the report. We are currently trying to tackle this issue in issue #4. Please have a look at that issue :)
