### ISSUE TITLE
Bug: Switching Media from YouTube to Groove Music renders the musical functions(pause,play etc) useless

### ISSUE THREAD

**Issue by EpicAchal** [ModernFlyouts-Community/ModernFlyouts#466]
**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Please share more info and screenshots, otherwise we won't be able to help.

**Comment by Samuel12321** [comment]
Please fill out the issue template correctly, wecant help if we don't have any information.
Closing this due to insufficient information. 
@EpicAchal k. Happy to reopen this if you can provide more information.
