### ISSUE TITLE
Feature Request: Compatibility with trackpad gestures

### ISSUE THREAD

**Issue by Eds1989** [ModernFlyouts-Community/ModernFlyouts#469]
**Is your feature request related to a problem? Please describe:**
When using trackpad gestures (4 fingers swipe up or down), the volume changes but uses the default flyout and not modern flyouts.

**Describe the solution you'd like:**
Would like to have modernflyouts trigger on mouse gestures in addition to keyboard controls.

**Describe alternatives you've considered:**
N/A

**Additional context:**
N/A

**Comment by Cyberdroid1** [comment]
Thanks for the report! This is a current bug for the app since a long time. We are tracking it in issue #4. Please have a look at that issue :)
