### ISSUE TITLE
Bug: Flyouts doesn't appear while holding any mousebutton 

### ISSUE THREAD

**Issue by Darkestjuni** [ModernFlyouts-Community/ModernFlyouts#470]
**Describe the bug:**
When I hold left click pressed and change the volume, the standard Volume Control appears instead of the Flyout.

**To Reproduce:**
1. Hold left click
2. Change the Volume while holding the left click

**OS Version:**
 - Windows 10 Version: Win 10 Pro 20H2 (19042.804)

**ModernFlyouts Version:**
 - Version: v. 0.9.0

**Comment by ShankarBUS** [comment]
I can certify that adb52c20ee14fb5f7c84986e7a97cb0d09e53d96 fixes this issue. 😄
