### ISSUE TITLE
Bug: when slider percentage indicator reaches 100, it will display in 2 rows

### ISSUE THREAD

**Issue by TTTPOB** [ModernFlyouts-Community/ModernFlyouts#471]
![image](https://user-images.githubusercontent.com/19909103/109105289-97ae0380-7768-11eb-959d-67ddf320369f.png)

**To Reproduce:**

adjust brightness/volume to 100%
**Screenshots:**

![image](https://user-images.githubusercontent.com/19909103/109105314-a4325c00-7768-11eb-9814-fc4d2ee532e8.png)

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 
0.9.0.0
**Additional context:**

I used [noMeiryoUI](https://github.com/Tatsu-syo/noMeiryoUI) to change my system default font but this should not affect uwp applications

**Comment by Cyberdroid1** [comment]
> I used noMeiryoUI to change my system default font but this should not affect uwp applications.

Apparently, Modernflyouts is NOT a UWP app.

**Comment by TTTPOB** [comment]
ok my fault then, but if there is a possibility that the app could adjust the layout, it would be great

**Comment by Samuel12321** [comment]
ModernFlyouts is a sort of hybrid, we use desktop bridge.

**Comment by Cyberdroid1** [comment]
This issue seems to be a duplicate of #359. 

Apparently, this issue is very specific to a case, and won't be fixed anytime soon.

I will be closing this issue now.

**Comment by TTTPOB** [comment]
thank you
