### ISSUE TITLE
Metro UI Volume Flyouts sometimes show up before the Modern Flyout does.

### ISSUE THREAD

**Issue by Hawksprey420** [ModernFlyouts-Community/ModernFlyouts#474]
So basically, the stock Metro volume flyout for Windows 10 pops up first when I press the volume macro that I set in AutoHotkey, instead of the Modern Flyouts volume flyout that I use. It seems that there's sometimes a delay or a bug in between the keystrokes (Windows key plus { for volume down, and Windows key plus } for volume up.) and the AutoHotkey, GSMTC reacting to the keystroke and the handoff reaction to Modern Flyouts to show up the Modern Flyouts volume flyout instead of the Metro ones. 

Can you work on this? Cause I'm testing this on VM's too.

I'll provide screenshots for you guys.
(this happened while I was typing this bug report, luckily)

![image](https://user-images.githubusercontent.com/75325547/109143633-37848500-779b-11eb-9627-6ce8249e869c.png)
(this is when I decreased the volume by increments of 2)

![image](https://user-images.githubusercontent.com/75325547/109143708-4b2feb80-779b-11eb-939c-afc8ebae2259.png)
(this appeared when I decreased it again by 2)

Autohotkey script 
[WINDOWS 10 VOLUME KEY REMAP text only for github.txt](https://github.com/ModernFlyouts-Community/ModernFlyouts/files/6042455/WINDOWS.10.VOLUME.KEY.REMAP.text.only.for.github.txt)
(this is in text format)

Modern Flyouts version:
![image](https://user-images.githubusercontent.com/75325547/109144116-be396200-779b-11eb-8425-179836c79166.png)

This is my first "bug" report on this application so bear with me okay? I'll be expecting a reply.

**Comment by Cyberdroid1** [comment]
Welcome to Github 😄!

Regarding your problem, can you please try Microsoft Powertoys and use the feature Keyboard Manager in the app? Do try that app and report if you still face the same problem.

**Comment by Hawksprey420** [comment]
> Welcome to Github 😄!
> 
> Regarding your problem, can you please try Microsoft Powertoys and use the feature Keyboard Manager in the app? Do try that app and report if you still face the same problem.

Okay, I will try MS Powertoys. Will also replicate this issue on my test VM's to see.

**Comment by Hawksprey420** [comment]
> Welcome to Github 😄!
> 
> Regarding your problem, can you please try Microsoft Powertoys and use the feature Keyboard Manager in the app? Do try that app and report if you still face the same problem.

Hey, it works now! But still, I'll be observing the behavior above for a week (maximum) to really see if it improves or not.
By the way, improve your AutoHotkey support. So that people who are using AutoHotkey don't run into the issues I put above.

**Comment by Cyberdroid1** [comment]
Glad it helps :D

Regarding autohotkey support, we have issues #222 and #222 for the same :)

I would be closing this issue now, as it seems to be an autohotkey issue. If you face the problem again, you are free to reopen this issue :)
