### ISSUE TITLE
Bug: Flyouts do not show when using touchpad controls.

### ISSUE THREAD

**Issue by MrConorAE** [ModernFlyouts-Community/ModernFlyouts#480]
**Describe the bug:**
When using touchpad media controls, the flyout does not show but the default W10 one does instead.

**To Reproduce:**
1. Have a prescision touchpad
2. Set a touchpad gesture to media (swipe left/right for track, up/down for volume)
3. Try to change volume with touchpad control

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 20H2 (Oct 20 update)

**ModernFlyouts Version:**
 - Version: 0.9.0.0

**Additional context:**
*none.*

**Comment by Cyberdroid1** [comment]
Hello, we are tracking this very issue in #4. Please have a look at that issue. Thanks for the report!
