### ISSUE TITLE
Bug: Run at Start-Up

### ISSUE THREAD

**Issue by rusti4** [ModernFlyouts-Community/ModernFlyouts#481]
<!-- 🟥🟥🟥 A few rules to keep in mind- 🟥🟥🟥
1. Please check if there is already an issue for the bug you are facing.
2. It would be best to create the issue in English language.
3. Properly follow the issue template and do not delete the template.
🟥🟥🟥 All good? Continue with your issue :) 🟥🟥🟥
--!>

**Describe the bug:**<br>
Program doesn't run at startup, settings show 'syntax error'. Toggle doesn't stay active.<br><br>

**Screenshots:**<br>
![image](https://user-images.githubusercontent.com/24264511/109579878-d15a8200-7b4d-11eb-999b-2c4a838e4121.png)<br><br>

**OS Version:**<br>
Edition	Windows 10 Pro<br>
Version	21H1<br>
Installed on	‎28/‎10/‎2020<br>
OS build	19043.844<br>
Experience	Windows Feature Experience Pack 120.2212.3030.0<br><br>

**ModernFlyouts Version:**<br>
 - Version: 0.9.0.0<br>

**Comment by Cyberdroid1** [comment]
@Samuel12321

**Comment by Samuel12321** [comment]
We seem to be getting lots of reports about this, I don't know why?

@ADeltaX can you take a look at this one.

**Comment by Samuel12321** [comment]
1040256
