### ISSUE TITLE
功能请求：[Feature+Request]CapsLock 开启后,30s后自动切换

### ISSUE THREAD

**Issue by justiony** [ModernFlyouts-Community/ModernFlyouts#484]
Need to add a new feature,

When I work on a document, I switch back and forth between the case buttons,

originally capital letters, after waiting for a while, did not switch to lowercase

Ask your team if they can help me to add a feature

Implementation: When the operation CapsLock is uppercase,

Wait 10s or 30s to change to lowercase automatically, without judging whether the keyboard is working at that time.

Thanks, waiting for your team's reply.

**Comment by justiony** [comment]
需要增加一个新功能。


当我在文档上工作时，我在大小写按钮之间来回切换。


原本是大写的字母，等了一会儿也没换成小写的。


如果你的团队能帮我添加一个功能，请问你的团队。


实施。当操作CapsLock为大写时。


等10s或30s后自动改成小写，不用判断当时键盘是否正常。


谢谢，等待贵团队的回复。

**Comment by Samuel12321** [comment]
Any feature request or bug report not in English will probably be ignored.

**Comment by Samuel12321** [comment]
This is way beyond the scope of ModernFlyouts, we only show an updated notification (or in caps case, we have added a notification) we don't actually change whether the system caps lock is engaged / disengaged.

**Comment by justiony** [comment]
> This is way beyond the scope of ModernFlyouts, we only show an updated notification (or in caps case, we have added a notification) we don't actually change whether the system caps lock is engaged / disengaged.

OK. I understand, given the current features, the team can try

**Comment by lucaspestana** [comment]
你好 @SouloTim! Hope you've been well! In case you're still interested in this…

> Implementation: When the operation CapsLock is uppercase,
> Wait 10s or 30s to change to lowercase automatically, without judging whether the keyboard is working at that time.

There's a third-party tool that serves that purpose already exists: [Caps Unlocker](http://www.itsamples.com/caps-unlocker.html) can turn off Caps Lock automatically after a time interval specified by the user.
Also, @roarrabbit, in case you're interested, there's also (ShiftOff), which automatically turns off Caps Lock when you are pressing Shift + any letter (A to Z) and/or other keys specified by the user -- so you won't find yourself typing with rEVERSE cAPITALIZATION (not quite what you asked for in issue #499, but perhaps you'll find it helpful).
I wrote about these and other similar Lock keys-related tools [here](https://reddit.com/r/Windows10/comments/12gr5a7/how_to_keep_num_lock_always_enabled/jfmtisf/).
