### ISSUE TITLE
Time indicator when playing media is not working

### ISSUE THREAD

**Issue by bluberrypaak** [ModernFlyouts-Community/ModernFlyouts#485]
When i play a media (audio/music/video), the time indicator is not working. I prefer to remove or hide this feature.

![Screenshot 2021-03-05 200952](https://user-images.githubusercontent.com/80107266/110119183-67b0d100-7df6-11eb-965a-0f11a367f702.png)

**Comment by Samuel12321** [comment]
duplicate of #392
