### ISSUE TITLE
Bug: When closing a media, media controls is still showing up

### ISSUE THREAD

**Issue by bluberrypaak** [ModernFlyouts-Community/ModernFlyouts#486]
When closing a media, media controls is still showing up.

**To Reproduce:**
1. Play a media
2. Close the media
3. The media controls is still showing up, below the volume controls

**Screenshots:**

![Screenshot 2021-03-05 200952](https://user-images.githubusercontent.com/80107266/110120752-6d0f1b00-7df8-11eb-9e6c-f2659428c624.png)

**OS Version:**
Windows 10 20H2

**ModernFlyouts Version:**
v.0.9.0

**Comment by Cyberdroid1** [comment]
@ADeltaX @Samuel12321 
Would this be fixed with 0.9.2?

**Comment by ADeltaX** [comment]
I already fixed this with 0.9.1, just waiting to push a (hopefully working) fix for the damned AV blocking our dll before publishing to the store.

**Comment by Cyberdroid1** [comment]
Alright, will then be closing this issue this issue as a duplicate now.
