### ISSUE TITLE
Bug: Volume flyout does not appear, when using touchpad volume control

### ISSUE THREAD

**Issue by Zwatotem** [ModernFlyouts-Community/ModernFlyouts#488]
When using touchpad gestures, you can set up for volume control, default system flyout appears, instead of ModernFlyout.
**To Reproduce:**

1. Open system settings.
2. Go to Devices->Touchpad
3. Look for "Three-finger gestures" section (might not be available on all laptops)
4. Set the "Swipe" setting to "Change audio and volume"
5. Swipe up and down with your touchpad. The native Windows flyout appears.
**Screenshots:**

Not necessery

**OS Version:**
 - Windows 10 Version: Windows 10 20H2, build 19042.804

**ModernFlyouts Version:**
 - Version: v0.9.0 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Thanks for the report. We are tracking this issue in #4. Please refer to that issue :)
