### ISSUE TITLE
功能请求：Incorrect sound source recognition

### ISSUE THREAD

**Issue by IXIPXIXI** [ModernFlyouts-Community/ModernFlyouts#498]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Samuel12321** [comment]
will re open if author provides more info

**Comment by Felix14-v2** [comment]
I noticed the same bug. But it seems that it is Windows 10 problem. Anyway,...

**Bug description**
When there are multiple sound sources from third-party programs ModernFlyouts doesn't display them. Also, an attempt to stop/play/switch media is applied to the wrong window/source.

**To Reproduce:**
Steps to reproduce the behavior:


**OS Version:**


**ModernFlyouts Version:**
 - Version:
