### ISSUE TITLE
Feature Request: "shift" key switch display

### ISSUE THREAD

**Issue by bittrabbit** [ModernFlyouts-Community/ModernFlyouts#499]
Thank you for developing this tool.
During use, I thought it would be useful to add a feature about the "shift" key switch display like "caps" key.

**Comment by fillwithjoy1** [comment]
Honestly, I don't think many people need to always know if they are hitting the shift key, as they'd know. It makes sense for Caps and Num Lock since sometimes you don't realise you hit the button, only to realise while typing. 
@ShankarBUS I guess 'low priority'?

**Comment by Cyberdroid1** [comment]
Thanks for your point, @fillwithjoy1. You are right.

This issue would not be worked on, atleast in the near future. Thanks!
