### ISSUE TITLE
Bug: More Controls button always highlighted (Media Control)

### ISSUE THREAD

**Issue by jeengbe** [ModernFlyouts-Community/ModernFlyouts#500]
**Describe the bug:**
The button for _More Controls_ on the Media Control Flyout looks like it's permanently enabled. I am not sure whether this is intended, but imo its background should rather be transparent (like it is for _Previous_/_Next_), and switch to enabled when the secondary control menu (_Shuffle_, _Repeat_, _Stop_) is opened.

**Screenshots:**
![Screenshot](https://user-images.githubusercontent.com/51749023/110944257-80604000-833c-11eb-84f4-b0d1885715b8.png)

**OS Version:**
Windows 10 Pro 10.0.19042 Build 19042

**ModernFlyouts Version:**
0.9.0.0

**Comment by Cyberdroid1** [comment]
This is intended behaviour. When you click on the More Controls option, it turns into a colored button of your accent color. 
Since the icon for this button are mere dots, removing the background might affect the visibility. 

I hope your doubts are answered :)

**Comment by jeengbe** [comment]
Not sure, whether I'm not understanding you correctly, but I don't see any change in colour upon toggling.
![Image](https://user-images.githubusercontent.com/51749023/111865776-4957e300-8969-11eb-883b-174f45164e9f.png)
![Image](https://user-images.githubusercontent.com/51749023/111865812-75736400-8969-11eb-88db-c217145726b9.png)

The only difference I notice is that the border colour change, although that's very subtle.
> Since the icon for this button are mere dots, removing the background might affect the visibility.

That's a good point :) Unfortunately, I have no clue about how to build and install Windows Apps like these locally, so could you maybe share a picture of how those dots would look without background colour? I really think background colour should be used for active elements.

**Comment by Cyberdroid1** [comment]
![image](https://user-images.githubusercontent.com/51435948/111952366-0e8db080-8b0b-11eb-9e18-c320014264fe.png)


![image](https://user-images.githubusercontent.com/51435948/111952327-fb7ae080-8b0a-11eb-9590-d93f1dddf7d2.png)
