### ISSUE TITLE
The start menu and operation center should be changed to the UI of Sun Valley, a new floating interface!

### ISSUE THREAD

**Issue by TU0YDH** [ModernFlyouts-Community/ModernFlyouts#504]
The start menu and operation center should be changed to the UI of Sun Valley, a new floating interface!Click the link to see the UI I need
 https://img.lancdn.com/landian/2021/02/85227.jpg

https://img.lancdn.com/landian/2021/01/84179-1.jpg
 https://img.lancdn.com/landian/2021/01/83735.jpg

**Comment by Samuel12321** [comment]
Out of scope of the project, ModernFlyouts will not be replacing the start menu.
There have been some ideas about the action centre with firecubestudios, but this is not a priority at the moment.

**Comment by ShankarBUS** [comment]
Microsoft itself is working on the Sun Valley project to do these.

Why should do it again?

**Comment by Samuel12321** [comment]
@ShankarBUS, why did you re open this?
do you have plans for the startmenu?

**Comment by ShankarBUS** [comment]
I didn't reopen it? Maybe FastHub is bugged? You can close it
