### ISSUE TITLE
Additional media sessions can only expand downward

### ISSUE THREAD

**Issue by Sceptrum** [ModernFlyouts-Community/ModernFlyouts#507]
**Describe the bug:**
Additional media sessions can only expand downward, so the flyout isn't really usable when it's positioned at the bottom of the screen. When a second media control appears, the flyout will stretch outside of the screen. It's either the volume bar or the media control, depends on stacking direction. Anchors could be a problem as well.

**Possible solution:** 
An option where user can set expand direction relatively to volume bar or defining the anchor on volume bar, so it couldn't be forced away and new media appears where it has the space to do so.

![3](https://user-images.githubusercontent.com/22861977/111057679-a515fe00-8489-11eb-8428-5c907194029a.png)

**OS version:**
Windows 10 Pro 20H2

**ModernFlyouts version:**
0.9.1.0

**Comment by ShankarBUS** [comment]
Did you try auto placement?

**Comment by Sceptrum** [comment]
I tried in both ways. I'm not sure what auto mode does. I was messing around with it's settings, but I didn't notice changes. 

As long as one media control is present, it's working well. Problems start with the second one, as you can see in the pictures.

In the title, I didn't included a "Bug" or "Enchancement" tag, because I didn't know, which one fits better. The app works well on top, where default is located too, so I'm assuming it's just lower at priority.

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/113599581-750ee480-965c-11eb-9359-421e5c64bb73.png)

Try these configs. I am sure it works quite well.

**Comment by Sceptrum** [comment]
I'd love to say it does, but unfortunately not. I set everything exactly as you suggested, perhaps our configs work differently at this point.

If I reproduce the flyout as you set with two media controls and I close one or both audio source apps, media controls will disappear but volume bar will keep it's position, instead of jumping down close to the tray. I assume, the application is designed to be placed at the top or the suggested settings are not working for me.

I'd prefer descending stacking direction if the flyout at bottom. 
Normally, I would expect a behaviour, where volume bar is constantly at the same pre-defined position - close to the tray - regardless of the number of media controls. If new media control triggered, it should be displayed above the volume bar, or above previous media control, if it wasn't the first one.

**Comment by ShankarBUS** [comment]
It is supposed to work that way and it does work!!!! I can't understand why it doesn't work for you! That's what auto placement does! It will always anchor to the preferred position. Something wrong.

What version are you using?
Can you try resetting the app?

**Comment by Sceptrum** [comment]
Resetting worked! Just like as I wanted. 
Thank you, Sir!

**Comment by ShankarBUS** [comment]
Yaaay! No need to thank me. It is my duty 😉.
