### ISSUE TITLE
Don't work music and volume widget when you use touchpad to adjust the volume.

### ISSUE THREAD

**Issue by BoGodAkim** [ModernFlyouts-Community/ModernFlyouts#525]
Don't work music and volume widget when you use touchpad to adjust the volume.

**Comment by BoGodAkim** [comment]
![image](https://user-images.githubusercontent.com/56846337/112349476-d092b700-8cd9-11eb-9aab-e66332da54d7.png)

**Comment by Samuel12321** [comment]
duplicate of #4
