### ISSUE TITLE
Bug: Default Windows flyouts also shows up

### ISSUE THREAD

**Issue by AmulyaParitosh** [ModernFlyouts-Community/ModernFlyouts#530]
Although I have selected ModernFlyout as the default Flyout, still Windows flyout showsup along with ModernFlyout
![Screenshot (2)](https://user-images.githubusercontent.com/76733670/112757306-db658880-9006-11eb-934c-008d8cc207d2.png)

windows version 20H2 (os build 19042.868)
modernflyout vaersion - 0.9.1.0

**Comment by eProject** [comment]
Hi, you on an Acer laptop? 

That's from Acer (other brands also use to come with this feature - onscreen indicator app) and not from Windows (Win doesn't have any onscreen caps/num/scroll lock indicators... only a tone "ToggleKeys")

You gotta disable and/or uninstall the Acer related app.

**Comment by ramos-lucas** [comment]
I also face this issue. I'm on a desktop

**Comment by Cyberdroid1** [comment]
> I also face this issue. I'm on a desktop

@ramos-lucas 
You need to disable this OEM feature on your PC. Whatever brand your PC is of, you need to remove the related software or look up online for the same. If it is not possible, just disable this feature of ModernFlyouts in settings.

**Comment by ramos-lucas** [comment]
@Cyberdroid1 I'm sorry, let me specify what happened.
I'm using only the media module, and the first interaction in a row opens the default Flyout and after that, the Modern Flyout starts to appear.
I recorded a video to help you understand. I pressed pause followed by play and took a short break before the next interaction.
[https://youtu.be/2i6xa4hnCr4](https://youtu.be/2i6xa4hnCr4)

**Comment by AmulyaParitosh** [comment]
> > I also face this issue. I'm on a desktop
> 
> @ramos-lucas
> You need to disable this OEM feature on your PC. Whatever brand your PC is of, you need to remove the related software or look up online for the same. If it is not possible, just disable this feature of ModernFlyouts in settings.

How to disable OME feature and where to find it?
Yes I use Acer laptop. @eProject

**Comment by eProject** [comment]
> How to disable OME feature and where to find it?


depending laptop model... Quick google search points to "acer launch manager" or "Acer quick access application"
acer (other brands) use to come with a bunch of bloatware pre-installed

**Comment by Cyberdroid1** [comment]
Dupe of #346
