### ISSUE TITLE
Bug:开始菜单里有图标，但是打不开也卸载不掉，完全用不了。请解决。

### ISSUE THREAD

**Issue by Topstones** [ModernFlyouts-Community/ModernFlyouts#531]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Topstones** [comment]
能不能在这里放一个安装包？

**Comment by Samuel12321** [comment]
Please use English or report will be ignored
