### ISSUE TITLE
Bug:i can't use this app normally,and also can't uninstall it.

### ISSUE THREAD

**Issue by Topstones** [ModernFlyouts-Community/ModernFlyouts#533]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Pls fill the whole issue and describe it more. Thanks!

**Comment by Samuel12321** [comment]
Closing due to insufficient information.
Happy to re-open if more info is provided.
