### ISSUE TITLE
Feature Request: When the volume is changed via a windows precision trackpad the new flyout doesn't appear, only the old one. The issue is also present if the volume is changed trough a bluetooth device.

### ISSUE THREAD

**Issue by Sajtospoga01** [ModernFlyouts-Community/ModernFlyouts#539]
**Describe alternatives you've considered:**
I don't know how the original program works but maybe using events for the volume change could eliminate the issue.

**Comment by Cyberdroid1** [comment]
Dupe of #4

**Comment by Samuel12321** [comment]
@Sajtospoga01 If you have any ideas of how to fix this problem they would be greatly appreciated, would you mind discussing it on #4
