### ISSUE TITLE
Bug: Progress par not functioning when playing music with Groove Music.

### ISSUE THREAD

**Issue by nhlap-glitch** [ModernFlyouts-Community/ModernFlyouts#542]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by ShankarBUS** [comment]
Groove Music doesn't support seeking playback position. Sorry for that. We can't do anything about this.
