### ISSUE TITLE
Feature Request: Wireless Projection flyout - similar to apple airplay flyout

### ISSUE THREAD

**Issue by Samuel12321** [ModernFlyouts-Community/ModernFlyouts#543]
Windows doesn't have a good system for wireless projection.

**Comment by ShankarBUS** [comment]
Wut?

**Comment by Samuel12321** [comment]
This was store feedback that i thought was valid. 
Apple has a flyout from the apple menu to manage airplay devices, windows instead hides this in the action center for miracast 
![image](https://user-images.githubusercontent.com/35312698/113978964-bee40e80-9898-11eb-9e8e-dcc68f113939.png)


Lowest possible priority.

**Comment by Samuel12321** [comment]
Will close this for now, as have moved it to "Features to Re-evaluate Post V1.0:"
