### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by sh-al-vi** [ModernFlyouts-Community/ModernFlyouts#544]
**Describe the bug:**
Non-working play/pause if music plays on Spotify. Non-working timeline rewind if music plays on Groove Music. Some problems with overlay. 

**To Reproduce:**
1. Go to Spotify or Groove Music
2. Play any track
3. Click on sound control keys 
3. Look at the ModernFlyouts' Flyout
4. Try to rewind track(If Groove) or play/pause(If Spotify)
5. See control bug
5. For overlay bug hold the cursor on any button on flyout
5. The annotation will be behind the flyout

**Screenshots:**
<img width="960" alt="bug" src="https://user-images.githubusercontent.com/68125523/113710303-345eac00-96ec-11eb-9461-e83e344d96d5.png">
<img width="960" alt="bug1" src="https://user-images.githubusercontent.com/68125523/113710702-b7800200-96ec-11eb-8753-6eee3c15f57c.png">
<img width="960" alt="bug2" src="https://user-images.githubusercontent.com/68125523/113710903-f910ad00-96ec-11eb-983a-1109286317ba.png">

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.9.1.0

**Additional context:**

**Comment by Samuel12321** [comment]
This can come under #392 for the timeline issue
Play pause buttons #532
