### ISSUE TITLE
Bug: When Holding the Scroll In Task manager and changing the volume at the same time, the modern flyout app doesn't work.

### ISSUE THREAD

**Issue by PythonKing920** [ModernFlyouts-Community/ModernFlyouts#550]
- OS: Windows 10 20H2
- App Version: 0.9.1.0
- When Holding the Scroll In Task manager and changing the volume at the same time, the modern flyout app doesn't work.
P.S: I'm on a Laptop.

**Comment by ErenAKGUN2007** [comment]
While holding any mouse button, Modern Flyouts not works. I don't know its reason.

**Comment by ErenAKGUN2007** [comment]
#546, #419

**Comment by ShankarBUS** [comment]
It has fixed and feature will be available to you within next week.
