### ISSUE TITLE
Bug: When clicking on Scroll Bar in Vs moderflyouts stops.

### ISSUE THREAD

**Issue by berryes** [ModernFlyouts-Community/ModernFlyouts#552]
When clicking on the scrollbar in Visual Studio Code modernflyouts disappear for the period of clicking it. Its not a life changing bug but it's interesting. It might just be Vs intervening. (https://drive.google.com/file/d/1AxSXFosU5VZa283SyTKUqbTVk_EQchUU/view?usp=sharing)

**Comment by Samuel12321** [comment]
does 0.9.X-beta.1 fix this?

**Comment by berryes** [comment]
I have the Microsoft Store V0.9.1 version. still visible. i'll download the latest and try it out

**Comment by Cyberdroid1** [comment]
@berryes are you still able to reproduce this bug?

**Comment by Cyberdroid1** [comment]
Closing due to no response
