### ISSUE TITLE
Bug: Caps Lock, Num Lock and other Key Lock dont work when Task Manager is active

### ISSUE THREAD

**Issue by Yash089610** [ModernFlyouts-Community/ModernFlyouts#555]
**Describe the bug:**

When task manager is the active window, the Caps Lock or other key locks don't show flyouts.
**To Reproduce:**

Make any other window active

**OS Version:**
 - Windows 10 Version: 
![image](https://user-images.githubusercontent.com/42301695/114261421-151b9380-99f8-11eb-8049-bb942c90315c.png)

**ModernFlyouts Version:**
 - Version: 
v0.9.1
**Additional context:**

**Comment by ADeltaX** [comment]
This happens with every window launched with admin privileges (like Task Manager).
To read key strokes (like Caps Lock) the flyout must also be launched with admin privileges.... which is overkill.
