### ISSUE TITLE
Richiesta funzionalità: Il modulo a comparsa del volume è funzionante solo con le scorciatoie da tastiera, mentre se utilizzi la rotellina del volume delle cuffie non funziona e quindi sarebbe molto utile inserirlo.

### ISSUE THREAD

**Issue by FastGamerITA** [ModernFlyouts-Community/ModernFlyouts#556]
Translation
Feature Request: The pop-up volume module only works with keyboard shortcuts, while if you use the headphone volume wheel it doesn't work and therefore it would be very useful to insert it

**Comment by Samuel12321** [comment]
Duplicate of #4, please see #4 for follow-up on this issue.

A fix for this has been included in 0.9.X - Beta.1
