### ISSUE TITLE
Is there a way to setup keyboard shortcuts for volume and brightness? 

### ISSUE THREAD

**Issue by Longshoez** [ModernFlyouts-Community/ModernFlyouts#56]
I'm using windows and i just realised there are no default volume/brightness flyouts for desktop, which is weird, i thought it'd be the same as in laptops, but i couldn't find the shortcut to activate them anywhere. so i was wondering if there was a way to set up something like this.

**Comment by ShankarBUS** [comment]
> I'm using windows and i just realised there are no default volume/brightness flyouts for desktop, which is weird

Only laptops have OEM provided keys to trigger them. Desktops won't have them

Planned for v0.10.0. (Hotkey, Jumplist entry and Tray ContextMenu entry to trigger them).

One thing to note is the brightness control uses **WmiMonitorBrightness**, **WmiSetBrightness**, **WmiMonitorBrightnessEvent** which I'm not sure will work for Desktop PCs.

But volume control will sure work 😁.

**Comment by Samuel12321** [comment]
> Only laptops have OEM provided keys to trigger them. Desktops won't have them

Not quite accurate, depends on keyboard manufacturer. Some do, some don't.

**Comment by ShankarBUS** [comment]
*for brightness. I know there are media keys on some keyboard 😁

**Comment by neubland** [comment]
For now you might want to take a look at SharpKeys, Microsoft Powertools or Autohotkey. All these programs should be able to set media shortcuts.

**Comment by Longshoez** [comment]
I found a way of getting the volume up/down flyout to show up, i cant believe i didnt thinked of this before, it is achieved by using the Keyboard Manager in Microsoft's PowerToys app.
![asd](https://user-images.githubusercontent.com/26613957/107836586-4adb2d80-6d63-11eb-9469-2b12caee9ee0.jpg)
the only issue i found on using this is that the Modern Flyout doesnt show up until you press the "volume down" shortcut followed by the "volume up". since for **PC** the brightness cant be controlled by windows (as somebody mentioned) this cant be set-up.
