### ISSUE TITLE
Bug: Function Lock keys: Caps lock not work with installed Logitech Options

### ISSUE THREAD

**Issue by SebaldJ** [ModernFlyouts-Community/ModernFlyouts#566]
**Describe the bug:**
The Lock key "Caps lock" flyout function is not displayed when the [Logitech Options](https://www.logitech.com/en-us/product/options) software is installed. All other lock key flyouts work very well. 👍

**To Reproduce:**

1. Start ModernFlyouts (downloaded at the Microsoft Store, Default Settings)
2. Set Caps lock on and off from the keyboard
3. No Flyout will be shown

**Screenshots:**
Setting in ModernFlyouts:

![image](https://user-images.githubusercontent.com/17111835/114761408-b724de00-9d60-11eb-924c-ea02b4cea293.png)

Settings Logitech Option Software

![image](https://user-images.githubusercontent.com/17111835/114761404-b429ed80-9d60-11eb-956e-ccfc90b1dd1f.png)

**OS Version:**
 - Windows 10 Version: 21H1, Build 10.0.19043.928, German System Language

**ModernFlyouts Version:**
 - Version: v0.9.1.0

**Additional context:**
I had disabled the Show Caps lock notification feature in the Logitech Option Software, v8.36.36.
I use the Logitech [MX Keys Wireless Keyboard](https://www.logitech.com/en-us/products/keyboards/mx-keys-wireless-keyboard.920-009294.html?crid=27), Firmware 012.000.00011.

**Comment by Cyberdroid1** [comment]
If you disable/uninstall the Logitech options app, does the caps lock flyout work then?

**Comment by SebaldJ** [comment]
> If you disable/uninstall the Logitech options app, does the caps lock flyout work then?

After uninstalling and reinstalling Logitech Options, the Caps Lock now works with ModernFlyouts. 😊
