### ISSUE TITLE
Feature Request: Add color Indicator

### ISSUE THREAD

**Issue by kasusa** [ModernFlyouts-Community/ModernFlyouts#570]
**Is your feature request related to a problem? Please describe:**

When I switch the `caps lock`, the Chinese characters are all three-character length, I can't tell whether I am on or off (although there is a small lock identifier on the left)

**Describe the solution you'd like:**
I hope you can add a color indicator like the one in my picture, then the status of the `caps lock` can be shown more clearly, can also make full use of the color display of the monitor.
> (Actually I want to make the effect like a light bulb, but my picture is just to show this idea)

**Additional context:**

![image](https://user-images.githubusercontent.com/49443405/115104294-19145c00-9f8a-11eb-8316-d9e1a1f01727.png)

**Comment by Samuel12321** [comment]
Given there is already a word message and an image/ icon i struggle to see the benefit of another indicator.

**Comment by kasusa** [comment]
It is true that there are already text and icon instructions, but when I use it, Normal situation is press `capsLOCK `many times to determine whether my caps lock is On. 

Relatively speaking,  color can make human reack faster that is why we use color as traffic light but not text. The lock pattern is really not have big different weather is on or not. you can see Rotation lock on alpple they change the lock to red and have a animation makes user get is more visually.

(Or maybe we can make change the color of that lock icon?

**Comment by kasusa** [comment]
![image](https://user-images.githubusercontent.com/49443405/115109797-79b39100-9faa-11eb-826f-899724a861ef.png)
Capslock is more feels like a status of keyboard input but not a LOCK actully , maybe consider using this?

**Comment by Samuel12321** [comment]
Unfortunately considering our very limited resources we wont be able to work on this any time soon.
Additionally i still cant see the benefit, it would complicate things if we ever added theme support, and doesn't really fit into fluent design in my opinion.

Your idea of an animation is an interesting idea and something we will look into if we have time.

> Capslock is more feels like a status of keyboard input but not a LOCK actully , maybe consider using this?

This is an interesting point of debate and i can definitely see why, my concerns would be consistency and clarity with this. Feel free to open a discussion regarding this.

**Comment by Samuel12321** [comment]
Considering our issue backlog at the moment, I will close this for now. We can revisit it in the future.
@ShankarBUS just getting your opinion on this decision.
