### ISSUE TITLE
Bug: Progress bar not working, even after reinstalling

### ISSUE THREAD

**Issue by Vetrix68** [ModernFlyouts-Community/ModernFlyouts#572]
**Describe the bug:**
Progress bar always shows 0:00 ----- 0:00 and nothing fixes it.

**Screenshots:**
![image](https://user-images.githubusercontent.com/75122363/115147695-901a2500-a05c-11eb-9cdc-d57efc0f9edb.png)

**OS Version:**
 - Windows 10 Version: 20H2 19042.870

**ModernFlyouts Version:**
 - Version: v0.9.1

**Comment by Cyberdroid1** [comment]
Which Spotify app are you using?
Edge PWA? MS Store version? Desktop version downloaded from Spotify website?

**Comment by Samuel12321** [comment]
could be solved by #392

**Comment by Poopooracoocoo** [comment]
I often see this with the Spotify app. Sometimes MF will just be completely broken and will need a restart, sometimes it's Spotify.

**Comment by Samuel12321** [comment]
@Poopooracoocoo Which Spotify app are you using?
Edge PWA? MS Store version? Desktop version downloaded from Spotify website?

**Comment by Poopooracoocoo** [comment]
I'm using the desktop version from the Spotify website. I could also reproduce with the MS Store version (they're the same anyway)
