### ISSUE TITLE
Feature Request: Add like song button for Spotify

### ISSUE THREAD

**Issue by Jarda-H** [ModernFlyouts-Community/ModernFlyouts#580]
**Describe the solution you'd like:**
Save to your Liked Songs/Remove from your Liked Songs. Ty

**Comment by ShankarBUS** [comment]
This will require integration with Spotify API which I don't prefer because it is hard to maintain and highly specific for your needs.

I do get it. Android does this perfectly but Windows? meh.

So, I can't guarantee you we will add this feature

**Comment by Cyberdroid1** [comment]
Well, you heard the boss. If we have any plans to implement this, this issue would be reopened. Thanks!
