### ISSUE TITLE
Feature Request: Flyout background same as Windows accent color

### ISSUE THREAD

**Issue by nolemretaWxd** [ModernFlyouts-Community/ModernFlyouts#587]
**Is your feature request related to a problem? Please describe:**
No, it's a customization feature request

**Describe the solution you'd like:**
Ability to make flyout bg same as Windows accent color
![image](https://user-images.githubusercontent.com/31414969/115989486-e3412a00-a5be-11eb-9399-f09c8c399610.png)

**Describe alternatives you've considered:**
ModernFlyouts does only have dark and bright colors for flyouts

**Additional context:**

**Comment by Cyberdroid1** [comment]
We have discussed this in #67. Please have a look at that issue and share your opinions :)
:point_down: 
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/67#issuecomment-700437720
