### ISSUE TITLE
Bug: App doens't work when using BT devices to control audio

### ISSUE THREAD

**Issue by rcondidorio** [ModernFlyouts-Community/ModernFlyouts#588]
Hi! 

I'm using a Sennheiser HD 4.5BTNC headset connected via Bluetooth and when I press the audio controls of this device to change volume and skip/forward music tracks, it activates windows standard constrols instead of ModernFlyouts. 

Is there a way to change this behavior ?

The keyboard shortcuts work normally.

**OS Version:**
I'm Windows 10 version 10.0.19042.928.

**ModernFlyouts Version:**
0.9.3.0

**Comment by Cyberdroid1** [comment]
Hmm, we recently fixed this bug with 0.9.3, strange that you are still facing it. 

Can you please try reinstalling the app?

**Comment by rcondidorio** [comment]
Yep, reinstalling solved the issue. Thanks!
