### ISSUE TITLE
Bug: version 0.9.3 is using much ram and GPU

### ISSUE THREAD

**Issue by PythonKing920** [ModernFlyouts-Community/ModernFlyouts#589]
in version 0.9.3, modern flyout is using ram so much and GPU

**Comment by Cyberdroid1** [comment]
Can you provide us some more info?

- When did this start happening? (Directly after update, or after waking PC from sleep, on startup)

 - Screenshots from Task Manager for ModernFlyouts

**Comment by PythonKing920** [comment]
> Can you provide us some more info?
> 
> * When did this start happening? (Directly after update, or after waking PC from sleep, on startup)
> * Screenshots from Task Manager for ModernFlyouts

it happened after update

**Comment by Cyberdroid1** [comment]
Can you try restarting the computer? If that doesn't fix it, try reinstalling the app.

**Comment by PythonKing920** [comment]
Done, solved thanks!
