### ISSUE TITLE
Bug: Switching off 'Enable Audlo Flyout' causes crash

### ISSUE THREAD

**Issue by Jeric-X** [ModernFlyouts-Community/ModernFlyouts#592]
**Describe the bug:**

Disable Audlo Flyout causes crash. 'Brightness', 'Airplane mode' and 'Lock Keys' do not.

**To Reproduce:**

Just click the switch under Audio label from On to Off. 

**Screenshots:**

![abc20210427_185143](https://user-images.githubusercontent.com/10058586/116230010-ba20c500-a789-11eb-99c8-ac03db04d59a.gif)
the exception is something like 
0x00007FFBE48B90B0 (ntdll.dll): 0xC0000005: Access violation writing location 0x0000000000000038

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

**Comment by alexruimy** [comment]
Also experiencing this bug, and ModernFlyouts doesn't work afterwards until a system restart.
