### ISSUE TITLE
Feature Request: Make "Lock Keys" alert UI smaller

### ISSUE THREAD

**Issue by oacoello** [ModernFlyouts-Community/ModernFlyouts#593]
**Is your feature request related to a problem? Please describe:**
Love that I can see in my screen if I activate a important key, but start to be annoying when I'm writing faster and the big alert for the "Lock keys" distract me from work.

**Describe the solution you'd like:**
Mak an smaller UI for the alert of this, with a toggle or better, by default.

**Describe alternatives you've considered:**
There's a lot of space to reduce in the alert, so I think won't have any problems for scaling without changing the text and icon size.

**Additional context:**
![Presentación1](https://user-images.githubusercontent.com/72462404/116449655-a328b400-a817-11eb-81f7-c54d8210df3b.png)

Concept about the changed UI

**Comment by ShankarBUS** [comment]
We'll consider this 😄
