### ISSUE TITLE
App crashes when trying to turn off audio flyout

### ISSUE THREAD

**Issue by LudanShrestha** [ModernFlyouts-Community/ModernFlyouts#594]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

When I try to turn off the audio flyout the app crashes and also stops to work. You will have to start the app again to run.

**Comment by ADeltaX** [comment]
I'm dumb, that's why it crashes.
(duplicate of: #592)

**Comment by LudanShrestha** [comment]
> I'm dumb, that's why it crashes.
> (duplicate of: #592)

@ADeltaX Is this really how you respond to a bug report?

**Comment by ShankarBUS** [comment]
@LudanShrestha, Y E S.

We are not professionals, you shouldn't expect professionality from us.

We built this app for fun and are still doing it for fun.

**Comment by LudanShrestha** [comment]
@ShankarBUS Didn't really want to offend you. The app overall is amazing tho.

**Comment by ShankarBUS** [comment]
@LudanShrestha,

No no mate, I am not really offended 😄.

We never have been professionals, we are just college students. We have been building this app for fun. That's why we are being playful.

We will change eventually.

**Comment by LudanShrestha** [comment]
@ShankarBUS Lol 🤣🤣Keep making these amazing projects. 😍Cheers mate ✌✌
