### ISSUE TITLE
Bug: AudioControl flyout appears when press win+space

### ISSUE THREAD

**Issue by PhyX-Meow** [ModernFlyouts-Community/ModernFlyouts#597]
**Describe the bug:**

Audio Control flyout appears when I press win+space and want to switch IME.
**To Reproduce:**
Add multiple IMEs to windows, and press win+space.

![屏幕截图(1)](https://user-images.githubusercontent.com/17513581/116693776-f30ea300-a9f0-11eb-87ce-47bf2b97f5b6.png)

**OS Version:**
 - Windows 10 Version: 10.0.21370.1 insider preview

**ModernFlyouts Version:**
 - Version: 0.9.3.0 Latest in microsoft store

**Additional context:**
I believe this issue is related to insider preview build, since no problem occurred in build 21364.
I don't know how to report the issue to microsoft so I come here for help.
Appreciate any help to solve the problem.

Edit: I restarted app and the problem disappeared......Sorry for bothering

**Comment by ilfarpro** [comment]
This is a Bug. I just discovered same issue. 
This happened on fresh installed Windows 10 Home 20H2 19042.928.
If there is any way to send log files, please let me know. I want to help make this awesome application better.
