### ISSUE TITLE
Bug: Spotify media doesn't show in display

### ISSUE THREAD

**Issue by damenangrybird** [ModernFlyouts-Community/ModernFlyouts#599]
**Describe the bug:**
 Just an issue about not showing what the song that's playing in the background.

**To Reproduce:**

**Screenshots:**

 - Windows 10 Version:  Windows 10 21H1 Insider Preview

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Samuel12321** [comment]
Which Spotify app are you using?
Edge PWA? MS Store version? Desktop version downloaded from Spotify website?

A screenshot would be helpful, does the media flyout show anything?

**Comment by Cyberdroid1** [comment]
Closing due to no response from author. Will be reopened once some information is provided.
