### ISSUE TITLE
[Enhancement] The side arrows overlap with the Title and the Thumbnail

### ISSUE THREAD

**Issue by hsusanoo** [ModernFlyouts-Community/ModernFlyouts#60]
I think there should be extra padding space, or some other solution, to solve this this :
<p align="center"><img src="https://user-images.githubusercontent.com/35850056/94373845-06c2f580-0100-11eb-8ae1-6d2111d741d0.png" width="150">
<img src="https://user-images.githubusercontent.com/35850056/94373870-3245e000-0100-11eb-9a85-5c87a9597076.png" width="150"></p>

**Comment by ShankarBUS** [comment]
Yep! That's a great request.

I should reconsider the design and make it better

**Comment by ShankarBUS** [comment]
But they are not disturbing you, right?

I mean they are not that much overlapping with the content.

**Comment by hsusanoo** [comment]
@ShankarBUS No, you can give this the lowest priority. I like the design overall 👍🏻

**Comment by ShankarBUS** [comment]
I had to make the scroll button as small as possible. I had to squash it to the edge. I copied the exact layout and dimensions from the Windows 10X global system media transport controls panel.

I'm currently confused about what to do 😅

**Comment by Cyberdroid1** [comment]
Expand the flyout size maybe? A few pixels won't hurt. But that's just me. 😂

**Comment by ShankarBUS** [comment]
I will reconsider the layout and UI later 😁😉

**Comment by Samuel12321** [comment]
i personally don't think there is a problem, as long as both items are visible. The arrow its self doesn't cover the text or picture, just the highlighting.

**Comment by zeealeid** [comment]
Maybe this problem could be fixed by making the arrows appear only when the curser is hovering over the flyout? Also adding a bit of padding on both sides can fix this issue as well :)

**Comment by ShankarBUS** [comment]
Hmm. Sounds interesting.
Carry on.

Should those buttons be round?

**Comment by zeealeid** [comment]
> Hmm. Sounds interesting.
> Carry on.
> 
> Should those buttons be round?

I like the pill shaped rounded buttons as it looks more in-line with the Windows 10X-ish look also it sort of looks like a clickable button with the background so it might be better but removing it wouldn't make a huge difference in terms of looks IMO.

**Comment by ShankarBUS** [comment]
@zeealeid,

In case you need the current design.

I made this figma project a while ago (haven't been useful since then).

Hope it helps https://www.figma.com/file/Gq5AKs5k8lOl0rmDjQeXT2/ModernFlyouts.

**Comment by ShankarBUS** [comment]
Done. Resolved in v0.10!

![image](https://user-images.githubusercontent.com/63704247/128132299-bc07f995-3e03-4899-99e6-27883fa0e1c2.png)
![image](https://user-images.githubusercontent.com/63704247/128132391-ad99c7e1-cd8a-4f0a-90c0-ecd3060b60fc.png)
![image](https://user-images.githubusercontent.com/63704247/128132478-6ab74bd0-3d2f-4f92-af6c-a505b4d5f1fe.png)
![image](https://user-images.githubusercontent.com/63704247/128132598-3f5160b0-cbda-4245-96a0-51ba675d042c.png)
