### ISSUE TITLE
Bug: App Appears on the Wrong Screen

### ISSUE THREAD

**Issue by MattWasTaken1** [ModernFlyouts-Community/ModernFlyouts#604]
**Describe the bug:**

Flyout appears on secondary monitor despite moving it to primary monitor (2 monitor set up).

**To Reproduce:**

1. Wait for monitors to go to sleep
2. Wake up monitors
3. Use ModernFlyouts
4. See Error

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 
 - Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 
 - v0.9.3.0

**Additional context:**

**Comment by Cyberdroid1** [comment]
So, before sleeping the displays, the flyout stays on screen 1, but after sleep, it starts appearing on screen 2. Am I right?

Can you try having a look at the Layout page in settings for the same?

**Comment by MattWasTaken1** [comment]
> So, before sleeping the displays, the flyout stays on screen 1, but after sleep, it starts appearing on screen 2. Am I right?
> 
> Can you try having a look at the Layout page in settings for the same?

Yes. This is exactly my issue. In the app's settings it labels my second monitor as 1 and my main monitor as 2. In Windows settings, it is the opposite.

**Comment by jiywww** [comment]
> > So, before sleeping the displays, the flyout stays on screen 1, but after sleep, it starts appearing on screen 2. Am I right?
> > Can you try having a look at the Layout page in settings for the same?
> 
> Yes. This is exactly my issue. In the app's settings it labels my second monitor as 1 and my main monitor as 2. In Windows settings, it is the opposite.

I got the same issue. I have 3 monitors set up and selected monitor 2 as my preferred display monitor to show the flyout on. However, it changes to monitor 1 every time when I reboot my pc.

**Comment by Samuel12321** [comment]
Closed in favor of #736

**Comment by Cabus1982** [comment]
It also happens when I connect the external display to my notebook, the program is still displayed on the notebook screen instead of the main or primary Windows screen, in my case the external one.
