### ISSUE TITLE
Bug: The flyout is not disappearing automatically and has to be removed manually everytime it's in use.

### ISSUE THREAD

**Issue by kaustav-gurey** [ModernFlyouts-Community/ModernFlyouts#609]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by ErenAKGUN2007** [comment]
#563

**Comment by Cyberdroid1** [comment]
Thanks @ErenAKGUN2007 !

Duplicate of #563.
