### ISSUE TITLE
Feature Request: Better action center & notification flyouts

### ISSUE THREAD

**Issue by lukemattle** [ModernFlyouts-Community/ModernFlyouts#632]
Are you able to add a better action center? The current one isn't ugly, I would just like it to look more like the Windows 10X screenshots. ![image](https://user-images.githubusercontent.com/84141955/119529633-30f5b180-bd7a-11eb-99dc-9bcfad2051ca.png)
I don't know whether you would have to make a new app or add it to this one but however it works, it would be a lovely feature. By notification flyouts, I mean the little box at the side of your screen that flys out when you get a notification, like this:
![image](https://user-images.githubusercontent.com/84141955/119530511-fb04fd00-bd7a-11eb-881e-42e39e225ffa.png)

As far as I can see, this doesn't exist yet (outside of Windows 10X screenshots).
This is quite a big ask, but it would be an amazing addition to the app!

**Comment by ShankarBUS** [comment]
The thing is, Windows 10 Sun Valley update will make all our efforts worthless. We can't waste our effort and time on something that Microsoft will take care of.

We can't do this unfortunately. Please wait for Windows 10 Sun Valley update.
