### ISSUE TITLE
Volume Flyout appears when I change keyboard language using Win + Spacebar

### ISSUE THREAD

**Issue by tarasburia** [ModernFlyouts-Community/ModernFlyouts#637]
I use three keyboard languages on my PC (English, Russian, and Ukrainian.) Whenever I change the language using the Win + Spacebar shortcut, ModernFlyouts displays the volume flyout.

The problem does not occur with the Shift + Alt shortcut.

**Windows version**: 19043.985
**ModernFlyouts version**: 0.9.3.0

Not sure if that is related, but I am using Logitech MX Keys keyboard with Logitech Options installed.

**Comment by ErenAKGUN2007** [comment]
Duplicate of #584

**Comment by Cyberdroid1** [comment]
Duplicate of #584.
