### ISSUE TITLE
Show message when you turn on / off the Keyboard brightness

### ISSUE THREAD

**Issue by Sav22999** [ModernFlyouts-Community/ModernFlyouts#64]
Show a message also when you turn on or off the Keyboard brightness

**Comment by Samuel12321** [comment]
do you mean keyboard backlight brightness controlled by function keys?

**Comment by Samuel12321** [comment]
if so there are some issues with this #57 due to most keyboards embedding this control in firmware.

**Comment by Sav22999** [comment]
@Samuel12321 Actually many keyboards (also mine) don't use `Fn` button for shortcuts, so you just need to press the relative button, without `Fn`.

But, anyway, if you got some issues, it's not a problem, it was a suggestion to improve this amazing project :smile:

**Comment by Samuel12321** [comment]
always looking for suggestions 😉. 
just out of curiosity, what is the output when pressing that key while on this site [http://keycode.info/](http://keycode.info/) , it is possible if it is software controlled.

**Comment by Sav22999** [comment]
Nothing :confused:, but also Volume, Display Brightness don't return anything...

**Comment by Cyberdroid1** [comment]
But then how is it possible to be controlled in Bootcamp Windows on an Apple computer? There is even a software window popup for that. Maybe exclusive, I don't know.

**Comment by ShankarBUS** [comment]
@Sav22999

> Nothing 😕 , but also Volume, Display Brightness don't return anything...

That's how it works. This is the reason it is non-trivial to detect them. It's not possible for us to do anything regarding this

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

I don't understand. Can you elaborate your statement?

**Comment by Cyberdroid1** [comment]
When we run Windows on an Apple Computer like a Mac, we use a utility called BootCamp. It is like a special control panel that controls various Mac-only features. That software is able to detect Keyboard brightness keys.

**Comment by Cyberdroid1** [comment]
![image](https://user-images.githubusercontent.com/51435948/94594825-98b93280-02a7-11eb-94e5-30ad0318ec5b.png)

We get a UI like this in lower bottom

**Comment by Cyberdroid1** [comment]
@Sav22999 
Assuming you are on a laptop, this setting can be changed by going into the BIOS of your laptop and changing "Action Keys" or something related to Off.

**Comment by ShankarBUS** [comment]
Is BootCamp a VM? Or a boot manager/OS installer for other OSes on Mac?

If it's not a VM how could it show a UI from macOS over Windows?

Does that add some special tools (i.e drivers or softwares) to Windows while installing it?

**Comment by ShankarBUS** [comment]
There are no concept of Brightness/Airplane mode/Fn keys on any OS. They are not passed as keys but as hardware signals (which the OEMs decide). That's the issue here. Any OS can receive those signals if they have the required driver. Even some Linux and Android distros can show brightness and airplane mode popups.

This is the hard part.

**Comment by Sav22999** [comment]
Oh, I've understood. Thanks anyway

**Comment by Cyberdroid1** [comment]
> Is BootCamp a VM? Or a boot manager/OS installer for other OSes on Mac?
> 
> If it's not a VM how could it show a UI from macOS over Windows?

BootCamp is utility software by Apple which allows running Windows on a Mac computer. It adds special software to create a link between both macOS and Windows.

> Does that add some special tools (i.e drivers or softwares) to Windows while installing it?

Yes, it adds some special drivers to Windows

**Comment by ShankarBUS** [comment]
Closing this issue as it's invalid and literally impossible to implement.

**Comment by ShankarBUS** [comment]
@Sav22999,

Does it look like this?
![image](https://user-images.githubusercontent.com/63704247/99710013-09214a80-2ac6-11eb-9dcc-166bab8367c3.png)

If you don't mind could you tell me what laptop you have or post photos of your laptop?

If you really want to see this implemented, I need to check if the message is actually received by Windows.
I need your help 😅😁🙏.

**Comment by Sav22999** [comment]
Similar to it.

![20201119_201049_HDR](https://user-images.githubusercontent.com/32335378/99712826-dd8d6880-2aa3-11eb-99f5-fc7f5c2ad5f2.jpg)

**Comment by ShankarBUS** [comment]
What are the other keys? Could you post a pic of the whole Fn keys? (just for research purposes? 😅)

**Comment by Sav22999** [comment]
Sure 
![20201119_203704_HDR](https://user-images.githubusercontent.com/32335378/99718389-13821b00-2aab-11eb-84d7-f1ae6438a58c.jpg)

**Comment by Riajyuu** [comment]
Just a question from curiosity: for mots plug-to-use keyboard, brightness adjustment command won't be responded on OS level but on keyboard firmware. How can that be supported then?

**Comment by Samuel12321** [comment]
keyboards don't often actually send windows the FN key pressed command

**Comment by Samuel12321** [comment]
Closing as to my knowledge it isnt possible.
If someone finds a solution to this, we would welcome its addition.
