### ISSUE TITLE
Bug: when changing keyboard language in v0.9.3, using the win+space the flyout appears and it's annoying sometime.

### ISSUE THREAD

**Issue by AbedYamout** [ModernFlyouts-Community/ModernFlyouts#643]
when changing keyboard language in v0.9.3, using the win+space the flyout appears and it's annoying sometime, also when playing music in spotify the controls from the flyout doesn't work.

- ModernFlyout version 0.9.3

**Comment by ErenAKGUN2007** [comment]
Duplicate of #584
