### ISSUE TITLE
Feature Request: Include Discord Sounds / Bots and VC's

### ISSUE THREAD

**Issue by LiamAmsdorf** [ModernFlyouts-Community/ModernFlyouts#651]
Hi i was jsut wondering if you could please include this for discord bots and for VC's 
you could also include this for youtube vids playing inside the application

**Comment by Cyberdroid1** [comment]
This feature is totally dependent on how Discord manages it. Nothing that this app can do. 

If Windows sees it as a media session, the app will show the media flyout. Otherwise, nothing can be done. Hope you understand :)

Closing this issue now.
