### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by JustAvocado** [ModernFlyouts-Community/ModernFlyouts#656]
**Describe the bug:**
Netflix doesn't show up in the audio flyout compared to YouTube (Shown in image below)

**To Reproduce:**
1. Open Netflix Windows 10
2. Pick a show
3. Increase volume

**Screenshots:**
![image](https://user-images.githubusercontent.com/37244367/121504096-54b62a00-c9ff-11eb-885c-be49c8f926b1.png)
![image](https://user-images.githubusercontent.com/37244367/121504850-f3428b00-c9ff-11eb-92e2-1da97e94d083.png)

**OS Version:**
 - Windows 10 Version: Windows 10 21H1

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Comment by Cyberdroid1** [comment]
Try this : After opening Netflix app, exit ModernFlyouts and then start it again.

**Comment by JustAvocado** [comment]
> Try this : After opening Netflix app, exit ModernFlyouts and then start it again.

I tried, it doesn't work for netflix but works for chrome and spotify...

**Comment by lazurit11** [comment]
Does Netflix appear in native Windows pop-up?

**Comment by BasicallyWiz** [comment]
It may just be possible that Netflix doesn't allow the use of Windows media controls. I'd suggest doing what lazurit11 suggested, and check if the default media controls even displays Netflix' controls.

**Comment by Cyberdroid1** [comment]
@JustAvocado Do the default windows flyouts show media info for Netflix? If they don't, then it is a limitation of the Netflix app.

**Comment by Cyberdroid1** [comment]
Closing this issue due to no response.
