### ISSUE TITLE
Bug: Timeout period expired error

### ISSUE THREAD

**Issue by jxpsert** [ModernFlyouts-Community/ModernFlyouts#658]
**Describe the bug:**

ModernFlyouts does not start, and instead displays an error message reading:
"This operation returned because the timeout period expired."

**To Reproduce:**
1. Open ModernFlyouts
2. Wait a few minutes, nothing happens
3. See error

**Screenshots:**

![image](https://user-images.githubusercontent.com/65042215/121770293-d1b0e300-cb68-11eb-94f6-3008c04e7f6a.png)

**OS Version:**
 - Windows 10 Version: Windows 10 Pro N, Build 19042

**ModernFlyouts Version:**
 - Version: v0.9.3

**Comment by jxpsert** [comment]
Any ideas on what could be causing this? Haven't seen any other issues about this.

**Comment by jxpsert** [comment]
Don't have this issue with my new pc, however still interested about this. Has anyone found any cause for this?

**Comment by Cyberdroid1** [comment]
It could have been a windows issue

**Comment by Cyberdroid1** [comment]
I will close this issue for now, will reopen if needed.
