### ISSUE TITLE
Bug: trackpad four finger slide cause the old flyouts

### ISSUE THREAD

**Issue by a-little-cat** [ModernFlyouts-Community/ModernFlyouts#662]
**Describe the bug:**

Use four finger slide in the trackpad, the old flyouts appears.
**To Reproduce:**

1. Go to windows seeting
2. Devices
3. Touchpad
4. Advanced gesture configuration
5. Configure your four finger gestures
6. Set the Up&Down as Volume up and Volume down
7. Slide at the trackpad with four finger.

**Screenshots:**

![image](https://user-images.githubusercontent.com/20008161/121808020-4a0ec580-cc89-11eb-9cfb-9a363485d3aa.png)
![image](https://user-images.githubusercontent.com/20008161/121808043-5e52c280-cc89-11eb-9317-cf836f771859.png)
![image](https://user-images.githubusercontent.com/20008161/121808046-66aafd80-cc89-11eb-9b5a-9ec056a7c801.png)

**OS Version:**
 - Windows 10 Version:  Windows 10.0.19042

**ModernFlyouts Version:**
 - Version: v0.9.1

**Additional context:**

Thanks for your works, I really love it.

**Comment by sky130** [comment]
Now it works on the touchpad on Windows11

**Comment by Samuel12321** [comment]
This was fixed by the 0.9.3 update

**Comment by a-little-cat** [comment]
thanks!
