### ISSUE TITLE
Bug: Volume flyout changes default to second monitor after screen turns off

### ISSUE THREAD

**Issue by frankiejr** [ModernFlyouts-Community/ModernFlyouts#663]
**Describe the bug:**
While using a television as a second monitor, the volume flyout switches its default location to that monitor after the screen turns off (my current setting is to turn the screen off after 10 minutes).

**To Reproduce:**

1. Let screen go black or lock machine
2. Wake screen or log in
3. Change volume

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**
My assumption is that this is because a TV is always recognized as "on" even if its power is turned off.

**Comment by ShankarBUS** [comment]
To which monitor? Can you please elaborate a bit more?

**Comment by frankiejr** [comment]
Main monitor: 5120x1440
Secondary monitor: 1920x1080 (TV)

When the screen wakes from "black" mode (not computer sleep, just screen sleep), the volume flyout location changes its default location to the Secondary monitor (TV). This causes me to have to go into the settings and switch back to the main monitor at least once per day.

My desktop is still extending to the TV even if it's powered off, so my assumption is that TVs are "always on." (I've never seen this happen with an actual computer monitor, but maybe it could be something related to HDMI?) Not sure if this has anything to do with my issue, but it is a quirk with my system so I figured it was worth mentioning.

**Comment by ShankarBUS** [comment]
It could be. I will investigate this furthermore

**Comment by LolicoreExpress** [comment]
Same here, but I don't think it's about your screens being TVs or monitors.
I've got two PC monitors, and any program that is opened on my main monitor, will automatically go to my secondary monitor if I turn off my main one. Including the Modern Flyout.
The programs will automatically get back to my main monitor when I turn it back on. 
But only ModernFlyout doesn't and stays on the second one.

**Comment by frankiejr** [comment]
No, that's the point... I'm not turning off my screens, they're just sleeping (not computer sleep, just screen going black). The monitor correctly reports as "off" so it's getting no signal, but the TV, while appearing off, is still reporting as "on." Because of this, MF defaults to the second monitor (TV) and does not reset to its default setting when my main monitor wakes.

**Comment by LolicoreExpress** [comment]
Oh ok

**Comment by Samuel12321** [comment]
Closed in favor of #736
