### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Wehttam140** [ModernFlyouts-Community/ModernFlyouts#668]
![modernlayout jpg](https://user-images.githubusercontent.com/85983458/122167110-1d50de80-ce40-11eb-9c84-b856f0a470c1.png)

**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

It got stuck like the screenshot shows. I play songs on spotify and doesnt show the spotify section and stuff.  Pd: I was listening to music on Spotify while taking the Ss .

**Comment by Samuel12321** [comment]
#392
