### ISSUE TITLE
The seekbar is not dynamic i.e. the seek bar does not move with time.

### ISSUE THREAD

**Issue by salim0786** [ModernFlyouts-Community/ModernFlyouts#670]
Description: The seek bar is not dynamic i.e. the seek bar does not move with time. It shows the plat time of a song for one second and then stops.

To Reproduce:
Just open and play a song in Spotify

Screenshots: NA

OS Version: Windows 10 Version: 20H2

ModernFlyouts Version: Version: 0.9.3.0

**Comment by lazurit11** [comment]
It refreshes every 5 seconds
(still not enough imo)

**Comment by Cyberdroid1** [comment]
This is due to Spotify player updating media information every 5 seconds. Even Microsoft's official guidelines says to update media information every 5 seconds. 
I know it is annoying, but nothing can be done about it (except giving feedback via Feedback Hub).

Closing this issue.
