### ISSUE TITLE
Enhancement: System Tray icon tooltip says "Tooltip"

### ISSUE THREAD

**Issue by Rogue-M** [ModernFlyouts-Community/ModernFlyouts#671]
![image](https://user-images.githubusercontent.com/44031016/122639192-267acd80-d116-11eb-966f-8d6989f24661.png)

**Comment by DaLumma** [comment]
strange says ModernFlyouts to me
![image](https://user-images.githubusercontent.com/51972073/122641191-f9bdba80-d103-11eb-9d30-99f060f40a1e.png)

**Comment by SaifAqqad** [comment]
@Rogue-M Are you on the windows 11 leaked build?

**Comment by Cyberdroid1** [comment]
> ![image](https://user-images.githubusercontent.com/44031016/122639192-267acd80-d116-11eb-966f-8d6989f24661.png)

Haha, that's a bug on the leaked Windows 11 build. I noticed it too.

**Comment by Cyberdroid1** [comment]
Currently, I am not going to keep this issue open, since it's an incomplete build.

If it still happens on the official builds of Windows 11, this issue will be reopened.

For now, I am going to close this issue.
