### ISSUE TITLE
Feature Request: Dynamic Monitor Choosing

### ISSUE THREAD

**Issue by AverageDood** [ModernFlyouts-Community/ModernFlyouts#672]
**Is your feature request related to a problem? Please describe:**
Currently, if you have a setup with two or more monitors on your computer, the program forces you to select a fixed monitor to show the flyouts. This is a bit unintuitive, as when you have multiple monitors, it'll be most likely that you're watching the one that has either window or cursor focus.

**Describe the solution you'd like:**
To have the flyout appear dynamically on the monitor that has focus, preferably according to the currently active window.

**Describe alternatives you've considered:**
None.

**Comment by Samuel12321** [comment]
Closed in favor of #736
