### ISSUE TITLE
Modern Flyouts not working for windows 11

### ISSUE THREAD

**Issue by osjohn01** [ModernFlyouts-Community/ModernFlyouts#685]
Though windows 11 and 10 share the same kernel, Modern flyouts doesnt run on Windows 11. Pls do something ASAP. This APp is the best out there!

**Comment by osjohn01** [comment]
My bad, flyouts does run on windows 11, it just didnt run at startup for me, so i thought it didnt work sorry

**Comment by Samuel12321** [comment]
Just to clarify, is run at start up broken or was it just not enabled?

**Comment by ShankarBUS** [comment]
It might not work for much longer. MS will sure break or change the APIs we depend (like they did a lot of times in the past).

Unless we manually alter the code to work on both 10 and 11, we won't assure you the stability.

For that we need to install and play with Windows 11. Unfortunately, it might take time for us to do so or might not happen.

**Comment by ShankarBUS** [comment]
TBH, even maintaining the app fpr Windows 10 is painful. Windows 11 support might not arrive to ModernFlyouts.

Given that, Microsoft is finally willing to refresh all parts of Windows, they will sure update the default metro flyouts in the future.

It all depends on the user demand. Most of users won't use ModernFlyouts once MS updates the deafult one. So, that's that.

It's upto the users.

**Comment by osjohn01** [comment]
> Just to clarify, is run at start up broken or was it just not enabled?

its set to run at startup, but for some reason, after updating to win 11, it dindt run at startup. even i did a manual restart later, still it didnt run

**Comment by osjohn01** [comment]
> TBH, even maintaining the app fpr Windows 10 is painful. Windows 11 support might not arrive to ModernFlyouts.
> 
> Given that, Microsoft is finally willing to refresh all parts of Windows, they will sure update the default metro flyouts in the future.
> 
> It all depends on the user demand. Most of users won't use ModernFlyouts once MS updates the deafult one. So, that's that.
> 
> It's upto the users.

its working now, workd perfectly on windows 11 now

**Comment by osjohn01** [comment]
anyways, keep up the effore on this
