### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by SoberPanda** [ModernFlyouts-Community/ModernFlyouts#689]
It doesn't work at all, the hot keys make it pop up, but nothing else. The media controls are never there. I've also tried re installing it.

**Comment by JohnLGalt** [comment]
Interesting.  I'm using it on Windows 11 and have no issues.  

OS?  AV program?  Any other desktop modification apps that you might have running?

**Comment by Cyberdroid1** [comment]
@SoberPanda please answer these questions-
- What device are you using? 
- Which flyouts are working, which are not working? 
- How are you triggering the flyouts?
- Do the windows default flyouts show media control?

**Comment by Samuel12321** [comment]
closing due to no response, will reopen if needed
