### ISSUE TITLE
Bug: Disable Audio Flyout force closes the app

### ISSUE THREAD

**Issue by namitgpta** [ModernFlyouts-Community/ModernFlyouts#694]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

https://user-images.githubusercontent.com/60420298/125156691-6caad600-e184-11eb-901e-393e14d5a23a.mp4

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Duplicate of #592.
