### ISSUE TITLE
Feature Request: Full Foobar2000 Support

### ISSUE THREAD

**Issue by Dogs777** [ModernFlyouts-Community/ModernFlyouts#698]
**Is your feature request related to a problem? Please describe:**
In my experience of using Foobar2000 with this program, I have come to realize that it only is partially supported. When I pull up the menu by changing my volume, I notice that the time seek bar, shuffle, and repeat options all do not work though the play/pause buttons, next/previous song buttons, song name/artist, and album art all work.

**Describe the solution you'd like:**
I would like to see Foobar2000 fully supported by this program so that the time seek bar, shuffle, and repeat options all work.

**Describe alternatives you've considered:**
I don't really know if there are any alternatives though if it's a software/API/etc. limitation causing this issue I'd assume it could be fixed by with a Foobar2000 plugin that's designed to add support between the two programs.

**Additional context:**
![gm0T7EVp5G](https://user-images.githubusercontent.com/10644674/125357733-89e3ce00-e357-11eb-83ec-013841f59008.png)
![Gm1gsoITB7](https://user-images.githubusercontent.com/10644674/125357454-32ddf900-e357-11eb-8b5b-4a2b302f2951.png)

**Comment by Movisivi** [comment]
MusicBee has this issue too. I was told in the past it was because the application lacks GSMTC support. Idk if their docs are out of date but foobar is supposed to be supported https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md

**Comment by Cyberdroid1** [comment]
@Dogs777 as you can see in [the doc](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md) linked above by @Movisivi, foobar2000 does not support shuffle, repeat or timeline. This is something that the foobar2000 app's dev need to implement so that ModernFlyouts can fully support it. 

This issue is something that ModernFlyout cannot help, and it completely depends on the media app's dev to implement in their app. 

Closing this issue.

**Comment by Dogs777** [comment]
Understandable though I'm not entirely sure about the statement of it not supporting shuffle/repeat. In Foobar2000 (I personally use Columns UI so it might be different on a per user basis) there is a dropdown/menu options that gives the user options to shuffle or repeat everything in the playlist/folder/album (I would post a picture though I'm on my phone).

I would understand if this still boils down to programming limitations though I would like to just address this.

In any event, if it hasn't been requested yet, I might as well make a request for features that can't work with programs like this to be hidden from the displayed menu.

**Comment by Samuel12321** [comment]
The app may internally support shuffling but doesn't support external programs (ModernFlyouts) doing this.
