### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by arnavbhate** [ModernFlyouts-Community/ModernFlyouts#699]
While trying to build in an up-to-date version of Visual Studio 2019 that has all the prerequisites listed installed, I am having a lot of problems building:
- I am unable to choose ModernFlyouts.Package as the startup project.
- Package.appxmanifest shows display name as ms-resource:Resources/PackageDisplayName. Other properties are also ms-resource:Resources.
- It claims to require .NET 6.0.
- I am unable to restore dependencies.
- If I just follow the developer guide and try to build from the right-click menu for ModernFlyouts.Package, the build fails.

![Screenshot (314)](https://user-images.githubusercontent.com/86760472/125396369-10d18e80-e3ca-11eb-8c2e-bfabc1d1a2d0.png)

**Comment by Samuel12321** [comment]
Yes we need to update those instructions, current builds require .net 6 preview sdk. If you are running a non insider version of visual studio, you will also need to enable "use preview sdks" in visual studio options.

**Comment by arnavbhate** [comment]
I installed .NET 6.0, however, I am still unable to build. For some reason, it is unable to restore NuGet packages. Also, it is trying to target uap10.0.17763 instead of .NET 6.0.

![image](https://user-images.githubusercontent.com/86760472/125409660-bf310000-e3d9-11eb-9797-f6293822f888.png)

**Comment by arnavbhate** [comment]
I fixed the issue. I was using the wrong certificate. 🤦

**Comment by Samuel12321** [comment]
Please explain?

**Comment by arnavbhate** [comment]
There was something wrong with the first certificate I had created. When I created another one, it worked. I think it is most likely because I hadn't installed .NET 6 when I created the first one.
