### ISSUE TITLE
Feature Request: Please don't show the Flyouts UI while switching IME

### ISSUE THREAD

**Issue by allenk** [ModernFlyouts-Community/ModernFlyouts#701]
**Is your feature request related to a problem? Please describe:**
No!

**Describe the solution you'd like:**
When you press Win Key + Space Key to switch Input method (IME), the Flyouts UI will appear.
Is there an option to enable/disable the behavior?

**Comment by ErenAKGUN2007** [comment]
Duplicate of #584

**Comment by Samuel12321** [comment]
This is a bug, fixed in next update
