### ISSUE TITLE
Bug: The media flyout is stuck with what ModernFlyouts was started with

### ISSUE THREAD

**Issue by arnavbhate** [ModernFlyouts-Community/ModernFlyouts#702]
**Describe the bug:**

The media flyout gets stuck with whatever app was playing when ModernFlyouts was started.

For example, if nothing was playing, the media flyout will never appear.
If it was Groove Music, even after I have stopped listening, the media flyout will still show Groove Music but the rest of it will be blank. If I start playing something on Edge or start Groove again, the media flyout does not change.

Further, if I switch to Windows flyouts while keeping ModernFlyouts running, the error persists. But when I exit ModernFlyouts the error disappears.

**To Reproduce:**
Steps to reproduce the behaviour:
Start ModernFlyouts and change what's playing (or play something).

**Screenshots:**

**OS Version:**
 - Windows 10 Version: Windows 10 21H1 19043.1083

**ModernFlyouts Version:**
 - Version: v0.9.3

**Additional context:**

This issue started happening yesterday (four days after install).
Note: When I am playing in the same app and the song changes then the flyout **does** update.

A reinstall did not fix the issue.

**Comment by arnavbhate** [comment]
The bug disappeared all of a sudden without me doing anything.

**Comment by Cyberdroid1** [comment]
😄
Closing this issue then.
If you face this issue again, will reopen this issue then.

**Comment by arnavbhate** [comment]
I had this problem again.
However, I fixed it myself by repairing the app from Settings.
Whatever caused the issue in the first place still needs to be fixed though.

**Comment by arnavbhate** [comment]
I now have to repair this app from settings everyday as I have this error everyday.
