### ISSUE TITLE
Media flyout doesn't appears

### ISSUE THREAD

**Issue by DeyGuevara** [ModernFlyouts-Community/ModernFlyouts#704]
Hello

I attached an image about my issue. I have opened spotify but the media controls not are displayed, i can only see the sound bar
i have the latest version and all the settings correctly  but i can't see the controls

thank you so much, i really like modernFlyouts and i hope help with this

![image](https://user-images.githubusercontent.com/11048015/125872506-8e55521b-9e68-4a5b-a613-fa2cba451a18.png)

**Comment by arnavbhate** [comment]
Is this the same as #702?

**Comment by Samuel12321** [comment]
Duplicate of #710
