### ISSUE TITLE
Feature Request: Make this app compatible with WebNowPlaying Companion 

### ISSUE THREAD

**Issue by DoomSlayer1095** [ModernFlyouts-Community/ModernFlyouts#711]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Cyberdroid1** [comment]
Can you please provide us more info on what WebNowPlaying companion is? Preferably a link too.

**Comment by ShankarBUS** [comment]
Bruh, the app is literally named as Modern"Flyouts". We make redesigned (hmmmm) flyouts. Not a global media controller.

But this does seem interesting.

**Comment by DoomSlayer1095** [comment]
no no u got me wrong, all u gotta do is connect web now playing and change
no other settings then for people who use YT music and YT can see their
music/video progress and play next or the previous video.
Web Now Playing is originally meant for pple who use rainmeter but  i think
u can make flyout outta it
wait a sec lemme send the link.

https://chrome.google.com/webstore/detail/webnowplaying-companion/jfakgfcdgpghbbefmdfjkbdlibjgnbli

and ill ask a friend of mine for the manual for it and ill send it
and if u have discord pls send add m cas i don't check GMAIL that
frequently

**Comment by DoomSlayer1095** [comment]
https://github.com/tjhrulz/WebNowPlaying-BrowserExtension
there u go

**Comment by DoomSlayer1095** [comment]
꧁༒ĐØØ₥ ₴Ⱡ₳ɎɆⱤ༒꧂#4080 ma discord acc

**Comment by ShankarBUS** [comment]
This is the same as our browser extension companion request. It would be cool feature, but I doubt we will be able to provide it in the near future.

**Comment by Poopooracoocoo** [comment]
Chrome currently doesn't support timeline data and seeking in its global media controls. 
And Chrome (and Firefox) won't supply timeline data for media sessions to the system because Windows has no native UI that presents timeline data.

Try convincing Microsoft and Google, as well as Mozilla. @DoomSlayer1095

**Comment by DoomSlayer1095** [comment]
well IDK rainmeter skins worked jst fine i don't have good knowledge in coding stuff

**Comment by Cyberdroid1** [comment]
> Chrome currently doesn't support timeline data and seeking in its global media controls. 
> And Chrome (and Firefox) won't supply timeline data for media sessions to the system because Windows has no native UI that presents timeline data.


This tool, WebNowPlaying companion, actually supplies the media info which browsers don't provide. It's basically a hack to get media info. @DoomSlayer1095 is asking to add support for this web extension to get media info.

**Comment by Poopooracoocoo** [comment]
@Cyberdroid1 yeah i get why @DoomSlayer1095 created the issue. But since Shankar said that there are no plans for it to be supported in the immediate future, I suggested that they plead with those people.

**Comment by DoomSlayer1095** [comment]
I get it, anyway, the app is good without it too, so NP. thx guys

**Comment by DoomSlayer1095** [comment]
ye, but this feature is a good one
guess we gotta wait and see (and ask..)

**Comment by Samuel12321** [comment]
It would be a convenient way to get this info without building our own extension, as Shankar said, unlikely to happen any time soon but nice idea for the future.
ModernFlyouts could provide the option to install the extension from the store to add this capability.
https://developer.chrome.com/docs/extensions/mv3/external_extensions/

**Comment by Samuel12321** [comment]
> Chrome currently doesn't support timeline data and seeking in its global media controls.
@DoomSlayer1095 @Poopooracoocoo @Cyberdroid1 @ShankarBUS 
There is actually a feature request open for this https://bugs.chromium.org/p/chromium/issues/detail?id=1153108
can everyone please upvote this so it can get some momentum.

**Comment by Samuel12321** [comment]
Closing this in favor of #170 , but have referenced this request as a possible solution. 
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/170#issuecomment-886280480

**Comment by Samuel12321** [comment]
Hi, i have just quickly opened another feature request with chromium for STMC Timeline Support, the other one was for multiple media sessions. Can everyone please upvote this so it is fixed.
https://bugs.chromium.org/p/chromium/issues/detail?id=1235985
@DoomSlayer1095 @Poopooracoocoo @Cyberdroid1 @ShankarBUS

**Comment by Cyberdroid1** [comment]
For both of these issues, one will need to click the star in the top-left to upvote the issue.

![image](https://user-images.githubusercontent.com/51435948/128026084-9ede31cb-80d1-4053-bcc3-d3ac53a1542f.png)
