### ISSUE TITLE
Bug: Flyout Content Stacking Direction/Flyout Placement

### ISSUE THREAD

**Issue by Aurgasm** [ModernFlyouts-Community/ModernFlyouts#713]
**Describe the bug:**
Flyout content stacking direction is not working properly when not using the auto flyout placement. The volume and lock keys (I have not tested brightness or airplane mode as my desktop supports neither) show up on the top when it should be locked at the bottom.

**To Reproduce:**
See screenshots.

**Screenshots:**

With auto flyout placement, it is working as intended.

![image](https://user-images.githubusercontent.com/87892285/126881009-ff498987-6f25-4167-a830-0f22c51a6e8e.png)
![image](https://user-images.githubusercontent.com/87892285/126880984-087135a1-6d6f-4213-8228-c930f8cd5bc1.png)
![image](https://user-images.githubusercontent.com/87892285/126880991-ddbacc3a-83f5-4aad-a5d3-766932677d51.png)

However, with manual placement (both through precise x & y from within the settings, or simply from dragging it, the "Flyout content stacking direction" doesn't seem to be working properly.

![image](https://user-images.githubusercontent.com/87892285/126881014-de25d176-5453-4ea6-8300-e584417c1566.png)
![image](https://user-images.githubusercontent.com/87892285/126880995-34780222-9bf2-40b1-97e2-8ff18fc4d0e9.png)
![image](https://user-images.githubusercontent.com/87892285/126881000-aac08baf-c71d-4326-aedd-3b00484930b8.png)

**OS Version:**
 - Windows 10 Version: Windows 10 Pro 21H1

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Comment by ShankarBUS** [comment]
This is the expected behavior. This is what we intended the placement APIs to be.

Manual placement will use absolute location.

This is not a bug. This is how it should behave.

**Comment by Aurgasm** [comment]
Seems counter productive to be able to manually place the volume in the bottom left or right corners, but then the media controls only expand downwards from there - especially since it "behaves properly" in auto-mode? Why have the drag to move function be on the volume slider when in reality the absolute location it's referencing isn't actually where you're moving it?

**Comment by ShankarBUS** [comment]
I guess you misunderstood how the placement works. I tried my best to explain.
