### ISSUE TITLE
ModernFlyouts to respond to 3RVX Control

### ISSUE THREAD

**Issue by ryohandoko9056** [ModernFlyouts-Community/ModernFlyouts#716]
ModernFlyouts is by all mean very great, especially its modern look, but something block me from using its full potential. That is my keyboard isn't a multimedia keyboard, so I have to use an old third-party app like 3RVX to control the volume from my keyboard. 

Can someone probably make something that can integrate ModernFlyouts to 3RVX Control?

**Comment by Samuel12321** [comment]
So what your actually requesting is hotkey support?

**Comment by ryohandoko9056** [comment]
> So what your actually requesting is hotkey support?

No, but what I mean is, I want ModernFlyouts to be able to respond to 3RVX's Control, as currently, it's not.

**Comment by Samuel12321** [comment]
I don't really understand what 3rvx is, I thought it was autohotkey plus it's own flyout like ModernFlyouts?

**Comment by ryohandoko9056** [comment]
Yes

**Comment by ShankarBUS** [comment]
Unfortunately, we can't support 3RVX. It is completely different.

What we could do is add hotkey support.

What do you mean by respond to 3RVX's control?

**Comment by ryohandoko9056** [comment]
Never mind, I abandoned 3RVX, and used AHK script that can trigger the Modern Flyouts, anyway, Thanks for the help all!

**Comment by ShankarBUS** [comment]
I was about to recommend PowerToys. But AutoHotKey is also great! Glad your issue is solved!
