### ISSUE TITLE
Bug: Windows wizard triggers modern flyouts volume.

### ISSUE THREAD

**Issue by awesomelewis2007** [ModernFlyouts-Community/ModernFlyouts#718]
**Describe the bug:**
When a windows wizard pops up modern flyouts volume is triggerd

**To Reproduce:**
Steps to reproduce the behaviour:
right click on desktop> new>shortcut
OR
right click a zipped folder> extract zipped folder

**Screenshots:**
![image](https://user-images.githubusercontent.com/60709927/127119907-259a9a75-8f57-4dcc-ae46-4b549910aa08.png)

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
9.3.0

**Comment by awesomelewis2007** [comment]
![image](https://user-images.githubusercontent.com/60709927/127120314-bd51905f-179b-4ef7-94c9-96bc7c2f7956.png)

**Comment by awesomelewis2007** [comment]
![image](https://user-images.githubusercontent.com/60709927/127120579-c70165f7-533f-419f-9e61-70b8756c316c.png)

network wizard dose not trigger modern flyouts

**Comment by Samuel12321** [comment]
Unable to reproduce
I just tried it as well as frequently using these shortcuts on other computers and couldn't reproduce this.

**Comment by Samuel12321** [comment]
We need more info, what os version etc.

Are you sure you didn't just accidentally trigger a volume change?

**Comment by awesomelewis2007** [comment]
> We need more info, what os version etc.
> 
> Are you sure you didn't just accidentally trigger a volume change?

Device name	LAPTOP-PJTAG1MU
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Home
Version	20H2
Installed on	‎19/‎06/‎2021
OS build	19042.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by awesomelewis2007** [comment]
i did not touch my volume changer as i would need to press fn+f11 or fn+f12 on my keyboard

**Comment by awesomelewis2007** [comment]
I'm reinstalling the app

**Comment by awesomelewis2007** [comment]
still happening after reinstalling

**Comment by Samuel12321** [comment]
Update to 21h1?

**Comment by awesomelewis2007** [comment]
ok

**Comment by awesomelewis2007** [comment]
bug fixed after an update I think its just a windows problem

**Comment by Samuel12321** [comment]
Which update fixed it just out of curiosity?

**Comment by awesomelewis2007** [comment]
21h1

**Comment by awesomelewis2007** [comment]
I Managed to reproduce the issue on windows 11

Edition	Windows 11 Home
Version	21H2
Installed on	‎27/‎10/‎2021
OS build	22000.282
Experience	Windows Feature Experience Pack 1000.22000.282.0

**Comment by Bear39** [comment]
I have the same issue and I'm currently at 21H2, quite sure it's not windows problem since the classic flyout not triggered (when creating shortcut), sometimes restarting explorer.exe fix the problem (But after I restarted the app then restart the explorer again the problem appear again)

**Comment by awesomelewis2007** [comment]
Issue still persistent on latest windows build
