### ISSUE TITLE
Bug: Spotify Media Thumbnail Doesn't Display Well in Windows 11

### ISSUE THREAD

**Issue by ccrsxx** [ModernFlyouts-Community/ModernFlyouts#721]
Describe the bug:
Spotify media thumbnail doesn't display correctly in Windows 11, previously worked in Windows 10. In Windows 11, there's an extra space below the media thumbnail, which makes the thumbnail not displaying correctly. This bug only appears in spotify.

Additional context:
Previously worked with Windows 10. I tried reinstalling Spotify without using any skins, but the thumbnail still doesn't display correctly. Other music players such as Youtube Music PWA and Groove Music works fine, only Spotify has this problem.

Expected, no extra space below the thumbnail (taken in windows 10):
![Screenshot (357)](https://user-images.githubusercontent.com/55032197/127635514-059aab2b-1988-403d-ab03-7ae5c88a8b8e.png)

Actual result (windows 11), there's an extra space below the thumbnail (see red circle):
![image](https://user-images.githubusercontent.com/55032197/127643063-97937a43-246c-4b9d-9648-042ba5e87ad0.png)

To Reproduce:
1. Open Spotify
2. Play any music
3. Open ModernFlyouts

OS version:
Windows 11 Beta (21H2 Build 22000.100)

ModernFlyouts Version:
Version: v0.9.3.0

**Comment by Samuel12321** [comment]
Why was this closed then reopened?

Sorry  i cant see the bug, can you explain further?

**Comment by ccrsxx** [comment]
Sorry for the confusion. I accidentally opened the issue before I finished writing the bug and closed it, reopened it again after I finished writing.

As for the bug, the thumbnail should fully cover the entire media flyout, also here there's no extra space below the thumbnail, like this: 
![Screenshot (357)](https://user-images.githubusercontent.com/55032197/127640328-d13c92de-7ccd-428b-869c-f7e4f2cf105f.png)
This screenshot was taken in Windows 10

In windows 11, for some reason, there's an extra space below the thumbnail (see red circle), which I believe makes the thumbnail not displaying correctly like in the screenshot above.
![Screenshot (364)_LI](https://user-images.githubusercontent.com/55032197/127640541-042aec86-fce9-43b9-86d3-3fe1fcdce898.jpg)

This bug only appears in Spotify. Youtube Music and Groove Music all display the thumbnail correctly with no extra space below the thumbnail. 
![Screenshot (362)](https://user-images.githubusercontent.com/55032197/127641430-2a10074e-aa30-4557-bfc6-9fd821095cea.png)
![Screenshot (363)](https://user-images.githubusercontent.com/55032197/127641448-ca2d6302-f953-41ad-80a0-1f05ce303f75.png)

I tried reinstalling Spotify multiple times, thinking that probably my custom skin caused it to happen, but nope the bug still appears.

**Comment by risalamin** [comment]
I'm having the same issue. That weird extra space appears after I upgraded to Windows 11.

**Comment by ShankarBUS** [comment]
Ok, let me explain this case:

1. The space you see there is because, Spotify intentionally adds padding and their logo into thumbnail. Not any other apps do this. Only Spotify does this.

2. Then, we got some suggestions from our users to remove this, we decided to manually crop out the spacing and Spotify logo from the thumbnail provided by Spotify

3. So we send the thumbnail to the cropping process, only if it is from Spotify:

https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/1e8997dadc47cfb99fd9948ef319894d862af345/ModernFlyouts.Core/Media/Control/NowPlayingMediaSession.cs#L222-L277

But this process is dependent on the app id. There are two types of Spotify, Store version and Desktop version. We have covered both. I think so.

Which version of Spotify are you using?

My most probable guess is, they might have changed the package ID.

I will investigate this further.

To be clear, it is Spotify's mistake. We tried our best to crop it out.

**Comment by ccrsxx** [comment]
Thanks for the response. I kinda understand the problem now. I'm only using the desktop version so that I can use skins. Based on your response, I tried installing the store version to see if the cropping works, and it works perfectly there. 

The cropping process apparently doesn't work only on the desktop version in Windows 11. I've tried installing the desktop version in several versions just to make sure, but the cropping still doesn't work. The desktop version worked fine tho previously in Windows 10 before I upgraded it to Windows 11.

I checked if the process name changed, it's still the same.
![image](https://user-images.githubusercontent.com/55032197/127719684-a7264db0-6e0f-48a0-a0cd-93e6ec05d6a4.png)

I don't why, but the cropping only works with the store version in Windows 11.

**Comment by ShankarBUS** [comment]
I will check it. Thanks for the feedback 😄.

And sorry for the inconvenience 💀.

**Comment by ccrsxx** [comment]
No problem. Keep up the good work 👍.

**Comment by ccrsxx** [comment]
The issue seems to be fixed after the latest Spotify update `1.1.68.628.geb44bd66`. I tried on multiple machines to make sure, and all of them display the thumbnail correctly with the latest update. I can confirm the previous version / <  `1.1.68.628.geb44bd66` still doesn't display the thumbnail correctly. I'm closing this issue now.
