### ISSUE TITLE
Audio flyout doesn't show only caps

### ISSUE THREAD

**Issue by Hannes2206** [ModernFlyouts-Community/ModernFlyouts#722]
Hi ich habe mir modern flyouts runtergeladen aber auf meinem Bildschirm erscheinen keine Anzeigen, außer wenn ich Caps aktiviere oder deaktiviere!! (keine Musik, lauter oder leiser... anzeigen)

bitte um hilfe

L.G. Hannes

-------

**Translation :** 

>‎Hi I have downloaded modern flyouts but on my screen no flyouts appear unless I activate or deactivate caps!! (no music, louder or quieter... show)‎
Asking for help‎

> L.G. Hannes

**Comment by Cyberdroid1** [comment]
**Translation :** 

>‎Hi I have downloaded modern flyouts but on my screen no flyouts appear unless I activate or deactivate caps!! (no music, louder or quieter... show)‎
Asking for help‎

> L.G. Hannes

**Comment by Cyberdroid1** [comment]
@Hannes2206 
What windows version are you running?

**Comment by Hannes2206** [comment]
I use Windows 10Gesendet mit der mobilen Mail AppAm 31.07.21 um 19:18 schrieb Prakhar B
                
            
            
                
                    Von: "Prakhar B" ***@***.***>Datum: 31. Juli 2021An: "ModernFlyouts-Community/ModernFlyouts" ***@***.***>Cc: "Hannes2206" ***@***.***>,"Mention" ***@***.***>Betreff: Re: [ModernFlyouts-Community/ModernFlyouts] keine Informationen zu sehen (modern flyouts (#722)
                
                
@Hannes2206
What windows version are you running?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/722#issuecomment-890378052",
"url": "https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/722#issuecomment-890378052",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Cyberdroid1** [comment]
Can you share a screenshot of winver?

open start menu
search winver
press enter
share the screenshot of the new window

it will be something like this-
![image](https://user-images.githubusercontent.com/51435948/127748176-60d531a6-3284-4e01-aa55-1867cea65be8.png)

**Comment by Hannes2206** [comment]
Thank you for helping me with the problem!Here is a photo of itGesendet mit der mobilen Mail AppAm 31.07.21 um 19:41 schrieb Prakhar B
                
            
            
                
                    Von: "Prakhar B" ***@***.***>Datum: 31. Juli 2021An: "ModernFlyouts-Community/ModernFlyouts" ***@***.***>Cc: "Mention" ***@***.***>,"Hannes2206" ***@***.***>Betreff: Re: [ModernFlyouts-Community/ModernFlyouts] keine Informationen zu sehen (modern flyouts (#722)
                
                
Can you share a screenshot of winver?
open start menu
search winver
press enter
share the screenshot of the new window
it will be something like this-


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/722#issuecomment-890380970",
"url": "https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/722#issuecomment-890380970",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Cyberdroid1** [comment]
You will need to send image from the website, and not the email.
