### ISSUE TITLE
Bug: ModernFlyouts appear when changing the language by clicking Win+Space bar or Shift+Alt.

### ISSUE THREAD

**Issue by hazem-abdelghani** [ModernFlyouts-Community/ModernFlyouts#726]
**Describe the bug:**
ModernFlyouts appears/shows on screen when changing the language by clicking Win+Space bar or Shift+Alt.

**To Reproduce:**
Steps to reproduce the behavior: Win+Space bar or Shift+Alt

**Screenshots:**

**OS Version:**
 - Windows 10 Version: Windows 10 21H1

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**

**Comment by vloot** [comment]
#584 duplicate?

**Comment by ShankarBUS** [comment]
Already fixed. Will be available in v0.10.
