### ISSUE TITLE
Feature Request:Touch panel switch display

### ISSUE THREAD

**Issue by dylumian** [ModernFlyouts-Community/ModernFlyouts#738]
**Is your feature request related to a problem? Please describe:**
Add  touch panel switch display

**Describe the solution you'd like:**
Display the touch panel when switching

**Describe alternatives you've considered:**
There is no alternative at this time

**Additional context:**
Sorry, I am a non-native English speaker，I don’t know if you can understand the problem I’m describing

**Comment by Cyberdroid1** [comment]
I was not able to understand your request :(

What do you mean by the touch panel? Do you mean the flyout?

When do you want to display the flyout?
