### ISSUE TITLE
Feature Request: Show flyout on change active language

### ISSUE THREAD

**Issue by Mannyrf** [ModernFlyouts-Community/ModernFlyouts#739]
It's a good idea to show the new chosen keyboard language when Windows active keyboard language is changed.
It happens when more than one keyboard layout is defined and on press Alt+Shift or WinKey+Space.

**Comment by Cyberdroid1** [comment]
Does windows not already show a flyout for that?

**Comment by Mannyrf** [comment]
> Does windows not already show a flyout for that?

Yes, but just when WinKey+Space press.

![image](https://user-images.githubusercontent.com/10153224/128677716-498837df-f4af-4178-a9cc-0a033d1a6edf.png)

**Comment by Mannyrf** [comment]
I also find a bug, sometimes when keyboard language changes, Volume flyout appears!
I saw it often when using WinKey+Space to change language, but just sometimes happened with Alt+Shift.

![image](https://user-images.githubusercontent.com/10153224/128678131-f15ec38d-f1e5-4310-b3c0-6fa943e3cb2a.png)

**Comment by Cyberdroid1** [comment]
> I also find a bug, sometimes when keyboard language changes, Volume flyout appears!
> I saw it often when using WinKey+Space to change language, but just sometimes happened with Alt+Shift.
> 

This bug has been fixed and will be released with the next update :)
