### ISSUE TITLE
Feature Request: Offer some sensible default positions

### ISSUE THREAD

**Issue by neubland** [ModernFlyouts-Community/ModernFlyouts#74]
It would be nice if the user could choose top/bottom and left/center/right, all with some padding to the borders. Moving it manually is not as pixel-perfect as just saying "center top".

For bottom positions, the expansion direction would have to be upwards.

**Comment by ShankarBUS** [comment]
This is a valid request.

So you want auto placement?

Where do you want the option to be, in settings or the flyout itself?

There should be an option to switch between **Auto/Manual** placement.

While having **Manual**, the users can move the flyout themselves. (And they can select which direction the flyout should expand)

While having Auto placement, how many modes should be there?

In theory we should have 9 (3 * 3) [{Top, Center, Bottom} * {Left, Center, Right}] (Expand direction will be automatically calculated)

**Comment by ShankarBUS** [comment]
As a temporary workaround, you can manually calculate the position.

Let's say your display is 1366x768 and you want the flyout to be at TopCenter

The horizontal center will be at 1366/2 = 683.

The flyout width is 354 currently. So the left or X position should be 683 - (354 / 2) = 506

And top or Y position could be 60


Go to settings and type "506,60" in the flyout default position.

Click the align button on the flyout.

It will be aligned to the center

**Comment by neubland** [comment]
Thanks a lot for the numbers!

The auto-position should take taskbar position into account. With taskbar to the left the current default clashes with the taskbar. I can imagine something similar might happen with taskbar to the right or bottom-aligned flyout.

I would expect the option to be in the settings.

**Comment by ShankarBUS** [comment]
Yes, TaskBar's region will excluded from our workarea. So they won't overlap.

**Comment by neubland** [comment]
Great! This would be something even the default Win10 flyout doesn't get right.

**Comment by Samuel12321** [comment]
I was about to open the exact same feature request.
Definitely a great idea

> Where do you want the option to be, in settings or the flyout itself?

Definitely in settings
> When the users drag the flyout, the placement mode will switch from auto to manual, would it be appropriate?

Yes

**Comment by OGordon100** [comment]
To add to this, could this also automatically adapt to remain in the same relative position after screen rotation? As an example, at the moment if I set the flyout to the top middle of the screen, then if I rotate my tablet from landscape to portrait, the flyout appears in the top right.

**Comment by ShankarBUS** [comment]
Wow! Thanks @OGordon100

I forgot such a scenario happens.

And what about mutli-monitor setups?

We currently have a problem, if the flyout has been moved manually to a second monitor in a previous session and later disconnected, the flyout will go outside of the first monitor's bounds.

Should it return to the primary monitor if the second monitor has been disconnected?

Should we provide auto placement for mutli-monitor setups?

**Comment by Samuel12321** [comment]
> Should it return to the primary monitor if the second monitor has been disconnected?

Yes

**Comment by Tropix126** [comment]
We could have a similar GUI to how [discord](https://discord.com) handles their overlay settings. Just some inspiration.

![image](https://user-images.githubusercontent.com/42101043/103470930-d44c1880-4d3e-11eb-8a05-a5151ae9251c.png)

**Comment by ShankarBUS** [comment]
We are planning to do a UI similar to Figma.

![](https://i.imgur.com/TohkXCg.jpg)

**Comment by Samuel12321** [comment]
I quite like discords one. I think it is more intuitive. I was also thinking that an option for default or tight alignment may be good. (Eg default uses current spacing and tight brings it a bit closer to the edges of the screen.

**Comment by ShankarBUS** [comment]
This is UI to control the flyout alignment.

https://user-images.githubusercontent.com/63704247/104181187-58378c00-5434-11eb-8032-0bbb6c3107a2.mp4

**Comment by Cyberdroid1** [comment]
Amazing!
