### ISSUE TITLE
Bug: Music informations not properly shown (Amazon music desktop app)

### ISSUE THREAD

**Issue by Flintpop** [ModernFlyouts-Community/ModernFlyouts#740]
**Describe the bug:**
In the music / audio section, the thumbnail and timestamp are not properly shown / activated with amazon music (HD desktop version) when showing sound stuff. Furthermore, the title and author of the music does not appear all the time.

**To Reproduce:**
1. Launch amazon music desktop app
2. Type on the keyboard the function that goes to the next or previous or pause music or modifying sound volume
3. See error

**Screenshots:**
![bug modern flyout](https://user-images.githubusercontent.com/79105055/128639493-d6731b2c-344a-4d80-9942-dd944d0fa861.png)

**OS Version:**
 - Windows 10 Version: Windows 10 21H1]

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**

**Comment by Cyberdroid1** [comment]
Do the windows default flyouts show the media thumbnail and name?

**Comment by Flintpop** [comment]
Nope, indeed it doesn't show it properly too. I dont have a thumbnail, but I have the title sometimes shown properly as in the modern flyout version... It's on amazon side then. And mb my app simply need a reinstall. I dunno. Ty anyway !
