### ISSUE TITLE
Bug: Seekbar not working

### ISSUE THREAD

**Issue by StLa1** [ModernFlyouts-Community/ModernFlyouts#745]
**Describe the bug:**
The seekbar does not work. I tried with media session created by Edge and Brave (Chromium browsers) with different websites (YT, YTM).
The times are stuck at 0:00 and the slider handle on the right of the bar.

**OS Version:**
 - Windows 10 Version: 21H1

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Comment by Cyberdroid1** [comment]
Have a look at this doc for support regarding your media app (here, your browser) 
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md
