### ISSUE TITLE
Bug: Setting will launch, but the actual flyouts won't appear

### ISSUE THREAD

**Issue by Dataslide** [ModernFlyouts-Community/ModernFlyouts#749]
Let me just say that I downloaded the app from Microsoft. 

I can open the settings and adjust them(though actually there is another bug with turning off the audio flyout(just crashes when turned off)), however, I can't for whatever reason get the actually flyouts to appear on my screen. I have Wallpaper Engine and at first I thought that might be interfering somehow, but even after I turned Wallpaper Engine off and restarted Flyouts, they still did not appear. I'm not too sure if this is on my end, I could just be stupid and not opening the app properly, but I figured I need help nonetheless. 

I also tried reverting back to an old version(0.9.1). This did not help, the flyouts still would not show. I then reverted back to the most updated version (0.9.3) and it did not change anything. [edit]

I also very much do not know anything about the code or anything, literally made a github account just to report this and possibly bring attention to this. 

Please let me know if I can provide anymore information.

**Comment by Cyberdroid1** [comment]
What keys have you tried to trigger the flyouts? Try pressing the caps lock key and see if the flyout opens.

Did you tweak anything in the layout page of settings?

Also, what is your windows version?

**Comment by Cyberdroid1** [comment]
Closing due to no response from author.
will reopen if author provides info.
