### ISSUE TITLE
Won't even start at all.

### ISSUE THREAD

**Issue by thisistiz** [ModernFlyouts-Community/ModernFlyouts#752]
After installing, i can click on the programm and it will appear on the bottom right but when i click on it, it just closes again.

**Comment by Cyberdroid1** [comment]
Can you open reliability monitor and see for any crashes related to ModernFlyouts?

**Comment by thisistiz** [comment]
> Can you open reliability monitor and see for any crashes related to ModernFlyouts?
I looked for it, ModernFlyouts wasn't mentioned there.

> Whats your app version?
I downloaded the newest Version from the Microsoft Store, it says 0.9.3.0 there

> Whats your windows version?

Windows 10 Home, Version 21H1

**Comment by Cyberdroid1** [comment]
Ok thanks.

This issue is pretty similar to #642 
Closing as duplicate.
