### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by WinterAxt** [ModernFlyouts-Community/ModernFlyouts#753]
https://user-images.githubusercontent.com/89042700/129626428-586e7abc-b30a-4228-b6a6-d1b5ae78fe32.mp4

**Describe the bug:**

**To Reproduce:**

**Screenshots / Video :** 

**OS Version:**
 - Windows 10 Version: Windows 10 20H2 190.42.1165

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Thats not how that feature works :smile: 
Clicking that button keeps the topbar expanded.

Closing as duplicate of #368
