### ISSUE TITLE
Bug: Some media buttons are greyed out in media flyout

### ISSUE THREAD

**Issue by PapaN0el** [ModernFlyouts-Community/ModernFlyouts#765]
Ive been using this widget for a week now but recently the app has been glitching and I cant use the pause/play/skip controls for apps like chrome and spotify.

I tried resetting the settings, reinstalling the app from the windows store, even tried installing the .exe of the app but it doesnt work. 
I also tried disabling and enabling the audio flyout option which makes the app crash.

OS version-
Windows 10 Pro 21H1

ModernFlyouts version- 
0.9.3.0

Extra info-
Sometimes I can also see the app media controls even after closing the app which makes it not work when I open another app.

**Comment by Cyberdroid1** [comment]
So, you are able to see the media flyouts but the play/pause, back, forward buttons are greyed out, correct?

**Comment by victorwctsang** [comment]
Also experiencing this problem.

**Screenshots:**
![image](https://user-images.githubusercontent.com/35205232/130311452-a7ef3b88-239b-4f96-8460-7070f4ff59de.png)


**OS Version:**
 - Windows 10 Version: Windows 10 Home 21H1

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**
- Interestingly, despite this issue I am able to control shuffle and repeat. 
![image](https://user-images.githubusercontent.com/35205232/130311472-12a607a9-28eb-4f6c-9fac-7e5c3cccb0b6.png)

**Comment by fitae** [comment]
I had the same issue. A reinstallation did the trick. After reinstalling i found the reset option tho, so maybe that one works too.

**Comment by inkss** [comment]
我有一个其他的问题，Groove 下音乐播放时没有进度条。
I have another problem with Groove music playing without progress bar.

![Snipaste_2021-10-11_09-05-04 png ‎- 照片_21-10-11_09-09-49](https://user-images.githubusercontent.com/31947043/136720084-7061b49f-8cda-4f12-ad7a-17528b648995.png)

**Comment by Cyberdroid1** [comment]
@inkss groove does not support the timeline bar, hence it is greyed out.

**Comment by arnavbhate** [comment]
I have a similar problem with Groove Music (and only Groove Music).

![Screenshot](https://user-images.githubusercontent.com/86760472/125165934-c1ffdb00-e1b6-11eb-919f-86bec9ed970f.png)

It only happens when I am playing something, then I "clear now playing", then close Groove Music, reopen it and play something.

**Comment by inkss** [comment]
> @inkss groove does not support the timeline bar, hence it is greyed out.

好的，谢谢。然后对于 Groove  这类不支持的应用是否隐藏它比较好？
Ok thanks. And is it better to hide it for unsupported apps like Groove?

**Comment by Cyberdroid1** [comment]
> Ok thanks. And is it better to hide it for unsupported apps like Groove?

@inkss yes, an update with improved UI for the timeline bar is due to come out, but there are some blocking issues, hence the delay.

**Comment by arnavbhate** [comment]
Related to #446 and #532?

**Comment by Samuel12321** [comment]
Closing in favor of #446 and #532
