### ISSUE TITLE
Bug:The app ModernFlyouts doesn't connect with Spotify at all.

### ISSUE THREAD

**Issue by CereteuPaul** [ModernFlyouts-Community/ModernFlyouts#767]
![image](https://user-images.githubusercontent.com/71525035/130325492-602abfd8-f258-48c2-8c9b-2e15ddfd5e99.png)
As you can see spotify is open and playing but the app won't recognize it at all. I tried everything

**Comment by Cyberdroid1** [comment]
Duplicate of #710
