### ISSUE TITLE
Bug: When I am turning up my volume while listening to spotify it used to show a preview of what song I am listening to but now it doesn't show anymore.

### ISSUE THREAD

**Issue by TronnoC** [ModernFlyouts-Community/ModernFlyouts#769]
**Describe the bug:**
 There used to be a preview of what song  was listening to on spotify but now it doesn't show when I am turning up the volume.

**To Reproduce:**
No signs to reproduce bug.

**Screenshots:**

**OS Version:**
 - Windows 10 Version:  0.9.3.0

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Duplicate of #710
