### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by tjhecker** [ModernFlyouts-Community/ModernFlyouts#771]
**It takes too much of system usage **

**you can make low CPU usage version of this software**

**Comment by lazurit11** [comment]
This app uses 0% CPU on idle and 5% on pop-up, on laptop i5-1035 processor.

How much CPU usage are you facing? What CPU do you have?

**Comment by Cyberdroid1** [comment]
Even on a spare potato PC I have (3rd gen i5 Intel), I dont see any CPU usage spikes while triggering the flyouts.

**Comment by Cyberdroid1** [comment]
@tjhecker You will need to provide us more details. Windows version, app version, PC specs and any other related info.

**Comment by tjhecker** [comment]
sorry for late reply, i am having a double potato pc with intel Celeron N3500 processor i think for that it is having high cpu usage.

**Comment by Cyberdroid1** [comment]
*Thats an omega potato! How do you manage to even run Windows normally lol*

Jokes aside, do you face high CPU usage with any other app?

**Comment by tjhecker** [comment]
I am having no problem with other apps and my windows 10 works normal on that it uses 2 percent CPU usage on idled without any software running. There a new problem arrived just just see the image below😅😅
![Screenshot (186)](https://user-images.githubusercontent.com/89440583/132951328-310a8afb-d2c0-4823-9de6-f0150a6f64de.png)

**Comment by Cyberdroid1** [comment]
>  There a new problem arrived just just see the image below😅😅
> ![Screenshot (186)](https://user-images.githubusercontent.com/89440583/132951328-310a8afb-d2c0-4823-9de6-f0150a6f64de.png)

Groove does not support the timeline feature in ModernFlyouts :/
Cannot do anything about it, except asking Microsoft to add it.

**Comment by tjhecker** [comment]
> > There a new problem arrived just just see the image below😅😅
> > ![Screenshot (186)](https://user-images.githubusercontent.com/89440583/132951328-310a8afb-d2c0-4823-9de6-f0150a6f64de.png)
> 
> Groove does not support the timeline feature in ModernFlyouts :/
> Cannot do anything about it, except asking Microsoft to add it.

which music player would i use to get the timeline feature.

**Comment by Cyberdroid1** [comment]
> which music player would i use to get the timeline feature.

You can try [Dopamine](https://github.com/digimezzo/dopamine-windows) and [Aurora Music](https://www.microsoft.com/store/productId/9NBLGGH6JVDT).

**Comment by tjhecker** [comment]
ok

**Comment by tjhecker** [comment]
Working properly and aurora music player is better than groove music.^_^
![Screenshot (191)](https://user-images.githubusercontent.com/89440583/133191891-660a718f-8cf0-4d0e-8c2a-2b59969ee07f.png)

**Comment by tjhecker** [comment]
my problems are fixed 😃😃

**Comment by Cyberdroid1** [comment]
Nice to know!
