### ISSUE TITLE
Bug:Slow/Frozen media progress bar

### ISSUE THREAD

**Issue by Dabmanz1** [ModernFlyouts-Community/ModernFlyouts#775]
**Describe the bug:**
The Progress of the song is slow/frozen, when playing music on spotify

**To Reproduce:**
1.Start a song on spotify
2.Open the ModernFlyouts Popup
3.See progress bar not syncing to time in song

**Screenshots:**
N/A

**OS Version:**
 - Windows 10 Version: Windows 10 21H1

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**

**Comment by Cyberdroid1** [comment]
What do you mean by frozen/slow? Can you share some screenshots or screen recording?

**Comment by Dabmanz1** [comment]
https://user-images.githubusercontent.com/77266761/130793896-b8030ae5-f93e-40ff-bda4-7f7538390d14.mp4

**Comment by Cyberdroid1** [comment]
So, the pause and back/forward buttons dont work and the timeline bar doesnt move, right?

**Comment by Dabmanz1** [comment]
they do work, the song does change when clicking pause and back/forward buttons; but the popup doesn't update that the song has changed nor that the song has progressed.

**Comment by Cyberdroid1** [comment]
Oh, so the media info does not get updated in the flyout?

**Comment by Dabmanz1** [comment]
no
