### ISSUE TITLE
Bug: ilk ses tuşuna bastığımda küçük bir zamanda eski görünüm gözüküyor.

### ISSUE THREAD

**Issue by herifuykusuzbe** [ModernFlyouts-Community/ModernFlyouts#784]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
And well, its a duplicate of #189
