### ISSUE TITLE
Feature Request : Add support for iTunes

### ISSUE THREAD

**Issue by JakeR04** [ModernFlyouts-Community/ModernFlyouts#787]
Modern Flyouts currently does not support music playback for the iTunes app on windows 10. It would be nice if we could control the playback in the same way that Spotify works with this application.

**Comment by Cyberdroid1** [comment]
iTunes does not support the timeline feature of Windows. Nothing that this app can do :(

You can maybe send this feedback to Apple, but I highly doubt they would fix it.
