### ISSUE TITLE
Audio flyouts/thumbnail not changing 

### ISSUE THREAD

**Issue by codmster** [ModernFlyouts-Community/ModernFlyouts#789]
So I just installed modernflyouts(from microsoft store) and played something on my browser. When I changed the volume I could see the browser thumbnail below the volume slider. Then I closed the browser and started playing spotify the thumbnail still showed browser. I have to restart modernflyouts everytime to see the thumbnail of different applications. Please help me fix this.

**Comment by Cyberdroid1** [comment]
Duplicate of #751
