### ISSUE TITLE
Bug: i doesent open

### ISSUE THREAD

**Issue by Meniboy06** [ModernFlyouts-Community/ModernFlyouts#794]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Explain what you are facing with the details

**Comment by Cyberdroid1** [comment]
Closing due to no response
