### ISSUE TITLE
Feature Request: RoundedTB Integration?

### ISSUE THREAD

**Issue by fillwithjoy1** [ModernFlyouts-Community/ModernFlyouts#798]
https://github.com/torchgm/RoundedTB?? Could be the next step? Also SmartTaskbar?

**Comment by Samuel12321** [comment]
please elaborate further, I'm not sure where we could integrate?

**Comment by fillwithjoy1** [comment]
Dismiss, I am indeed a retard (at the time, since I didn’t know how it could work). It’s based on RoundedTB, a windows app and a GitHub project that exists currently. I’m assuming (at the time) that this could be a feature suggestion to possibly merge that project with this one.  Sent from Mail for Windows From: SamSent: Sunday, 19 September 2021 7:03 PMTo: ModernFlyouts-Community/ModernFlyoutsCc: Joy; AuthorSubject: Re: [ModernFlyouts-Community/ModernFlyouts] Feature Request: RoundedTB Integration? (#798) please elaborate further, I'm not sure where we could integrate?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fillwithjoy1** [comment]
wtf was my email service doing at the time
