### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by lxcas-html** [ModernFlyouts-Community/ModernFlyouts#799]
I try to open the app but it seems to not work. I reinstalled it three times but whenever I try to open it, either it closes before it can open, or it does not even run. 
Is it my computer or a recent issue with the app?

**Comment by Cyberdroid1** [comment]
Look for any crash reports in reliability monitor or event viewer related to ModernFlyouts.

**Comment by Samuel12321** [comment]
closing due to insufficient info
