### ISSUE TITLE
Bug: The flyout auto appears when extract a file

### ISSUE THREAD

**Issue by NguyenASang** [ModernFlyouts-Community/ModernFlyouts#800]
**Describe the bug:**

When I'm going to extract a file, the flyout auto appears although I don't press the volume button.

**Screen Capture**

![New Project](https://user-images.githubusercontent.com/87893636/132005914-14abb6a3-11a9-4058-94d9-25f20a03fccf.gif)

Sorry about that ugly quality of the video

**OS Version:**
 
- Windows 11 Build 22000.176

**ModernFlyouts Version:**
 
- Version: v0.9.3.0

**Comment by Samuel12321** [comment]
ok, haven't seen that one before.
There will be an update coming out sooner or later - 0.10 which may fix this.

Will look into this.

**Comment by NguyenASang** [comment]
@Samuel12321 This error cause by Window, now it has been fixed
