### ISSUE TITLE
Bug: switch language

### ISSUE THREAD

**Issue by lisssonekiq** [ModernFlyouts-Community/ModernFlyouts#801]
**Describe the bug:**

when I switch the language in windows, a window comes out with the volume
**To Reproduce:**

Click on 'win+space ; shift+alt'
**Screenshots:**

**OS Version:**
 - Windows 10 Version: 
Windows 10 Pro 21H1 19043.1165

**ModernFlyouts Version:**
 - Version: 
0.9.3.0
**Additional context:**

**Comment by Cyberdroid1** [comment]
Use GitHub search feature, this is duplicate.
