### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by honeming** [ModernFlyouts-Community/ModernFlyouts#806]
**Describe the bug:**
Time bar doesn't work in Spotify WebPlayer.It always show 0:00 to 0:00.
But it work in Spotify on Windows.

**To Reproduce:**

**Screenshots:**
![圖片](https://user-images.githubusercontent.com/57797481/132985703-e8ab4224-33dc-401a-8bbc-5edd3b58d84e.png)
![圖片](https://user-images.githubusercontent.com/57797481/132985980-3da1e4ac-da15-4525-b2b8-c1aa25d4b4a8.png)

**OS Version:**
 - Windows 11 Home Insider Preview:22449.1000
 - Firefox Nightly:94.0a1（2021-09-11）（64 bit）

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**
I'm Taiwan user,so that song name and lyric is Chinese(Traditional)

**Comment by Cyberdroid1** [comment]
Firefox does not support timeline. 

[<h3> Read more here](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md)
