### ISSUE TITLE
Feature Request: Have media popup show when media automatically changes.

### ISSUE THREAD

**Issue by ActuallyTomas** [ModernFlyouts-Community/ModernFlyouts#810]
Have an option for the flyout to popup on media change i.e. when a song ends and a new one starts playing, when a video ends and the next video autoplays.

This would be nice for the user to be able to see what is song playing now or what video just autocued *(if they have it playing in the background and are just listening)* without having to pause, change the volume or give any user input. You can even call it "Enable Quick Glance"

**Comment by Samuel12321** [comment]
Duplicate of #78
