### ISSUE TITLE
Bug:the tab does not come off, it stays fixed for a long time

### ISSUE THREAD

**Issue by cheloalfaro** [ModernFlyouts-Community/ModernFlyouts#813]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
#464 
<h3> Please use search feature of Github to see whether is already an issue open.

Also, fill the issue correctly with all the information
