### ISSUE TITLE
Bug: Auto quit in Windows 11

### ISSUE THREAD

**Issue by myfix16** [ModernFlyouts-Community/ModernFlyouts#816]
**Describe the bug:**

The app sometimes automatically quit in Windows 11 for no reason (No security software running, game mode off, etc.).

**To Reproduce:**

1. Run the app
2. Use the OS as usual for some time
3. Let the computer go sleep and awaken (Optional)
4. With some possibility, the app will quit automatically 

**Screenshots:**

Not applicable.

**OS Version:**
 - Windows 10 Version: 
[Windows 11 Beta 22000.194]

**ModernFlyouts Version:**
 - Version: 
 - [v0.9.3.0]

**Additional context:**

None

**Comment by Cyberdroid1** [comment]
Duplicate of #642
