### ISSUE TITLE
Bug: Crashes when right-clicking the taskbar icon

### ISSUE THREAD

**Issue by pklion** [ModernFlyouts-Community/ModernFlyouts#819]
**Describe the bug:**
ModernFlyouts crashes when right-clicking the taskbar icon.

**To Reproduce:**
1. Run ModernFlyouts
2. Right-click the taskbar icon
3. See error

**Screenshots:**

**OS Version:**
 - Windows 10 Version: Windows 11 22000.194

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Samuel12321** [comment]
Haven't been able to reproduce this bug. Can you post a screenshot or crash log or some more info about this bug.

**Comment by pklion** [comment]
I'm sorry that I can't take screenshot of that because it doesn't show up dialog and just crash.
Where can I find the crash log?

**Comment by pklion** [comment]
I don't know why but I could solve the problem with making new user.
Thank you for your support. :)
