### ISSUE TITLE
Feature Request: Spotify heart button on fluent flyouts

### ISSUE THREAD

**Issue by t3dium** [ModernFlyouts-Community/ModernFlyouts#823]
Since there's already loop/shuffle widgets on the media controls, having one to heart songs would also be incredibly useful as I wouldn't have to re-open the app everytime.

**Comment by BasicallyWiz** [comment]
I'm not a developer of this app, nor do I know anything about how it works, (trust me, I tried to figure it out, but I don't know enough c#), but I'm pretty confident that this app's UI is entirely dependent on the UI of Windows' default flyout.

What I'm getting at here, is that I don't think this is possible. Unless for whatever reason windows' flyout comes with a heart button specifically for Spotify, I don't think it can be done.

Unless Spotify has some media controls bind to do it, It's probably not doable. Even if said bind existed, that is a feature that will only function for the one service, so I don't quite understand the logic behind the effort.

I hope you understand my point of view on this.

**Comment by Samuel12321** [comment]
>  but I'm pretty confident that this app's UI is entirely dependent on the UI of Windows' default flyout.

Guess again 😄.

But you are entirely correct about Spotify not exposing any way to do this.

So unfortunately this isn't possible unless Spotify were to make changes to allow other apps to modify this.
