### ISSUE TITLE
Bug: Incompatability with "Spicetify"

### ISSUE THREAD

**Issue by crrystalz** [ModernFlyouts-Community/ModernFlyouts#825]
**Describe the bug:**
When using Spicetify, the media controls on the flyout (pause, skip song, etc,) do not function correctly. They work normally without using Spicetify, but are broken when using it.

**To Reproduce:**
1. Install Spicetify (https://github.com/khanhas/spicetify-cli/wiki/Installation)
2. Apply a theme to it (https://github.com/morpheusthewhite/spicetify-themes/tree/master/Dribbblish)
3. Use modern flyouts and try to use media control buttons 

**OS Version:**
 - Windows 10 Version: Windows 10 Home 21H1

**ModernFlyouts Version:**
 - Version: 0.9.30

**Additional context:**
ModernFlyouts downloaded from MS Store

**Comment by Cyberdroid1** [comment]
Do the buttons work on the default flyouts?

**Comment by CrystalzCodez** [comment]
Yes, they do.

**Comment by Samuel12321** [comment]
Closing due to issue being media player
Have added more documentation in commit 896e41f167b9f331cef96e6a2b3dfcf52202c66a
