### ISSUE TITLE
Bug: Shown on windows + space

### ISSUE THREAD

**Issue by marksamfd** [ModernFlyouts-Community/ModernFlyouts#842]
**Describe the bug:**
when i change the keyboard language using windows + space key it pops out  

**To Reproduce:**
add another keyboard language change the language using windows key and space

**Screenshots:**

![image](https://user-images.githubusercontent.com/62911833/137554638-3322c8a1-b77b-4944-963f-08f84fe56fd7.png)

**OS Version:**
 - Windows Windows 10 20H2

**ModernFlyouts Version:**
 - Version:  v0.9.3

**Comment by Cyberdroid1** [comment]
It has been fixed in code and will be released with the next update, version 0.10
