### ISSUE TITLE
Bug:At volume control,cannot control the track while music is going on

### ISSUE THREAD

**Issue by PeriyaThala09** [ModernFlyouts-Community/ModernFlyouts#848]
At volume control,cannot control the track while music is going on

**To Reproduce:**
1.Play a music at groove music
2.Press volume up or volume down at your keyboard
3.Try to adjust the track 
**OS Version:**
 - Windows Version: Windows 10 21H1
 
**ModernFlyouts Version:**
 - Version:0.9.3.0

![image](https://user-images.githubusercontent.com/92815671/137959859-d48439b2-e496-416d-8e88-4b2c20360ddb.png)

**Comment by Cyberdroid1** [comment]
Groove music does not support the timeline ability. More info [here](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md)
