### ISSUE TITLE
Bug: App needs restart when switching screen's with different resolutions

### ISSUE THREAD

**Issue by 100mph** [ModernFlyouts-Community/ModernFlyouts#849]
**Describe the bug:**

I use a 3440x1440 monitor and occasionally a 3840x2160 TV. If I switch from monitor to the TV, the app will sometimes stop working and when switching back to the monitor it stops appearing as well.

**To Reproduce:**

If you have access to a 4k TV then you'll need to connect both and swap back and forth (Win+P & select 'Second screen only' and then 'PC screen only').

**Screenshots:**

It disappears so no screenshot available sorry.

**OS Version:**
 - Windows Version: 
21H1

**ModernFlyouts Version:**
 - Version: 
0.9.3.0
**Additional context:**

**Comment by Samuel12321** [comment]
Closing in favor of #736
