### ISSUE TITLE
Feature Request: Change Volume Flyout Shortcut.

### ISSUE THREAD

**Issue by a7ce** [ModernFlyouts-Community/ModernFlyouts#853]
I would appreciate it if you could change the Shortcut for the Volume Flyout since my Keyboard doesn't have the Fn key.

**Comment by Samuel12321** [comment]
we are working on custom hotkey support, this will be in a future update.

**Comment by Cyberdroid1** [comment]
@a7ce you can use the keyboard manager in Microsoft powertoys for the time being :)
