### ISSUE TITLE
Album art flickers on next track in Windows Subsystem for Android

### ISSUE THREAD

**Issue by Hawksprey420** [ModernFlyouts-Community/ModernFlyouts#855]
Issue description:
The issue is related to the album art flickering in Modern Flyouts, wherein if I try to skip to the previous/next track with the flyout showing, the album art flickers fast and does not transition nicely. This happens when I play music in Spotify/Apple Music for Android inside Windows Subsystem for Android, which somehow this software caught and showed it in the audio flyout

Steps to reproduce the issue:
1. Open Spotify/Apple Music (or whatever streaming app in your system that is Android only)
2. Skip back to the previous track or skip to the next one
3. The result should be the album art flickering

Current behavior should look like this:
![Animation](https://user-images.githubusercontent.com/75325547/138425263-3e53155e-7a1e-4791-938f-d83cea1a3344.gif)

Expected behavior:
![normal](https://user-images.githubusercontent.com/75325547/138426631-409baf56-8dda-4ffa-ab7a-dee0e426a026.gif)

System info:
OS: Windows 11 21H2 22000.282 (Insider build, Beta Channel)
Windows Subsystem for Android version 1.7.32815.0

**Comment by Samuel12321** [comment]
Closing in favor of #639
