### ISSUE TITLE
ModernFlyouts doesn't detect Spotify after watching a video on Edge

### ISSUE THREAD

**Issue by Ketamaboy** [ModernFlyouts-Community/ModernFlyouts#858]
**Describe the bug:**

If you reproduce a video on Microsoft Edge, and then later try to listen to a song on Spotify, ModernFlyouts doesn't detect Spotify, it only detects Edge, even if it's closed.
**To Reproduce:**
1: Play a video on Microsoft Edge
2: Close Edge and Open Spotify
3: Reproduce a song on Spotify and then try to use ModernFlyouts
4: See error

**Screenshots:**

![image](https://user-images.githubusercontent.com/91992179/138745715-bff4e00a-5ac4-410c-a384-da5d562a9386.png)

**OS Version:**
 - Windows Version: 21H1 

**ModernFlyouts Version:**
 - Version: 0.9.3 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Are you using the Spotify pwa in edge?

**Comment by arnavbhate** [comment]
Is this similar to #710?

**Comment by Ketamaboy** [comment]
> Are you using the Spotify pwa in edge?

Nope, using the Spotify app

**Comment by GamerAway** [comment]
Same here 😥 + my function keys messed up 
Fn + F5 F6 F7 F7 dose not work anymore

**Comment by GamerAway** [comment]
did you fix it?

**Comment by Ketamaboy** [comment]
> Is this similar to #710?

Yes

**Comment by Ketamaboy** [comment]
> did you fix it?

nope

**Comment by GamerAway** [comment]
> > did you fix it?
> 
> nope

I hope they fix it soon I can't do anything.

**Comment by GamerAway** [comment]
> Does restarting your PC not help?

nope
I Del the app and reinstall it still fked up the app stuck and my Fn key with F5, F6, F7, F8 not working with any app even the default player

**Comment by arnavbhate** [comment]
I had a similar issue and fixed it by repairing the app from settings. I have done it three times already since July. This is a temporary fix but for some reason the app is corrupting itself.

**Comment by GamerAway** [comment]
> I had a similar issue and fixed it by repairing the app from settings. I have done it three times already since July. This is a temporary fix but for some reason the app is corrupting itself.

i tried that it did not fix it idk why 😪

**Comment by arnavbhate** [comment]
> > I had a similar issue and fixed it by repairing the app from settings. I have done it three times already since July. This is a temporary fix but for some reason the app is corrupting itself.
> 
> i tried that it did not fix it idk why 😪

Have you repaired it from settings or just u installed and reinstalled? The latter doesn't work.

**Comment by GamerAway** [comment]
> > > I had a similar issue and fixed it by repairing the app from settings. I have done it three times already since July. This is a temporary fix but for some reason the app is corrupting itself.
> > 
> > 
> > i tried that it did not fix it idk why 😪
> 
> Have you repaired it from settings or just u installed and reinstalled? The latter doesn't work.

I tried both of them still have the same problem

**Comment by Ketamaboy** [comment]
Okay, I think the app updated and now my problem is fixed
