### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by hrcxr** [ModernFlyouts-Community/ModernFlyouts#869]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows Version:  Windows 10 Pro

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

Pressing Windows + M changes language for my PC, and it also opens up the ModernFlyout and i am wondering how do i disable this as there is no settings for this..

**Comment by arnavbhate** [comment]
Duplicate of #584
