### ISSUE TITLE
Feature Request: add a option - click the system tray icon (or press hotkey) to call the media control layout out

### ISSUE THREAD

**Issue by RCAPSN** [ModernFlyouts-Community/ModernFlyouts#876]
Since I often use an online music player that plays in the background, 
it would be much more convenient if I could left-click on the system tray icon to call the media control layout out. 
It would be nice if the hotkey call-out feature could be added. 

Thank you so much.

**Comment by Samuel12321** [comment]
Duplicate of #468

We are working on this for 0.11 #840
