### ISSUE TITLE
Bug: Hi guys, your application don't see Spotify aplication, at all, when i press stop/play button at my keyboard it's don't notify me, please fix it 

### ISSUE THREAD

**Issue by mellotrixmusuic** [ModernFlyouts-Community/ModernFlyouts#883]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by Cyberdroid1** [comment]
Hi, edit your issue and fill in the issue template properly. Thanks.

**Comment by eProject** [comment]
Is this feature even present on the Win default flyout? 
not 100% sure
default flyout only pops when I change volume/mute (not with media keys - play/pause, next/previous) same with ModernFlyouts.

This is a feature request duplicate (# insert number) flyout pop-up when music/video changes or when user uses media keys.

**Comment by Cyberdroid1** [comment]
@eProject it is a windows default behaviour, that the media flyout appears on press play/pause, next, previous buttons

**Comment by eProject** [comment]
hmm strange... can't reproduce

**Comment by Samuel12321** [comment]
Duplicate of #532
