### ISSUE TITLE
Bug: wrong times on youtube for audio flyout!!

### ISSUE THREAD

**Issue by yazan1107** [ModernFlyouts-Community/ModernFlyouts#885]
**Describe the bug:**

when going to youtube it shows wrong times on youtube for audio flyout!!

**To Reproduce:**

**OS Version:**
 - windows 11

**ModernFlyouts Version:**
 - Version: lasetst

**Additional context:**

**Comment by Cyberdroid1** [comment]
Can you provide a video recording for the same?

**Comment by yazan1107** [comment]
> Can you provide a video recording for the same?
it is time 19 sec on real videom it shows 00:00 on media flyout
![image](https://user-images.githubusercontent.com/78726445/144235866-a35475f5-9873-49a6-b292-201f62954e18.png)

**Comment by Cyberdroid1** [comment]
Ah, you meant this. 

No browser on windows supports the timeline feature :(  , hence it appears as 0:00

More info here : https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md
