### ISSUE TITLE
I lost my media function keys

### ISSUE THREAD

**Issue by GamerAway** [ModernFlyouts-Community/ModernFlyouts#893]
I still have the same problem.
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/863#issue-1041223223
can anyone help, please I am on the lasts update 0.9.3.0
it's not working with any browser, app, media player

**Comment by Cyberdroid1** [comment]
Hi
Sorry for the problem you face. You should add your point to the already existing issue #863 instead of opening duplicate issues. 

Closing as duplicate
