### ISSUE TITLE
Bug: Timeline not working in any app

### ISSUE THREAD

**Issue by SteveFour** [ModernFlyouts-Community/ModernFlyouts#895]
**Describe the bug:**

Video and music timeline is always 0:00 (see screenshot below)
This apply to Groove Music and Microsoft Edge (the two I used to listen to music)

**Screenshots:**

![image](https://user-images.githubusercontent.com/79463793/146387120-d99019bf-8b1a-416d-9772-514a71937634.png)

**Temporary Solution**
Hide the timeline altogether

**OS Version:**
 - Windows Version: 
 Windows 11 Home build 22000.318

**ModernFlyouts Version:**
 - Version: 0.9.3.0, Windows Store version 
 

**Additional context:**

There's also a lot of issues with certain app settings when switch will crash it, but I saw most of reports on the Issue page already.
And consider update the app with Windows 11 theme (Mica material, rounded buttons, etc).

**Comment by Cyberdroid1** [comment]
Hi. Both Groove and Edge don't support the timeline feature, hence they are greyed out.

We have already implemented the feature of auto hiding the timeline bar (when not supported) in v0.10, which is in a beta state currently. If you like, you can try it out from the releases page. Though, note that flyout for lock keys are currently broken in this beta.
