### ISSUE TITLE
Bug: Volume Slider doesn't move

### ISSUE THREAD

**Issue by Crispy-Cream** [ModernFlyouts-Community/ModernFlyouts#901]
**Describe the bug:**
When changing the volume, the volume slider does not move. It is stuck till you move it with your mouse.

**To Reproduce:**
1 .Change the volume 

![image](https://user-images.githubusercontent.com/61794525/147267427-6edf2048-4a6e-4797-936f-ce8ea034a444.png)

**OS Version:**
Windows 10 up to date

**ModernFlyouts Version:**
0.9.3.0

**Additional context:**
I was using the download from windows when this first happened. Uninstalled and tried with github download.

The audio slider works on the default windows audio control

**Comment by Cyberdroid1** [comment]
Duplicate of #569
