### ISSUE TITLE
Bug: Flyout on the second monitor

### ISSUE THREAD

**Issue by ishid4** [ModernFlyouts-Community/ModernFlyouts#910]
**Describe the bug:**

Showing the flyout on the second monitor.

**To Reproduce:**

1. Stay AFK
2. Wait for monitors to auto turn off
3. Wake up your monitors (I think this problem happens because my second monitor wakes up quicker than my primary monitor)
4. See the error

**Screenshots:**

https://imgur.com/a/rLMR54r

**OS Version:**
 - Windows Version: Windows 11 21H2

**ModernFlyouts Version:**
 - Version: v0.9.3.0

**Additional context:**

I also noticed that, after the problem happens, the app also changes the display to 2 (See the screenshot).

**Comment by Samuel12321** [comment]
Just clarifying, you set monitor 1 but it changes to monitor 2.
I have the same issue
Closing in favor of #736
