### ISSUE TITLE
Bug: App runs on a discrete GPU 

### ISSUE THREAD

**Issue by xperiandri** [ModernFlyouts-Community/ModernFlyouts#915]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro

### OS build

22000

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

Launch on a device with 2 GPUs (integrated and discrete)

### ✔️ Expected Behavior

App works on an embedded GPU

### ❌ Actual Behavior

App works on a discrete GPU
![Знімок екрана 2022-01-05 164045](https://user-images.githubusercontent.com/2365592/148296170-1de35252-9ffb-4087-bd8d-d6bacdbc82d0.png)

### Other Software

Nothing special

### Additional Context

It prevents me from disconnecting an external GPU without killing or exiting the app

**Comment by BobbyESP** [comment]
You mean of being able to choose in what GPU the app should run?

**Comment by xperiandri** [comment]
The issue is that even if I choose integrated GPU in Windows 11 Settings it still runs on discrete GPU

**Comment by BobbyESP** [comment]
Ok, later i will see the problem

**Comment by Samuel12321** [comment]
This is an issue with your laptops settings, windows (or device manufactures software) controls which gpu the app uses, not the app.
I also just confirmed ModernFlyouts isn't affected on my Surface Book with 2 GPU's,

**Comment by xperiandri** [comment]
So on Surface Book when you detouched the keyboard base, there is no notification about Nvidia GPU usage, isn't it?

And if you look at Task Manager is integrated GPU shown for Modern Flyouts process?

**Comment by Samuel12321** [comment]
yes

**Comment by xperiandri** [comment]
Looks like only the apps that create overlays are affected. Maybe some API Force that

**Comment by xperiandri** [comment]
@Samuel12321 are you on Windows 11 RTM?
