### ISSUE TITLE
Bug: Media Flyout doesnt appear for spotify and groove music

### ISSUE THREAD

**Issue by Esketet** [ModernFlyouts-Community/ModernFlyouts#917]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 Pro

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

opening spotify and groove music to display audio flyout

### ✔️ Expected Behavior

audio flyout displays

### ❌ Actual Behavior

Audio Flyout is not displaying at all. 

### Other Software

Im using spotify and groove music

**Comment by Samuel12321** [comment]
Closing in favor of #532
