### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by sannier3** [ModernFlyouts-Community/ModernFlyouts#921]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Pro Insider DEV

### OS build

22533.1001

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout, Lock keys Flyout, Battery Flyout, Audio Tray Flyout, Camera Flyout, Mic Flyout

### Steps to reproduce

Translated FR to EN :
Simply with the new dev version of Windows 11, as soon as you modify the volume, the explorer restarts

### ✔️ Expected Behavior

That the explorer does not restart

### ❌ Actual Behavior

Explorer will restart even if Modern Flyout is running fine for

**Comment by sannier3** [comment]
As much for me, there are already bugs #919 and #920,. Unlike me, the explorer restarts but the flyout works

**Comment by Cyberdroid1** [comment]
The moment you press any volume key, the explorer restarts?

**Comment by sannier3** [comment]
Yes, I am using RoundedTB, Start11 and ModernFlyouts at the same time but without these 3 software, the explorer still restarts when I press the volume button

**Comment by sannier3** [comment]
I give you a video of 1m17 to show you my problem
[https://jbsan.fr/autre/feedback/2022-01-13-Modern-Flyouts-GIT/OBS-2022-01-13_19-42-31.mp4](https://jbsan.fr/autre/feedback/2022-01-13-Modern-Flyouts-GIT/OBS-2022-01-13_19-42-31.mp4)

**Comment by Cyberdroid1** [comment]
> Yes, I am using RoundedTB, Start11 and ModernFlyouts at the same time but without these 3 software, the explorer still restarts when I press the volume button

Hmmm, seems like you modified your installation too much that it is breaking stuff.

**Comment by Samuel12321** [comment]
> but without these 3 software, the explorer still restarts when I press the volume button

So the problem has nothing to do with ModernFlyouts.

**Comment by sannier3** [comment]
Like problem #922, my explorer restarts so my other software also works fine. It’s just since updating Windows that it seems to be bugging after pressing the volume button. See this issue anyway
