### ISSUE TITLE
Display new song playing

### ISSUE THREAD

**Issue by Crissomar** [ModernFlyouts-Community/ModernFlyouts#925]
### Description of the new feature / enhancement

could be displayed every time the song changes 

### Scenario when this would be used?

So you can see if you want to skip it or be ready for the drop ♪.ıılıll|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅|llılıı.♫

### Additional context

I don't know why I liked this feature in aimp xD

**Comment by Samuel12321** [comment]
Duplicate of #78
