### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Sutken** [ModernFlyouts-Community/ModernFlyouts#928]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 

### OS build

22538.10.10

### Platform

x86

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

With the newest Win update it shows both Windows volume icon and the Modern Flyouts icon
![Näyttökuva (16)](https://user-images.githubusercontent.com/98242588/150660439-19181cd2-b8e8-49dc-9a50-94dc080f001a.png)
.

### ✔️ Expected Behavior

Only the Modern Flyouts to show

### ❌ Actual Behavior

Again it shows the Win volume icon.

**Comment by saboooor** [comment]
duplicate issue
