### ISSUE TITLE
Bug: Groove Music Timeline greyed out

### ISSUE THREAD

**Issue by fillwithjoy1** [ModernFlyouts-Community/ModernFlyouts#930]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 10 Home 21H1

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Open Groove Music. Start playing music
![Screenshot (4)](https://user-images.githubusercontent.com/29514446/150723836-359a9e5e-ac1d-47db-b85c-da2dbc320696.png)
And the ability to seek the timeline is greyed out. This wasn't the issue before

### ✔️ Expected Behavior

Being able to seek the timeline

### ❌ Actual Behavior

It's greyed out.

**Comment by Cyberdroid1** [comment]
Groove music does not support the timeline feature. Hence it is greyed out.

Interestingly, the new media player for windows 11 (which is an update to groove music) supports the timeline feature.
