### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Styphoryte** [ModernFlyouts-Community/ModernFlyouts#931]
### ModernFlyouts Version

0.9.3

### Windows version

Windows 11 Pro Version 21H2 Installed on ‎12/‎24/‎2021

### OS build

OS build	22000.466 Experience Windows Feature Experience Pack 1000.22000.466.0

### Platform

x64

### Steps to reproduce

Restart windows, app will not open unless data is reset or uninstalled / reinstalled. [https://imgur.com/a/ARknc8E](url)

### ✔️ Expected Behavior

It to start up fine.

### ❌ Actual Behavior

It did not start up fine.

### Additional Context

Had the same issue with MSI's command center if that helps any...

**Comment by walkxcode** [comment]
Just like the error message says. You may not have permission to access the files. Try using this https://www.windowscentral.com/how-take-ownership-files-and-folders-windows-10

**Comment by Styphoryte** [comment]
I have took ownership of the shell32.dll in the Windows/system32 folder as well as Program Files & its folders and subcontainers. Weird... I think this is a Windows 11 issue.

**Comment by Cyberdroid1** [comment]
Hm, looks like the permissions are messed up in your installation.
I would recommend using `sfc /scannow` and DISM tool to repair your installation.

**Comment by Styphoryte** [comment]
Same issues, I ran cmd as administrator. https://imgur.com/a/yyxzi3W

**Comment by Samuel12321** [comment]
closing as issue is with users computer not ModernFlyouts
