### ISSUE TITLE
 Adjusting volume via scroll wheel while hovering the notification tray icon.

### ISSUE THREAD

**Issue by cgohier** [ModernFlyouts-Community/ModernFlyouts#933]
### Description of the new feature / enhancement

The flyout would (optionally maybe) open while adjusting the volume with the scroll wheel over the tray icon, and the volume would increase or decrease according to the direction of the scroll wheel.

### Scenario when this would be used?

It would be used to quickly and easily adjust the volume.

### Additional context

This functionality exists in earTrumpet and various Linux desktop environments.

**Comment by vvirtues** [comment]
the tray icon is only for settings though, and it works on the flyout itself

**Comment by prakharb5** [comment]
When your mouse is near the tray anyway, you can just scroll on the volume icon instead of this app's. This app's tray is not a replacement for the volume tray icon.
