### ISSUE TITLE
Regarding adding more chromium browsers in the Issue Templates

### ISSUE THREAD

**Issue by FahimFBA** [ModernFlyouts-Community/ModernFlyouts#939]
### Provide a description of requested docs changes

The `bug-report.yml` contains 2 chromium-browser although it includes `...`. I want to add Brave and Vivaldi also since these two chromium browsers are getting popular and there might be some people who get confused regarding the browser whether Brave or Vivaldi is Chromium or else.

I am adding a PR for that.

**Comment by Samuel12321** [comment]
merged
