### ISSUE TITLE
ModernFlyouts new appearance for Twinkle Tray

### ISSUE THREAD

**Issue by Artaherzadeh** [ModernFlyouts-Community/ModernFlyouts#942]
### Description of the new feature / enhancement

[Twinkle Tray](https://github.com/xanderfrangos/twinkle-tray) ( from @xanderfrangos ) is software giving users the ability to change the monitor's brightness using shortcuts but the menu is still UWP old design and not ModernFlyouts new appearance.
Brightness slider :
![Brightness](https://user-images.githubusercontent.com/64541682/152667928-d520d62e-3011-46ac-9039-2976abb42e62.png)
Sound slider :
![Sound](https://user-images.githubusercontent.com/64541682/152667942-8487ee1c-29bd-41df-9fdf-d3419d6b2d8a.png)

**Comment by Samuel12321** [comment]
Not quite sure what you are asking?
ModernFlyouts isn't compatible with twinkletray.
We are adding this functionality in the next release.

**Comment by Cyberdroid1** [comment]
The old metro slider is from twinkle tray itself, it's a custom flyout.
Nothing which modernflyouts can do about.
