### ISSUE TITLE
Bug:  Media Flyout bugs

### ISSUE THREAD

**Issue by PastaSempai** [ModernFlyouts-Community/ModernFlyouts#949]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 

### OS build

22000.526 corelease

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

play any music player (tested on groove and NEW windows media player for windows 11
1. move to the next song , happens every 3 or 4 songs.

![Screenshot 2022-02-13 004535](https://user-images.githubusercontent.com/95404315/153725118-a28a93ca-51d2-4864-adff-8b817af4df8b.png)
nothing is visible, 

2. same as previous, when you move to the next song
![image](https://user-images.githubusercontent.com/95404315/153725132-07629400-4c34-4ac7-9624-99baa8512339.png)
no album art visible even though album art is available

3.  notice the media next and previous button in the given images is greyed out and unavailable to press.

### ✔️ Expected Behavior

for 1 and 2, the song metadata loading shouldnt be bugged and must load accordingly

for 3, next and previous media options should work properly

### ❌ Actual Behavior

1. most of the time no song info at all (its blank) is shown until you go to the next song and return and the time progress of the song also doesn't change unless it is paused and resumed. 

2.  the album art doesn't appear  even if the music info and time works perfectly (this bug will appear always even if previous bug doesnt happen and if previous bug happens this will happen). same as the previous, you have to move to the next song and return to the previous one to get its album art. this always happens. unlike previous which happens once every 3 or 

3.  in the media flyout, sometimes next song and previous song options are unavailable, have to restart ModernFlyouts to get it.

### Other Software

Groove Music
new windows 11 media player Version 11.2112.40.0

**Comment by Samuel12321** [comment]
@PastaSempai any reason you opened then closed these?
