### ISSUE TITLE
Bug: Not Working On Windows 11

### ISSUE THREAD

**Issue by AlexDev404** [ModernFlyouts-Community/ModernFlyouts#953]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11

### OS build

 22543.1000

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

1. Open Modern Flyouts. 
2. Attempt to change volume of audio device using keyboard hotkeys or buttons on audio device (example: headphones)

### ✔️ Expected Behavior

System Flyout is supposed to disappear and switch place with Modern Flyouts.

### ❌ Actual Behavior

System Flyout **does not** disappear, but instead **both** Modern Flyout and System Flyout are present.

### Other Software

This bug is present while using any type of software.

**Comment by Cyberdroid1** [comment]
#920
