### ISSUE TITLE
Bug: Title of music doesn't show using the built in Media Player.

### ISSUE THREAD

**Issue by TheCarisLost** [ModernFlyouts-Community/ModernFlyouts#957]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 21H2

### OS build

22000.493

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Using AudioFlyouts on the latest version of win11 and built in Media Player (previously Groove Music)

### ✔️ Expected Behavior

![2022-02-22 (1)](https://user-images.githubusercontent.com/100221804/155210244-beb19130-ae98-4acf-b1e1-aa1815ac2975.png)

### ❌ Actual Behavior

![image_2022-02-22_195006](https://user-images.githubusercontent.com/100221804/155179477-fb95326d-b060-407f-95e5-04852f64e001.png)
The title and thumbnail of any song dont show at all.

### Additional Context

I have 2 playlists with music, and the first songs/music in each playlist are the only songs that show a title, while all the others don't,

**Comment by Cyberdroid1** [comment]
Can you try this?

Open the flyout with no info. While it is open, open the action centre.

Does the music info appear now?

**Comment by Samuel12321** [comment]
Media Player at fault, it doesnt fully support STMP properly

**Comment by Cyberdroid1** [comment]
Oh wait, just encountered your bug. Clearly looks like the app is buggy, since it is broken in the control centre too :/

![image](https://user-images.githubusercontent.com/51435948/160451122-1cb83583-7a8a-4283-bbaa-2da0dd58e8d6.png)
