### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by narotuwi** [ModernFlyouts-Community/ModernFlyouts#962]
### ModernFlyouts Version

0.9.3.0

### Windows version

Microsoft Windows 10 Home

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Having the flyout open, not able to click on the pause/play button for the windows spotify app

### ✔️ Expected Behavior

For the music to play/pause

### ❌ Actual Behavior

Nothing happens

**Comment by RakibPro** [comment]
I'm having same problem 😢
Fix this bug on next update

https://user-images.githubusercontent.com/71222636/157668693-0d66ac3c-b46a-4db8-8b7a-d63d80f058e8.mp4

**Comment by Samuel12321** [comment]
Duplicate of #532
