### ISSUE TITLE
Bug: Timeline only updates every 10 seconds

### ISSUE THREAD

**Issue by yodaluca23** [ModernFlyouts-Community/ModernFlyouts#963]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 21H2

### Area(s) with issue?

Media Flyout

### Steps to reproduce

1: Play Music on Spotify
2: Try to adjust the volume
3: Look at the timeline
4: whitness bug

### ✔️ Expected Behavior

See live updates to the timeline

### ❌ Actual Behavior

only updates approxomently every 10 seconds.

### Other Software

Spotify (Not Windows 10/11 Store) Version: 

Spotify for Windows
1.1.79.763.gc2965cdf

**Comment by Cyberdroid1** [comment]
Unfortunately, this is an issue on the side of the media apps you use.
Apparently, Microsoft recommends apps to update timeline info every 6 seconds or so.

There is nothing here which ModernFlyouts can do about.

**Comment by yodaluca23** [comment]
Lol I made the suggestion to Spotify:
https://community.spotify.com/t5/Idea-Submissions/Option-to-make-the-windows-media-timeline-update-every-second/idi-p/5348972#M152926

**Comment by yodaluca23** [comment]
> Unfortunately, this is an issue on the side of the media apps you use. Apparently, Microsoft recommends apps to update timeline info every 6 seconds or so.
> 
> There is nothing here which ModernFlyouts can do about.

Hey, so I thought of a way to fix this... (I got the idea from MC mod "Craftify" [Their Git could also prob help] ) You could have the option to sign to your Spotify and give modern layouts authorization to see what song and progress you are listening to. If it detects you listening to Spotify it will get the timeline from Spotify API instead of Windows...
