### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Tloh146** [ModernFlyouts-Community/ModernFlyouts#967]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 21H2

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

![image](https://user-images.githubusercontent.com/101043226/156918980-9668dffc-8a25-40e3-af89-452343c18e69.png)
 There is something wrong with media flyout. I'm usually using Groove Music for listening music and sometimes media flyout doesn't show right thing (like in the screenshot).

### ✔️ Expected Behavior

I'm expecting for it to show the right thing.

### ❌ Actual Behavior

It doesnt show right thing.

### Other Software

Groove Music

### Additional Context

It would be good if we can change sound level from media flyout.
![Ekran Görüntüsü (455)](https://user-images.githubusercontent.com/101043226/156919268-b038ec5c-70ad-4bd0-b0d0-a8a69ffe99a4.png)
Like this but more simpler.

**Comment by Cyberdroid1** [comment]
Does the song already have a thumbnail in Groove?

Groove does not support the timeline feature.

The app volume level is planned to be released soon

**Comment by GamerAway** [comment]
Same here
I am dying cuz of it
even when I turn off the app and turn back to windows default I miss the old one
my media function keys not working without the app anymore
i hope they fix it

**Comment by Tloh146** [comment]
> Does the song already have a thumbnail in Groove?
> 
> Groove does not support the timeline feature.
> 
> The app volume level is planned to be released soon

**Comment by Tloh146** [comment]
Yes, it has a thumbnail in Groove.

**Comment by Cyberdroid1** [comment]
Hmm, i am guessing this is just the media session integration bugging out. We already have an issue on that :)

**Comment by Cyberdroid1** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md
