### ISSUE TITLE
Bug: ModernFlyouts don't show media information from Youtube Music Desktop (https://ytmdesktop.app)

### ISSUE THREAD

**Issue by supersej** [ModernFlyouts-Community/ModernFlyouts#973]
### ModernFlyouts Version

"0.9.3"

### Windows version

"Windows 11 Pro 21H2"

### OS build

22000.493

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

The Windows 10 Media service in YTMD is activated.
But I can not under any circumstances get media info shown om ModernFlyouts.

Futhermore, and this could indicate that this might not be a ModernFlyout problem only.
If I turn on my pc and start Youtube Music Desktop App Actions Center shows media info from YTMD correctly.
If I then stop YTMD and start ex. Spotify, stop it and then start YTMD I get an arrow as shown below to switch between the two players. But even if I switch ModernFlyouts wont show media info from YTMD

![ModernFloyouts-vs-actioncenter](https://user-images.githubusercontent.com/18198121/158243695-0fb5358a-0d9b-48ff-bd39-67fded70131a.gif)
 

### ✔️ Expected Behavior

ModernFlyouts should be showing media info from YTMD since it is the one playing.
This was working fine on the original Flyouts in Windows 11 as far as I can remember.
Not to keen on uninstalling ModernFlyouts to test (I like it too much otherwise) 😂

### ❌ Actual Behavior

![image](https://user-images.githubusercontent.com/18198121/158242203-7650a019-9261-4866-ab01-3303a2d1a549.png)

### Other Software

https://ytmdesktop.app/
Spotify.com

### Additional Context

A wierd sidenote.
ModernFlyouts popup when a new song starts on YTMD, so it somehow knows that a new song is started, but it still shows Spotify media information.
I haven't testet with other players since it's the only 2 players I use at the moment.

**Comment by arnavbhate** [comment]
There is an arrow in the ModernFlyouts flyout as well in your image. Have you tried that?
![image](https://user-images.githubusercontent.com/86760472/158776811-12306e74-9231-4199-824a-03d8eb67aa72.png)

**Comment by supersej** [comment]
Dooh. No I did not notice that.
It works as expected and I am able to switch between the players.

Thanks for the heads-up.
