### ISSUE TITLE
Show message when you toggle FnLock

### ISSUE THREAD

**Issue by Burraby** [ModernFlyouts-Community/ModernFlyouts#975]
### Description of the new feature / enhancement

Duplicate of #64 but for FnLock.

### Scenario when this would be used?

When FnLock is toggled.

### Additional context

Default:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/70784752/158744828-0dc4af9a-585c-481d-a8f9-5e728d5f2ed7.png">
Feature request:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/70784752/158744986-98be3c1e-a64d-408a-82cc-91cd7f9d5a84.png">

**Comment by Samuel12321** [comment]
unfortunately this isn't possible, the fn key toggle is handled in the keyboard firmware and not passed on to the OS.
We could detect if a function key is pressed eg. volume or f2 and use that to work out the fn state, but there is no way to tell when the fn key itself is pressed.

If someone has found a miraculous way around this, i would love to know as i agree this would be a useful flyout i would love to add.
