### ISSUE TITLE
ModernFlyouts is a great app but it need windows 11 modern look

### ISSUE THREAD

**Issue by IAmPratham2006** [ModernFlyouts-Community/ModernFlyouts#976]
### Description of the new feature / enhancement

There is nothing in ModernFlyouts UI but it didnot match completely with new windows 11 ui, so can you update it asap.

### Scenario when this would be used?

There is nothing in ModernFlyouts UI but it didnot match completely with new windows 11 ui, so can you update it asap.

### Additional context
![image](https://user-images.githubusercontent.com/100473734/158785171-8baa5c93-6846-466c-800f-ce9478fcc208.png)
_No response_

**Comment by Cyberdroid1** [comment]
#890
