### ISSUE TITLE
Bug: The flyout not showing the duration of a song from Youtube Music Desktop

### ISSUE THREAD

**Issue by Felzow47** [ModernFlyouts-Community/ModernFlyouts#978]
### ModernFlyouts Version

0.9.3.0

### Windows version

Win 10 20H2

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

 
**Step one :** Download youtube music desktop client from [This repo GitHub ](https://github.com/th-ch/youtube-music) 
**Step two :** Start a music using youtube music desktop 
**Step three :** open the flyout and see the duration is not showing on the flyout. 

![image](https://user-images.githubusercontent.com/49567056/160034814-ff69ee34-7d84-46dc-9bff-3fd7b3a970b3.png)

### ✔️ Expected Behavior

I was expecting to see real duration from Youtube Music Desktop directly in the flyout

### ❌ Actual Behavior

the duration of the music is not showing up in the flyout

### Other Software

Youtube music desktop client from [This repo GitHub ](https://github.com/th-ch/youtube-music) ( V 1.16.0)

**Comment by Samuel12321** [comment]
Problem is due to Youtube Music app not supporting the STMC api.
Have opened an issue on their repo [Here](https://github.com/th-ch/youtube-music/issues/661)
