### ISSUE TITLE
I installed ModernFlyouts for myself and don't know how to control the volume *on windows 11*

### ISSUE THREAD

**Issue by RudiManWi** [ModernFlyouts-Community/ModernFlyouts#983]
### ModernFlyouts Version

0.91

### Windows version

21H2

### OS build

5345345345435

### Steps to reproduce

sus

### ✔️ Expected Behavior

i think

### ❌ Actual Behavior

nvm

### Additional Context

uhh

**Comment by Samuel12321** [comment]
closing as
