### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by FlaminXred** [ModernFlyouts-Community/ModernFlyouts#984]
### ModernFlyouts Version

0.3.0

### Windows version

Windows 8.1

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

install on windows 8.1

### ✔️ Expected Behavior

Icons appearing

### ❌ Actual Behavior

icons were appearing as squares
![image](https://user-images.githubusercontent.com/96554714/160314395-5d77dd72-ec77-4f5e-9536-6ce4b8567d21.png)

**Comment by Samuel12321** [comment]
Hi @FlaminXred, 
Hmm that's odd, i hadn't heard of that bug before.
Unfortunately all i can suggest would be to reinstall 0.3 or try an older version (0.1 or 0.2).
Unfortunately 0.3 was the last release to support Windows 8 so there wont be an update released to fix this.
Sorry i couldn't be of more help
