### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by CHSXuan** [ModernFlyouts-Community/ModernFlyouts#985]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2 Preivew

### OS build

22581.100

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Close Audio Flyout button

### ❌ Actual Behavior

Closing Audio Flyout after Windows 11 22H2 crashes the program

**Comment by Cyberdroid1** [comment]
Duplicate of https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/592
