### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by xFeathers** [ModernFlyouts-Community/ModernFlyouts#986]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

the flyout won't appear i don't know if there's a button i need to click or it simply doesn't work.

### ✔️ Expected Behavior

I was expecting the popup to be able to play my spotify

### ❌ Actual Behavior

the only thing the app opens is it's settings and the pop out for my music wont appear

**Comment by Cyberdroid1** [comment]
You need to press the volume up/down button, or the media control buttons (play/pause, next, previous) for the flyout to appear.

You can also press the caps/num lock button for flyout. Refer to the readme in the repo for more info.
