### ISSUE TITLE
Bug: I am using Spotify, and when my songs change the widget stays the same with a previous song.

### ISSUE THREAD

**Issue by xSneetches** [ModernFlyouts-Community/ModernFlyouts#988]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Hopefully this works.

![image](https://user-images.githubusercontent.com/102634506/160727594-1c3a428b-48ad-4837-996d-fcef5f023d6d.png)

### ✔️ Expected Behavior

The song to change, it used to but then it started acting up.

ALSO - Sorry if the image doesn't work, I'm a little confused with that as well.

### ❌ Actual Behavior

The song in spotify would change, but the widget in the top left wouldn't.

### Other Software

Spotify

### Additional Context

I was using this maybe 2 or 3 days ago and then I went on vacation and left my computer. I came back and started playing my songs and such, and the widget was a little messed up.

**Comment by Cyberdroid1** [comment]
Can you check if you have the same issue (media info not updating) in the windows default flyout?

**Comment by Cyberdroid1** [comment]
Closing due to no response.
