### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by TrySfast** [ModernFlyouts-Community/ModernFlyouts#990]
### ModernFlyouts Version

0.9.3.0

### Windows version

windows 10 20h2

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

![image](https://user-images.githubusercontent.com/102595072/161396184-e9a1ecc8-1b1c-417e-9a48-ff26adfb183a.png)
the pause skip not working

### ❌ Actual Behavior

please help the pause and skip not working

**Comment by Cyberdroid1** [comment]
Does this also happen with the default windows flyout?

**Comment by TrySfast** [comment]
no

**Comment by TrySfast** [comment]
in win+g works

**Comment by TrySfast** [comment]
in gamebar works

**Comment by Cyberdroid1** [comment]
Can you update to windows 10 21h2 and check this issue again?

**Comment by TrySfast** [comment]
sorry im on 21h2
i didnt realize i put 20h2

**Comment by TrySfast** [comment]
i uninstalled the app and put again
and nothing happened
the problem is with spotify because on youtube works

**Comment by Cyberdroid1** [comment]
> the problem is with spotify because on youtube works

If only spotify knew "if it is not broken, don't fix it".........

Anyways, I would suggest you to install the website "https://open.spotify.com" as a PWA from your browser, and use that.

I will be closing this bug report then. Thanks
