### ISSUE TITLE
Bug: Modern Flyouts does not hide the new windows volume flyout

### ISSUE THREAD

**Issue by Majorzen51** [ModernFlyouts-Community/ModernFlyouts#991]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 22H2

### OS build

22581.200

### Platform

x64

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

Use the volume controls and see that as well as the modern flyout, the normal volume flyout will also show.

![image_2022-04-05_200843](https://user-images.githubusercontent.com/93481392/161831151-498556fc-43bf-4ea6-9ace-53efa3afadea.png)

### ✔️ Expected Behavior

Just the modern flyout to show instead of both of them showing up.

### ❌ Actual Behavior

Both of the flyouts showed up.
![image_2022-04-05_200921](https://user-images.githubusercontent.com/93481392/161831232-f2771539-7798-4922-a79d-96e2a8c9b9c7.png)

**Comment by Cyberdroid1** [comment]
#920
