### ISSUE TITLE
Bug: Song name and play/pause button and next/previous button is not available 

### ISSUE THREAD

**Issue by PeriyaThala09** [ModernFlyouts-Community/ModernFlyouts#992]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 10 21H2

### Platform

x64

### Area(s) with issue?

Audio Flyout, Media Flyout

### Steps to reproduce

When i play song play/pause button and next/previous button not available

### ✔️ Expected Behavior

It should show when song start to play

### ❌ Actual Behavior

It not showing when i play a song

### Other Software

Google Chrome(100.0.4896.75)

### Additional Context

![image](https://user-images.githubusercontent.com/92815671/161872324-e706f857-2b06-4b9f-8d22-24a06eaf9e95.png)
![image](https://user-images.githubusercontent.com/92815671/161872346-e166f39a-f678-40fa-9ebd-a63702c5ea7c.png)

**Comment by Cyberdroid1** [comment]
Does the windows default flyout have the media info?

**Comment by PeriyaThala09** [comment]
> 

yes

**Comment by PeriyaThala09** [comment]
> Does the windows default flyout have the media info?

before this i have media info but after update i cant see media info

**Comment by PeriyaThala09** [comment]
> 

no

**Comment by Cyberdroid1** [comment]
Looks like a windows issue to me, which I don't think the app can do anything about :/

You can try restarting the media app, or windows, or maybe some setting/flag which you might have enabled/disabled.

I will be closing this issue now.
