### ISSUE TITLE
Bug: No more music cover

### ISSUE THREAD

**Issue by linguaccia22** [ModernFlyouts-Community/ModernFlyouts#996]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 21H2

### OS build

22000.593

### Platform

x64

### Area(s) with issue?

Media Flyout

### Steps to reproduce

After Microsoft's update of Groove Music, the covers of the music you are listening to are no longer showing on ModernFlyouts.
![Senza titolo](https://user-images.githubusercontent.com/95597809/162812010-578cae1c-2aad-47a1-a109-d662a4555b6a.png)

how can i solve?

Thanks!

### ❌ Actual Behavior

After Microsoft's update of Groove Music, the covers of the music you are listening to are no longer showing on ModernFlyouts.
![Senza titolo](https://user-images.githubusercontent.com/95597809/162812010-578cae1c-2aad-47a1-a109-d662a4555b6a.png)

how can i solve?

Thanks!

### Other Software

Groove Music Media Player: 11.2202.45.0

**Comment by linguaccia22** [comment]
I forgot to write an important detail.

When you first open groove music and start a song the cover on ModernFlyouts is not visible, but if you go to the next track and then go back the cover is visible, this applies to all tracks

**Comment by Samuel12321** [comment]
So this only happened since a grove update?
Sounds like microsoft broke groove.
Does this occur in the action centre media flyout?

**Comment by linguaccia22** [comment]
Yes this started after the Groove Music update.

The second question I did not understand what you mean sorry.
I'm using Google Translate to communicate and sometimes Google Translate translates incorrectly.

So premised that this thing is not a common problem to all, I thought it was a general problem of the cover sheet after the update of Groove Musica.

**Comment by Samuel12321** [comment]
Report this to microsoft using feedback hub
